### ISSUE TITLE
Enhance MET tools to define map data using GIS shapefiles

### ISSUE THREAD

**Issue by dwfncar** [dtcenter/MET#1012]
## Describe the Enhancement ##
Several MET tools generate plots, including Plot-Data-Plane, Plot-Point-Obs, MODE, and Wavelet-Stat. They read static map data files bundled with the MET tarball to do so. The default map data settings and defined in the ConfigMapData file.

Over the years that static map data has caused several headaches. It eventually becomes out of date and requires updates. However, updating it is somewhat tedious. It is currently based on [Natural Earth](https://www.naturalearthdata.com/) shapefiles which come in 3 different resolutions (110m, 50m, and 10m) and are updated relatively frequently. Of course, higher resolution map data makes for much larger PostScript output files which take longer to create and render.

This task it to add the option of defining map data using GIS shapefiles instead of this custom map data format. Doing so is beneficial for several reasons.
1. Swapping in update shapefile versions becomes very easy.
2. Gives users much greater flexibility to select higher or lower resolution shapefiles as well as their own custom files.
3. Enables users to plot shapefiles which are NOT static, such as daily polygon warning areas.

For backward compatibility, MET should continue to support the custom data file format. However, rather than distributing custom map data files, recommend that we distributed either 50m or 110m resolution shapefiles.

### Time Estimate ###
2 days.

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
No sub-issues needed.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [ ] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
