### ISSUE TITLE
Enhance MET to compute the CBS score.

### ISSUE THREAD

**Issue by davidfillmore** [dtcenter/MET#1031]
## Describe the New Feature ##
The AF project needs to generate the CBS score on its GPP verification. This requires adding another method of interpolation (areal). Michelle Harrold has provided some code (from Bob Craig) and helpful references (see attachments).

From Bob:

"All, the attached document describes the CBS verification process , I.7-36 Table F. The verification is done over a 1.5 degree remap of the model using an area averaging technique. The ground truth is the model analysis. I have attached the program we use to average the data. The index based on the CBS score is from UKMO. I attached the program that calculates it along with the configuration files."

I have attached the WMO document with I.7-36 Table F as well as the the areal weighting IDL script (around line 251 is the weighting code) and the CBS score python program. Also, the areal weighting script references a paper, which might have some helpful background:

https://www.wmo.int/pages/prog/www/BAS/documents/AnnexDoc3-3.pdf

The work for this issue may include supporting a new interpolation method, computing the CBS score, and writing its output somewhere. Recommend coordinating with @michelleharrold since she's likely familiar with the details.

### Acceptance Testing ###
*List input data types and sources.*
*Describe tests required for new functionality.*

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: John HG
- [ ] Select **scientist(s)** or **no scientist** required: unknown

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [x] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
Depending on the changes to the output, may need an issue for METviewer to handle new output. May also need a METplus issue if new configuration file options are added.

## New Feature Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [x] Add/update log messages for easier debugging.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.

**Comment by lisagoodrich** [comment]
If there are problems with these attachments, see original JIRA Location:
https://sdg.rap.ucar.edu/jira/browse/MET-1031?filter=12903

[WMO_485_Vol_I.pdf](https://github.com/NCAR/MET/files/3292070/WMO_485_Vol_I.pdf)
[area_averaging_grib2_cbs.pro.txt]

[cbs_um_index_weights.txt](https://github.com/NCAR/MET/files/3292098/cbs_um_index_weights.txt)

These files have been changed to txt files so they can be saved in this location.
(https://github.com/NCAR/MET/files/3292081/area_averaging_grib2_cbs.pro.txt)

[cbs_scoresheet_test.py.txt](https://github.com/NCAR/MET/files/3292095/cbs_scoresheet_test.py.txt)

**Comment by JohnHalleyGotway** [comment]
Note that the changes for this task are included in PR dtcenter/MET#1892.
