### ISSUE TITLE
Transition MET user's guide from lyx to sphinx.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1217]
## Describe the Task ##
Follow the same workflow for transitioning METplus and METviewer UGs to sphinx 

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [x] Try using pandoc to see if any files can be automatically converted.
- [x] Create gh-pages branch
- [x] Create docs subdirectory
- [x] Create some template files to get Lisa started
- [x] Move basic content over to Sphinx by Monday and merge into develop
- [x] Incorporate recent changes from the transition Google doc and merge into develop.
- [x] Add references and titles to the MET Documentation
- [x] Publish the user's guide using gh-pages.

### Relevant Deadlines ###
5/3 if possible but if not 5/20 (met-9.1-beta2)

### Funding Source ###
2702691 - Dan (30hrs), Julie (60hrs), Lisa(60hrs)

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones
- [x] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the task and verify your changes.
- [ ] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**, listing the **\<Issue Number\>** in the title.
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.

**Comment by lisagoodrich** [comment]
Moved basic content over to Sphinx by Monday and merged into develop (DONE 4/21/20 Lisa Goodrich)

**Comment by jprestop** [comment]
This work is complete.
