### ISSUE TITLE
Consider swapping out importlib.util instead of __import__ for python embedding

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/MET#1265]
## Describe the Enhancement ##
When importing modules, we use __import__ with the script name (remove .py and path). If a user's python script is named the same as an existing python module (like test for example), then the import will fail. It is better to use importlib.util to load a module from a full path.

    import importlib.util
    spec = importlib.util.spec_from_file_location("module.name", "/path/to/file.py")
    foo = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(foo)
    foo.MyClass()

Code snippet taken from:
https://stackoverflow.com/questions/67631/how-to-import-a-module-given-the-full-path

### Time Estimate ###
1-2 days

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [X] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
None

### Funding Source ###
None

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required
- [X] **no scientist** required

### Labels ###
- [X] Select **component(s)**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones
- [X] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [X] Complete the issue definition above.
- [X] Fork this repository or create a branch of **develop**.
Branch name:  `feature_1265_importlib`
- [X] Complete the development and test your changes.
- [X] Add/update unit tests. N/A
- [X] Add/update documentation. N/A
- [X] Push local changes to GitHub.
- [X] Submit a pull request to merge into **develop**.
Pull request: `feature 1265 importlib`
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.
