### ISSUE TITLE
new RPS statistic in the RPS line type; inverted score

### ISSUE THREAD

**Issue by j-opatz** [dtcenter/MET#1280]
## Describe the New Feature ##
A new RPS statistic output for the RPS line type that inverts the current scale being used. The new RPS statistic would have 1 as a perfect score, and 0 as having no skill.
Since this changes the output format, we also need to update the version number from met-9.0 to met-9.1.

### Acceptance Testing ###
*List input data types and sources.*
*Describe tests required for new functionality.*

### Time Estimate ###
8 hours.

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
No sub-issues required.

### Relevant Deadlines ###
None

### Funding Source ###
2760811
### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones
- [x] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)
- [X] Define new issue for METdb to update the schema for met-9.1:
https://github.com/NCAR/METdb/issues/25
- [X] Define new issue for METviewer to handle the met-9.1 updates:
https://github.com/NCAR/METviewer/issues/185
- [X] Define new issue for METcalcpy to handle the met-9.1 updates:
https://github.com/NCAR/METcalcpy/issues/11

## New Feature Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [X] Complete the issue definition above.
- [X] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`: feature_1280_rps
- [X] Complete the development and test your changes.
- [X] Add/update unit tests: no new tests are needed.
- [X] Add/update documentation: updated the Lyx to Sphinx transition Google doc.
- [X] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**, listing the **\<Issue Number\>** in the title.
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.

**Comment by JohnHalleyGotway** [comment]
Test link to METplus/#213

**Comment by j-opatz** [comment]
Informed from CPC that primary score would be RPSS, which scores negative infinite to 1, with 1 being perfect skill. Possible choice to invert score orientation of RPS was to match the typical scale of skills scores and RPSS. Reaching out to EMC members for naming preference, possible option is "RPS (positive oriented)".

**Comment by j-opatz** [comment]
EMC has suggested naming conventions of "RPS + oriented" and "RPS - oriented" for RPS statistics.

**Comment by JohnHalleyGotway** [comment]
The existing RPS columns are named:
TOTAL, N_PROB, RPS_REL, RPS_RES, RPS_UNC, RPS, RPSS, and RPSS_SMPL

This issue will add another column for the quantity "1 - RPS".  RPS is a well-defined statistic between 0 and 1, with 0 being perfect.  As such, I recommend that we keep the existing RPS column name unchanged.

The recommended names, "rps + oriented" and "rps - oriented", would make more sense when used together, but less sense when used individually.  In probability-space, the value "1-p" is often called the "complement" of p.  Following that convention, I propose that we name our new column RPS_COMP, for the complement of the RPS statistic.

**Comment by JohnHalleyGotway** [comment]
On 4/28/20, confirmed with NCAR statisticians (Barb Brown and Eric Gilleland) and EMC scientists (Binbin Zhou) that naming the new column RPS_COMP is acceptable.  Per Binbin, we should install met-9.1_beta1 on venus or mars for him to test.

**Comment by JohnHalleyGotway** [comment]
The WWRP/WGNE Joint Working Group on Forecast Verification Research (https://www.cawcr.gov.au/projects/verification/) does include the following note about RPS:

_Range: 0 to 1.  Perfect score: 0.
Characteristics: Measures the sum of squared differences in cumulative probability space for a multi-category probabilistic forecast. Penalizes forecasts more severely when their probabilities are further from the actual outcome. **Negative orientation - can "fix" by subtracting RPS from 1**_

This negative orientation version of RPS is exactly what we added in the new RPS_COMP (for the complement of RPS).
