### ISSUE TITLE
MODE-Multivar boolean logic from config file

### ISSUE THREAD

**Issue by dwfncar** [dtcenter/MET#1282]
## Describe the Task ##
In mode_multivar.cc,
multivar_field_logic = "#1 && #2 && #3" should be set in the config file.
Development config file coincides with MODEMultivarConfig_default.

### Time Estimate ###
2 project days.

### Relevant Deadlines ###
04/30/2020 (in time for MET-9.1-beta1).

### Funding Source ###
779997 -- RAL Opportunity Fund: Dryline IR&D.

### Assignee ###
- [X] Select **engineer(s)** : David Fillmore
- [X] Select **scientist(s)** : Lindsay Blank

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)** : N/A

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones
- [X] Select **milestone**

## Define Related Issue(s) ##

Related to Issues:
- #1184 
- #1283 
- #1284 

## Task Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [X] Complete the issue definition above.
- [X] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the task and verify your changes.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**, listing the **\<Issue Number\>** in the title.
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
