### ISSUE TITLE
Enhance gen_vx_mask to support python embedding and more ways to specify the input grid.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1292]
## Describe the Enhancement ##
Enhance gen_vx_mask to support python embedding and more ways to specify the input grid.

(1) Testing of gen_vx_mask during the development of a METplus wrapper for it (NCAR/METplus#387) revealed that it does not support python embedding when using the "-input_field" or "-mask_field" options.  See below for commands that demonstrate this.  Enhance gen_vx_mask to support python embedding in both contexts.

(2) Rename the first argument to gen_vx_mask from "input_file" to "input_grid".  Be sure to update the usage statement, users guide, and online tutorial.  Port over the library code used to parse the "regrid.to_grid" config entry, minus the FCST and OBS options of course.  Enable "input_grid" to be defined as a gridded data file (current behavior), named grid (e.g. G003), or grid specification string.

Commands for testing:
- Python embedding with "-input_field":
```
> /usr/local/met-9.0/bin/gen_vx_mask PYTHON_NUMPY data/poly/CONUS.poly test_input_field.nc -input_field 'name="scripts/python/read_ascii_numpy.py data/python/fcst.txt FCST";'
DEBUG 1: Input File:		PYTHON_NUMPY
DEBUG 1: Mask File:		data/poly/CONUS.poly
ERROR  : 
ERROR  : Met2dDataFile::grid() -> no grid defined!
ERROR  : 
```
- Python embedding with "-mask_field":
```
> /usr/local/met-9.0/bin/gen_vx_mask data/sample_fcst/2005080700/wrfprs_ruc13_12.tm00_G212 PYTHON_NUMPY test_mask_field.nc -mask_field 'name="scripts/python/read_ascii_numpy.py data/python/fcst.txt FCST";' -thresh gt0 -type data
DEBUG 1: Input File:		data/sample_fcst/2005080700/wrfprs_ruc13_12.tm00_G212
DEBUG 1: Mask File:		PYTHON_NUMPY
DEBUG 2: Parsed Data Grid:	Lambert Conformal (185 x 129)
ERROR  : 
ERROR  : Met2dDataFile::grid() -> no grid defined!
ERROR  : 
```
- Set "input_grid" to a named grid:
```
 > /usr/local/met-9.0/bin/gen_vx_mask G003 /poly/CONUS.poly test_named_grid.nc
```
### Time Estimate ###
3 days

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
No sub-issues required.

### Relevant Deadlines ###
NONE

### Funding Source ###
NONE

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required (John HG)
- [X] Select **scientist(s)** or **no scientist** required (none required)

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones
- [X] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)
- [x] Coordinate development with METplus wrapper of gen_vx_mask (NCAR/METplus#387)

## Enhancement Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update unit tests.
Ran full regression test on changes on dakota:
```
cd /d3/projects/MET/MET_regression/feature_1292_gen_vx_mask
/d3/projects/MET/MET_development/git/MET/scripts/test_regression.sh \
develop-ref feature_1292_gen_vx_mask \
>& test_regression_develop-ref_vs_feature_1292.log
```
- [x] Add/update documentation: Listed here during transition from Lyx to Sphinx:
https://docs.google.com/document/d/1nCPBzu0eYognWWDHyocF3riuzydkF01N87cDWG3Bu0g
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**, listing the **\<Issue Number\>** in the title.
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.

**Comment by JohnHalleyGotway** [comment]
I made the necessary changes and added a new unit test to gen_vx_mask to exercise the python embedding functionality.  However, there is an underlying problem in how the grid "name" is passed along.  See below for an example of how the name gets garbled.  This occurs during the assignment operation on line 224 of src/libcode/vx_data2d_python/data2d_python.cc:
223
224 (*Dest_Grid) = (*Raw_Grid);
225

Here's the command that demonstrates this issue:
```
/Volumes/d1/projects/MET/MET_development/MET-feature_1292_gen_vx_mask/met/share/met/../../bin/gen_vx_mask \
PYTHON_NUMPY PYTHON_NUMPY PYTHON_FCST_or_OBS_mask.nc \
-type data \
-input_field 'name="met/python/read_ascii_numpy.py met/data/python/fcst.txt FCST";' \
-mask_field  'name="met/share/met/python/read_ascii_numpy.py met/data/python/obs.txt  OBS";' \
-thresh gt0 -union -v 3
...
DEBUG 2: Parsed Input Grid:	?h?? (185 x 129)
DEBUG 2: Parsed Mask Grid:	3r?? (185 x 129)
...
```
In both cases, the grid should be named 'FooGrid'.

**Comment by JohnHalleyGotway** [comment]
Fixed this grid name issue by updating the logic in the copy() function for the Grid classes:
https://github.com/NCAR/MET/commit/8c488ced41be88f7b5ad3f7ab30167cdeb6e1803

**Comment by JohnHalleyGotway** [comment]
The regression test ran successfully with the only difference being one new output file from unit_gen_vx_mask.xml:
   gen_vx_mask/PYTHON_FCST_or_OBS_mask.nc

And here's a plot of what that new mask looks like.
![PYTHON_FCST_or_OBS_mask](https://user-images.githubusercontent.com/21087144/78819782-ff623100-7993-11ea-9470-cc1781bb220e.png)
