### ISSUE TITLE
Create the met-9.0.1 bugfix release.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1311]
## Describe the Task ##
Create the met-9.0.1 bugfix release.
Update the version number from 9.0 to 9.0.1 and update the MET User's Guide.

### Time Estimate ###
1 hour.

### Sub-Issues ###
Consider breaking the task down into sub-issues.
No sub-issues.

### Relevant Deadlines ###
None

### Funding Source ###
2780541 - up to 7 hours

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required (John HG)
- [X] Select **scientist(s)** or **no scientist** required (none required)

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones
- [X] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)
No impacts to other repos, but will announce the met-9.0.1 bugfix release to other METplus components.

## Task Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [X] Complete the issue definition above.
- [X] Fork this repository or create a branch of **master_v9.0**.
Branch name:  `bugfix_<Issue Number>_master_<Version>_<Description>`
- [X] Complete the task and verify your changes.
- [X] Add/update unit tests - none required.
- [X] Add/update documentation - updates include changes to the user's guide.
- [X] Push local changes to GitHub.
- [X] Submit a pull request to merge into **master_v9.0**.
Pull request: `bugfix <Issue Number> master_<Version> <Description>`
- [X] Iterate until the reviewer(s) accept and merge your changes.
- [X] Delete your fork or branch.
- [x] Close this issue.

**Comment by JohnHalleyGotway** [comment]
On 4/23/20 after merging into develop, I restarted the NB to make sure no diffs are flagged between 9.0 and 9.0.1.
