### ISSUE TITLE
Fix MET to compile using PGI version 20.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1317]
## Describe the Task ##
As reported by a user via met-help (https://rt.rap.ucar.edu/rt/Ticket/Display.html?id=95051), met-9.0.1 does not compile using the PGI version 19 compilers.  The compilation error is in the vx_nc_obs library:
```
1 catastrophic error detected in the compilation of "nc_obs_util.cc".
Compilation aborted.
pgc++-Fatal-/usr/local/pgi/linux86-64-nollvm/19.10/bin/pggpp1 TERMINATED by signal 6
```

Julie Prestopnik tested using PGI 19.9 on Cheyenne and was able to replicate this compilation error.  This task is to update met-9.1 to once again compile using the PGI compilers.

You can find the test environment on cheyenne in /glade/p/ral/jntp/MET/MET_cross_platform_testing/met-9.0.1/pgi

Ideally, we could automate the testing of MET using PGI compilers via Docker containers, but there would likely be issues with the PGI license file.

### Time Estimate ###
1 day.

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- No sub-issues required.  I expect this to only require a small number of changes.

### Relevant Deadlines ###
None

### Funding Source ###
2760811

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [X] Select **scientist(s)** or **no scientist** required - no scientist required

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones
- [ ] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)
- No impacts to other METplus components.

## Task Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above.
- [ ] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [ ] Complete the task and verify your changes.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by jprestop** [comment]
Bart Brashers, who submitted the met-help ticket referenced in the issue, is willing to help test a PGI fix.

**Comment by jprestop** [comment]
Compiling with PGI version 19 is still problematic, however MET an its required external libraries compile well with PGI version 20.4.  This compilation was tested on Cheyenne at /glade/p/ral/jntp/MET/MET_cross_platform_testing/met-10.0.0-beta4/pgi.
