### ISSUE TITLE
Update the name attribute for the NetCDF matched pairs output from Grid-Stat.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1324]
## Describe the Enhancement ##
Modify the name attribute used in the gridded NetCDF matched pairs output files from Grid-Stat.

Currently the name attribute is written as the name of the field being processed and the name includes embedded whitespace.  Replace the name attribute with the actual variable name being written.

For example, here's some current sample output:
```
	float OBS_APCP_24_A24_CONUS(lat, lon) ;
		OBS_APCP_24_A24_CONUS:name = "APCP_24" ;
	float DIFF_APCP_24_A24_APCP_24_A24_DTC165(lat, lon) ;
		DIFF_APCP_24_A24_APCP_24_A24_DTC165:name = "Forecast APCP_24 minus Observed APCP_24" ;
```

Replace these with:
```
	float OBS_APCP_24_A24_CONUS(lat, lon) ;
		OBS_APCP_24_A24_CONUS:name = "OBS_APCP_24_A24_CONUS" ;
	float DIFF_APCP_24_A24_APCP_24_A24_DTC165(lat, lon) ;
		DIFF_APCP_24_A24_APCP_24_A24_DTC165:name = "DIFF_APCP_24_A24_APCP_24_A24_DTC165" ;
```
Having embedded whitespace would cause a problem if you read this data back into MET and we tried to write those columns to output .stat files.  

### Time Estimate ###
2 hours.

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- No sub-issues required.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required - no scientist required.

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones
- [X] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)
- No impacts to other repos.

## Enhancement Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above.
- [x] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.

**Comment by JohnHalleyGotway** [comment]
The branch was merged into develop via https://github.com/NCAR/MET/pull/1388.
I did expect the NB to fail because of the changes, but some of the diffs were unexpected. For example:
```
ERROR: NetCDF headers differ:
15c15
< 		FCST_edr_0_0_all_all_G212:name = "edr" ;
---
> 		FCST_edr_0_0_all_all_G212:name = "FCST_edr_0,0,*,*_G212" ;
29c29
```
We do not want the name attribute to include commas and stars. It's an easy to fix to actually use the variable name.

**Comment by JohnHalleyGotway** [comment]
Reconciled the differences to the name attribute in the NetCDF output of grid_stat in the nightly build. Updated develop-ref to get past these differences.
