### ISSUE TITLE
Fix parsing of timestamps in CF-compliant files produced by CDO.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1331]
## Describe the Enhancement ##
Running the cdo tool using the -import_binary option to read GraDS data produces a CF-compliant NetCDF output file.  However the MET tools are not able to parse the timestamps used therein.

Here is an example:

cdo -f nc import_binary 20190710H1radar.ctl 20190710H1radar.nc
plot_data_plane 20190710H1radar.nc r_lev_7000.ps 'name="r"; level="(0,14,*,*)";'

Only issue is this warning message:
WARNING: parse_cf_time_string() -> unexpected NetCDF CF convention time unit "hours since 1-1-1 00:00:00"

I ran the date command to double-check that the math is correct:
> date -ud '0001-01-01 UTC '17694048' hours' +%Y%m%d%H
2019071300

We just need to enable the year, month, and day to accept values of 1.

### Time Estimate ###
2 hours.

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
None required.

### Relevant Deadlines ###
None

### Funding Source ###
This is needed for the HAFS METplus use-case to enable MET to handle the output from cdo.
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required (John Halley Gotway)
- [X] Select **scientist(s)** or **no scientist** required (no scientist required)

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones
- [X] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)
No impacts.

## Enhancement Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above.
- [x] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update unit tests - no changes.
- [x] Add/update documentation - no changes.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.
