### ISSUE TITLE
Add useful gen_vx_mask error message when -type is used more than once.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1333]
## Describe the Enhancement ##
DTC scientists using the gen_vx_mask tool found it confusing that the gen_vx_mask tool only supports one masking "-type" option at a time. Add an error message when the user specifies "-type" more than once to point them in the right direction.

### Time Estimate ###
1 hour.

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
None required.

### Relevant Deadlines ###
None

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required (John Halley Gotway)
- [X] Select **scientist(s)** or **no scientist** required (Michelle Harrold)

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones
- [X] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)
No impacts

## Enhancement Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [X] Complete the issue definition above.
- [X] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [X] Complete the development and test your changes.
- [X] Add/update unit tests.
- [X] Add/update documentation.
- [X] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [ ] Close this issue.
