### ISSUE TITLE
point2grid: improve error message if the requested variable does not exist

### ISSUE THREAD

**Issue by hsoh-u** [dtcenter/MET#1338]
*Replace italics below with details for this issue.*

## Describe the Enhancement ##
The variables in the point observation NetCDF (generated by MET) can not be the field name for point2grid. The field name should come from the content of the "obs_var" variable or the GRIB code string. The available GRIB codes come from the content of "obs_vid" variable, too. The current error message only shows the cause. It does not help how to find the field name. It would be nice to show the available field names or GRIB codes along with the error message.

Here are John's suggestion:
  Try setting the "name" in the "-field" command line option to one of the available observations: APCP, TMP, RH
... or...
  Try setting the "name" in the "-field" command line option to one of the available GRIB codes: 61, 33, 34

### Time Estimate ###
4 hours

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- No sub-issues required

### Relevant Deadlines ###
NONE

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: (Howard)
- [ ] Select **scientist(s)** or **no scientist** required: no scientist required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones
- [x] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose) No impacts to other repos.

## Enhancement Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above.
- [ ] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
