### ISSUE TITLE
Support CF NetCDF input with lat/lon variable for point2grid

### ISSUE THREAD

**Issue by hsoh-u** [dtcenter/MET#1345]
*Replace italics below with details for this issue.*

## Describe the Enhancement ##
point2grid supports two input datasets: GOES16/17 and MET generated point observation data. It would be nice to support NetCDF file with lat/lon variable. There was an request via MET-HELP: https://rt.rap.ucar.edu/rt/Ticket/Display.html?id=95225. The other case will be the tri-polar grid work for Lindasy which used python embedding. One issue is finding lat/lon variables if not CF-complaint NetCDF. It be resolved by the configuration.

### Time Estimate ###
3 days

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
NONE.

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: (Howard)
- [x] Select **scientist(s)** or **no scientist** required: None

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones
- [x] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above.
- [ ] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by hsoh-u** [comment]
Fail to read UKMet_tripolar NetCDF (CF Complaint) because "deptht_bounds" was picked as the data variable which does not have the grid information (not related with lat/lon). Need to enhance the logic on picking the data variable.

        float deptht(deptht) ;
                deptht:units = "m" ;
                deptht:long_name = "Vertical T levels" ;
                deptht:bounds = "deptht_bounds" ;
                deptht:positive = "down" ;
                deptht:axis = "Z" ;
        float deptht_bounds(deptht, axis_nbounds) ;
        float nav_lat(y, x) ;
                nav_lat:units = "degrees_north" ;
                nav_lat:long_name = "Latitude" ;
                nav_lat:standard_name = "latitude" ;
                nav_lat:nav_model = "grid_T" ;
...

        float votemper(time_counter, deptht, y, x) ;
                votemper:_FillValue = 1.e+20f ;
                votemper:coordinates = "time_instant deptht nav_lon nav_lat" ;
                votemper:online_operation = "instant" ;
                votemper:interval_write = "1 h" ;
                votemper:cell_methods = "time: point (interval: 60 s)" ;
                votemper:units = "C" ;
                votemper:missing_value = 1.e+20f ;
                votemper:interval_operation = "60 s" ;
