### ISSUE TITLE
Provide a more descriptive error message when the user formats NetCDF timestamps incorrectly.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1347]
## Describe the Enhancement ##
The pcp_combine tool failed when Michelle Harrold passed it a CF-compliant NetCDF file with a timestring that was formatted slightly incorrectly. John Halley Gotway recommended that we add a check for this case and print a more useful error message.

### Time Estimate ###
4 hours.

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
No sub issues required.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
None

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required - John Halley Gotway
- [X] Select **scientist(s)** or **no scientist** required - None required.

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones
- [X] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)
No impacts to other repos.

## Enhancement Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [X] Complete the issue definition above.
- [x] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.

**Comment by JohnHalleyGotway** [comment]
Running plot_data_plane on the develop branch yields:
```
plot_data_plane gtg_obs_forecast.20130730.i00.f00.nc test.ps 'name="edr"; level="(20130730_00000,0,*,*)";'
ERROR  :
ERROR  : plot_data_plane -> trouble getting field "name="edr"; level="(20130730_00000,0,*,*)";" from file "gtg_obs_forecast.20130730.i00.f00.nc"
ERROR  : 
```
Note that the timestring is missing a trailing 0. Since it's not one of the supported time string formats, it's passed to the "atoi()" function to be parsed as an integer.

Update the logic in var_info_nccf.cc to...
(1) Call is_datestring() to check for supported time strings. If true, convert the timestring to unixtime.
(2) Otherwise, if the string is entirely numeric, call atoi() to parse it as an integer.
(3) Otherwise, error out with this message:

```
ERROR  : 
ERROR  : VarInfoNcCF::set_magic() -> trouble parsing NetCDF dimension value "20130730_00000"!
ERROR  : 
```
