### ISSUE TITLE
Read IODA file by MET

### ISSUE THREAD

**Issue by hsoh-u** [dtcenter/MET#1355]
#1269  Describe the Enhancement ##
JEDI has IODA converter which converts the raw input data to IODA file. The github for IODA converter has the sample output IODA files (https://github.com/JCSDA/ioda-converters/tree/develop/test/testoutput). MET should read the IODA file (at least, IODA file for ODB).

### Time Estimate ###
3 days

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
Dec 2021

### Funding Source ###
2799991

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required (Howard)
- [x] Select **scientist(s)** or **no scientist** required (Will)

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones
- [ ] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above.
- [ ] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by hsoh-u** [comment]
Use "datetime@MetaData" for time info and ignore "time@metadata".

From: Will Mayfield
Btw on the time variables, datetime "old style" was used for a relative time to analysis, meaning plus or minus in decimal value in hours. Now datetime is in an iso standard with yearmonthday time etc string format. Relative plusminus time is now sometimes optionally stored in time@metadata but may not be used by jedi.
