### ISSUE TITLE
Fortify issues from met-9.0.2 scan.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1359]
## Describe the Enhancement ##
The Fortify scan of the met-9.0.2 release identified 25 issues in the code:
- 20 of them in point2grid.cc are fixed by #1352 
- The issue is to fix the other 5 issues, listed below:

![Screen Shot 2020-06-03 at 2 50 32 PM](https://user-images.githubusercontent.com/21087144/83687944-cb794580-a5a9-11ea-8bbe-f6453972705b.png)

### Time Estimate ###
1 day

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
No sub-issues required.

### Relevant Deadlines ###
None

### Funding Source ###
None

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required: John Halley Gotway
- [X] Select **scientist(s)** or **no scientist** required: None required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones
- [X] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)
No impacts to other repos.

## Enhancement Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above.
- [ ] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
In addition to the 5 issues listed above, recent development in the develop branch caused a spike of 65 new issues. A breakdown of the findings from 20200610 versus 20200611 is shown in the table below. Also fix as many of these increased issue counts as possible.

  | 20200610 | 20200611 | Delta
-- | -- | -- | --
Buffer   Overflow | 37 | 75 | 38
Buffer   Overflow: Signed Comparison | 1 | 1 | 0
Code   Correctness: Memory Free on Stack Variable | 4 | 4 | 0
Command   Injection | 7 | 7 | 0
Dangerous   Function: strcpy() | 56 | 56 | 0
Dead Code | 149 | 149 | 0
Double Free | 10 | 0 | -10
Format String | 50 | 50 | 0
Integer   Overflow | 85 | 115 | 30
Memory Leak | 21 | 21 | 0
Missing Check   against Null | 24 | 24 | 0
Null   Dereference | 1 | 1 | 0
Obsolete | 19 | 19 | 0
Out-of-Bounds   Read | 4 | 4 | 0
Out-of-Bounds   Read: Off-by-One | 2 | 2 | 0
Path   Manipulation | 1 | 7 | 6
Poor Style:   Redundant Initialization | 1 | 1 | 0
Poor Style:   Value Never Read | 23 | 27 | 4
Poor Style:   Variable Never Used | 82 | 90 | 8
Race   Condition: File System Access | 4 | 4 | 0
Redundant Null   Check | 321 | 321 | 0
Setting   Manipulation | 12 | 12 | 0
String   Termination Error | 164 | 164 | 0
System   Information Leak: Internal | 232 | 232 | 0
Type Mismatch:   Signed to Unsigned | 4 | 4 | 0
Unchecked   Return Value | 20 | 20 | 0
Uninitialized   Variable | 1 | 2 | 1
Use After Free | 12 | 0 | -12
  |   |   |  
Total | 1347 | 1412 | 65
