### ISSUE TITLE
Enhance Series-Analysis to print a warning about a common misconfiguration.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1372]
## Describe the Enhancement ##
Enhance Series-Analysis to print a warning about common misconfiguration. There were 2 questions via met-help in the past week about configuring Series-Analysis:
https://rt.rap.ucar.edu/rt/Ticket/Display.html?id=95583
https://rt.rap.ucar.edu/rt/Ticket/Display.html?id=95398

In both cases, the user defined the cat_thresh and/or cnt_thresh options inside the first entry of the fcst.field array. However, the code parses those from the fcst and obs level of context. As a result, the default values of NA are used. This is a bit confusing since in Point-Stat and Grid-Stat they can be set separately for each field array entry whereas in Series-Analysis, they can only be set once for the entire series.

This task it to check for this condition and print a very descriptive warning message about it. However, this is a bit tricky because of the config file lookup logic of reading higher and higher levels of context. Recommend the following:
(1) For the fcst dictionary, parse the cat_thresh and cnt_thresh settings from the top level of context.
(2) When parsing each entry of the field array, execute a lookup for the cat_thresh and cnt_thresh.
(3) If those settings differ from the actual fcst level settings, print a detailed warning message.
(4) Apply the same logic to the obs dictionary.

### Time Estimate ###
4 hours.

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
None required.

### Relevant Deadlines ###
None

### Funding Source ###
None

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [X] Select **scientist(s)** or **no scientist** required: None required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones
- [x] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above.
- [x] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.

**Comment by JohnHalleyGotway** [comment]
Made the change in the feature_1372_series_analysis branch and tested in dakota:/d3/personal/johnhg/MET/MET_development/MET-feature_1372_series_analysis. To test, I added cat_thresh and cnt_thresh inside the field array entry and was able to produce these warning messages:
```
WARNING: 
WARNING: SeriesAnalysisConfInfo::process_config() -> "cat_thresh" should be specified in the fcst dictionary, not within each fcst.field array entry!
WARNING: 
WARNING: 
WARNING: SeriesAnalysisConfInfo::process_config() -> "cnt_thresh" should be specified in the fcst dictionary, not within each fcst.field array entry!
WARNING: 
WARNING: 
WARNING: SeriesAnalysisConfInfo::process_config() -> "cat_thresh" should be specified in the obs dictionary, not within each obs.field array entry!
WARNING: 
WARNING: 
WARNING: SeriesAnalysisConfInfo::process_config() -> "cnt_thresh" should be specified in the obs dictionary, not within each obs.field array entry!
WARNING:
```

Next, I removed them and reran to confirm that those warnings do not appear when configured properly.

**Comment by JohnHalleyGotway** [comment]
Made the requested change in the feature_1372_series_analysis branch and reproduced the warning messages, as listed below:
```
WARNING: 
WARNING: SeriesAnalysisConfInfo::process_config() -> "cat_thresh" should be specified in the top level of the fcst dictionary, not within each fcst.field array entry!
WARNING: 
WARNING: 
WARNING: SeriesAnalysisConfInfo::process_config() -> "cnt_thresh" should be specified in the top level of the fcst dictionary, not within each fcst.field array entry!
WARNING: 
WARNING: 
WARNING: SeriesAnalysisConfInfo::process_config() -> "cat_thresh" should be specified in the top level of the obs dictionary, not within each obs.field array entry!
WARNING: 
WARNING: 
WARNING: SeriesAnalysisConfInfo::process_config() -> "cnt_thresh" should be specified in the top level of the obs dictionary, not within each obs.field array entry!
WARNING: 
```
