### ISSUE TITLE
Enhance TC-Gen to print warnings about duplicate genesis events for the same storm.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1380]
## Describe the Enhancement ##
When running TC-Gen, Dan Adriaansen found a discrepancy between the number of BEST track genesis events reported (209) versus the number of unique lat/lon locations listed in the log file (202). Genesis at the same lat/lon location and time were counted twice seven times. In all 7 cases, genesis was identified both in the INVEST and the numbered storm. This can easily be avoided by ignoring the INVEST track files or by setting a minimum category threshold, such as:
   category = [ "TD", "TS"]; 

To make the code more user-friendly, identify these situations and print a warning message about them. Then the user can decide how to proceed. 

For example, the first duplicate occurs in these 2 files...
kiowa:/d1/dadriaan/projects/s2s/tc/data/weiwei/obs/allvigh> egrep "119N, 1416W," b*
bcp012018.dat:CP, 01, 2018092618,   , BEST,   0, 119N, 1416W,  25, 1008, DB,   0,    ,    0,    0,    0,    0, 1009,  180,  50,   0,   0,    ,   0,    ,   0,   0,     INVEST,  , 
bcp972018.dat:CP, 97, 2018092618,   , BEST,   0, 119N, 1416W,  25, 1008, DB,   0,    ,    0,    0,    0,    0, 1009,  180,  50,   0,   0,    ,   0,    ,   0,   0,     INVEST,  , 

And the second duplicate occurs in these 2 files:
kiowa:/d1/dadriaan/projects/s2s/tc/data/weiwei/obs/allvigh> egrep "145N,  832W," b*
bal142018.dat:AL, 14, 2018100418,   , BEST,   0, 145N,  832W,  20, 1007, DB,   0,    ,    0,    0,    0,    0, 1009,  100,  90,   0,   0,    ,   0,    ,   0,   0, GENESIS036,  ,  0,    ,    0,    0,    0,    0, genesis-num, 036, 
bal912018.dat:AL, 91, 2018100418,   , BEST,   0, 145N,  832W,  20, 1007, DB,   0,    ,    0,    0,    0,    0, 1009,  100,  90,   0,   0,    ,   0,    ,   0,   0, GENESIS036,  ,  0,    ,    0,    0,    0,    0, genesis-num, 036, 

## Time Estimate ###
4 hours.

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- No sub-issues needed.

### Relevant Deadlines ###
NONE

### Funding Source ###
TC-Gen Project

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required: John Halley Gotway
- [X] Select **scientist(s)** or **no scientist** required: Dan Adriaansen

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones
- [X] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)
No impacts.

## Enhancement Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above.
- [x] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.
