### ISSUE TITLE
Print Series-Analysis warning for verbosity >= 3.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1382]
## Describe the Enhancement ##
This suggestion arose via met_help:
https://rt.rap.ucar.edu/rt/Ticket/Display.html?id=95583

Running Series-Analysis at verbosity level >= 3 results in voluminous logging output, especially when using the cnt_thresh setting. When the user sets verbosity >= 3, print a warning message about this.

### Time Estimate ###
2 hours

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- None required.

### Relevant Deadlines ###
None

### Funding Source ###
None

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required - John Halley Gotway
- [X] Select **scientist(s)** or **no scientist** required - No scientist required

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones
- [X] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)
None required.

## Enhancement Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above.
- [x] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
