### ISSUE TITLE
Additional testing and refinement of the Grid-Diag tool.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1391]
## Describe the Enhancement ##
Bri Nelson and Michelle Harrold ran into issues running the Grid-Diag tool. I ran their commands and agree that some cleanup is needed. This task is to do that cleanup, add more error checking, and make the tool more user-friendly with better log messages.

Bri originally reported this error message:
ERROR  : DataPlane::two_to_one() -> range check error: (Nx, Ny) = (0, 0), (x, y) = (0, 0)

The tool was unable to read the data that was requested, didn't check whether the read was successfully, and tried to regrid an empty dataset to a new grid. That resulted in this error message.

The tasks for this work include, but are not limited to:
(1) Check that each attempt to read gridded data is successful. If not, print a warning message and continue.
(2) Enhance the NetCDF output file to make it more self-describing, adding global and variable attributes as needed.
(3) Make sure the output variable names do not include the use of stars and comma's, which happens when reading NetCDF input files.
(4) Review existing log messages at all verbosity levels and tweak them to make them more user friendly.
(5) Remove any unnecessary development code.
(6) Review existing documentation and update as needed.
(7) Review existing unit tests and update as needed.
 
### Time Estimate ###
3 days.

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
No clear sub-issues yet. I hope to complete this is less than 1 week.

### Relevant Deadlines ###
None

### Funding Source ###
7790971 UIUC S2S

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required: John Halley Gotway
- [X] Select **scientist(s)** or **no scientist** required: Michelle Harrold

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones
- [X] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)
No impacts.

## Enhancement Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above.
- [x] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.

**Comment by JohnHalleyGotway** [comment]
Getting started on this work by reproducing the behavior Bri described on cheyenne:
```
/glade/p/ral/jntp/MET/MET_releases/9.0/bin/grid_diag \
-data /gpfs/fs1/p/ral/jntp/GMTB/ufs_global_tne/ops_GFS/pcp_24h/2020031512/metprd/pcp_combine_24h/gfs.t12z.pgrb2.0p25.f120_a24h \
-out /gpfs/fs1/p/ral/jntp/GMTB/ufs_global_tne/grid_diag/grid_diag_out_ops_GFS_f120.nc \
-config /gpfs/fs1/p/ral/jntp/GMTB/ufs_global_tne/parm/met/GridDiagConfig_use
ERROR  : DataPlane::two_to_one() -> range check error: (Nx, Ny) = (0, 0), (x, y) = (0, 0)
```

**Comment by JohnHalleyGotway** [comment]
I'm feeling pretty good about the code cleanup and log messages. But I have a few questions and am looking for more direction:

(1) The config file has an entry for "model" but that isn't actually used anywhere. Should I remove it, or should I keep it, and write it as a global attribute of the NetCDF output file?

(2) The config file includes entries to define a masking region. While the mask is processed, it is NOT actually applied to the data! I assume that I should apply a masking region, if specified? And I should write out the mask name as a global attribute to the NetCDF output file. If none is specified, I'll write "FULL" to indicate that the full domain was processed.

(3) Below, I've listed the header of the NetCDF output file. I think I should add global attributes to make it more self-describing, including:

- model (from above)

- vx_mask (from above)

- FileOrigins, MET_version (V9.1), and MET_tool (grid_diag)... similar to NetCDF matched pairs output files from Grid-Stat.

- Since this data is no longer gridded, I don't *think* we need to include any grid information. What do you think? I could add the dimensions of input grid and/or the number of grid points included in the masking region.

- What other information, particularly variable attributes, should be added? Perhaps name and long_name?

Think about this from the perspective of plotting. If you wrote a script to read this NetCDF file and wanted to plot the histograms, what other metadata would you like present to potentially include on your plot? Perhaps min/max init times, valid time, or lead times? Or add actual variables for each to list the length of the series and the init, valid, and lead time for each entry in the series?

**Comment by JohnHalleyGotway** [comment]
- Added global attributes for FileOrigins, MET_version, MET_tool, model, mask_grid, and mask_poly (like series_analysis).

- Added 1d variables for grid_size, mask_size, and n_series (like series_analysis).

- Ensured that the mask_area is actually being applied.

- Added long_name attributes for all output variables.

- Added global attributes for init_beg, init_end, valid_beg, valid_end, lead_beg, and lead_end (like series_analysis).

- Still need to add another call in unit_grid_diag.xml to process multiple time steps.

**Comment by JohnHalleyGotway** [comment]
Michelle requested via email that the "model" config option be renamed to "desc" (for description). Using "desc" provides for a more generic description of the data source whereas "model" implies forecast data and "obtype" implies analysis or observation data.

**Comment by JohnHalleyGotway** [comment]
Michelle, I made the 2 changes we discussed and have updated/recompile on cheyenne for you to test:
/glade/p/ral/jntp/MET/MET_development/MET-feature_1391_grid_diag/met/bin/grid_diag

(1) "model" in the config file has been replaced with "desc".
(2) If "-data" is used once, all input fields are read from each input file. If "-data" is used multiple times, it must match the number of fields in the config file... and the n-th field is read from the n-th file list.

The second change was pretty big. Along the way, I made the processing more efficient, removing unnecessary multiple reads of data. I also updated the log messages somewhat.

Please re-test using multiple input file lists to confirm that it works the way you expect and review the log messages.

**Comment by michelleharrold** [comment]
I tested the new functionality, and it worked as expected!

(1) desc works as intended

(2) Tested -data fairly extensively, and it works as intended

For record, here is a command line argument I issues to run with multiple files (on cheyenne):
/glade/p/ral/jntp/MET/MET_development/MET-feature_1391_grid_diag/met/bin/grid_diag 
-data /gpfs/fs1/p/ral/jntp/GMTB/ufs_global_tne/ops_GFS/pcp_24h/2020031512/metprd/pcp_combine_24h/gfs.t12z.pgrb2.0p25.f120_a24h/gpfs/fs1/p/ral/jntp/GMTB/ufs_global_tne/ops_GFS/pcp_24h/2020031100/metprd/pcp_combine_24h/gfs.t00z.pgrb2.0p25.f120_a24h 
-data /gpfs/fs1/p/ral/jntp/GMTB/ufs_global_tne/ops_GFS/gfs.20200315/12/gfs.t12z.pgrb2.0p25.f120 /gpfs/fs1/p/ral/jntp/GMTB/ufs_global_tne/ops_GFS/gfs.20200311/00/gfs.t00z.pgrb2.0p25.f120 -out grid_diag_multfiles_ops_GFS_f120.nc 
-config GridDiagConfig

**Comment by JohnHalleyGotway** [comment]
PR #1426 merged this into the develop branch. This change broke the NB since it modified the existing unit_grid_diag.xml output and added 2 new output files. After inspecting the diffs and verifying they were correct, I updated the develop-ref tag to move past them.

**Comment by JohnHalleyGotway** [comment]
I am reopening this issue. Testing for #1279 revealed the need to tweak some of the Grid-Diag log messages.

(1) Grid-Diag checks the range of the full field of data without subsetting based on the user-defined mask. We should subset first!
(2) If the range of the data from (1) falls outside the user-specified range, it prints a warning message for each file. That's too verbose. Instead track the min/max values across all input files for each field and report debug level 2 info about it.
