### ISSUE TITLE
Enhance the MET compilation script and its documentation

### ISSUE THREAD

**Issue by jprestop** [dtcenter/MET#1395]
Enhance the compilation script and its documentation.

## Describe the Enhancement ##
* DONE - Remove --enable-modis from configure when COMPILE_HDF = 0 and COMPILE_HDFEOS=0 (need to account for when using an existing build of HDF and HDFEOS and not compiling)
* DONE - Create defaults for default BUFRLIB_NAME and GRIB2CLIB_NAME
* DONE - Changes George suggested in Slack
** cp include/*.h ${LIB_DIR}/include/. : line 443 you could remove the . at the end. The copy fails if you already instealled HDFEOS and you try to rerun the script. The 2nd time the files weren't overwritten in $LIB_DIR/include.
** Line 667: You could change to: if [ "${SET_D64BIT}" == "TRUE" ]; then; There were no quotes around ${SET_D64BIT} so if that is unset accidentally, it would evaluate to "" and fail the if test. Without it, you get a unary operator error; That could be applied to other checks for environment variables that may not be set by the user
**CLARIFIED IN DOCUMENTATION UPDATES - in the example install_met_env.kiowa file, I suggest commenting out the 2nd section of variables and change the comment to say uncomment if you have already compiled these. I was being hasty and didn't read the comment, so it skipped all of those and failed.
* DONE - Add syntax to check if path exists (eliminating extra colons) when adding to, for example, LDFLAGS
**export PATH=/usr/local/anaconda3/bin${PATH:+:$PATH}
**export PYTHONPATH=${PYTHONPATH:+$PYTHONPATH:}${HOME}/git/ConfigMaster
* DONE - Add LIBPNG_LIB to LDFLAGS (and potentially other libs) (this fixed Logan's MRMS problem on WCOSS)
* DONE - Add option for --bindir call to MET
* DONE - Improve documentation for script based on changes above which will simplify a recalling of the script
* CLARIFIED IN DOCUMENTATION - Add comments for each var to the install_env_<machine>.conf files or just to the generic file
* DONE - "python --version" should really be "${MET_PYTHON}/bin/python --version"
* DONE - Add check for GNU version 10. If 10 or greater, have ‘-fallow-argument-mismatch' in BUFRLIB compilation.   If less than 10, have ‘-Wno-argument-mismatch'' in BUFRLIB compilation.  

### Time Estimate ###
*Estimate the amount of work required here.*
1 - 3 days of work.

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
Split 2771021 AF and 2700042 WPC

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required (Julie Prestopnik)
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones
- [x] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above.
- [ ] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by jprestop** [comment]
Added ability for MET_GSL to be read in and have GSL compiled if MET_GSL is not set.
