### ISSUE TITLE
Enhance point2grid to process multiple fields and update the usage statement and documentation to list supported options for the -method command line argument.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1396]
## Describe the Task ##
Based on this met-help question: https://rt.rap.ucar.edu/rt/Ticket/Display.html?id=95747
The point2grid tool fails to list the supported options for -method. Update both the usage statement and documentation to list them. Line 300 of https://github.com/NCAR/MET/blob/master_v9.0/met/src/tools/other/point2grid/point2grid.cc
indicates that they are MIN, MAX, MEDIAN, and UW_MEAN. However we could also clarify when/how Gaussian interpolation is applied.

### Time Estimate ###
2 hours

### Sub-Issues ###
Consider breaking the task down into sub-issues.
None required.

### Relevant Deadlines ###
NONE

### Funding Source ###
NONE

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones
- [ ] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above.
- [ ] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [ ] Complete the task and verify your changes.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
Also, replace the Description documentation block at the top of the point2grid.cc file, which was clearly copied/pasted over from regrid_data_plane.cc:

```
//   Description:
//      This tool reads 2-dimensional fields from a gridded input file,
//      regrids them to the user-specified output grid, and writes the
//      regridded output data in NetCDF format.
```

**Comment by JohnHalleyGotway** [comment]
Also note that the point2grid tool claims to support the specification of multiple input fields:
```
	"-field string" may be used multiple times to define the data to be regridded (required).
```
However, specifying more than one field results in this runtime error:
```
ERROR  : process_point_file() -> Support only 1 variable. "2" variables were requested.
```
Either correct the functionality of the tool to match the description or correct the usage statement and documentation to match the functionality.

**Comment by hsoh-u** [comment]
Added unittest point2grid_pb2nc_methods with different valid time
