### ISSUE TITLE
Ensemble-Stat runtime error when obs_thresh <= CDP10 results in 0 pairs being used.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1397]
## Describe the Enhancement ##
Binbin Zhou from NOAA/EMC pointed out a runtime error he is seeing from the Ensemble-Stat tool. He is applying multiple obs_thresh filtering options, as shown below:
```
obs_thresh = [ <=CDP10, >CDP10&&<=CDP20, >CDP20&&<=CDP30, >CDP30&&<=CDP40, >CDP40&&<=CDP50, >CDP50&&<=CDP60, >CDP60&&<=CDP70, >CDP70&&<=CDP80, >CDP80&&<=CDP90, >CDP90 ];
```
However, Ensemble-Stat exits with the following error message:
```
DEBUG 2: Processing gridded verification HGT/P500 versus HGT/P500, for observation type ANALYS, over region TRP, for interpolation method NEAREST(1), using 2448 matched pairs.
DEBUG 3: Using 0 of 2448 ensemble pairs for observation filtering threshold <=CDP10.
ERROR  :
ERROR  : RPSInfo::set(const PairDataEnsemble &) -> no thresholds provided to compute the RPS line type! Specify thresholds using the "prob_cat_thresh" configuration file option.
ERROR  :
```
Since 0 pairs survive the obs_thresh filtering of <=CDP10, I would guess that Ensemble-Stat just isn't handling this degenerate case correctly. Need to replicate this behavior, add more checking, and prevent this error condition from occurring so that Ensemble-Stat can run to completion.

### Time Estimate ###
2 days

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
No sub-issues required.

### Relevant Deadlines ###
None

### Funding Source ###
None

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required: John Halley Gotway
- [X] Select **scientist(s)** or **no scientist** required: John Optaz

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones
- [X] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)
No impacts to other repositories.

## Enhancement Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above.
- [x] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
