### ISSUE TITLE
Add new version of the anomaly correlation statistic to the CNT line type.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1399]
## Describe the New Feature ##
Binbin Zhou from NOAA/EMC discovered a discrepancy between between the anomaly correlation reported by MET and what's reported by VSDB. He created this plot to illustrate the large differences:
![plot_20200628_185930-AC-trop](https://user-images.githubusercontent.com/21087144/86187489-234b9380-baf9-11ea-882e-869cf5406be4.png)

Binbin created a small test case to illustrate the differences between MET and VSDB. John Halley Gotway explored that test case, confirmed that the ensemble mean, climo mean, and analysis values matched for all of the 14,760 grid points in the Tropical region (+/-20 degrees latitude).

Please see:
http://www.atmos.albany.edu/daes/atmclasses/atm401/spring_2016/ppts_pdfs/ECMWF_ACC_definition.pdf

The link above clarifies the source of the difference. The EMC global ensembles group is computing anomaly correlation without including the mean error while MET is using the WMO version which does include the mean error. Both are useful and both should be included in the CNT line type. However, the current definition for ANOM_CORR in Appendix C of the MET User's Guide is NOT correct. It lists the non-mean-error variant when it should list the EMC variant.

This task is to add new output columns for the non-mean-errror AC statistic to the CNT output line type. Correct the contents of the MET User's Guide to reflect this change.

### Time Estimate ###
1 day.

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- No sub-issues needed.

### Relevant Deadlines ###
None

### Funding Source ###
None

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required
- [X] Select **scientist(s)** or **no scientist** required

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones
- [X] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)
- New GitHub issues are needed for METviewer and METdatadb.
METviewer: https://github.com/NCAR/METviewer/issues/194
METdb: https://github.com/NCAR/METdb/issues/29

## New Feature Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above.
- [x] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.

**Comment by JohnHalleyGotway** [comment]
Please see:
http://www.atmos.albany.edu/daes/atmclasses/atm401/spring_2016/ppts_pdfs/ECMWF_ACC_definition.pdf

**Comment by JohnHalleyGotway** [comment]
After adding ANOM_CORR_RAW, running a regression test to compare against develop in kiowa:/d1/projects/MET/MET_pull_requests/met-9.1_beta2/feature_1399.

**Comment by JohnHalleyGotway** [comment]
Reopening this issue since a name change was requested, to rename ANOM_CORR_RAW to ANOM_CORR_UNCNTR to clarify that this is the uncentered version of the anomaly correlation which does not account for the mean error.
