### ISSUE TITLE
Clarifiy GAUSSIAN and MAXGAUSS documentation for point2grid

### ISSUE THREAD

**Issue by hsoh-u** [dtcenter/MET#1413]
## Describe the Enhancement ##
The interpolation method MAXGAUSS is the combination of MAX interpolation and GAUSSIAN interpolation. It's different meaning at the point2grid. Only four interpolations are applied to the raw data and GAUSSIAN is only applied to probability variable only. This difference was not described well.

One alternative is MAXGAUSS does the same with regrid_data_plane. MAX and GAUSSIAN interpolation to the selected variable. And the same behavior with GAUSSIAN method (only into the probability variables).

### Time Estimate ###
3 hours

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
NONE

### Funding Source ###
NONE

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required (Howard)
- [x] Select **scientist(s)** or **no scientist** required (None)

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones
- [x] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above.
- [ ] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
Please make updates here:
https://github.com/NCAR/MET/tree/task_1217_lyx_to_sphinx/met/docs/Users_Guide

**Comment by hsoh-u** [comment]
I put the documentation into "PDF/Web Documentation Comparison Chapter Sign Up Sheet". And merged back to develop branch with task_1217_lyx_to_sphinx branch.

**Comment by JohnHalleyGotway** [comment]
Howard,

Julie just merged task_1217 into develop yesterday. Can you please check
the develop branch to confirm that your changes are included?

John

**Comment by hsoh-u** [comment]
I confirmed MAXGAUSS was added into the develop branch
