### ISSUE TITLE
Check for inconsistent setting of flags (-D__64BIT__) in MET and the GRIB2C library

### ISSUE THREAD

**Issue by jprestop** [dtcenter/MET#1416]
## Describe the Enhancement ##
When the GRIB2 flags are set inconsistently, MET’s GRIB2 library code thinks it needs to read a ridiculously large amount of memory. We want to find that spot, add a sanity check, and print a warning message message if requesting an unreasonable amount of memory. Don't make it an error message on the off chance that whatever size threshold we choose is too small for some user.  This issue comes up often enough in met_help issues where it seems worthwhile to add a check in the code.

Can test using the data in /d3/personal/jpresto/met_help/shilpi_kalra_20200712.
Run: pcp_combine -subtract WRFPRS_d01.48 48 WRFPRS_d01.24 24 APCP.nc
Compile a version of MET where there is inconsistent setting of the -D__64BIT__  flag between the GRIB2C library and MET.

### Time Estimate ###
4 hours.

### Sub-Issues ###
No sub-issues needed.

### Relevant Deadlines ###
NONE

### Funding Source ###
NONE

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required: John Halley Gotway
- [X] Select **scientist(s)** or **no scientist** required: No scientist needed

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones
- [x] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above.
- [x] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.

**Comment by JohnHalleyGotway** [comment]
Testing on dakota in /d3/personal/johnhg/MET/MET_development/MET-feature_1416_64bit.
I had been compiling on dakota using:
```
CFLAGS=-g -DUNDERSCORE -fPIC -D__64BIT__
CXXFLAGS=-g -DUNDERSCORE -fPIC -D__64BIT__
```
For this work, I removed the -D__64BIT__ flag from these settings and recompiled and tested by running:
```
/d3/personal/johnhg/MET/MET_development/MET-feature_1416_64bit/met/bin/pcp_combine -subtract \
/d3/personal/jpresto/met_help/shilpi_kalra_20200712/WRFPRS_d01.48 48 \
/d3/personal/jpresto/met_help/shilpi_kalra_20200712/WRFPRS_d01.24 24 \
APCP.nc

ERROR  : 
ERROR  : out of memory!  Exiting!
ERROR  :
```

**Comment by JohnHalleyGotway** [comment]
Added a new oom_grib2() function and call set_new_handler() to point to it inside the GRIB2 library code. Retest to produce this new out of memory error message:
```
ERROR  : 
ERROR  : Out of memory reading GRIB2 data!  Exiting!
ERROR  : Check that MET and the GRIB2C library were compiled consistently, either with or without the -D__64BIT__ flag.
ERROR  : 
```
