### ISSUE TITLE
Enhance the performance of point2grid

### ISSUE THREAD

**Issue by hsoh-u** [dtcenter/MET#1421]
## Describe the Enhancement ##
Jemie Wolff reported point2grid took less than 1 minute with HRRR domain (1799 by 1059)  but it took more than 40 minutes with GFS domain (3072 by 1536) at Cheyenne.
HRRR case, the data is mapped to 1.7M grid cells (out of 1.8 M cells). GFS case,  mapped to 3.1 M grid cells (out of 4.5 M cells).

Commands to load:

module use /glade/p/ral/jntp/MET/MET_releases/modulefiles
module load met/9.0
setenv MET_TMP_DIR /glade/p/ral/jntp/AF/cloud_vx/goes_data/test_met

To HRRR grid:

point2grid /glade/p/ral/jntp/AF/cloud_vx/goes_data/level2/abi_tb_fd_2020070300_C13_G16.nc /glade/p/ral/jntp/AF/cloud_vx/model_data/HRRR/2020060800-05/hrrr.t00z.wrfprsf01.grib2 test_hrrr_chey.nc -field 'name="tb"; level="(*,*)";' -v 3

To GFS grid:

point2grid /glade/p/ral/jntp/AF/cloud_vx/goes_data/level2/abi_tb_fd_2020070300_C13_G16.nc /glade/p/ral/jntp/AF/cloud_vx/model_data/GFS/gfs.20200608/00/gfs.t00z.special.grb2f001 test_gfs_chey.nc -field 'name="tb"; level="(*,*)";' -v 3

### Time Estimate ###
4 to 8 hours

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
NONE.

### Funding Source ###
2791541

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required (Howard)
- [x] Select **scientist(s)** or **no scientist** required (None)

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones
- [ ] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above.
- [ ] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by hsoh-u** [comment]
The bottleneck is building cell mapping. The main factor seems to be the resolution of TO_GRID rather than the resolution of FROM_GRID:
- GOES: 5424 by 5424 (about 25M)
- GFS: 3072 by 1536 (about 4.5 M)
- G212: 185 by129

Not sure how to improve the performace.
Currently IntArray is used. So there is 4.5M members of IntArray and 25M cells are mapped to 4.5M cells. And most time was spent on building cell mapping.

**Comment by hsoh-u** [comment]
Another test data is UKMet_tripolar at /d3/personal/hsoh/data/MET-1492/UKMet_tripolar/prodm_op_gl.dm3d.grid_T_20200907_00.036_temp.nc
