### ISSUE TITLE
Change formatting of the values shown in the colorbar of plot_data_plane from %f to %g.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1423]
## Describe the Enhancement ##
This a one line change in data_plane_plot.cc. Replace %f with %g when formatting the values plotted next to the color bar in the output of the plot_data_plane tool.

This was requested by Lindsay Blank when plotting very small PV values using plot_data_plane.

### Time Estimate ###
1 hour.

### Sub-Issues ###
No sub-issues required.

### Relevant Deadlines ###
None.

### Funding Source ###
None.

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required: John Halley Gotway
- [X] Select **scientist(s)** or **no scientist** required: Lindsay will review the pull request.

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones
- [X] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)
No impacts.

## Enhancement Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above.
- [x] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.

**Comment by JohnHalleyGotway** [comment]
Made the one line change. This will likely impact the output of MET's nightly build.

See the impact of this change by running:
```
plot_data_plane ../../../../data/sample_fcst/2005080700/wrfprs_ruc13_12.tm00_G212 ~/Desktop/plot1.ps 'name="TMP"; level="P500"; convert(x)=x/1000000;'
plot_data_plane ../../../../data/sample_fcst/2005080700/wrfprs_ruc13_12.tm00_G212 ~/Desktop/plot2.ps 'name="TMP"; level="P500"; convert(x)=x/10000000;'
```
Note the values next to the colorbar in the attached plots.
![plot1](https://user-images.githubusercontent.com/21087144/88237038-9dc08c80-cc3b-11ea-8474-004393b59a42.png)
![plot2](https://user-images.githubusercontent.com/21087144/88237043-a1ecaa00-cc3b-11ea-8c66-8b58d4b98e5d.png)
