### ISSUE TITLE
Update the logic for parsing ASCII file lists to make them work with python embedding.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1432]
##  Describe the Enhancement ##
Enhance the logic of parse_ascii_file_list() to check whether the first "word" matches "file_list" in a case-insensitive way. If so, parse and return the rest of the strings without actually checking to see if those strings exist as files on the system. If not, employ the existing logic in that function.

Update the MET User's Guide with this information.

The background is that the introduction of python embedding has impacted the logic of parsing file lists.
When testing python embedding with ensemble_stat, John Opatz ran into an issue when using an input ascii file list:
```
cat 20160815000000_12_ensemble.txt
icap_2016081500_aod.nc:total_aod:201608151200:0
icap_2016081500_aod.nc:total_aod:201608151200:1
icap_2016081500_aod.nc:total_aod:201608151200:2
icap_2016081500_aod.nc:total_aod:201608151200:3
icap_2016081500_aod.nc:total_aod:201608151200:4
icap_2016081500_aod.nc:total_aod:201608151200:5
icap_2016081500_aod.nc:total_aod:201608151200:6
```
This file list contains file names followed by variable names, time stamps, and integesr. But ensemble_stat errors out with:
```
ERROR  : process_command_line() -> no valid input ensemble member files specified!
```
The existing parse_ascii_file_list() function checks that at least 1 of the first 10 words exists as a file on the system. If not, it assumes that it is NOT an ascii file list and therefore returns an empty list. In John Opatz's example, none of these strings are actually file names on the system. This logic does not work well for python embedding, in general, and the new "file_list" keyword provides a way to explicitly tell MET how the strings should be handled.

### Time Estimate ###
4 hours.

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
No sub-issues required.

### Relevant Deadlines ###
None.

### Funding Source ###
None.

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required: John Halley Gotway
- [X] Select **scientist(s)** or **no scientist** required: John Opatz

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones
- [X] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)
No impacts.

## Enhancement Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above.
- [x] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.

**Comment by JohnHalleyGotway** [comment]
I compiled a version of MET with this proposed change on eyewall in:
/d1/johnhg/MET/MET_development/MET-feature_1432_file_list/met

Rerunning the sample command George sent to me (with updated paths and inputs) now works:
```
export CLIMO_MEAN_FILE=""; export CLIMO_STDEV_FILE=""; export ENS_FIELD="{ name=\"/d1/projects/nrl_aerosol/forecast_embedded.py MET_PYTHON_INPUT_ARG\"; }"; export ENS_FILE_TYPE="file_type = PYTHON_NUMPY;"; export ENS_THRESH="0.1"; export FCST_FIELD="{ name=\"/d1/projects/nrl_aerosol/forecast_embedded.py MET_PYTHON_INPUT_ARG\"; }"; export FCST_FILE_TYPE="file_type = PYTHON_NUMPY;"; export FCST_LEAD="012"; export INPUT_BASE="/d1/projects/nrl_aerosol/input"; export MET_OBS_ERROR_TABLE=""; export MODEL="ICAP"; export OBS_FIELD="{ name=\"/d1/projects/nrl_aerosol/analysis_embedded.py /d1/projects/nrl_aerosol/input/AGGR_HOURLY_20160815T1200_1deg_global_archive.nc aod_nrl_total Mean\"; }"; export OBS_FILE_TYPE="file_type = PYTHON_NUMPY;"; export OBS_WINDOW_BEGIN="0"; export OBS_WINDOW_END="0"; export OBTYPE="nrl_aod"; export OUTPUT_PREFIX=""; export REGRID_TO_GRID="NONE";
export MET_TMP_DIR=/tmp;
export MET_PYTHON_EXE=/home/met_test/.conda/envs/metplus_env/bin/python;

echo file_list > ens_file_list.txt
cat /d1/projects/nrl_aerosol/mp_work/embedded/stage/file_lists/20160815000000_12_ensemble.txt | sed 's/ /:/g' >> ens_file_list.txt

/d1/johnhg/MET/MET_development/MET-feature_1432_file_list/met/bin/ensemble_stat -v 4 ens_file_list.txt /d1/projects/nrl_aerosol/mp_work/EnsembleStatConfig_Embedding -grid_obs PYTHON_NUMPY -outdir /d1/projects/nrl_aerosol/mp_work/embedded/201608150000/ensemble_stat
```

**Comment by JohnHalleyGotway** [comment]
I updated Appendix F to include:

The Ensemble-Stat, Series-Analysis, and MTD tools support the use of file lists on the command line, as do some other MET tools. Typically, the ASCII file list contains a list of files which actually exist on your machine and should be read as input. For Python embedding, these tools loop over the ASCII file list entries, set MET_PYTHON_INPUT_ARG to that string, and execute the Python script. This only allows a single command line argument to be passed to the Python script. However multiple arguments may be concatenated together using some delimiter, and the Python script can be defined to parse arguments using that delimiter. When file lists are constructed in this way, the entries will likely not be files which actually exist on your machine. In this case, users should place the constant string "file_list" on the first line of their ASCII file lists. This will ensure that the MET tools will parse the file list properly.
