### ISSUE TITLE
Fix point_stat compiler warnings.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1435]
## Describe the Task ##
Fix the following compiler warning from point_stat:
```
point_stat.cc:831:53: warning: array comparison always evaluates to false [-Wtautological-compare]
         is_ugrd = ( use_var_id &&         var_name == ugrd_abbr_str ) ||
                                                    ^
point_stat.cc:833:53: warning: array comparison always evaluates to false [-Wtautological-compare]
         is_vgrd = ( use_var_id &&         var_name == vgrd_abbr_str ) ||
                                                    ^
```
This warning indicates that the correct logic is not being applied.

### Time Estimate ###
1 hour.

### Sub-Issues ###
Consider breaking the task down into sub-issues.
No sub-issue required.

### Relevant Deadlines ###
None.

### Funding Source ###
None.

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required: John Halley Gotway
- [X] Select **scientist(s)** or **no scientist** required: None required

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones
- [X] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)
No impacts.

## Task Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above.
- [ ] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [ ] Complete the task and verify your changes.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
