### ISSUE TITLE
Enhance the validation of masking regions to check for non-unique masking region names.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1439]
## Describe the Enhancement ##
This issue arose via met-help: https://rt.rap.ucar.edu/rt/Ticket/Display.html?id=96043

The user passed configured Point-Stat to apply 18 different masking regions that are output from gen_vx_mask. However, all of them had the default "data_mask" variable name. When he ran Point-Stat he got 0 pairs for all masks because only the last of the 18 masking regions was actually being used.

This behavior can be found here in Point-Stat:
https://github.com/NCAR/MET/blob/0cee9fbd0b3c691fd3cf4dd1d665f5d2b0db9a37/met/src/tools/core/point_stat/point_stat_conf_info.cc#L306

It can be replicated by running Point-Stat using 2 masks that are different but share the same name. Only the last mask will actually be applied.

This task is to do several things:
(1) In Point-Stat when processing masking regions, check to see if the mask name is already in use. If it is, make sure the existing mask and the new mask are identical. If not, print an error message about the problem and exit.
(2) Find and fix the same problem in Grid-Stat.
(3) Investigate the other tools to see if the problem exists there as well.

### Time Estimate ###
1 day

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
No sub-issues needed.

### Relevant Deadlines ###
None.

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: John HG
- [x] Select **scientist(s)** or **no scientist** required: No scientist required

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones
- [X] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)
No impacts.

## Enhancement Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above.
- [x] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.
