### ISSUE TITLE
Enhance Ensemble-Stat log messages.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1440]
## Describe the Task ##
Add a log message to Ensemble-Stat to indicate which -grid_obs file is being read.

This arose via met-help:
https://rt.rap.ucar.edu/rt/Ticket/Display.html?id=96084

It would be helpful for Ensemble-Stat to indicate the file from which verifying observations are being read.

### Time Estimate ###
1 hour.

### Sub-Issues ###
Consider breaking the task down into sub-issues.
No sub-issues required.

### Relevant Deadlines ###
None

### Funding Source ###
None

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required: John Halley Gotway
- [X] Select **scientist(s)** or **no scientist** required: none

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones
- [X] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)
No impacts.

## Task Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above.
- [x] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [x] Complete the task and verify your changes.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.

**Comment by JohnHalleyGotway** [comment]
The log messages from the ensemble_stat test script from "make test" now include this useful message:
```
DEBUG 2: Reading gridded observation for APCP/A24 from file: ../data/sample_obs/ST4/ST4.2010010112.24h
```
