### ISSUE TITLE
Enhance tc_gen to support file lists for the -genesis and -track command line options.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1442]
## Describe the Enhancement ##
Enhance tc_gen to support file lists for the -genesis and -track command line options.

### Time Estimate ###
1 day.

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
No sub-issues required.

### Relevant Deadlines ###
None

### Funding Source ###
None

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required: John Halley Gotway with George McCabe to review.
- [X] Select **scientist(s)** or **no scientist** required

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones
- [X] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)
No impacts.

## Enhancement Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [X] Complete the issue definition above.
- [X] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [X] Add/update unit tests.
- [X] Add/update documentation.
- [X] Push local changes to GitHub.
- [X] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [X] Iterate until the reviewer(s) accept and merge your changes.
- [X] Delete your fork or branch.
- [X] Close this issue.

**Comment by JohnHalleyGotway** [comment]
The usage statement for tc_gen to indicate that -genesis and -track can be set to file_lists:
```
Usage: tc_gen
	-genesis path
	-track path
	-config file
	[-out base]
	[-log file]
	[-v level]

	where	"-genesis path" is one or more ATCF genesis files, an ASCII file list containing them, or a top-level directory with files matching the regular expression "atcf_gen" (required).
		"-track path" is one or more ATCF track files, an ASCII file list containing them, or a top-level directory with files matching the regular expression ".dat" for the verifying BEST and operational tracks (required).
		"-config file" is used once to specify the TCGenConfig file containing the desired configuration settings (required).
		"-out base" overrides the default output file base (./tc_gen) (optional).
		"-log file" outputs log messages to the specified file (optional).
		"-v level" overrides the default level of logging (2) (optional).
```
