### ISSUE TITLE
Alert users to the renaming of AVN to GFS in MET tropical cyclone tools.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1444]
## Describe the Task ##
This minor issue arose via met-help:
https://rt.rap.ucar.edu/rt/Ticket/Display.html?id=96109

In the MET tropical cyclone library code, all instances of "AVN" in ATCF ID's are automatically renamed to "GFS" (e.g. AVNO is renamed to GFSO). This issue is to add log messages to alert the user to this behavior.
 
This occurs in the code here:
https://github.com/NCAR/MET/blob/0cee9fbd0b3c691fd3cf4dd1d665f5d2b0db9a37/met/src/libcode/vx_tc_util/atcf_line_base.cc#L236

Make the following changes:
(1) If the user requests in their config file, a model name that includes "AVN", print a WARNING message about the behavior.
(2) If any AVN does actually occur in the input ATCF files, print a DEBUG(1) message about this behavior. But make sure to only print that message once.
(3) Make sure this behavior is clearly documented in the user's guide.

### Time Estimate ###
2 hours.

### Sub-Issues ###
Consider breaking the task down into sub-issues.
No sub-issues required.

### Relevant Deadlines ###
None.

### Funding Source ###
None.

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required: John Halley Gotway
- [X] Select **scientist(s)** or **no scientist** required: Lindsay Blank should do the PR review.

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones
- [X] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)
No impacts.

## Task Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above.
- [x] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [x] Complete the task and verify your changes.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.

**Comment by JohnHalleyGotway** [comment]
I updated...
- The documentation
- The parsing of the model config file option for tc_gen and tc_pairs. If AVN appears in the list, a warning is printed.
- The processing of the ATCF model names. If AVN appears, a DEBUG(1) message is written once explaining that AVN is automatically replaced with GFS.

**Comment by JohnHalleyGotway** [comment]
To test, I modified: test/config/TCPairsConfig_ALAL2010
model = [ "OFCL", "AVNO", "HWFI", "ABCAVNDEF" ];

Running the first command from unit_tc_pairs.xml produces the expected 2 warnings:
```
/Volumes/d1/projects/MET/MET_development/MET-develop/met/share/met/../../bin/tc_pairs       -adeck /Volumes/d1/projects/MET/MET_unit_test/MET_test_input/tc_data/adeck/*2010.dat       -bdeck /Volumes/d1/projects/MET/MET_unit_test/MET_test_input/tc_data/bdeck/*2010.dat       -config /Volumes/d1/projects/MET/MET_development/MET-develop/test/config/TCPairsConfig_ALAL2010       -out /Volumes/d1/projects/MET/MET_unit_test/MET_test_output/tc_pairs/alal2010       -log /Volumes/d1/projects/MET/MET_unit_test/MET_test_output/tc_pairs/tc_pairs_ALAL2010.log       -v 2
 
WARNING: parse_conf_tc_model() -> Requesting tropical cyclone model name "AVNO" will yield no results since "AVN" is automatically replaced with "GFS" when reading ATCF inputs.
WARNING: parse_conf_tc_model() -> Requesting tropical cyclone model name "ABCAVNDEF" will yield no results since "AVN" is automatically replaced with "GFS" when reading ATCF inputs.
```

Additional testing using AVNO input track data produces the expected log message:
```
DEBUG 1: When reading ATCF track data, all instances of "AVN" are automatically replaced with "GFS" (ATCF ID = AVNI).
```

**Comment by JohnHalleyGotway** [comment]
Updated with Kathryn's PR feedback which results in the updated warning message:
```
WARNING: parse_conf_tc_model() -> Requesting tropical cyclone model name "AVNI" will yield no results since "AVN" is automatically replaced with "GFS" when reading ATCF inputs. Please use "GFS" in the "model" entry of the configuration file to read/process "AVN" entries.
```
