### ISSUE TITLE
Correct the tc_gen BEST track genesis event definition.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1447]
## Describe the Enhancement ##
Dan Halperin did more testing of the tc_gen tool with the met-9.1_beta3 development release and found a bug. tc_gen is not identifying genesis at the correct point for BEST tracks. Test this using bal022019.dat. The BEST track genesis is identified when the storm is a disturbance (category=DB) rather than the correct time when it is a tropical depression (category=TD), as requested in the TC-Gen configuration file:

```
best_genesis = {
   technique   = "BEST";
   category    = [ "TD", "TS" ];
   vmax_thresh = NA;
   mslp_thresh = NA;
}
```

### Time Estimate ###
1 day.

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
No sub-issues required.

### Relevant Deadlines ###
None.

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required: John Halley Gotway
- [X] Select **scientist(s)** or **no scientist** required: Kathryn Newman

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones
- [X] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)
No impacts.

## Enhancement Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above.
- [x] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.

**Comment by JohnHalleyGotway** [comment]
Input from Dan H showing examples of bug (1) where genesis is identified at the wrong time:

![image](https://user-images.githubusercontent.com/21087144/89667029-9da9c900-d898-11ea-8b3f-4820b73cf536.png)

**Comment by JohnHalleyGotway** [comment]
I found the bug in tc_gen.cc on this line:

https://github.com/NCAR/MET/blob/10c4da8ba90c5f85416ae86a0e68c1ab29d1a0ce/met/src/tools/tc_utils/tc_gen/tc_gen.cc#L588

This adds the track to the list of Genesis events without specifying the track point at which genesis actually occurred. The library code just chooses the first track point. Instead, pass a second argument indicating the genesis track point.

Used this BEST track to test:
[bal022019.txt](https://github.com/NCAR/MET/files/5043043/bal022019.txt)

Prior to the fix, GenesisTime = "20190710_120000":
```
DEBUG 6: |    [1] GenesisInfo: IsSet = true, IsBest = true, IsOper = false, IsAnly = false, StormId = "AL022019", Basin = "AL", Cyclone = "02", StormName = "BARRY", TechniqueNumber = -9999, Technique = "BEST", Initials = "(nul)", GenesisTime = "20190710_120000", InitTime = "NA", LeadTime = "000000", Lat = 28.50000, Lon = -86.50000, DLand = 92.24668, NPoints = 25, MinValidTime = "20190710_120000", MaxValidTime = "20190716_060000", MinWarmCoreTime = "NA", MaxWarmCoreTime = "NA"
```
After the fix, GenesisTime = "20190711_000000":
```
DEBUG 6: |    [1] GenesisInfo: IsSet = true, IsBest = true, IsOper = false, IsAnly = false, StormId = "AL022019", Basin = "AL", Cyclone = "02", StormName = "BARRY", TechniqueNumber = -9999, Technique = "BEST", Initials = "(nul)", GenesisTime = "20190711_000000", InitTime = "NA", LeadTime = "000000", Lat = 27.80000, Lon = -87.60000, DLand = 118.85302, NPoints = 25, MinValidTime = "20190710_120000", MaxValidTime = "20190716_060000", MinWarmCoreTime = "NA", MaxWarmCoreTime = "NA"
```
And that matches the time and location of the first instance of category = TD in the ATCF input file:
```
AL, 02, 2019071100,   , BEST,   0, 278N,  876W,  30, 1008, TD,   0,    ,    0,    0,    0,    0, 1013,  180,  80,  35,   0,   L,   0,    ,   0,   0,        TWO, M,  0,    ,    0,    0,    0,    0, genesis-num, 005,
```
