### ISSUE TITLE
Enhance MET to error out when reading CF-compliant NetCDF data with incomplete grid definition.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1454]
## Describe the Enhancement ##
This issue arose during the DTC AF cloud project. A user ran wgrib2 to export a HRRR GRIB2 record to NetCDF format. The output NetCDF file claims to follow the CF-1.0 convention. And MET's plot_data_plane tool is able to plot that file... however, the grid definition is incorrect.

This task is to replicate this behavior and enhance the grid parsing code in the vx_data_nccf library by adding more error checking. MET should error out when reading this file and print a useful error message indicating that the projection information cannot be read.

Sample commands to demonstrate this issue:
```
mv nam_prmsl.grib2.txt nam_prmsl.grib2
wgrib2 -netcdf nam_prmsl.nc nam_prmsl.grib2 
plot_data_plane nam_prmsl.grib2 nam_prmsl.grib2.ps 'name="PRMSL"; level="L0";'
plot_data_plane nam_prmsl.nc nam_prmsl.nc.ps 'name="PRMSL_meansealevel"; level="(0,*,*)";'
```
[nam_prmsl.grib2.txt](https://github.com/NCAR/MET/files/5064964/nam_prmsl.grib2.txt)

Here's the correct projection from GRIB2.
![nam_prmsl grib2](https://user-images.githubusercontent.com/21087144/90054516-34abc200-dc99-11ea-9b58-b45d50b435a4.png)

And here's the incorrect one using the NetCDF output of wgrib2.
![nam_prmsl nc](https://user-images.githubusercontent.com/21087144/90054626-5c9b2580-dc99-11ea-972b-57917e0bfa7d.png)

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones
- [ ] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above.
- [ ] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop** and link the pull request to this issue..
Pull request: `feature <Issue Number> <Description>`
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by hsoh-u** [comment]
I'm not sure what causes the differences.
The plottings by IDV are also slightly different.

GRIB2: min/max = 952 to 1052
NetCDF:  min/max = 99,232 to 104,215

IDV Plot of the NetCDF converted by wgrib2:
![nam_prmsl_nc_raw_idv](https://user-images.githubusercontent.com/15203106/108447150-9f2b5500-721c-11eb-9baa-133a1992c59a.png)

IDV Plot of the NetCDF converted by wgrib2 (The range for the color table is changed to match GRIB2 plot):
![nam_prmsl_nc_idv](https://user-images.githubusercontent.com/15203106/108446130-e0226a00-721a-11eb-9434-7d746a4b3c57.png)

IDV Plot of the GRIB2 before converting:
![nam_prmsl_grib2_idv](https://user-images.githubusercontent.com/15203106/108446308-24156f00-721b-11eb-86be-b78480235c9e.png)

**Comment by hsoh-u** [comment]
IDV Plot of the NetCDF converted by wgrib2 (the contour interval was reduced to 200Pa from500Pa): 
![nam_prmsl_nc_raw_idv_200](https://user-images.githubusercontent.com/15203106/108447950-085f9800-721e-11eb-8096-ac4bb768f09f.png)

IDV Plot of the NetCDF converted by wgrib2 (The range for the color table is changed. the contour interval was reduced to 200Pa from500Pa):
![nam_prmsl_nc_idv_200](https://user-images.githubusercontent.com/15203106/108448148-6be9c580-721e-11eb-878f-96e70fd97887.png)

IDV Plot of the GRIB2 before converting (the contour interval was reduced to 200Pa from500Pa):
![nam_prmsl_grib2_idv_2](https://user-images.githubusercontent.com/15203106/108448250-95a2ec80-721e-11eb-8b1c-566040eefdd9.png)

**Comment by JohnHalleyGotway** [comment]
@hsoh-u you are pointing out that the VALUES before/after the conversion to NetCDF are different. And I agree that they do appear to be... but that isn't the point of this issue. This issue is not about debugging the wgrib2 NetCDF conversion functionality. The output of this wgrib2 dump contains 2d latitude and longitude variables. It is assuming that this is simply a lat/lon grid, but it is not! It's Lambert Conformal.

Trying to process nam_prmsl.nc in MET should result in an error. We need more validation and error checking when processing 2D lat/lon variables. It can only be a lat/lon grid if the latitude and longitude values remain constant for each row (or column?).

So the problem is that MET's assumption that this data in on a lat/lon projection is WRONG.

**Comment by hsoh-u** [comment]
Issue 1: MET is looking for the "grid_mapping" attributes which should provide the projection information (about Lambert Conformal). The wgrib2 output does not have a variable with "grid_mapping" attribute. MET ignores the standard_name "projection_x_coordinate" and "projection_y_coordinate".

Issue 2: The data variable "PRMSL_meansealevel" has the "coordinates" attributes and they are  "longitude latitude". Processing this as lat/lon is a CF way.

        float PRMSL_meansealevel(time, y, x) ;
                PRMSL_meansealevel:_FillValue = 9.999e+20f ;
                PRMSL_meansealevel:short_name = "PRMSL_meansealevel" ;
                PRMSL_meansealevel:long_name = "Pressure Reduced to MSL" ;
                PRMSL_meansealevel:level = "mean sea level" ;
                PRMSL_meansealevel:units = "Pa" ;
                PRMSL_meansealevel:coordinates = "longitude latitude" ;

**Comment by hsoh-u** [comment]
The current value of DELTA_TOLERANCE for sanity checking is 15.0. This is too big for lat/lon projection (may work for the Lambert Conformal). What's the tolerance for Lat/Lon projection for sanity check?

**Comment by JohnHalleyGotway** [comment]
Fixed by PR #1688.
