### ISSUE TITLE
Documentation Updates

### ISSUE THREAD

**Issue by jprestop** [dtcenter/MET#1455]
## Describe the Task ##
Clean up the documentation

[PDF/Web Documentation Comparison Chapter Sign Up Sheet - Things for the next version](https://docs.google.com/document/d/1fqxbxU23wXWEGTTkp7ZPRw40g93OLn7YdqPjXB5jKLY/edit?ts=5f1a4de5#)

### Time Estimate ###
1 to 3 days of work for each sub task

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [x] Correct spelling errors
- [x] Hanging indents for references
- [x] Make bolding consistent
- [x] Make references to Appendices consistent
- [x] Make references to external web pages consistent
- [x] Move README and README_TC contents to Sphinx

### Relevant Deadlines ###
Next MET release

### Funding Source ###
?

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones
- [x] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above.
- [ ] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [ ] Complete the task and verify your changes.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop** and link the pull request to this issue.
Pull request: `feature <Issue Number> <Description>`
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
Julie, FYI, PR #1474 broke the Docker build. Here's the log:
https://hub.docker.com/repository/registry-1.docker.io/dtcenter/met/builds/f24be0ea-b738-4826-b862-e869484cf9c9
```
Compiling MET develop and writing log file /met/MET-develop/make_install.log
[91mmake[2]: *** No rule to make target `README', needed by `all-am'. Stop.
[0m[91mmake[1]: *** [install-recursive] Error 1
[0m[91mmake: *** [install-recursive] Error 1
```
Please take a look in met/data/config/Makefile.am
Try removing references to README since that's gone. When "README_TC" goes away, we'll need to remove that from Makefile.am as well.

**Comment by jprestop** [comment]
This issue is nearing completion.  Current things to be completed are consistent bolding of config arguments to the various tools and consistent italicizing of directories.

**Comment by jprestop** [comment]
Final pull request was approved and merged.  Closing issue.
