### ISSUE TITLE
Move MET repository from the NCAR to DTCenter organization.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1462]
## Describe the Task ##

Move the MET repository from the NCAR organization to the DTCenter organization. The GitHub URL needs to be updated in many locations:
```
grep "github.com\/NCAR" `find ./ -type f` | cut -d":" -f1 | sort -u
.//.git/logs/HEAD
.//.git/logs/refs/heads/master_v9.0
.//.git/logs/refs/remotes/origin/HEAD
.//.github/ISSUE_TEMPLATE/bug_report.md
.//.github/ISSUE_TEMPLATE/enhancement_request.md
.//.github/ISSUE_TEMPLATE/new_feature_request.md
.//.github/ISSUE_TEMPLATE/task.md
.//met/data/version.txt
.//met/docs/Users_Guide/appendixF.rst
.//met/docs/Users_Guide/index.rst
.//met/docs/Users_Guide/overview.rst
.//met/docs/Users_Guide/release-notes.rst
.//met/share/met/version.txt
.//scripts/docker/Dockerfile
.//scripts/met_checkout_and_build.sh
.//scripts/run_fortify_sca.sh
.//scripts/run_fortify_sca_nightly.sh
.//scripts/test_nightly.sh
.//scripts/test_regression.sh
.//scripts/test_unit.sh
```

These changes should be made to both the develop and master_v9.1 branches.

After the documentation updates are complete, re-push the met-9.1 User's Guide to GitHub pages.

### Time Estimate ###
2 hours.

### Sub-Issues ###
Consider breaking the task down into sub-issues.
No sub-issues required.

### Relevant Deadlines ###
None

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required: John Halley Gotway
- [X] Select **scientist(s)** or **no scientist** required: No scientist required

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones
- [X] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)
This change does not affect the other repositories, but similar changes will be required in those repos.

## Task Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above.
- [x] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [x] Complete the task and verify your changes.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop** and link the pull request to this issue.
Pull request: `feature <Issue Number> <Description>`
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.

**Comment by JohnHalleyGotway** [comment]
On 8/18/20, I actually moved the MET repo from the NCAR to DTCenter organization through GitHub. Details listed below:

1. Make the move on GitHub
In GitHub, edit the “NCAR/MET” repository settings. Under “Danger Zone”, click the “Transfer” button to transfer the ownership.
New org name = DTCenter
Team access: select “METplus” and “MET Developers”
Note that https://github.com/NCAR/MET now automatically redirects to https://github.com/dtcenter/MET. But I don’t know how long that redirect will persist.

2. GitHub DTCenter/MET updates
Edit “DTCenter/MET” settings “Manage access”
Grant “MET Developers” team write access
Confirm “METplus” team has read access
Remove individual user names who had been listed as outside collaborators under the NCAR organization (except those listed as “Admin”)

3. MET website updates
Update the “MET version 9.1” documentation link on https://dtcenter.org/community-code/model-evaluation-tools-met/documentation to point to https://dtcenter.github.io/MET/
Update the tarball download, user’s guide, and release notes URL’s for versions 9.1 and 9.0.3 on https://dtcenter.org/community-code/model-evaluation-tools-met/download by switching NCAR to dtcenter.
NOTE MORE CHANGES REQUIRED AFTER MOVING METPLUS AND METVIEWER.

4. DockerHub updates
Reconfigure automated builds for https://hub.docker.com/repository/docker/dtcenter/met/builds/edit
Select organization = dtcenter and repo = MET.
The previously defined automated builds repopulated.
Select “Save and Build”

5. Reclone the repo from it’s new location
```
git clone https://github.com/dtcenter/MET
```

6. Update existing repo to point to new location
```
git remote -v
git remote set-url origin https://github.com/dtcenter/MET
git remote -v
```
Did this for all my development repositories on musial6. Also updated the repos used by the NB on dakota in /d3/projects/MET/MET_regression for MET-develop and MET-master_v9.1.

**Comment by JohnHalleyGotway** [comment]
Updated from github.com/NCAR to github.com/dtcenter using the following commands:
```
grep "github.com\/NCAR" `find ./ -type f` | cut -d":" -f1 | sort -u | egrep -v '/logs/' > file_list

for file in `cat file_list`; do
  cat $file | sed 's/github.com\/NCAR/github.com\/dtcenter/g' > new
  mv new $file
done
rm file_list
```

**Comment by JohnHalleyGotway** [comment]
I forgot to make 2 additional changes:
- change ncar.github.io to dtcenter.github.io
- rename METdb to METdatadb
