### ISSUE TITLE
Enhance Ensemble-Stat, Stat-Analysis, TC-Pairs, and TC-Stat to print log messages with rejection reason counts.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1481]
## Describe the Enhancement ##
This is likely too large of an issue. It should probably be broken down into 4 separate development issues; one each for Ensemble-Stat, Stat-Analysis, TC-Pairs, and TC-Stat

This issue arose out of a met-help question (https://rt.rap.ucar.edu/rt/Ticket/Display.html?id=96458) from a user trying to figure out why TC-Pairs used 0 input ATCF lines via METplus. Ultimately, 0 lines were used because the model requested in the config file did not match the model string present in the input ATCF data. This task is to enhance these 4 tools to print log messages with reason codes listing why point observations or input data lines were not used in the analysis. This is very similar to the logic in Point-Stat in which verbosity level 3 (-v 3) prints such counts. The tasks are as follows:

* Enhance Ensemble-Stat to report rejection reason counts at verbosity level 3 for each verification task when processing point observations.
* Enhance Stat-Analysis to report rejection reason counts at verbosity level 3 for each job for the .stat lines processed.
* Enhance TC-Pairs to report rejection reason counts at verbosity level 3 for the ATCF lines processed.
* Enhance TC-Stat to report rejection reason counts at verbosity level 3 for each job for the .tcst lines processed.

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones
- [ ] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above.
- [ ] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop** and link the pull request to this issue..
Pull request: `feature <Issue Number> <Description>`
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
@j-opatz and @JohnHalleyGotway discussed this over Slack on 4/19/21. This feature would have saved John O time because it would have shown him that his "-alpha 0.05" setting was causing all the PCT lines to be discarded. Recommend modeling the verbosity 3 log messages after Point-Stat output:
```
DEBUG 2: Number of lines used      = 0
DEBUG 2: Number of input lines     = 1000
DEBUG 2: Rejected: -alpha          = 1000
...
```
But only log the non-zero rejection reason counts to keep the log messages tidy. Could have the same logic as Point-Stat... print them at verbosity level 3. Or at verbosity level 2 when 0 lines are used.
For Stat-Analysis, we'd mostly need to add logic to this "is_keeper()" function:
https://github.com/dtcenter/MET/blob/develop/met/src/libcode/vx_analysis_util/stat_job.cc#L642

But the big concern is whether or not adding this tracking logic would make the code run much slower. If possible, do some stress testing to make sure it doesn't cause a significant hit to the runtime.
