### ISSUE TITLE
Supporting unsigned data type for the input NetCDF files

### ISSUE THREAD

**Issue by hsoh-u** [dtcenter/MET#1492]
MET does not support the unsigned data types for NetCDF file. MET only supported the unsigned values by applying "_Unsigned" attribute at the signed data type. Ho-Chun reported the data type changes at GOES16 AOD daata (https://rt.rap.ucar.edu/rt/Ticket/Display.html?id=96687). It's changed to the "unsigned short" and the "unsigned byte" type without "_Unsigned" attribute. The point2grid does not work with new AOD data file.

## Describe the New Feature ##
MET library should support unsigned data types (unsigned byte/short/int/int64) and point2grid should check if the the data type is signed or unsigned before reading the NetCDF variables.

### Acceptance Testing ###
point2grid should process the new GOES data file (dakota:/d3/personal/hsoh/data/RT-96687/OR_ABI-L2-AODC-M6_G16_s20202581441152_e20202581443525_c20202581445493.nc)

### Time Estimate ###
2 or 3 days

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
NONE

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required (Howard)
- [x] Select **scientist(s)** or **no scientist** required (None)

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones
- [x] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## New Feature Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by hsoh-u** [comment]
How to handle a missing value for unsigned data type?
MET sets -9999 if the missing value is not given..

**Comment by JohnHalleyGotway** [comment]
> How to handle a missing value for unsigned data type?
> MET sets -9999 if the missing value is not given..

Howard, I assumed we were enhancing MET to READ unsigned data type inputs but STORE them into DataPlane objects as doubles. If that's the case, storing bad data as -9999 would not be a problem. But if there's a particular line of code or function that's causing a problem in the logic, please point me to it.

**Comment by JohnHalleyGotway** [comment]
On 10/15/2020, I recreated the develop-ref tag to get past the addition to the unit tests for this work.

But it was actually a little messier than that. On kiowa in NB20201015, the regression test for develop-ref actually failed because of bug #1508. So I manually ran comp_dir.sh to compare NB20201014/develop-ref (which succeeded) to NB20201015/develop. The only difference was the addition of one new output file:

ERROR: folder ../NB20201014/MET-develop-ref/test_output missing 1 files
    point2grid/point2grid_GOES_16_AOD_TO_G212_unsigned.nc
