### ISSUE TITLE
Enhance MET NetCDF library code to handle time variables of type byte.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1493]
## Describe the Enhancement ##
This issue arose when attempting to read a new dataset into MET in preparation for physics testing in HAFS. Kathryn Newman is the contact person for this work.

CYGNSS data (level 3 surface wind data) in NetCDF format can be found here:
https://podaac.jpl.nasa.gov/dataset/CYGNSS_L3_V2.1

The NetCDF level 3 data is gridded and is on a lat/lon grid... so no projection details with which to contend. I grabbed a sample data file and ran:
```
plot_data_plane cyg.ddmi.s20200803-003000-e20200803-233000.l3.grid-wind.a10.d21.nc wind_speed.ps 'name="wind_speed"; level="(0,*,*)";'
ERROR  : 
ERROR  : get_double_var() -> data type mismatch (double vs. "byte").
ERROR  : It won't be converted because of dimension issue.
ERROR  : Please correct the data type to double for variable "time".
ERROR  :
```
After running ncdump/ncgen to manually change the time variable from type byte to double, plot_data_plane reads this data just fine and produces this image:
![wind_speed](https://user-images.githubusercontent.com/21087144/93268648-c3b16b80-f76a-11ea-9c22-8fe2359b2a48.png)

This task is to enhance the NetCDF library support in MET to handle the time variable being defined as type byte directly. A sample input NetCDF data file is attached.
[cyg.ddmi.s20200803-003000-e20200803-233000.l3.grid-wind.a10.d21.nc.txt](https://github.com/dtcenter/MET/files/5228436/cyg.ddmi.s20200803-003000-e20200803-233000.l3.grid-wind.a10.d21.nc.txt)

### Time Estimate ###
1 day.

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
No sub-issues required.

### Relevant Deadlines ###
NONE.

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required: Howard
- [X] Select **scientist(s)** or **no scientist** required: Kathryn

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [X] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
No impacts.

## Enhancement Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by hsoh-u** [comment]
It's done for attribute (get_att_unixtime at nc_var_info.cc), but not for the data variable.

**Comment by hsoh-u** [comment]
It's different from handling of an time attribute which contains the string of "yyyymmdd" form. The time variable at the sample data is 1 byte integer (not character).
