### ISSUE TITLE
Enhance probabilistic verification in Point-Stat and Grid-Stat to better handle probabilities that have already been binned.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1495]
## Describe the Enhancement ##
This issue arose via a met-help question from Mike Erickson at NOAA/WPC:
https://rt.rap.ucar.edu/rt/Ticket/Display.html?id=96562

He's running Grid-Stat to verify WPC's Excessive Rainfall Outlooks (e.g. only have values of 0, 0.05, 0.1, 0.2 or 0.5) against thresholded observations (e.g. values of 0 or 1). Those probabilities have effectively already been binned. The probabilistic verification in MET somewhat assumes a continuous probability field. The user defines the probability bins and MET constructs and Nx2 probabilistic contingency table from which statistics are derived. When computing the Brier Score, the mid-point of each bin is used.

Mike used the following cat_thresh setting in Grid-Stat to match his probability values:
cat_thresh = [ >=0.0, >=0.05, >=0.1, >=0.2, >=0.5, >=1.0 ];
 
But this led to a discrepancy in results when Mike compared the Brier Score computed by hand to the one computed by MET. For example, probability values of 0.1 fall into the 0.05 to 0.1 bin, so they're evaluated using the mid-point of that bin 0.075 instead of 0.1.

Taking MET's binning methodology into account this is the closest we could approximate his hand computations:
```
cat_thresh = [ >=0.0, >=0.001, >=0.05, >=0.0501, >=0.10, >=0.101, >=0.2, >=0.201, >=0.5, >=0.501, >=0.999, >=1.0 ];
```
That yeilds a bin center-point within 0.0005 of the actual value to minimize the binning effect.

But this is not a very good solution. Instead recommend that we add a configuration option to Point-Stat and Grid-Stat to better handle already-binned probabilities. Essentially, have a flag which indicates that the thresholds provided correspond to the probability bins present in the data.

In implementing this, we'd likely need to add some checks and print a warning message if the values in the data DO NOT match the thresholds specified. And we need to make sure that the correct bin value is used instead of the center-point for that bin.

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required: John Halley Gotway
- [X] Select **scientist(s)** or **no scientist** required: Mike Erickson

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [X] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
No impacts.

## Enhancement Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
