### ISSUE TITLE
Enhance Gaussian grid support to convert non-integer (x, y) to (lat, lon).

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1497]
## Describe the Enhancement ##
During the Air Force cloud evaluation project, we attempted to run GFS data from a Gaussian grid through MODE. That results in the following runtime error:

```
ERROR  : 
ERROR  : GaussianGrid::xy_to_latlon() const -> x and y must be integers
HDF5-DIAG: Error detected in HDF5 (1.10.5) thread 0:
  #000: H5T.c line 1754 in H5Tclose(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
NetCDF: HDF error
file: ncFile.cpp  line:33
```
Here's the source of that error message:
https://github.com/dtcenter/MET/blob/3804255cf682ae6582f6505e29f82f29c7c29589/met/src/libcode/vx_grid/gaussian_grid.cc#L251

This occurs when MODE is writing the object statistics files. It might be happening when converting the object centroid (x, y) to (lat, lon), but I'm not positive on that.

This task is to enhance the GaussianGrid::xy_to_latlon() function to handle non-integer input x/y values... assuming this is mathematically possible. Use the attached sample data file to replicate:
```
> mv gfs.gaussian.sample.grib2.txt gfs.gaussian.sample.grib2
> mode gfs.gaussian.sample.grib2 gfs.gaussian.sample.grib2 MODEConfig.txt -v 3
DEBUG 1: Creating Fcst-Obs Object Statistics file: ./mode_120000L_20200608_120000V_000000A_obj.txt
ERROR  : 
ERROR  : GaussianGrid::xy_to_latlon() const -> x and y must be integers
```
Input file: [gfs.gaussian.sample.grib2.txt](https://github.com/dtcenter/MET/files/5257885/gfs.gaussian.sample.grib2.txt)
MODE config file:  [MODEConfig.txt](https://github.com/dtcenter/MET/files/5257903/MODEConfig.txt)

While this issue arose during the Air Force cloud evaluation project, fully supporting Gaussian grids is not a deliverable for that project. So we'll need to find funding elsewhere for this work.

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
No sub-issues required.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required: Randy Bullock
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [X] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
Moving this issue from met-10.0-beta1 to met-10.0-beta2 since it won't be done by next week.
