### ISSUE TITLE
Cleanup autoconf warnings when running bootstrap.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1498]
## Describe the Task ##
When compiling MET in development mode (e.g. MET_DEVELOPMENT = TRUE), after cloning the repo, the next step is running "./bootstrap". Currently that produces the following warnings:
```
src/tools/dev_utils/Makefile.am:64: warning: source file '../other/pb2nc/openpb.f' is in a subdirectory,
src/tools/dev_utils/Makefile.am:64: but option 'subdir-objects' is disabled
automake: warning: possible forward-incompatibility.
automake: At least a source file is in a subdirectory, but the 'subdir-objects'
automake: automake option hasn't been enabled.  For now, the corresponding output
automake: object file(s) will be placed in the top-level directory.  However,
automake: this behaviour will change in future Automake versions: they will
automake: unconditionally cause object files to be placed in the same subdirectory
automake: of the corresponding sources.
automake: You are advised to start using 'subdir-objects' option throughout your
automake: project, to avoid future incompatibilities.
src/tools/dev_utils/Makefile.am:64: warning: source file '../other/pb2nc/readpb.f' is in a subdirectory,
src/tools/dev_utils/Makefile.am:64: but option 'subdir-objects' is disabled
src/tools/dev_utils/Makefile.am:77: warning: source file '../other/pb2nc/openpb.f' is in a subdirectory,
src/tools/dev_utils/Makefile.am:77: but option 'subdir-objects' is disabled
src/tools/dev_utils/Makefile.am:77: warning: source file '../other/pb2nc/readpb.f' is in a subdirectory,
src/tools/dev_utils/Makefile.am:77: but option 'subdir-objects' is disabled
src/tools/dev_utils/Makefile.am:51: warning: source file '../other/pb2nc/openpb.f' is in a subdirectory,
src/tools/dev_utils/Makefile.am:51: but option 'subdir-objects' is disabled
src/tools/dev_utils/Makefile.am:51: warning: source file '../other/pb2nc/readpb.f' is in a subdirectory,
src/tools/dev_utils/Makefile.am:51: but option 'subdir-objects' is disabled
```
This task is the adjust the configure.ac and Makefile.am files as needed to address those warning.

### Time Estimate ###
2 hours.

### Sub-Issues ###
Consider breaking the task down into sub-issues.
No sub-issues required.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required - John Halley Gotway
- [X] Select **scientist(s)** or **no scientist** required - none required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [X] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
No impacts.

## Task Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
