### ISSUE TITLE
Refine log messages when verifying probabilities.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1502]
## Describe the Task ##
This issue consists of 2 tasks:

Task 1:
As described in met-help (https://rt.rap.ucar.edu/rt/Ticket/Display.html?id=96813), clarify the log messages when no climatology bins have been defined.
Existing log message:
```
DEBUG 4: parse_conf_climo_cdf() -> For "cdf_bins" (1) and "center_bins" (false), defined climatology CDF thresholds: >=0.00000,>=1.00000
```
New log message:
```
DEBUG 4: parse_conf_climo_cdf() -> Since "cdf_bins" = 1, no climatology bins will be applied.
```

Task 2:
The "prob" config file entry can either be specified as a dictionary (when parsing NOAA GRIB files) or as a boolean (for other probability data). Both types are supported and fine. However, when specified as a boolean, met-9.1 prints the following warning message:
```
WARNING: Dictionary::lookup_dictionary() -> dictionary lookup failed for name "prob"
```
Modify the code to suppress this warning message since it only causes confusion.

### Time Estimate ###
1 hour.

### Sub-Issues ###
Consider breaking the task down into sub-issues.
None required.

### Relevant Deadlines ###
None.

### Funding Source ###
None

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required
- [X] Select **scientist(s)** or **no scientist** required

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [X] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
No impacts.

## Task Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update log messages for easier debugging.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.

**Comment by JohnHalleyGotway** [comment]
Tested by running one of the Grid-Stat commands executed by running "make test".
With met-9.1:
```
cd met/scripts
export TEST_OUT_DIR=../out 
../bin/grid_stat ../data/sample_fcst/2005080312/pop5km_2005080312F096.grib_G212    ../out/pcp_combine/sample_obs_2005080800V_12A.nc    config/GridStatConfig_POP_12    -outdir ../out/grid_stat -v 4
```
The log messages include:
```
WARNING: 
WARNING: Dictionary::lookup_dictionary() -> dictionary lookup failed for name "prob"
WARNING: 
DEBUG 4: parse_conf_climo_cdf() -> For "cdf_bins" (1) and "center_bins" (false), defined climatology CDF thresholds: >=0.00000,>=1.00000
```
After compiling this change and rerunning, the log messages are now:
```
DEBUG 4: parse_conf_climo_cdf() -> Since "cdf_bins" = 1, no climatology CDF bins will be applied.
```
