### ISSUE TITLE
Change point_stat log message from "obs type" to "obs var name".

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1514]
## Describe the Enhancement ##
This is a very minor, quick, and easy change, as described in this RT ticket:
   https://rt.rap.ucar.edu/rt/Ticket/Display.html?id=97010

The following DEBUG3 log message from Point-Stat isn't very clear:
DEBUG 2: Processing TMP/P900-750 versus TMP/P900-750, for observation type ADPUPA, over region DTC165, for interpolation method NEAREST(1), using 132 matched pairs.
DEBUG 3: Number of matched pairs   = 132
DEBUG 3: Observations processed    = 89893
DEBUG 3: Rejected: station id      = 0
**DEBUG 3: Rejected: obs type        = 79788**
DEBUG 3: Rejected: valid time      = 0
DEBUG 3: Rejected: bad obs value   = 0
DEBUG 3: Rejected: off the grid    = 5
DEBUG 3: Rejected: topography      = 0
DEBUG 3: Rejected: level mismatch  = 9219
DEBUG 3: Rejected: quality marker  = 0
DEBUG 3: Rejected: message type    = 344
DEBUG 3: Rejected: masking region  = 405
DEBUG 3: Rejected: bad fcst value  = 0
DEBUG 3: Rejected: bad climo mean  = 0
DEBUG 3: Rejected: bad climo stdev = 0
DEBUG 3: Rejected: duplicates      = 0

Replace "obs type" with "obs var name".

### Time Estimate ###
1 hour.

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
No sub-issues.

### Relevant Deadlines ###
None

### Funding Source ###
None

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: John HG
- [x] Select **scientist(s)** or **no scientist** required: none required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [x] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
None

## Enhancement Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update log messages for easier debugging.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.
