### ISSUE TITLE
Add a pull request template to MET repository.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1516]
## Describe the Task ##
Add a pull request template to the MET repository. Note that this will need to be merged into the main_v9.1 branch and should also be merged into the develop branch.

Should seek input from team members for what the PR template should contain:
- John HG: Include a radio button for the requestor to ask the review to either delete or retain the feature branch.
- John HG: Will this PR cause the regression test to fail? If so, how? New output or changes to existing output?
- Julie: Include sections describing what testing the submitter has done and recommending testing for the review should do.

### Time Estimate ###
2 hours.

### Sub-Issues ###
Consider breaking the task down into sub-issues.
No sub-issues.

### Relevant Deadlines ###
None.

### Funding Source ###
None.

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: John and Julie
- [x] Select **scientist(s)** or **no scientist** required: Lindsay, others?

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [x] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
Will eventually migrate over to the other METplus repos, but separate issues for each would definitely be overkill.

## Task Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by hsoh-u** [comment]
How about creating a script with an argument, the branch name (feature or bugfix), which does
- checkout from github (from the feature/bugfix branch)
- build and do the unit test
- Compare with the latest reference build (nightly build)

**Comment by JohnHalleyGotway** [comment]
Howard, agreed, automated testing will be very useful. However, we'll do that using TravisCi rather than a shell script.
That being said, I do already have a script on kiowa that does half of this:
```
cd /d1/projects/MET/MET_pull_requests/
mkdir -p met-10.0_beta1/feature_1345
cd met-10.0_beta1/feature_1345
../../compile_MET_PR_kiowa.sh develop feature_1345_point2grid_netcdf
```
With that compiled, you could run the unit tests and diff against the NB output.
