### ISSUE TITLE
Update the Air Force GRIB tables in MET to reflect current AF usage.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1519]
## Describe the Task ##
During the Air Force testing and evaluation projects for 2020, the DTC developed some GRIB tables to reflect the Air Force metadata usage. Also, Bob Craig has some local GRIB tables he uses when running MET.

This task is to collect and clarify the Air Force GRIB table usage and add the resulting table files for met-10.0.

See: https://github.com/dtcenter/MET/tree/main_v9.1/met/data/table_files

### Time Estimate ###
2 days.

### Sub-Issues ###
Consider breaking the task down into sub-issues.
No sub-issues.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: John HG
- [x] Select **scientist(s)** or **no scientist** required: Michelle Harrold

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [x] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
No impacts.

## Task Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
@michelleharrold, just wanted to ping you on this. It'd be good to get this wrapped up in the next couple of weeks. Wondering if, at the end of the AF performance period, we have a good working definition of their GRIB tables we could use to update MET?

**Comment by JohnHalleyGotway** [comment]
@michelleharrold we're getting close to crunch time here. Are we going to be able to get the AF GRIB tables updated for met-10.0.0 or push it off for another year?

**Comment by michelleharrold** [comment]
@JohnHalleyGotway - The Grib tables we (the DTC) use match what is available in MET. We reached out to Bob Craig to see if they wanted to make any additions - he said what we had match what they use, and he would run some tests to see if any changes needed to be made. I have not heard back, so I am guessing no modifications need to be made.

**Comment by JohnHalleyGotway** [comment]
Based on Michelle's interaction with Bob, I will close this issue without making any changes. If we do ever hear back that the AF would like changes to their GRIB tables in MET, feel free to reopen this issue or create a new one.
