### ISSUE TITLE
Create the MET 10.0-beta1 release.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1523]
## Describe the Task ##
This task is to create the MET 10.0-beta1 release currently scheduled for 10/21/2020.

The METplus repo currently includes instructions for building a METplus release here:
   https://github.com/dtcenter/METplus/wiki/Creating-a-new-METplus-release
Copy these over to a MET repository wiki page and modify them for MET.

### Time Estimate ###
4 hours.

### Sub-Issues ###
Consider breaking the task down into sub-issues.
No sub-issue required.

### Relevant Deadlines ###
None

### Funding Source ###
None

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: Minna
- [x] Select **scientist(s)** or **no scientist** required: No scientist required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [x] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
Will need related issues for beta1 releases for each component.

## Task Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update log messages for easier debugging.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.

**Comment by JohnHalleyGotway** [comment]
Listed below are the step I followed to create the met-10.0_beta1 release from the develop branch of MET.

1. Defined (this) GitHub issue for the release changes.

2. Created feature_1523_v10.0-beta1 branch from develop.

3. Update Release Notes:

Since met-10.0 increases the major version number, discard existing met-9.1 release notes.
Edit met/docs/Users_Guide/release-notes.rst.
Create notes from the following GitHub issue:
met-9.1.1 issues:
https://github.com/dtcenter/MET/issues?q=is%3Aissue+milestone%3A%22MET+9.1.1+%28bugfix%29%22+is%3Aclosed
met-10.0-beta1 issues:
https://github.com/dtcenter/MET/issues?q=is%3Aissue+project%3Adtcenter%2FMET%2F20+is%3Aclosed

4. Update the version number:

Update util_constants.h from V9.1 to V10.0.
Add met_header_columns_V10.0.txt and met_10_0.hdr.
Update the release date in docs/conf.py to the current day.
Update the version number listed in the all the config files from 9.1 to 10.0.
Submitted a PR #1536 to merge feature_1523_v10.0-beta1 into develop.
After the PR was approved, I confirmed that the changes were merged.

5. Create a new release on GitHub from the develop branch.
https://github.com/dtcenter/MET/releases/new
https://github.com/dtcenter/MET/releases/tag/met-10.0_beta1

6. On kiowa, checkout and build the tarball for this release.
```
cd /d1/projects/MET/MET_pull_requests/MET
git checkout develop
git pull
scripts/build/met_checkout_and_build.sh tag met-10.0_beta1
ls met-10.0_beta1.20201022.tar.gz
```

7. Upload the release tarball as an asset on the GitHub release page.

8. Re-render the Sphinx documentation, copy the html to the develop directory on the gh-pages branch, and push changes to GitHub.

9. Create a new entry for the met-10.0_beta1 release on the DTC website:
http://dtcenter.org/community-code/model-evaluation-tools-met/download

10. Compile met-10.0_beta1 on kiowa in /d1/projects/MET/MET_releases.
```
runas met_test
cd /d1/projects/MET/MET_releases
wget https://github.com/dtcenter/MET/releases/download/met-10.0_beta1/met-10.0_beta1.20201022.tar.gz
cd met-10.0_beta1
source /d1/projects/MET/MET_pull_requests/MET/scripts/environment/development.kiowa
unset MET_DEVELOPMENT
./configure --prefix=`pwd` --enable-grib2 --enable-modis --enable-mode_graphics --enable-lidar2nc --enable-python
make install test >& make.log
```

11. Update the actual release date on the GitHub project page, resolve this issue, and close the beta1 project.
