### ISSUE TITLE
Parse -v and -log command line options first.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1527]
## Describe the Enhancement ##
When testing for another issue, I ran across a pesky little detail. The CommandLine class currently parses options in the order they are processed. However, it should ideally process the -v and -log command line options first. Otherwise, the default logging level of 2 and no output log file remain in effect until those options are processed. So if the user requests a high level of logging, it won't go into effect until processing all the log command line options prior to it.

This is confusing and unexpected behavior but not quite a bug.

### Time Estimate ###
4 hours.

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
No sub-issues.

### Relevant Deadlines ###
None

### Funding Source ###
None

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: John HG
- [x] Select **scientist(s)** or **no scientist** required: no scientist required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [x] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
No impacts.

## Enhancement Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update log messages for easier debugging.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.

**Comment by JohnHalleyGotway** [comment]
The -v and -log command line arguments are common to all the MET tools. They affect the global instance of the Logger class named mlog. To simplify things, I moved support for handling the -v and -log options into the CommandLine class itself and removed many, many set_verbosity() and set_log_file() functions from the application code. The CommandLine::parse() function now parses the -v and -log options prior to parsing the remaining command line options.

**Comment by JohnHalleyGotway** [comment]
I am compiling these changes on kiowa in:
/d1/projects/MET/MET_pull_requests/met-10.0_beta2/feature_1527/MET-feature_1527_log_into_develop
I will run the full set of unit tests to make sure these changes have no unintended consequences.
