### ISSUE TITLE
Implement Continuous Integration with GitHub Actions in MET

### ISSUE THREAD

**Issue by fentoad72** [dtcenter/MET#1546]
*Replace italics below with details for this issue.*

## Describe the New Feature ##
Implement Travis CI into MET
- error checking on git push
- DockerHub/Docker image integration
- what tests to run?

### Acceptance Testing ###
John -- what tests should be run each build

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
- [ ] *Write a travis.yml file*
- [ ] Integration/conflict with Travis on METplus

### Relevant Deadlines ###
MET future versions

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [ ] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## New Feature Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by fentoad72** [comment]
Outline basic step we want to do -- 
* branch rules (which branches kick off a travis build)
* branch rules (add logic on what tests to run based on build (develop, feature_, ...)
* building the Docker image
* pull the develop and build using that as cache-from, it will only build what needs to be updated
* run make test for develop & feature branches
* run regression tests and save a docker data volume of output for reference image with output saved
* use docker data volume to compare each run (docker data vol is "truth"), don't need to run reference each time
* how to evaluate a different output from reference, is this something that makes sense -- if so, update reference (evaluating the differences would probably be done by hand)
* how to behave with feature branches (later)

**Comment by ksearight** [comment]
This issue needs to be retitled for GitHub Actions instead of Travis (or closed).

**Comment by JohnHalleyGotway** [comment]
On 1/19/22, @georgemccabe and @JohnHalleyGotway met to discuss these details.

Goals for this test automation.

- Should restructure the MET Dockerfile define a base image from which the MET images inherits.
  - Recommend having 3 base images:
    - Minimal image for compiling MET source code.
    - Minimal + packages for running unit and regression tests.
    - Minimal + useful runtime tools (e.g. ncview, wgrib)
  
- For each push to each feature or bugfix branch:
  - Run "make install test" to confirm the code compiles. Only for changes to the "met/src" subdirectory. Disable using "ci-skip-compile". Test using "docker build".
- For all PR's into the develop or main_v* branch.
  - ...

**Comment by JohnHalleyGotway** [comment]
Running all of the unit tests for MET takes over an hour. Instead of running serially, we'd like to break them down into groups that can run concurrently. To figure out the dependency structure, I ran the following commands. Note that this is only a first order cut at the dependencies... and will require review to manually refine it.

```
cd MET/test

# Generate the commands to be run for each of unit test xml files
for file in `ls -1 xml/*.xml`; do
  cmd_file=`basename $file | sed 's/.xml/.cmd/g'`; perl/unit.pl $file --cmd > commands/$cmd_file;
done

# For each of these command files, extract all unique instances of files in the MET_test_output directory
rm unit_test_deps.txt
for cmd_file in `ls -1 commands/*.cmd`; do
  unit=`basename $cmd_file | cut -d'.' -f1`
  deps=''
  for ref_file in `grep MET_test_output $cmd_file | egrep -v "outdir|file_list" | sed -r 's/.*MET_test_output\///g' | grep '\.' | cut -d' ' -f1 | sort -u`; 
  do
    deps="${deps}:`grep -l $ref_file xml/unit*.xml | egrep -v ${unit}.xml | sed -r 's/$/:/g' | tr -d '\n'`"
  done
  deps=`echo $deps | sed -r 's/:+/\n/g' | sort -u | sed -r 's/$/ /g' | tr -d '\n'`
  echo "$cmd_file DEPENDS ON $deps" >> unit_test_deps.txt
done
```
Here's the output  [unit_test_deps.txt](https://github.com/dtcenter/MET/files/7909493/unit_test_deps.txt).

**Comment by JohnHalleyGotway** [comment]
@georgemccabe thanks for making lots of good progress on this issue. As discussed in Slack, we have many options for reducing the overall runtime of the unit tests in GHA (which are currently a little less than an hour). Here's a list of tasks to consider (add more as you see fit):

- Break the input test data down into small pieces so that each test pulls smaller data volumes overall. It takes ~3 minutes for each job to pull the full set of input data).
  - [ ] Break the inputs down into some logical subsets. 
- Remove independent tasks from the longest chain.
  - [x] Group 1a includes unit_ascii2nc.xml which takes ~12 minutes to run. Move any ascii2nc tasks whose output is not used downstream into a separate unit XML file which can run as an independent task. Be sure to write output to a directory which matches the unit_{NAME}.xml convention. That will likely make ascii2nc run faster than pb2nc in group 1a.
    - unit_ascii2nc.xml runs the tool 27 times but only 6 output files are used downstream:
dup_test.nc
edr_hourly.20130827.nc
gauge_2012041012_24hr.nc
gdas1.20120409.t12z.prepbufr.ascii_name.nc
surfrad.nc
trmm_2012040912_3hr.nc
  - [x] If that makes ascii2nc run faster than pb2nc (~7 minutes), then do the same thing for unit_pb2nc.xml.
    - unit_pb2nc.xml runs the tool 10 times but only 3 output files are used downstream:
gdas1.20120409.t12z.prepbufr.nc
ndas.20120409.t12z.prepbufr.tm00.nc
ndas.20120410.t12z.prepbufr.tm00.nc
- Break down long running serial tasks into ones that can run concurrently:
  - [x] unit_ref_config.xml runs gen_vx_mask once, and then pb2nc/pcp_combine/point_stat/grid_stat for 5 different lead times, and then stat_analysis to sum them all up. That takes 30 minutes. We could break that down into 5 different unit_ref_config_f{NN}.xml files for NN = 00, 12, 24, 36, 48 followed by unit_ref_config.xml to run series-analysis on the output. Rather than running gen_vx_mask once as a pre-req, running it 5 times (at the beginning of each unit_ref_config_f{NN}.xml file) would likely be faster overall.
