### ISSUE TITLE
Fix MET to compile using GCC version 10

### ISSUE THREAD

**Issue by jprestop** [dtcenter/MET#1552]
## Describe the Task ##
As reported by a user via met-help (https://rt.rap.ucar.edu/rt/Ticket/Display.html?id=97359) met-9.1 does not compile using the GCC version 10 compilers.  The issue lies with the compilation of the required BUFRLIB library:
`ufbtab.f:306:31:

  288 |          DO WHILE(IREADMG(-LUNIT,SUBSET,IDATE).GE.0)
      |                                        2
......
  306 | 10    IF(IREADMG(-LUNIT,SUBSET,JDATE).LT.0) GOTO 25
      |                               1
Error: Rank mismatch between actual argument at (1) and actual argument at (2) (rank-1 and scalar)
ufbtab.f:534:37:

  288 |          DO WHILE(IREADMG(-LUNIT,SUBSET,IDATE).GE.0)
      |                                        2
......
  534 |       DO WHILE(IREADMG(-LUNIT,SUBSET,JDATE).GE.0)
      |                                     1
Error: Rank mismatch between actual argument at (1) and actual argument at (2) (rank-1 and scalar)
`
I want to try to reproduce the problem using GCC version 10 and let the developers of BUFRLIB know of the issue.

### Time Estimate ###
1 day

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- No sub-issues required. I expect this to only require a small number of changes.

### Relevant Deadlines ###
None

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required - no scientist required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [x] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by jprestop** [comment]
In compiling BUFRLIB:
"Error: Rank mismatch between actual argument at (1) and actual argument at (2) (rank-1 and scalar)"

Added:
"-fallow-argument-mismatch" to the compilation of BUFRLIB

From:
https://gcc.gnu.org/gcc-10/changes.html
Mismatches between actual and dummy argument lists in a single file are now rejected with an error. Use the new option -fallow-argument-mismatch to turn these errors into warnings; this option is implied with -std=legacy. -Wargument-mismatch has been removed.

**Comment by jprestop** [comment]
In compiling HDF4.2r3:
"Error: Type mismatch between actual argument at (1) and actual argument at (2) (CHARACTER(0)/INTEGER(4))"

Added:
"-w -fallow-argument-mismatch" to the compilation of HDF4.2r3 to FFLAGS in the hdf/src/Makefile

**Comment by jprestop** [comment]
Testing on cheyenne:/glade/p/ral/jntp/MET/MET_cross_platform_testing/met-10.0.0-beta4/gcc/met-10.0.0-beta4 using gnu/10.1.0

**Comment by jprestop** [comment]
I got a successful compilation on Cheyenne, including using HDF4, HDFEOS, Cairo, and Freetype, the build and test logs can be viewed at /glade/p/ral/jntp/MET/MET_cross_platform_testing/met-10.0.0-beta4/gcc/met-10.0.0-beta4.
