### ISSUE TITLE
Enhance Python Embedding logic to better match Python standards

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/MET#1561]
This came up while trying to implement a METplus use case (dtcenter/METplus#686) that involves using a python driver script to extract the valid time from a file by calling a single function from a python script, then trying to use the same script to read the data/attributes into MET.

Currently, we instruct users to run their python embedding script on the command line to ensure that it works correctly. However, the Python embedding logic in the C code *imports* the script and reads global variables to read the data and attributes. Importing a Python script runs all of the lines of the script and makes the functions/global variables available to reference.

If a Python script is designed to be run from the command line, a block at the bottom of the script is defined to determine what should be run when the script is called directly (See https://docs.python.org/3/library/__main__.html). This is done so that the file can be imported by another python script without calling the main block so that the functions in the file can be used by the importing script.

The current design of the Python embedding scripts has all of the logic in the body of the script, including reading the command line arguments from sys.argv. This means that if you want to import one of these scripts into another Python script, the command line arguments of the calling script must match what is expected by the imported script exactly. This is very limiting, especially if there is a single function in the script that you want to utilize in another script.

If a Python script is formatted in the recommended way (implementing __main__ logic for running the script directly), then the met_data and attrs global variables are not available to the C code as it is currently written.

## Describe the Enhancement ##
Update the Python Embedding logic in the C code to call the python script (instead of importing?) and retrieve the data/attributes that doesn't require the script to be written in such a limiting way. We should still support the current python embedding script format by first checking if the met_data and attrs global variables are set and using them if they are.

### Time Estimate ###
~3 days

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
None

### Funding Source ###
None

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [X] Select **scientist(s)** or **no scientist** required

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [X] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [X] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by georgemccabe** [comment]
[read_tdr_mccabe.py.txt](https://github.com/dtcenter/MET/files/5548406/read_tdr_mccabe.py.txt)

Attached is a script that sets met_data in attrs in the main section when the script is run from the command line, but can be imported in another script to be able to call the get_valid_time function.

**Comment by JohnHalleyGotway** [comment]
@georgemccabe we do not plan on getting this done for MET 10.0.0.
Is it OK to move to MET 10.1.0?

**Comment by georgemccabe** [comment]
> 
> 
> @georgemccabe we do not plan on getting this done for MET 10.0.0.
> Is it OK to move to MET 10.1.0?

Yes, that is OK with me.
