### ISSUE TITLE
Update the NCL-derived color tables provided for MET version 10.0.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1568]
## Describe the Enhancement ##
When testing the pull request for MET #1528, Michelle noted that it would be nice to provide a colortable in MET that's well-suited for plotting topography. The data/config/colortable/NCL_colortables directory contains MET-friendly versions of the NCL colortables derived from:
https://www.ncl.ucar.edu/Document/Graphics/color_table_gallery.shtml

MET currently has 56 NCL colortables but it looks like there are several new ones, including a few with "topo" in the name. This task is to update the NCL colortables directory to include the full set of 270. Use files ending with ".rgb" from here:
https://github.com/NCAR/ncl/tree/6.6.2/ni/src/db/colormaps

Include the conversion script directly in the repository.

### Time Estimate ###
3 hours.

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
None required.

### Relevant Deadlines ###
None.

### Funding Source ###
None.

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: John HG
- [x] Select **scientist(s)** or **no scientist** required: Michelle to review PR

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [x] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
No impacts.

## Enhancement Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
I did a spot check of the changes to the existing NCL colortables. Some of them changed very slightly (4th decimal place?) because of imprecise rounding the past and precise rounding now.

Also, these 270 NCL colortables are all those ending with *.rgb. Note that the NCL repo contains colormaps with multiple suffixes:
270 *.rgb, 22 *.gp, and 8 *.ncmap

However, all *.gp and *.ncmap files have a corresponding *.rgb file. I did find slight differences in their contents in at least one file.  But I'm only processing the *.rgb files for simplicity.
