### ISSUE TITLE
Enhance support for rotated latlon grids and update related documentation.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1574]
## Describe the Task ##
MET #1029 added partial support to MET for rotated lat/lon projections.

A comment from #1029:
Randy finished this for the met-8.0 for GRIB2, MET NetCDF, and the python interface.
May still need to be added for GRIB1 and CF-Compliant NetCDF.

This task is to...
- Add support for rotated lat/lon grids as grid specification strings.
- Review/update the documentation, as needed.

I am not able to add support for rotated lat/lon grids for the GRIB1 or NetCDF CF-compliance libraries since I cannot find any sample input data files. Rotated lat/lon is listed as a possible grid type in GRIB1 documentation (https://www.nco.ncep.noaa.gov/pmb/docs/on388/table6.html), but I am unable to run copygb to generate a sample data on that project. 

This issues arose via met-help:
https://rt.rap.ucar.edu/rt/Ticket/Display.html?id=97502

### Time Estimate ###
4 hours

### Sub-Issues ###
Consider breaking the task down into sub-issues.
None needed.

### Relevant Deadlines ###
None.

### Funding Source ###
None.

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: John HG with George to review PR
- [x] Select **scientist(s)** or **no scientist** required: none scientist required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [x] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
No impacts.

## Task Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update log messages for easier debugging.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.

**Comment by JohnHalleyGotway** [comment]
- Re-tested GRIB2 and MET NetCDF for rotated lat/lon and confirmed that it works.
- Re-tested python embedding for rotated lat/lon and confirmed that it works.
- Consolidated and simplified the documentation of the grid specification string and python embedding dictionaries.
- Updated grid specification string parsing logic to handled rotated lat/lon grid spec strings.
