### ISSUE TITLE
Add detailed log messages to Point-Stat when discarding observations.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1588]
## Describe the Enhancement ##
This is a request from NRL submitted via met-help:
https://rt.rap.ucar.edu/rt/Ticket/Display.html?id=97623

At Debug(3), Point-Stat prints out counts of reason codes listing why observations were excluded from each verification task, as shown below.

When discarding observations based on topography differences, a detailed Debug(4) level message is logged explaining why. This task is to enhance vx_statistics/pair_data_point.cc with additional Debug(4) detailed log messages for other types of observation exclusions.

718 DEBUG 3: Number of matched pairs  = 1292
719 DEBUG 3: Observations processed   = 19696
720 DEBUG 3: Rejected: SID exclusion  = 0
721 DEBUG 3: Rejected: obs type       = 16198
722 DEBUG 3: Rejected: valid time     = 0
723 DEBUG 3: Rejected: bad obs value  = 0
724 DEBUG 3: Rejected: off the grid   = 355
725 DEBUG 3: Rejected: topography     = 665
726 DEBUG 3: Rejected: level mismatch = 0
727 DEBUG 3: Rejected: quality marker = 0
728 DEBUG 3: Rejected: message type   = 0
729 DEBUG 3: Rejected: masking region = 0
730 DEBUG 3: Rejected: bad fcst value = 1186
731 DEBUG 3: Rejected: duplicates     = 0
732 DEBUG 2: Computing Continuous Statistics.

Add detailed log messages for:
bad obs value, off the grid, topography (already present), bad fcst value, duplicates

Do not add detailed log message for:
SID exclusion, obs type, valid time, level mismatch, quality marker, message type, masking region

We are weighing useful log messages vs swamping the user with too many messages. The latter reasons are easily investigated by re-configuring/re-running Point-Stat. The former set cannot be easily investigated in this way.

### Time Estimate ###
4 hours.

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
No sub-issues needed.

### Relevant Deadlines ###
None

### Funding Source ###
NRL

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: John HG
- [x] Select **scientist(s)** or **no scientist** required: no scientist required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [x] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
No impacts.

## Enhancement Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update log messages for easier debugging.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.

**Comment by JohnHalleyGotway** [comment]
Added/updated log messages for:
- bad obs value
```
DEBUG 4: For TMP/P1000-200 versus TMP/P1000-200, skipping observation with bad data value:
DEBUG 4:    ADPUPA 72365 20070331_120000 35.03000 106.62000 1618.00000  755.29999 2438.00000 NA -9999.00000
```
- off the grid
```
DEBUG 4: For TMP/P1000-200 versus TMP/P1000-200, skipping observation off the grid where (x, y) = (1372, 1103) and grid (nx, ny) = (614, 428):
DEBUG 4:    ADPUPA 72365 20070331_120000 35.03000 -106.62000 1618.00000  815.29999 1829.00000 NA 276.45001
```
- bad topo values
```
DEBUG 4: For TMP/Z2 versus TMP/Z2, skipping observation due to bad topography values where observation elevation = 20 and model topography = -9999:
DEBUG 4:    ADPSFC CYKO 20120409_120000 60.82000 78.15000 20.00000 TMP 1015.20001 19.96650 9 269.14999
```
- large topo diff
```
DEBUG 4: For TMP/Z2 versus TMP/Z2, skipping observation due to topography difference where observation elevation (41) minus model topography (849.15) = 808.15 is not >=-100&&<=100:
DEBUG 4:    ADPSFC 71114 20120409_120000 49.36000 121.48000 41.00000 TMP 1014.09998 40.97427 8 280.35001
```
- bad fcst value
```
DEBUG 4: For TMP/Z2 versus TMP/Z2, skipping observation due to bad data in the interpolated forecast value:
DEBUG 4:    ADPSFC 78397 20120409_120000 17.93000 76.78000 9.00000 TMP 1012.59998 8.99371 9 297.64999
```
- duplicate obs
```
For TMP/P1000-200 versus TMP/P1000-200, skipping observation since it is a duplicate:
DEBUG 4:    ADPUPA 72365 20070331_120000 35.03000 106.62000 1618.00000  837.00000 1618.00000 NA 273.04999
```
