### ISSUE TITLE
Add documentation for Multivariate MODE to the MET User's Guide.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1592]
## Describe the Task ##
MET #1184 adds support for multi-variate MODE, but due to time and funding limitations, the corresponding documentation changes are not included with the code changes. This task is to update the MET User's Guide with information about multi-variate MODE.

### Time Estimate ###
1 day (?)

### Sub-Issues ###
Consider breaking the task down into sub-issues.
No sub-issues required.

### Relevant Deadlines ###
Required by the met-10.0.0 release.

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*
2700042

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: no engineer required
- [x] Select **scientist(s)** or **no scientist** required: Lindsay

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [x] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
No impacts.

## Task Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
Please see this MET-Help ticket:
https://rt.rap.ucar.edu/rt/Ticket/Display.html?id=98171 

Looking in the MET User's Guide at the chapter about MODE:https://dtcenter.github.io/MET/latest/Users_Guide/mode.html

This description is not sufficient:
```
The field entries in the forecast and observation dictionaries specify the model and observation variables and level to be compared. See a more complete description of them in Section 3.5.1. In the above example, the forecast settings are copied into the observation dictionary using obs = fcst;.
```

All we're doing there is referring to the common config file options section about setting the "field" entry. I realize that we should modify that to point out that in MODE the "field" is defined as a single dictionary entry... and not as an array of fields.

However, one complication is that in MET version 10.0.0, "field" can either be set to a single entry or an array of entries. If it's an array of entries, then those multiple fields are combined into a single set of MODE objects rather than looping over the list and running MODE once for each.

I'm going to copy/paste this email as a comment on the GitHub issue for updating the multi-variate MODE documentation:https://github.com/dtcenter/MET/issues/1592

Thanks for pointing out the confusion.

**Comment by lindsayrblank** [comment]
@JohnHalleyGotway I was able to add some preliminary documentation, but not the details like the usage statement (due to the seg fault). In lieu of full documentation, here are the step by step instructions for how to run multivariate MODE as it stands now. I had sent these to Tina Kalb. 

Perform the following steps on dakota:
1. Copy the following script: /d2/lblank/multivariate_mode/case_study_2019061500/run_case_study_2019061500

2. Open that script and change the name of the environment variable "MET_DRYLINE" to something that makes sense for your project, but keep the same path.

3. Create a text file that contains each filename for the file that corresponds to each field. There must be one file for each field, even if the same file is read for different fields. Create one for forecast and one for observation.

4. In the script, replace your "2019061500_fcst_files.txt" with the name of your forecast file list file and "2019061500_obs_files.txt" with the name of your observation file list file. 

5. Create a multivariate MODE config file. You can modify "MultivariateMODEConfig_2019061500" or you can modify an existing MODE config file. Just make sure the "multivar_logic" statement is included.

6. Create a MODE config file for the "super object", the object that results from combining the fields in the first MODE run. You can modify "super_config" or create your own. 

7. Create as many directories for however many fields you are running. They should be named as such: 00, 01, etc. 

Now you should be able to run. As a note, the names of the forecast AND observation super object fields will be the same as the first field entry in the forecast field dictionary.

**Comment by TaraJensen** [comment]
Found this issue in the MET v11.0.0 beta 1 project but it was completed in conjunction with [#1184](https://github.com/dtcenter/MET/issues/1184) PR so closing it without its own PR.
