### ISSUE TITLE
Enhance tc_gen to write a matched pair output line type.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1597]
## Describe the Enhancement ##
The tc_gen tool currently writes Debug(4) log messages for each pair indicating how it was classified.

(1) HIT:
DEBUG 4: SUI1 20160525_120000 initialization, 51 lead, 20160527_150000 genesis at (28.4, -73.6) is a HIT for BEST 20160527_180000 genesis at (28.3, -74.4).
DEBUG 4: SUI1 20160813_120000 initialization, 36 lead, 20160815_000000 genesis at (8.5, -23.5) is a HIT for CARQ 20160815_120000 genesis at (9.2, -23.7).

(2) MISS:
DEBUG 4: BEST 20160913_060000 genesis at (27.3, -80.2) for 20160908_060000 initialization, 120 lead is a MISS.

(3) FALSE ALARM:
DEBUG 4: SUI1 20160101_000000 initialization, 39 lead, 20160102_150000 genesis at (10.5, -70.9) is a FALSE ALARM.

This task is to provide the option to write this detailed log information to the actual output files by defining a new STAT line type. This is analogous to the RIRW_MPR line type written by TC-Stat. However that line is only written to the log file and not a fully support STAT output line type. Recommend adding a GENESIS_MPR line type that includes the ADECK and BDECK location and timing information and classifies the pair as being a HIT, MISS, FALSE ALARM, or DISCARD (where the discard logic is described by MET #1448).

One compilation is that Stat-Analysis would also need to be enhanced to be able parse this new STAT line type. However, I'd recommend that Stat-Analysis only support the filtering job type for this new line type and nothing else.

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: John HG
- [x] Select **scientist(s)** or **no scientist** required: Dan H and Kathryn

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [x] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
Adding a new STAT line type would require METviewer and METdatadb to handle it.

## Enhancement Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
Email discussion chain...

From John:
I'm a little torn on one point. I wrote it up as adding a new output STAT line type from TC-Gen. That would format the output nicely and consistently. However, it would also mean that Stat-Analysis would be able to read data from that line type. That is doable... we could only support the "-job filter" option.

However it would also mean that METviewer and METdatadb would need to know what to do with this data... even if it's just to ignore it.

So the question is... does writing it to a new STAT line type make sense with all the implications? Or should I do something short of that?

From Dan H:
I was envisioning this capability would allow users to take a more in-depth look at some of the individual forecast events.  I think the expectation would be that users would write some code on their own to analyze these events based on their particular application.  So, in that regard, perhaps a formatted log file would be more appropriate than a new STAT line type.

However, I could see this output being useful in order to generate spatial plots of each event.  If METViewer will support this type of plot, then perhaps a new STAT line type is warranted.

From John:
Thanks for the response. If we would like METviewer, or even METplotpy, to eventually create plots of this paired data, then storing it in a new STAT line type would be the way to go.

So I'll proceed with that plan. We'll need to figure out exactly what info this line type should contain. I'm guessing it'll be the storm id info, category (hit, miss, fa, discard), location, timing, and intensity (max wind, min pressure, and cyclone level) for both the forecast and BEST track. But I'll ask you to review the contents when we get to that point.

From Dan H:
That sounds good.  The information you listed would definitely be good to include.  I'll think about potential additional fields.

**Comment by JohnHalleyGotway** [comment]
Question about how this matched pair information should be written. Should it be like the MPR line type from Point-Stat or the RIRW_MPR log messages from TC-Stat?

Some background:

The Point-Stat tool writes a line type named MPR to the .stat output file. The Stat-Analysis tool can read the MPR line type, aggregate the data together across multiple runs, and recompute most statistics that can be computed by a single run of Point-Stat. This is a *fully-featured* implemenation.

The TC-Pairs tool pairs up fcst/Best track ATCF data and writes the TCMPR line type. The TC-Stat tool reads those TCMPR lines and, among other things, can run an RIRW job on the data. This does a contingency table verification of the RIRW events. It writes out the individual cases to an output named RIRW_MPR. But this is NOT actually a fully-supported .stat line type. It's just data written to the output file. Here's sample RIRW_MPR output...

COL_NAME: ATIME  BTIME  AEXACT BEXACT ATHRESH BTHRESH WINDOW_BEG WINDOW_END AMODEL BMODEL STORM_ID            INIT    LEAD           VALID AMAX_WIND_PRV AMAX_WIND_CUR AMAX_WIND_DLT ARIRW BMAX_WIND_PRV B
MAX_WIND_CUR BMAX_WIND_DLT BRIRW CATEGORY
RIRW_MPR: 240000 240000 true   true   <=-15   <=-15   000000     000000       AHWI   BEST AL062010 20100831_000000  000000 20100831_000000            NA            60            NA   NA             NA  
          60            NA   NA        NA

So the question is... Should the matched pair output from TC-Gen be done formally as a full .stat line type, or make it less formal, like the RIRW_MPR line type?

Logically, this seems very, very similar to the RIRW_MPR data. So I'll plan to write it the less formal way, unless I hear otherwise.

**Comment by halperin-erau** [comment]
I think writing the output in the less formal, RIRW_MPR type format is reasonable here.  The goal is to provide information about each event so that users can work with that data on their own for any analysis beyond what the contingency table statistics would provide in the current tc_gen output line types.

**Comment by KathrynNewman** [comment]
I agree - the RIRW_MPR approach is the best fit and provides the desired output.

**Comment by JohnHalleyGotway** [comment]
Notes from checkin meeting on 20210121:
- Confirm that genesis_window has been fully replaced.
- Change config file names: genesis_hit_radius to dev_hit_radius, genesis_hit_window to dev_hit_window, genesis_minus_init_diff to ops_hit_tdiff.
- Update tc_gen docs accordingly (typos for spelling genesis and ** should be ||).
- In the log messages, which state "MATCHED BEST track" or "NO MATCH", change lead to forecast hour.
- Check range of longitude values written to the NetCDF matched pairs file. I would expect them to be -180 to 180.
