### ISSUE TITLE
Enhance Ensemble-Stat to compute statistics for an ensemble of neighborhood fractional coverage fields.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1602]
## Describe the New Feature ##
This work should be considered in the context of other GitHub issues:
- MET #1450: Add Hersbach CRPS to Ensemble-Stat
- MET #1904: Split Ensemble-Stat out into 2 separate tools for computing ensemble products (gen_ens_prod) vs ensemble verification (ensemble_stat).

This task is to enhance Ensemble-Stat to compute statistics for an ensemble of neighborhood fractional coverage fields. As of met-9.1, Ensemble-Stat supports nbrhd_prob and nbrhd_nmep dictionaries in the config file. Those options control the application of neighborhood methods when creating ensemble probability products. They are only applied to the fields listed in the "ens" dictionary.

Recommend that we port over the existing "nbrhd" dictionary from the Grid-Stat config file to Ensemble-Stat.  After reading the fields from the "fcst" and "obs" dictionaries, use the "nbrhd" config options to derive fractional coverage fields for the ensemble members and verifying gridded analyses. Note that this logic only applied when verifying against gridded analyses, not points! After converting the ensemble members and verifying analyses to fractional coverage fields, proceed with the computation of ensemble statistics as usual.

Be sure to populate the STAT output columns accordingly:
- FCST_THRESH and OBS_THRESH indicate the neighborhood threshold
- INTERP_MTHD is set to NBRHD_SQUARE or NBRHD_CIRCLE
- INTERP_PNTS indicates the neighborhood size
- Recommend that we update FCST_VAR and OBS_VAR to differentiate between the input variable and the derived fractional coverage field.  Perhaps just append "_NBRHD" to the existing variable names?

### Acceptance Testing ###
*List input data types and sources.*
*Describe tests required for new functionality.*

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: John HG
- [x] Select **scientist(s)** or **no scientist** required: Tara (for now, can be reassigned)
Coordinate development and testing with UK Met Office staff (Roger H and Marion M).

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [x] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
No impacts.

## New Feature Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
@mpm-meto please review this issue as written. Has this already been addressed via changes to HiRA in Ensemble-Stat in MET version 10.1.0? If so, recommend closing this issue.

**Comment by JohnHalleyGotway** [comment]
During the MetOffice development meeting on 9/15/2022, we discussed that this functionality must be in beta4 since it needs to be fully tested at the MetOffice by the end of the year, 2022. Switching from required for official release to required for development release.

**Comment by JohnHalleyGotway** [comment]
@mpm-meto, @j-opatz and I discussed this issue today, and I'm writing to request some more direction. This issue was written about 2 years ago and I'd like to clarify the details before going too far with it.

Note that we have already removed the ensemble post-processing from Ensemble-Stat and placed it in Gen-Ens-Prod. Reading the issue, I see that we want to port the logic of the `nbrhd` dictionary over from Grid-Stat to Ensemble-Stat. I understand that, and doing so is easy enough.

The question is how do we use those neighborhood settings and how do they impact the output?

I see two ideas as being reasonable possibilities:

1. As written, this issue says that this applies only when verifying against gridded analyses. We should use the thresholds and neighborhoods to convert each ensemble member into a fractional coverage field, as well as the gridded analysis. And we should proceed with ensemble verification logic (i.e. ECNT statistics, Rank Histograms, and so on). So rather than verifying raw data, we're verifying an ensemble of fractional coverage fields and writing typical ensemble statistics.

2. Another reasonable possibility would be computing Fractions Skill Score, but using input ensemble data in Ensemble-Stat rather than deterministic data in Grid-Stat. In this way, we'd be computing a single fractional coverage field over a *volume* of data (including all ensemble members in the computation). Then we'd compare the single ensemble-derived fractional coverage field to that of the gridded analysis. And in this case, we'd compute Fractions Skill Score and write it to the NBRCNT line type.

Can you please clarify which of these algorithms the Met Office is requesting?

**Comment by RogerHar** [comment]
Hi John,

We're requesting (1). This is mainly for work I'm doing with partners in India.

I don't believe (2) it's something we need at present. It was suggested by [Duc et al. (2013)](http://doi.org/10.3402/tellusa.v65i0.18171) who called it the 'Ensemble FSS' but I'm not aware if it has been very used much. 

Marion @mpm-meto may wish to comment but she's on leave until 19 Oct, and is unlikely to have seen this or your email yet as she was at a conference last week.

--

On a related point, I'd really like to be able to obtain _fields_ of empirical CRPS and Fair CRPS values, including but not only for neighbourhood coverage fractions, i.e. for `ensemble_flag` to include `crps_emp` and `crps_emp_fair` flags. (Such output fields would typically then be meaned over a time series but that could be done separately using Series-Analysis or other tools for NetCDF.) Maybe I should start a separate discussion about that? I've no idea how much work that would involve for you.

**Comment by mpm-meto** [comment]
Suggest we close this @JohnHalleyGotway as I think we can deal with FSS for ensembles via feeding in the ensemble mean and/or running for individual ensemble members and post-processing the results. At the end of the day the Duc et al reference boils down to FSS on the ensemble mean.
