### ISSUE TITLE
Update GridDiag docs

### ISSUE THREAD

**Issue by dwfncar** [dtcenter/MET#1611]
## Describe the Task ##
Update GridDiag documentation to clarify behavior when the
-data command line option is used twice.
e.g. -data fileA -data fileB.

Also confirm that the existing grid_diag unit tests include an example of using -data multiple times to specify different input datasets.

### Time Estimate ###
4 hours.

### Sub-Issues ###
Consider breaking the task down into sub-issues.
No sub-issues.

### Relevant Deadlines ###
MET 10.0.0

### Funding Source ###
None

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
David Fillmore
- [x] Select **scientist(s)** or **no scientist** required
None

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [x] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
No impacts.

## Task Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by dwfncar** [comment]
In a config data block with varA and varB.
-data fileA -data fileB can be used to have varA read from fileA and varB read from fileB.

**Comment by dwfncar** [comment]
Merged to dev.
