### ISSUE TITLE
Update MET unit test logic to unset environment variables after each test.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1624]
## Describe the Enhancement ##
George found a small omission for the python_numpy_point_stat tests in unit_python.xml. The Point-Stat config file references the ${OBS_COMMAND} environment variable. But that isn't actually set by the test. Instead, it inherits the setting from the previous test.

This task is to fix that omission. In addition, update the unit test logic. After each test is run, unset any environment variables that were explicitly set for that test. This will ensure that each test can run independently.

### Time Estimate ###
2 hr

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
None required.

### Relevant Deadlines ###
None.

### Funding Source ###
None.

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: John HG
- [x] Select **scientist(s)** or **no scientist** required: none needed

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [x] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
No impacts.

## Enhancement Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
Updated perl/unit.pl to unset the test-specific environment variables after each test. I made sure to also write the unsets commands to the log output. I am currently testing this PR on kiowa to see if this problem with test-specific environment variable settings exists in for any of the other unit tests:
kiowa:/d1/projects/MET/MET_pull_requests/met-10.0.0_beta3/feature_1624

**Comment by georgemccabe** [comment]
Closed with PR #1625
