### ISSUE TITLE
Add TC-Gen configuration file options for init_inc, init_exc, and basin_mask.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1626]
## Describe the Enhancement ##
We've been revamping the TC-Gen tool in several ways for the MET 10.0.0 release. The updates include an overhaul to the matching logic, a new gridded NetCDF output file, and a new genesis matched pair (GENMPR) output line type. During the development process, we realized that adding 3 more configuration file options for TC-Gen would be very useful:
```
init_inc = [ ]; // Strings in YYYYMMDD[_HH[MMSS]] format
init_exc = [ ]; // Strings in YYYYMMDD[_HH[MMSS]] format
basin_mask = [ ]; // Strings with basin_name values
```
The first 2 options explicitly specify which model initialization times should be included or excluded from the processing logic. If the inclusion list is non-empty, only those times explicitly listed will be included. If the exclusion list is non-empty, any initialization times listed will be excluded.
The basin_mask entry is an array of strings of basin name values. They should match the basin_name variable values defined in met/data/tc_data/basin_global_tenth_degree.nc. If multiple basins are listed, their union will be used. If both vx_mask and basin_mask are specified, their intersection will be used.

### Time Estimate ###
2 days.

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
No sub-issues needed.

### Relevant Deadlines ###
None.

### Funding Source ###
7790901

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: John HG
- [x] Select **scientist(s)** or **no scientist** required: Kathryn

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [x] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
No impacts.

## Enhancement Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
While adding support for basin_mask, I've come to realize that it'd be much better to update the basin data file to include basin abbreviations. For example, right now we have name = "ATLANTIC", and I'd like to add abbrev = "AL".
We need those abbreviations to correspond to the contents of ATCF data files, and right now we have a very kludgy hard-coded mapping of integers to strings. Much better to read the values and strings from the data file instead.
