### ISSUE TITLE
Update the plotting R-scripts to handle output from different versions of MET.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1653]
## Describe the Enhancement ##
This issue is based on a request that came in via met-help:
https://rt.rap.ucar.edu/rt/Ticket/Display.html?id=98517

I actually already posted updates for plot_cnt.R and plot_mpr.R prior to realizing that these scripts actually do live in the MET repository. So this task is to make the same updates in the develop branch. Also, check if the same changes are needed in any of the other R-scripts. The change is this...
- add a -met_base command line argument
- if not specified there, check for a MET_BASE environment variable
- if neither are set, error out
- read the data and extract the MET version number from the first column of the first line
- read the corresponding header for that line type/version number from MET_BASE/table_files/met_header_columns_vX.Y.txt
- remove the hard-coded headers from the top of these scripts

### Time Estimate ###
4 hours.

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
No sub-issues required.

### Relevant Deadlines ###
None.

### Funding Source ###
?

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: John HG
- [x] Select **scientist(s)** or **no scientist** required: no scientist required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [x] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
No impacts.

## Enhancement Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
Updated plot_cnt.R and plot_mpr.R. Need to do the same for plot_ensemble.R.
