### ISSUE TITLE
Reformat the magic_str() for NetCDF data files.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1655]
## Describe the Enhancement ##

This is a minor change to how the magic_str() should be formatted when processing NetCDF data files. This caused some confusion for a user, as described in this MET-Help ticket:
https://rt.rap.ucar.edu/rt/Ticket/Display.html?id=98524

When processing gridded NetCDF data created by other MET tools, the "level" string in the MET configuration file can be set two different ways.
```
float APCP_12(lat, lon) ;
	APCP_12:name = "APCP_12" ;
	APCP_12:long_name = "Total precipitation" ;
	APCP_12:level = "A12" ;
	APCP_12:units = "kg/m^2" ;
```
(1) Define how to index into the NetCDF variable dimensions:
```
level="(*,*)";
```
Which results in this type of log message:
```
DEBUG 2: Processing APCP_12(*,*) versus APCP_12(*,*), for smoothing method NEAREST(1), over region DTC165, using 2651 matched pairs.
```
(2) Or define the value for the "level" attribute of the NetCDF variable being read:
```
level="A12";
```
Which results in this type of log message:
```
DEBUG 2: Processing APCP_12A12 versus APCP_12A12, for smoothing method NEAREST(1), over region DTC165, using 2651 matched pairs.
```
The log message from (2) caused confusion. This task is to change the formatting of that string to be "APCP_12/A12" instead.

Instead of just always inserting '/' between the name and level, recommend only doing so if the first character of the level string is NOT '('. Recommend making this change for all vx_data2d libraries that process gridded NetCDF data.

### Time Estimate ###
2 hours. But this might cause some diffs to the NB output which may take a while to check.

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
No sub-issues required

### Relevant Deadlines ###
None

### Funding Source ###
?

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: John HG
- [x] Select **scientist(s)** or **no scientist** required: none required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [x] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
No impacts.

## Enhancement Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update log messages for easier debugging.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.
