### ISSUE TITLE
Allowing shapefile to predefined grid conversion 

### ISSUE THREAD

**Issue by j-opatz** [dtcenter/MET#1675]
## Describe the New Feature ##
CPC has an interest in the ability to load in shapefiles to a grid of predefined resolution. Currently, MET only supports a shapefile to VX mask conversion. The desired ability would allow for uploading of hazards map data and verification against observational datasets.

### Acceptance Testing ###
Shapefiles should be from hazards map: Needs to be collected
Acceptance criteria from users will need to be more defined

### Time Estimate ###
Need input from engineers

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
None

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [x] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [x] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## New Feature Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by j-opatz** [comment]
New data has been shared from CPC group: a forecast shapefile dataset and an observation binary dataset. Details on the observations provided from CPC:

> "A .ctl file ("haf.ob.ctl") is there for grads to read which lists also the gridded specs. Each binary file contains 6 records, the first 5 records ( prcp, wind, snow, cold, heat) pertain to probabilistic hazard types based on the assignments on the jamboard, and the last record is simply all wwa shapes issued for the day. The gridded values consist of either ones or zeros denoted by either an event or no event for verification. For example, any pixels with ones in the 'prcp' grid (1st record) in the first time series file 'haf.ob_20150101.dat' correspond to any heavy prcp related wwa (typhoon, coastal flood, hurricane, etc) that was issued from 12Z Jan 1 to 12Z Jan 2."

Link provided is to a description of the shapefile archive directory: https://docs.google.com/document/d/1p7nEOzVNgadaIcjwRSdFC3-Nh4zOOIcU-AHgdPp8B3Q/edit

Data (tar'd and zipped) is located on Kiowa, in /d1/projects/CPC_data/input/shapefile_data

**Comment by JohnHalleyGotway** [comment]
@j-opatz the existing gen_vx_mask tool has the ability to read shapefile areas and apply them to a user-defined grid.
We could do that as a pre-processing step to define the forecast dataset to be verified.

In fact, @LoganDawson-NOAA may already be doing this... at least, I recall us talking about this in the past.

Logan, can you provide any more info on this? Are you running gen_vx_mask convert shapefile warning areas into gridded data to be verified by Grid-Stat or Point-Stat?

**Comment by JohnHalleyGotway** [comment]
@j-opatz there are definitely improvements we could make to MET's use of shapefiles. Right now it requires the user to figure out exactly which shapes should be used. Please take a look at this issue for ideas on how it could be made more user-friendly.
https://github.com/dtcenter/MET/issues/1060

Might make sense to work on #1060 in conjunction with this issue.

**Comment by LoganDawson-NOAA** [comment]
@JohnHalleyGotway yes, I am running shapefiles (from the Storm Prediction Center) through gen_vx_mask to define masking regions that are used by both Grid-Stat and Point-Stat. I'm still using gen_vx_mask in a shell script rather than in a METplus wrapper.

The command looks like this:
`gen_vx_mask ${GRID_FILE} ${SHP_FILE}.shp ${MASK_NAME}.nc -type shape -shapeno ${REC} -name DAY${DAY}_${NAME} -v 3`

Where `${GRID_FILE}` is a file providing the grid that the shapefile is mapped to, and `${REC}` is the record number from the shapefile. The number of records in a given shapefile is determined with this command:

``N_REC=`gis_dump_dbf ${SHP_FILE}.dbf | grep n_records | cut -d'=' -f2 | tr -d ' '` ``

Were those the details you were asking about?

**Comment by JohnHalleyGotway** [comment]
@LoganDawson-NOAA yes, that's exactly what I was wondering! Thanks for sending these details.

@j-opatz perhaps Logan has some sample output you could show to CPC to demonstrate this logic?

I do think we'll need to look carefully at the CPC-provided shapefiles. When I ran one through gen_vx_mask I got incoherent, unexpected output... so we'd need to track down the source of the problem.
I definitely think there's room for improvement in MET's handling of shapefiles.
For example, it'd be nice if Logan could tell gen_vx_mask to do string matching instead of picking a single record number. So replace "-shapeno 3" with "-shape_name 'High Risk'" ... or something like that. Seems like it'd be convenient to compute the mask as the *union* of all the shapes which match the name criteria. So if Hawaii is split into many shapes for many islands, you could just run "-shape_name 'Hawaii'".

**Comment by LoganDawson-NOAA** [comment]
@j-opatz I can definitely share output with CPC to show how I've been using it this MET capability

@JohnHalleyGotway I'd definitely support string matching versus requiring that the decoding be done by record number. 

It appears that MET currently handles the union of all shapes into one object. This [SPC outlook](https://www.spc.noaa.gov/products/outlook/archive/2021/day1otlk_20210214_1200_prt.gif) has multiple areas included in the TSTM risk area. Here's a quick plot of the output from gen_vx_mask:
<img width="967" alt="day1_TSTM" src="https://user-images.githubusercontent.com/62668456/109719803-31195300-7b77-11eb-9913-14c38c4f05fe.png">

I'm not sure if the resultant mask is a product of how "smart" MET is or if SPC has encoded their shapefiles to lead to this result. Essentially, I think we'd need to try running other shapefiles with discontinuous areas through MET to see what the result is.

**Comment by j-opatz** [comment]
Some time after the last discussion on this issue, CPC decided to move away from the shapefile approach and instead use netCDF files for their warning areas. So the need to display a shapefile's contents on a user-defined grid is no longer necessary. In fact, as John HG indicated and Logan demonstrated, this ability is already available.

More importantly, the larger issue that this ties into, allowing users the ability to access shapefile contents via string matching and being all around more user-friendly, is a pre-existing issue (#1060). So this issue is being closed.
