### ISSUE TITLE
Add support for the Lambert Azimuthal Equal Area grids

### ISSUE THREAD

**Issue by michelleharrold** [dtcenter/MET#1693]
## Describe the New Feature ##
As of 10/25/22 - Identified as **CRITICAL for Met Office**:

MET assumes a spherical Earth. The EUMETNET (radar) dataset is on a Lambert Azimuthal Equal Area grid, which uses an ellipsoidal Earth. Randy already has some code for latlon_to_xy. The xy_to_latlon code still needs to be implemented, and the code needs to be implemented in MET (and tested accordingly). 

### Acceptance Testing ###
Same data is located on Cheyenne:
/gpfs/fs1/p/ral/jntp/AF/gswr/eumetnet (in HDF5 format)

This data can be moved to a more convenient location. Some sample data has already been shared with Randy.

Tests will need to be done to make sure the Lambert Azimuthal Equal Area projection is working as anticipated (will work with Randy to establish necessary tests).

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
No sub-issues required.

### Relevant Deadlines ###
Goal is to target the met-10.1.0_beta1 release scheduled for 5/13/21.

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: Randy B
- [x] Select **scientist(s)** or **no scientist** required: Michelle H

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [x] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
No impacts.

## New Feature Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
From @michelleharrold:

The deliverable for this project is due 31 May, so the sooner the better!

For reference - the EUMETNET data is what this is needed for. It is currently in HDF5, so the goal is to have you write the python code to convert to MET-friendly NetCDF and then have MET be able to handle the lambert azimuthal equal area grid. I suppose we could also have you include a regridding in the python script to bypass needing the lambert azimuthal equal area grid...but that seems like a cop out? But there is a hard deadline of 31 May -- and that is when the analysis needs to be done, so we need about 2 weeks to actually run MET and analyze output. Is this reasonable?

**Comment by JohnHalleyGotway** [comment]
From @rgbullock 

I finished up the laea grid code.  I've also tested it and it seems to be working well.  I decided to go with the series expansion rather than the iterative scheme in the code, because it turns out that the iteration doesn't always converge.

The definition for the grid Michelle and Tracy are using is contained in the source file "laea_grid_defs.h".  It's currently called tracy_data ... you'll probably want to change the name to something else.

For the benefit of those who will ultimately have the task of maintaining my grid code, the main reference for this work is

   **"Map Projections --- A Working Manual", by John P. Snyder
   U. S. Geological Survey Professional Paper 1395**

I'll let someone else write the code for wiring this up to the 2D data factory class.  It should just be a matter of populating the LaeaData struct from the info in the data file.

I guess that's it unless there's something I've forgotten about.

One thing:  Since this grid is on a non-spherical earth, any code that uses it will need to link to libvx_geodesy.a when compiling, so someone should probably add that to any of the Makefile.am files where it's needed so that autoconf knows about it.

**Comment by JohnHalleyGotway** [comment]
@rgbullock has finished development for this support. Added @JohnHalleyGotway to the assignee list so he can work on integrating these changes into the rest of the MET codebase.

**Comment by JohnHalleyGotway** [comment]
Here is a link to the GRIB2 definition of Lambert Azimuthal Equal Area grids:
https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_temp3-140.shtml

Along with an ECMWF grid template:
https://apps.ecmwf.int/codes/grib/format/grib2/templates/3/140

And here is a sample LAEA GRIB2 file I found on the MetOffice website:
https://metoffice.apiconnect.ibmcloud.com/metoffice/development/projection
```
wgrib2 -V ukv_agl_temperature_1.5_12.grib
	Lambert Azimuthal Equal Area grid: (1042 x 970) input WE:SN output WE:SN res 48
	Lat1 44.517153 Lon1 2164.600777 Cen Lon -2.500000 Std Par 54.900000
	Dx 2000.000000 m Dy 2000.000000 m mode 48
```

@rgbullock, how can we translate these GRIB2 projection definitions to the entries in the [LaeaData struct](https://github.com/dtcenter/MET/blob/91495ac1e7418378801d548b209baf1bbd9fe837/met/src/libcode/vx_grid/laea_grid_defs.h#L20) that you've already added?

**Comment by JohnHalleyGotway** [comment]
@rgbullock can you please provide an update on this issue? Are you able to update the MET library code to instantiate a LAEA grid from a GRIB2 file?

**Comment by JohnHalleyGotway** [comment]
@rgbullock, @TaraJensen recently updated this issue to a "blocker", meaning that we'd like to get it fixed in the first development cycle for MET 11.0.0, [MET-11.0.0-beta1](https://github.com/orgs/dtcenter/projects/20/views/12). Are you available to work on this feature? Perhaps you've already added this functionality in your feature branch and just need to add a test to demonstrate it?

I see your [feature_1693_equal_area](https://github.com/dtcenter/MET/tree/feature_1693_equal_area) branch was last modified May 19, 2021. Please let me know if you have any questions about merging the latest from the develop branch into that feature branch.

**Comment by rgbullock** [comment]
Hi John -

I can work on this.  In fact I was going to email you to see what you'd
like me to work on.

Randy

**Comment by michelleharrold** [comment]
@rgbullock @JohnHalleyGotway - I was wondering if there was an update on this? Thanks!

**Comment by rgbullock** [comment]
Hi MIchelle -

The grid projection code is all written (at least in my own projection code
library.  I'm not sure if that's been imported into the MET code yet).

As far as the example data file I'm working with, the information we need
to instantiate the grid is not in the Grid Description Section of the
file.  Even wgrib can't make sense of the grid information in the file, so
it's not just me.

I figure we have two options:  (1)  try to get whatever institution is
producing this data to clean up the grid description section in their data
files.  I've talked with John about this and we think this is unlikely to
happen  (2)  Figure out the grid info by hand by trial and error and then
hard-code an exception to MET's internal code to recognize this grid and
bypass the usual grid-instantiation code.  I don't like this option for two
reasons:  first, it's ugly, and second, it sets a bad precedent --- one
that I think we'd deeply regret later.  John gave me the name of a contact
that I can ask questions of, but that doesn't change my reasons for
disliking this option.

Randy

**Comment by JohnHalleyGotway** [comment]
Added @robdarvell as an assignee since he will provide sample LAEA data to use in development and testing.
@rgbullock, per @TaraJensen, this issue is "hyper critical" and must be completed ASAP.

**Comment by robdarvell** [comment]
Within the ftp server I have put some files which hopefully will be of use for this.
The forecasts don't have the same timestamp as the analysis but hopefully they can be used to check things like regridding can be done OK.

**Comment by JohnHalleyGotway** [comment]
FYI, I have copied the files that @robdarvell provided into seneca:/d1/projects/MET/MET_issues/feature_1693.

**Comment by JohnHalleyGotway** [comment]
See the following for reference:

- GRIB1: No LAEA definition found: https://www.nco.ncep.noaa.gov/pmb/docs/on388/table6.html
- GRIB2: LAEA defintion: https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_temp3-140.shtml
   - Defines `Standard parallel` and `Central longitude`
- NetCDF CF-Convention: LAEA definition: https://cfconventions.org/Data/cf-conventions/cf-conventions-1.10/cf-conventions.html#lambert-azimuthal-equal-area
   - Defines `longitude_of_projection_origin` and `latitude_of_projection_origin`

But the existing MET `LaeaData` structure defines:
```
   double lat_ll;   //  lower left
   double lon_ll;

   double lat_ul;   //  upper left
   double lon_ul;

   double lat_lr;   //  lower right
   double lon_lr;

   double lat_pole;
   double lon_pole;
```
How does we use the GRIB2/NCCF metadata to populate this struct?
Would prefer that the LaeaData structure be modified to match the GRIB2 conventions.

Remember to also support this for MET NetCDF, grid specification strings, and python embedding.

FYI, I did try to visualize the sample `ukv_agl_temperature_1.5_12.grib` file with both Panoply and IDV but both errored out. So neither is able to visualize this data.

**Comment by JohnHalleyGotway** [comment]
@robdarvell and @mpm-meto I'm working away on this issue. I'm using the GRIB2 file name `ukv_agl_temperature_1.5_12.grib2` for development and testing.

**Can you please send me a plot of to demonstrate where on the earth this data should live?**

For reference, here's the [ECMWF definition](https://apps.ecmwf.int/codes/grib/format/grib2/templates/3/140) and [NOAA definition](https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_temp3-140.shtml). And those match.

I'm getting some conflicting output from ECMWF's grib_dump utility and NOAA's wgrib2 utility.
From grib_dump:
```
  numberOfPointsAlongXAxis = 1042;
  numberOfPointsAlongYAxis = 970;
  latitudeOfFirstGridPointInDegrees = 44.5172;
  longitudeOfFirstGridPointInDegrees = -17.1171;
  standardParallelInMicrodegrees = 54900000;
  standardParallelInDegrees = 54.9;
  centralLongitudeInMicrodegrees = -2500000;
  centralLongitudeInDegrees = -2.5;
```
From wgrib2:
```
Lambert Azimuthal Equal Area grid: (1042 x 970) input WE:SN output WE:SN res 48
Lat1 44.517153 Lon1 2164.600777 Cen Lon -2.500000 Std Par 54.900000
Dx 2000.000000 m Dy 2000.000000 m mode 48
```
The issue is with the longitudes:
`longitudeOfFirstGridPointInDegrees = -17.1171` versus `Lon1 2164.600777`
So while the NOAA GRIB2 libraries claim to read LAEA grids, I suspect there's an issue to be fixed.
But the first step is deciding what the "right answer" is for this sample data. And at this point, the ECMWF (grib_dump) output certainly looks more reasonable!

**Comment by robdarvell** [comment]
@JohnHalleyGotway looking at the filename (and once I spotted where you obtained it from) it seems to be one of our UK model domains. Having searched around for an image, I have attached the best thing I could find, but it should give you an indication of where it is supposed to be.
![Screenshot 2022-11-10 154040](https://user-images.githubusercontent.com/63108044/201140408-d3ed415d-8472-40e1-95f0-9788ac5aa1e7.png)

**Comment by JohnHalleyGotway** [comment]
@rgbullock please see this image that @robdarvell provided (Thanks Rob!).

Please use this for your development/testing of the MET LAEA library code.

Running the `ukv_agl_temperature_1.5_12.grib` file ([ukv_agl_temperature_1.5_12.grib.gz](https://github.com/dtcenter/MET/files/9983460/ukv_agl_temperature_1.5_12.grib.gz)) through `wgrib2` does not produce believable results for `Lon1 = 2164.600777`:
```
wgrib2 -d 1 -V ukv_agl_temperature_1.5_12.grib
	Lambert Azimuthal Equal Area grid: (1042 x 970) input WE:SN output WE:SN res 48
	Lat1 44.517153 Lon1 2164.600777 Cen Lon -2.500000 Std Par 54.900000
	Dx 2000.000000 m Dy 2000.000000 m mode 48
```

But running it through `grib_dump` does for `longitudeOfFirstGridPointInDegrees = -17.1171`:
```
grib_dump ukv_agl_temperature_1.5_12.grib
  shapeOfTheEarth = 4;
  numberOfPointsAlongXAxis = 1042;
  numberOfPointsAlongYAxis = 970;
  latitudeOfFirstGridPointInDegrees = 44.5172;
  longitudeOfFirstGridPointInDegrees = -17.1171;
  standardParallelInMicrodegrees = 54900000;
  standardParallelInDegrees = 54.9;
  centralLongitudeInMicrodegrees = -2500000;
  centralLongitudeInDegrees = -2.5;
  # Cannot open flag table 
  # flags: 00110000
  resolutionAndComponentFlags = 48;
  xDirectionGridLengthInMillimetres = 2000000;
  xDirectionGridLengthInMetres = 2000;
  yDirectionGridLengthInMillimetres = 2000000;
  yDirectionGridLengthInMetres = 2000;
  iScansNegatively = 0;
  jScansPositively = 1;
  jPointsAreConsecutive = 0;
  alternativeRowScanning = 0;
  gridType = lambert_azimuthal_equal_area;
```

**Comment by JohnHalleyGotway** [comment]
@robdarvell and @mpm-meto, I went hunting for the NetCDF sample data file for this LAEA grid. Based on [this comment](https://github.com/dtcenter/MET/issues/1693#issuecomment-1262481787) I made back in September, I looked at these sample files:
```
prods_op_ukv_20220201_00.nc
prods_op_ukv_20220201_06.nc
prods_op_ukv_20220201_12.nc
prods_op_ukv_20220201_18.nc
```
However, these sample files define a "Rotated Lat/Lon" projection rather than a Lambert Azimuthal Equal Area one, as expected:
```
float stratiform_rainfall_amount(dim0, grid_latitude, grid_longitude) ;
...
		stratiform_rainfall_amount:grid_mapping = "rotated_latitude_longitude" ;
int rotated_latitude_longitude ;
		rotated_latitude_longitude:grid_mapping_name = "rotated_latitude_longitude" ;
		rotated_latitude_longitude:longitude_of_prime_meridian = 0. ;
		rotated_latitude_longitude:earth_radius = 6371229. ;
		rotated_latitude_longitude:grid_north_pole_latitude = 37.5 ;
		rotated_latitude_longitude:grid_north_pole_longitude = 177.5 ;
		rotated_latitude_longitude:north_pole_grid_longitude = 0. ;
```
@robdarvell can you please double-check and send (or resend) sample LAEA NetCDF files?

**Comment by robdarvell** [comment]
@JohnHalleyGotway : I have put some files into darvell_data (on the ftp server) which should hopefully assist you.

The ones above you reference are from our UKV model (which is rotated-pole rather than LAEA)

**Comment by JohnHalleyGotway** [comment]
Thanks @robdarvell, I just grabbed those files but did not find what I expected:
```
ncdump -h 202211150600_nimrod_ng_radar_rainrate_composite_1km_UK.nc
	float rainfall_rate_composite(projection_y_coordinate, projection_x_coordinate) ;
...
		rainfall_rate_composite:grid_mapping = "transverse_mercator" ;
	int transverse_mercator ;
		transverse_mercator:grid_mapping_name = "transverse_mercator" ;
		transverse_mercator:longitude_of_prime_meridian = 0. ;
		transverse_mercator:semi_major_axis = 6377563.396 ;
		transverse_mercator:semi_minor_axis = 6356256.91 ;
		transverse_mercator:longitude_of_central_meridian = -2. ;
		transverse_mercator:latitude_of_projection_origin = 49. ;
		transverse_mercator:false_easting = 400000. ;
		transverse_mercator:false_northing = -100000. ;
		transverse_mercator:scale_factor_at_central_meridian = 0.9996012717 ;
```
Looks like this is for a [Transverse Mercator](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.10/cf-conventions.html#_transverse_mercator) projection rather than [Lambert Azimuthal Equal Area](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.10/cf-conventions.html#lambert-azimuthal-equal-area).

Do you have any sample data for the latter that I can use to develop/test this issue?

**Comment by robdarvell** [comment]
Apologies @JohnHalleyGotway for the duff data. I was told the radar files were on the LAEA grid, but I hadn't actually checked through the ncdump before I sent them.

I have placed a new temperature and visibility file onto the ftp server, and checked that the ncdump talked about LAEA on them. Hopefully (!) they are what you need.
They cover the UKV (ie UK) domain.

Rob

**Comment by TaraJensen** [comment]
Trying to get this going again.  @JohnHalleyGotway - did we ever grab the files @robdarvell put up on the FTP server?  If not - hopefully @robdarvell can post them again.

**Comment by robdarvell** [comment]
I have put some alternate LAEA grid files on the ftp server in darvell_data
(they are probs of thresholds being met fields)
