### ISSUE TITLE
Replace temporary pickle files in PyLineDataFile with temporary ASCII

### ISSUE THREAD

**Issue by dwfncar** [dtcenter/MET#1700]
## Describe the New Feature ##

Replace temporary pickle files in PyLineDataFile with temporary ASCII.
This should be done in basic/vx_util/python_line.h and python_line.cc.
write_pickle_mpr.py will be replaced by write_tmp_mpr.py.
If possible re-use read_tmp_ascii.py.

### Acceptance Testing ###
*List input data types and sources.*
*Describe tests required for new functionality.*

### Time Estimate ###
2 days.

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
No sub-issues required.

### Relevant Deadlines ###
For met-10.0.0 realease

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: John HG
- [x] Select **scientist(s)** or **no scientist** required: Dan A can test and/or review PR.

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [x] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
No impacts.

## New Feature Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update log messages for easier debugging.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.

**Comment by JohnHalleyGotway** [comment]
However, for this issue, I'll also tackle a continuing problem with the path that @DanielAdriaansen has reported. Listed below is an email from Dan that explains the path problem:

I am still having problems with the same issue- same problem as here: https://github.com/dtcenter/MET/issues/1319#issuecomment-774321157

Using the develop branch on kiowa. Here's some output:
```
04/16 20:45:39.158 metplus INFO: COMMAND: /d1/projects/MET/MET_regression/develop/NB20210412/MET-develop/met/bin/ascii2nc "/home/dadriaan/projects/tmp/METplus/parm/use_cases/model_applications/data_assimilation/read_nrl_ascii_point.py /home/dadriaan/projects/nrl/NRL_data/innovar_1_2020051800.h5" /home/dadriaan/projects/tmp/output/model_applications/data_assimilation/ascii2nc_python.nc -format python -v 2
OUTPUT:
DEBUG 1: Config File: /d1/projects/MET/MET_regression/develop/NB20210412/MET-develop/met/share/met/config/Ascii2NcConfig_default
Python Script:   /d1/projects/MET/MET_regression/develop/NB20210412/MET-develop/met/share/met/wrappers/write_tmp_point.py
User Command:    ['/home/dadriaan/projects/tmp/METplus/parm/use_cases/model_applications/data_assimilation/read_nrl_ascii_point.py', '/home/dadriaan/projects/nrl/NRL_data/innovar_1_2020051800.h5']
Write Temporary Ascii:   /home/dadriaan/projects/tmp/output/tmp/tmp_ascii2nc_8351_0.txt
Traceback (most recent call last):
  File "/d1/projects/MET/MET_regression/develop/NB20210412/MET-develop/met/share/met/wrappers/write_tmp_point.py", line 28, in <module>
    spec.loader.exec_module(met_in)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/dadriaan/projects/tmp/METplus/parm/use_cases/model_applications/data_assimilation/read_nrl_ascii_point.py", line 7, in <module>
    import read_xiv_met as inn
ModuleNotFoundError: No module named 'read_xiv_met'
ERROR  :
ERROR  : PythonHandler::do_tmp_ascii() -> command "/home/dadriaan/.conda/envs/nrltest/bin/python3 /d1/projects/MET/MET_regression/develop/NB20210412/MET-develop/met/share/met/wrappers/write_tmp_point.py /home/dadriaan/projects/tmp/output/tmp/tmp_ascii2nc_8351_0.txt /home/dadriaan/projects/tmp/METplus/parm/use_cases/model_applications/data_assimilation/read_nrl_ascii_point.py /home/dadriaan/projects/nrl/NRL_data/innovar_1_2020051800.h5" failed ... status = 256
ERROR  :
```
The error (**ModuleNotFoundError: No module named 'read_xiv_met'**) should not occur because the script read_xiv_met.py lives in the directory where my Python embedding script lives but it can't find it.

**Comment by JohnHalleyGotway** [comment]
Replicating this behavior on kiowa:
```
cd /d1/personal/johnhg/MET/MET_Help/adriaansen_data_20210420

# Running python directly works fine (and read_ascii_point.py imports a toy script named hello.py)
/usr/local/python3/bin/python3 python/read_ascii_point.py python/sample_ascii_obs.txt

# Running ascii2nc with straight python embedding works great
MET-bugfix_1620_python/met/bin/ascii2nc 'python/read_ascii_point.py python/sample_ascii_obs.txt' obs.nc -format python

# Writing a temp python file for ascii2nc FAILS, just like Dan described
export MET_PYTHON_EXE=/usr/local/python3/bin/python3
MET-bugfix_1620_python/met/bin/ascii2nc 'python/read_ascii_point.py python/sample_ascii_obs.txt' obs.nc -format python
ModuleNotFoundError: No module named 'hello'

# Writing a temp python file for stat_analysis FAILS, just like Dan described
export MET_PYTHON_EXE=/usr/local/python3/bin/python3
MET-bugfix_1620_python/met/bin/stat_analysis -lookin python python/read_ascii_mpr.py python/mpr.txt -job filter -dump_row dump.stat
ModuleNotFoundError: No module named 'hello'
```
I tested all 3 instances of python embedding MET:
(1) For gridded data, imports for straight and user python work great.
(2) For ascii2nc, imports for straight python work, but imports for user python **DO NOT WORK**.
(3) For stat_analysis, imports for straight python work, but imports for user python **DO NOT WORK**.
So there are 2 problems to fix.
