### ISSUE TITLE
Derive climo probabilities for complex CDP thresholds like >=CDP33&&<=CDP67.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1705]
## Describe the Enhancement ##
The CDP threshold type in MET is for "climatological distribution percentile" thresholds. This threshold type requires that the climo mean and standard deviation be defined. When they are, a threshold like <CDP33 is applied by computing the 33rd percentile of the climo distribution (assumed normal) at each grid point. NOAA/CPC produces probability forecasts of being in the lower (<33), middle (33 to 67), and upper (>67) terciles. When computing statistics, MET must determine the probability of event for the climatology. For simple thresholds like, <CDP33 and >CDP67, the climatological probability is simple and constant... namely there's a 33% probability of being in the lower tercile and a 33% probability of being in the upper tercile. And the existing code handles those just fine.

The problem is that the MET library code does NOT currently handle complex thresholds like >=CDP33&&<=CDP67. It cannot determine that the climatological probability of being in the that range is 34%. This issue is to enhance MET to handle this type of complex CDP threshold. Specifically, enhance the logic of derive_climo_prob() in pair_base.cc.

Currently the percentile type for complex thresholds is undefined. Recommend enhancing that logic to return CDP if all simple threshold which comprise it are of that type.

### Time Estimate ###
 1 day

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
No sub-issues required.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [x] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
No impacts.

## Enhancement Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update log messages for easier debugging.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.

**Comment by JohnHalleyGotway** [comment]
I compiled this updated version for you to test on kiowa:
/d1/projects/MET/MET_pull_requests/met-10.0.0_beta5/feature_1705/MET-feature_1705_cdp_prob/met/bin

Note these new DEBUG 4 log message to confirm the result of this logic:
```
DEBUG 4: For threshold >CDP67, using a constant climatological probability value of 0.33.
DEBUG 4: For threshold <CDP33, using a constant climatological probability value of 0.33.
DEBUG 4: For threshold >=CDP33&&<=CDP67, using a constant climatological probability value of 0.34.
```
And it can even handle some fancy ones like this:
```
DEBUG 4: For threshold (>=CDP5&&<=CDP25)||(>=CDP75&&<=CDP95), using a constant climatological probability value of 0.4.
```
But it's easy to trick it with overlapping ranges:
```
DEBUG 4: For threshold (>=CDP33&&<=CDP67)||(>CDP50), using a constant climatological probability value of 0.84.
```
This probability should be 0.67, not 0.84. Sensible, non-overlapping input thresholds should produce good output probability values. But overlapping thresholds may produce unexpected results.
