### ISSUE TITLE
Enhance the `set_attr_grid` processing logic to support input files lacking a grid definition

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1729]
## Describe the Enhancement ##
When reading gridded data, often from NetCDF files, the parsing of the grid can cause the MET tool to error out. That means that the grid information in the NetCDF file is either missing or inconsistent. It may be the case that the user is aware of the problem but still wants to process the data in MET. In this situation, it would be nice for users to supply the "set_attr_grid" option to manually define the grid information.

The set_attr_grid option does work BUT only if the library code was successful in actually parsing the grid information from the original files. Any errors in that process will cause the tool to error out. Two options to consider are:

(1) Change the NetCDF library errors to warning messages to prevent the tools from erroring out. But ignoring those warning would lead to bad output.

(2) Check for set_attr_grid PRIOR TO calling the NetCDF library code. Only attempt to parse the grid information from the file if it has not already been set.

Run the following commands with the attached file to demonstrate:
```
mv MITLL.ProxyEchoTopsCalibratedMosaic.20200831_235328_v_20200831_235328.nc.txt MITLL.ProxyEchoTopsCalibratedMosaic.20200831_235328_v_20200831_235328.nc
plot_data_plane MITLL.ProxyEchoTopsCalibratedMosaic.20200831_235328_v_20200831_235328.nc ~/plot.ps 'name="ProxyEchoTopsCalibratedMosaic"; level="(*,*)";'
```
This errors out, and defining a grid using "set_attr_grid" does NOT prevent that.

[MITLL.ProxyEchoTopsCalibratedMosaic.20200831_235328_v_20200831_235328.nc.txt](https://github.com/dtcenter/MET/files/6172564/MITLL.ProxyEchoTopsCalibratedMosaic.20200831_235328_v_20200831_235328.nc.txt)

### Time Estimate ###
1 day

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
No sub-issues required.

### Relevant Deadlines ###
Would be nice to include in 10.0.0 if possible

### Funding Source ###
None

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: John HG
- [x] Select **scientist(s)** or **no scientist** required: Michelle

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [ ] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
Please work on this at the same time as MET#2857.

**Comment by jprestop** [comment]
@hsoh-u Can you please provide a status update and let me know if any more work is needed on this before the 12.0.0-beta5 release?  Or should this be moved to beta6?

**Comment by hsoh-u** [comment]
Not ready for beta5. Please move this to beta 6

**Comment by JohnHalleyGotway** [comment]
@hsoh-u I'm following up on questions from Slack.

- There is no '-set_attr_grid' command line option. Instead, it can be specified within a field string, like this:

name="TMP"; level="Z2"; convert(x)=K_TO_C(x); set_attr_units="C"; set_attr_grid="G212";

These field strings are read whenever a MET tool reads gridded data.

Please look at all the vx_data2d_nc* libraries. The issue is that the grid is read during the file opening step. So it fails before the set_attr_grid logic can be applied.

We could either move the processing of the set_attr_grid logic to occur earlier (and have the NC libs only read the grid if it's not already set)... or we could move the NC logic for reading the grid further down.

I don't know the best solution without looking through the details.
