### ISSUE TITLE
Enhance Stat-Analysis skip writing job output to the logfile when the -out_stat option is provided.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1736]
## Describe the Enhancement ##
This is a request from NOAA/MDL that arose during a telecon on 3/29/2021. Here's the correspondence:

From NOAA/MDL:
When we run stat_analysis, all of the stat output lines are written to the logs as well.  Is there a way to turn that off?

Response:
Stat-Analysis originally just wrote its output to log files. Then we added the "-out" option to write the output to a separate file instead. When "-out" is used, the output is written to the "-out" file INSTEAD OF the log file.

Then we added the "-out_stat" option to format and write the output to a true .stat file including all the header columns. But specifying "-out_stat" DOES NOT prevent the output from being written to the log file.

It does make sense to me that when "-out" or "-out_stat" is provided, Stat-Analysis should NOT write its output to the log file.

This task is to suppress the logging of job output when the "-out_stat" option is provided. It is already suppressed when "-out" is used.

### Time Estimate ###
1/2 day

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
No sub-issues required.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: John HG
- [x] Select **scientist(s)** or **no scientist** required: no scientist required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [x] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
No impacts.

## Enhancement Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update log messages for easier debugging.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.
