### ISSUE TITLE
Make the specification of a binary threshold in Wavelet-Stat optional.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1746]
## Describe the Enhancement ##
This issue arose via the JTTI project meeting. For this project, we need the ability to run Wavelet-Stat without applying a categorical threshold to convert the data to a binary image instead. This task is to make the thresholding step optional and deal with any consequences of that change.

Be sure to:
(1) Make the Wavelet-Stat thresholding step optional in the config file
(2) Consider the scientific impact of this change. For example, this may make MSE no longer summable across scales.
(3) Consider the impacts to the PostScript and NetCDF output from Wavelet-Stat.
(4) Add new unit tests to exercise this functionality.
(5) Update the scientific and technical documentation in the MET User's Guide.

Recommend coordinating with May Wong to test the changes. 

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
164951 - NOAA JTTI FV3SAR

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: John HG
- [x] Select **scientist(s)** or **no scientist** required: Eric G

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [x] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by ericgilleland** [comment]
> 
> ## Describe the Enhancement
> 
> This issue arose via the JTTI project meeting. For this project, we need the ability to run Wavelet-Stat without applying a categorical threshold to convert the data to a binary image instead. This task is to make the thresholding step optional and deal with any consequences of that change.
> 
> Be sure to:
> (1) Make the Wavelet-Stat thresholding step optional in the config file
> (2) Consider the scientific impact of this change. For example, this may make MSE no longer summable across scales.
> (3) Consider the impacts to the PostScript and NetCDF output from Wavelet-Stat.
> (4) Add new unit tests to exercise this functionality.
> (5) Update the scientific and technical documentation in the MET User's Guide.
> 
> Recommend coordinating with May Wong to test the changes.
> ### Time Estimate
> 
> _Estimate the amount of work required here._
> _Issues should represent approximately 1 to 3 days of work._
> ### Sub-Issues
> 
> Consider breaking the enhancement down into sub-issues.
> 
>     * [ ]  _Add a checkbox for each sub-issue here._
> 
> 
> ### Relevant Deadlines
> 
> _List relevant project deadlines here or state NONE._
> ### Funding Source
> 
> _Define the source of funding and account keys here or state NONE._
> ## Define the Metadata
> ### Assignee
> 
>     * [x]  Select **engineer(s)** or **no engineer** required: John HG
> 
>     * [x]  Select **scientist(s)** or **no scientist** required: Eric G
> 
> 
> ### Labels
> 
>     * [x]  Select **component(s)**
> 
>     * [x]  Select **priority**
> 
>     * [x]  Select **requestor(s)**
> 
> 
> ### Projects and Milestone
> 
>     * [x]  Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
> 
>     * [x]  Select **milestone** to next major version milestone or "Future Versions"
> 
> 
> ## Define Related Issue(s)
> 
> Consider the impact to the other METplus components.
> 
>     * [x]  [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
> 
> 
> ## Enhancement Checklist
> 
> See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
> 
>     * [ ]  Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
> 
>     * [ ]  Fork this repository or create a branch of **develop**.
>       Branch name: `feature_<Issue Number>_<Description>`
> 
>     * [ ]  Complete the development and test your changes.
> 
>     * [ ]  Add/update log messages for easier debugging.
> 
>     * [ ]  Add/update unit tests.
> 
>     * [ ]  Add/update documentation.
> 
>     * [ ]  Push local changes to GitHub.
> 
>     * [ ]  Submit a pull request to merge into **develop**.
>       Pull request: `feature <Issue Number> <Description>`
> 
>     * [ ]  Define the pull request metadata, as permissions allow.
>       Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
> 
>     * [ ]  Iterate until the reviewer(s) accept and merge your changes.
> 
>     * [ ]  Delete your fork or branch.
> 
>     * [ ]  Close this issue.

I think this idea is a good one.  It may change the interpretation of the IS (and other summaries from the Casati papers) but in practical terms, a wavelet decomposition provides information about a variable at independent scales, so MSE and the like will still be meaningful.  The approach is described in Briggs and Levine (1997).

Briggs, W. M. and R. A. Levine, 1997: Wavelets and field forecast verification. Mon. Wea. Rev., 125, 1329 - 1341, doi: 10.1175/1520-0493(1997)125<1329:WAFFV>2.0.CO;2.

**Comment by JohnHalleyGotway** [comment]
In met/src/tools/core/wavelet_stat...
In the WaveletStatConfig_default file, see the "cat_thresh" configuration option.

If cat_thresh is set to an empty list, skip the thresholding. This prevents the user from being able to apply no threshold and other thresholds in the same run, but that's probably just fine.

First thing would be running unit_wavelet_stat.xml. Next, modify one of the config files by setting cat_thresh to an empty list and see it error out... and that'll tell you where to start.

Contact May Wong to get her code changes. We should make the same or similar changes in GitHub and document well.

**Comment by sethlinden** [comment]
In the config file, I noticed there is both the fcst field cat_thresh and also the obs field cat_thresh. I noticed these are somewhat tied together in the sense that if I set the fcst cat_thresh to an empty list, but don't change the obs cat_thresh, the error message I get is: 

WaveletStatConfInfo::process_config() -> The number of thresholds for each field in "fcst.cat_thresh" must match the number of thresholds for each field in "obs.cat_thresh".

So can the obs and fcst cat_thresholds both be independently optional? That is, can one can have an empty list and the other still have a non-empty list (has the  thresholds)? Or do they both need to be empty lists (if one is empty)?

**Comment by sethlinden** [comment]
From May Wong's email

The lines that were modified were (lines 1011-1018):

 // Apply the threshold to each point to create 0/1 mask fields
      // MW: remove the thresholding 
      for(j=0; j<n; j++) {
         //f_dat[j] = isc_info[i].fthresh.check(f_na[j]);
         //o_dat[j] = isc_info[i].othresh.check(o_na[j]);
         diff[j]  = f_dat[j] - o_dat[j];
      } // end for j

It’s a really simple mod, so hopefully it’ll be straightforward to make this modification a configuration option.

**Comment by sethlinden** [comment]
It looks like May is basically ignoring both the fcst and obs thresholds. That is, not applying any threshold to both the fcst data and the obs. So in this case the thresholds are the same: none, which would be an empty list for both the obs and fcst cat_thresh in the config files once I make the change.

**Comment by jprestop** [comment]
@sethlinden Please keep in mind that I have not worked with this tool, but am doing my best to pull pieces together to try to help.

Looking at the message:
> WaveletStatConfInfo::process_config() -> The number of thresholds for each field in "fcst.cat_thresh" must match the number of thresholds for each field in "obs.cat_thresh".

and knowing that "the “cat_thresh” entry is an array of thresholds to be used when computing categorical statistics" (from https://met.readthedocs.io/en/latest/Users_Guide/config_options.html), tells me that the obs and fcst cat_thresholds cannot be independently optional and that they have to have the same length.  I do not believe that one can have an empty list and the other still have a non-empty list.  I believe that if one is empty they both need to be empty.  I hope that helps confirm what it sounds like you were already thinking.  Please let me know if you have any other questions.

**Comment by sethlinden** [comment]
@jprestop that sounds correct from what I can tell. I think they both need to be empty lists. That's what I'll work towards first. Thanks for the help!

**Comment by sethlinden** [comment]
I have made good progress on this issue but have some questions. I have the code working, using a specific "missing" threshold (using >-9999) in the config file in order to skip the masking but still produce the output / statistics and have the output show "NONE" for the  FCST_THRESH and OBS_THRESH in the txt and stat output files. Since the fcst-threshold (and obs-threshold) are of type: SingleThresh (or ThreshArray), I initially took the path of least resistance: so in order to skip using the threshold (skip masking) I set this to ">-9999". If you look at the code in wavelet_stat.cc it loops over the number of thresholds, so in order for this to work (as May set it up), you have to pass in at least 1 threshold (for both fcst and obs thresholds). So I pass in the ">-9999", then I use strcmp to skip applying the thresholds to the data. Then I use strcmp to to change the output columns to say "NONE" in the output file. I also had to modify the library: vx_stat_out/stat_columns.cc: write_header_cols() so it would recognize the ">-9999" and change the output string to "NONE". The question I have is I'm not sure we want to use ">-9999" in the config file to indicate no masking (not applying the threshold)?

**Comment by jprestop** [comment]
@sethlinden Thanks for explaining what you did and why you did it that way.  Unfortunately, I am also not sure if we would want to use ">-9999" in the config file to indicate there is no masking (not applying the threshold).  I do not know if this situation exists in other tools and there is already a way to handle it or not.  If so, it seems we would want to be consistent.  If you're able to attend the MET engineering meeting on Thursday, it would be good to talk about this, as maybe others would know.  If not, I'd suggest we wait until @JohnHalleyGotway gets back so that he can provide guidance.  If you will be able to attend the meeting, please add an agenda item to the [meeting notes](https://docs.google.com/document/d/1Dy3-uC2XD8SHX1InxzeY5uDIwk2Bj20p8rjCOvyckCg/edit) and we can talk about it there.  Thanks for all of your work on this!

**Comment by sethlinden** [comment]
I'm going to try and get this to work using empty lists (cat_thresh = [];). The main issues is that code loops over the number of thresholds (fcat_ta[i_vx].n_elements()) and this gets set to 0 if the list is empty. So if I can set the number of elements to 1 and then handle this accordingly down stream it should work.

Or is there a better "value" to use to indicate missing or non-existent thresholds for the SingleThresh type?

**Comment by sethlinden** [comment]
I was able to use a an empty list in the config file (cat_thresh = [];). Then in  wavelet_stat_conf_info.cc, the empty list comes through as "NA" using the .get_str() function. So I can key on that (using strcmp to "NA"), then I add back in a "missing" threshold: I add back ">-9999" to the thresh array (for both fcst_thresh and obs_thresh). Then all the downstream code recognizes the ">-9999" as missing, skips applying the thresholds and uses "NONE" as the thresholds strings in the .stat and .txt output. Next I need to check the netCDF output and post-script (.ps) output to see if it's using any of the threshold strings and try to set those to "NONE" as well.

**Comment by JohnHalleyGotway** [comment]
@sethlinden I made several changes here, described in the commit messages above.
- Code alignment... please configure your editor to insert spaces instead of tabs. The MET code generally indents 3 spaces.
- Fixed a couple of typos/tweaked wording in docs.
- By convention, all warning/error messages start with the function name and begin/end with a blank line to make them stand out in the logfile. So the message begins with one '\n' and ends with two '\n\n'.
- Updated logic to check each pair of fcst/obs thresholds for inconsistent NA usage.
- Updated logic to reinitialize apply_fcst/obs_thresh variables to true inside the loop since NA can appear anywhere in the threshold list.
- I took the opportunity to replace 'n_elements()' with 'n()' to make the code a bit more concise. I've been doing that incrementally whenever I touch old parts of the code.
