### ISSUE TITLE
Speed up the MODE convolution step using the algorithm for the fractional coverage field.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1759]
## Describe the Enhancement ##
This idea arose in discussions with @michelleharrold about MODE taking 2 hours to run on dense global grid. One relatively slow step in MODE is the convolution smoothing step. It takes a significant amount of processing. Here's the place where that's done:
https://github.com/dtcenter/MET/blob/develop/src/libcode/vx_shapedata/shapedata.cc#L517
(before restructured: https://github.com/dtcenter/MET/blob/develop/met/src/libcode/vx_shapedata/shapedata.cc#L517)

There is room for improvement in this function. We could switch to using the algorithm used for the fractional coverage field:
https://github.com/dtcenter/MET/blob/c3329cdecd48f80ebe451e28e11670afc9f8a26c/met/src/basic/vx_util/data_plane_util.cc#L204

The latter is more efficient. Instead of processing w*w neighborhood points for each grid point, it'd only processes 2*w points. With a convolution radius of 5, that's processing 10 points per grid point instead of 25. So that change *might* speed up the convolution step by 40%. Of course, that isn't the only runtime hog but it is significant.

This would also be very useful for other projects that lean heavily on MODE, including UW-CIMMS.

Need to make sure we get exactly the same result before/after this change.

### Time Estimate ###
3 days.

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- No sub-issues required.

### Relevant Deadlines ###
Must be done by Jul 2021

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [x] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
No impacts.

## Enhancement Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
@TaraJensen I'm wondering if there's room in my matrix for @michelleharrold to make a small (20 - 40 hours?) allocation to fund work for this issue? We discussed this issue at the AF/GSWR meeting on 5/3/21.
