### ISSUE TITLE
Add configuration option to Point-Stat and Ensemble-Stat to define the uniqueness key for point observations.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1762]
## Describe the Enhancement ##
This is a request that arose via a MET-Help question from the USAF:
   https://rt.rap.ucar.edu/rt/Ticket/Display.html?id=99675

This feature request should provide configuration options to control the identification of "duplicate" point observations. The same configuration option should be added to Point-Stat and Ensemble-Stat, both of which process point observations.

This uniqueness key applies to the existing config file settings for:
   duplicate_flag = NONE or UNIQUE;
   obs_summary = [Many options]

In PairBase::add_point_obs(), the following code defines the contents of the uniqueness key:
```
   //  build a uniqueness test key
   string obs_key = str_format("%.3f:%.3f:%.2f:%.2f",
                       lat,         //  lat
                       lon,         //  lon
                       lvl,         //  level
                       elv).text(); //  elevation
```
Currently, any obs with the same latitude, longitude, level, and elevation are grouped into the same bucket that is processed by the obs_summary logic. In addition, if check_unique is set and the valid times are the same, then the new obs is skipped entirely:
```
     if(check_unique) {
        vector<ob_val_t>::iterator o_it = (*it).second.obs.begin();
        for(;o_it != (*it).second.obs.end(); o_it++) {
           if((*o_it).ut == ut) return false;
        }
     }
 ```
Recommend adding something like:
```
obs_unique_key = [ "OBS_LAT", "OBS_LON", "OBS_LVL", "OBS_ELV" ];
```
And make sure that this is parsed for each vx task from each obs.field array entry. It's possible that users may want to define uniqueness differently for each vx task. Recommend loop through the array allocation and building the uniqueness key based on the entries. Recommend supporting names which correspond to the existing MPR column names for user convenience rather than defining any new convention.

I do worry about this implementation being slow. So when duplicate_flag = obs_summary = NONE, don't waste time keeping track of this. Also, try to make it as fast as possible.

### Time Estimate ###
3 days.

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
No sub-issues required.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [x] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
Will need to define a METplus issue to support this configurable option.

## Enhancement Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
