### ISSUE TITLE
Enhance TC-RMW to process gridded data with a higher time frequency than the corresponding track data.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1773]
## Describe the Enhancement ##
This is an issue that arose via the DTC staff meeting on 4/29/21 during Evan's portion of the presentation about UFS physics suites across scales testing.

For this project, the team evaluated hourly model output against hourly MRMS analyses. They ran the tc-rmw tool to convert precipitation data to storm-relative components. While the data was hourly, the corresponding BEST track data was 6-hourly. The tc-rmw tool is not handling the difference in time-frequency very well. For each valid time, I suspect that tc-rmw just uses the closest storm location in time.

This task is to enhance tc-rmw to interpolate the storm location linearly between the track points before/after each model output time. Specifically, test this using hourly MRMS precipitation data with 6-hourly BEST track data.

Recommend getting sample model output and track data from @evankalina for testing.

### Time Estimate ###
2 days.

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
No sub-issues needed.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: John HG
- [x] Select **scientist(s)** or **no scientist** required: Kathryn and Evan

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [x] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
No impacts.

## Enhancement Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by evankalina** [comment]
@JohnHalleyGotway excellent summary; thanks for recording it. One clarification, for the model runs, everything is working well, because we have both hourly model output and hourly model tracks. The problem occurs when processing the observations, because we have hourly rainfall obs, but 6-hourly tracking data from the National Hurricane Center. We have to linearly interpolate that track data before we give it to TC-RMW.

I am happy to provide sample data illustrating the problem – just let me know.
