### ISSUE TITLE
Create outline for the MET Contributor's Guide

### ISSUE THREAD

**Issue by jprestop** [dtcenter/MET#1774]
## Describe the Task ##
Create an outline for a MET Contributor's Guide.

Please use this rst guide for formatting sections:
https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html
```
# with overline, for parts
* with overline, for chapters
=, for sections
-, for subsections
^, for subsubsections
“, for paragraphs
```

### Time Estimate ###
1 to 3 days of work

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
NONE

### Funding Source ###
2702691, 2792541

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [x] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
Recommend that we schedule a working meeting to brainstorm topics for the Contributor's Guide.

**Comment by jprestop** [comment]
Add information regarding running the unit tests individually for testing.  In particular, we want to note that some tests are dependent on output from others.  For example, xml/unit_wavelet_stat.xml requires the obs file stage4_2012040912_F012_APCP12.nc, which would only be created by running xml/unit_pcp_combine.xml first.  This issue arose when @sethlinden was testing for [Issue 1746](https://github.com/dtcenter/MET/issues/1746).

**Comment by jprestop** [comment]
Add information regarding adding new unit test data.  New data should be added to mohawk in /d2/www/dtcenter/dfiles/code/METplus/MET/MET_unit_test/unit_test.  This is linked to from kiowa and seneca in the project area.

**Comment by georgemccabe** [comment]
Pull request #2029 includes CI functionality via GitHub Actions that should be documented here. We should at very least document the commit keywords used to override the default logic.

@jprestop  is editing this comment to add the notes from the MET Engineering meeting on 20220127:
GitHub actions for MET (#1546) - up to 10 min
George: Brief overview of logic (https://github.com/dtcenter/MET/actions/runs/1753512237)
- Details live in .github/workflows/*.yml
- Every push to a feature/bugfix/develop*/main* branch = compilation
- Every pull request = run all unit tests and diff vs truth data
- “**ci-run-unit**” turns ON regression test for your feature branch
- Input data on seneca (trimmed from 50G down to ~7G) and lives on DockerHub 
- Lots of changes to the unit test output directory names
- Status: PR submitted this morning
- What you need to do… After PR is merged, merge latest from develop into your feature branch.

**Comment by j-opatz** [comment]
Noting that there should be a section that describes how skills scores/verification statistics should be introduced and benchmarked.

**Comment by JohnHalleyGotway** [comment]
Recommend documenting how we add new test data files that are needed for new unit tests. Note that this requires the ability to run as the met_test user on mohawk.

1. Log on to mohawk.
2. Execute ```runas met_test```.
3. Go to ```cd /d2/www/dtcenter/dfiles/code/METplus/MET/MET_unit_test```
4. Copy the full set of new file(s) into the ```unit_test``` subdirectory.
5. Use wgrib, wgrib2, or a NetCDF utility to create the smallest possible subset of those files that are necessary to run the tests, and copy the minimal subset of new file(s) into the ```develop/unit_test``` subdirectory.
6. Recreate the test data tarfile by running ```cd develop; rm unit_test-all.tgz; tar -cvzf unit_test-all.tgz unit_test```
7. The next time GitHub actions runs are triggered for MET, they'll notice that the tarfile is newer than the MET test data image and automatically go regenerate that image. That data image is housed in DockerHub at [dtcenter/met-data-dev:develop-all](https://hub.docker.com/layers/191857061/dtcenter/met-data-dev/develop-all/images/sha256-eca18cc7938a9f55965b934d2eb46865d63bb56f78b1dce4fab46c29e3c5921b?context=repo).

**Comment by JohnHalleyGotway** [comment]
Recommend adding sections describing how to...
1. add new columns to existing line types
2. add a new output line type
3. add new GRIB table files
4. setting up your development environment (req'd env vars, input test data, etc)\
5. link into the METplus development workflow documentation

**Comment by jprestop** [comment]
@lisagoodrich, just a note that I already created a branch for this work (feature_1774_contrib_outline).  I added the names for the rst files to the existing index.rst page in the docs/Contributors_Guide directory.

**Comment by jprestop** [comment]
While the outline has been created and merged (https://github.com/dtcenter/MET/pull/2253), coding standards aren't yet in place.  Leaving this issue open.

**Comment by jprestop** [comment]
Consider adding a section to list the steps needed for creating a GitHub project:

- copy/update the title and description
- add new columns to the default view
- define all the other views
- change from default private to public
- copy over the workflow automation settings
- add the METplus team with write permission plus any other admins
- go to each repo and "add" the new project to it

**Comment by jprestop** [comment]
While the outline has been created and merged (https://github.com/dtcenter/MET/pull/2253), coding standards aren't yet in place.  A new task [Add content to the Contributor's Guide](https://github.com/dtcenter/MET/issues/2360) and subtask [Create and add coding standards to the Contributor's Guide](https://github.com/dtcenter/MET/issues/2361) have been created for future work in the Contributor's Guide.  Closing this issue.
