### ISSUE TITLE
Enhance Stat-Analysis to write the GO Index and CBS Index into a new SSIDX STAT line type.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1788]
## Describe the Enhancement ##
This enhancement is recommended for the DTCenter Air Force LIS project. The Stat-Analysis tool supports the skill score index and GO index job types. The GO Index is just a special version of the skill score index job. As of MET version 10.0.0, Stat-Analysis simply prints the output for this job to the screen or to an output file. This task is to create a new .stat line type to store the relevant output.

Still need to decide exactly what columns should be written to this new line type. Could be as little as the final score, or as complex, as the individual scores/weights for each component. So this may end up being a fixed number of columns or variable length and based on the number of user-defined components in the configurable Skill Score index.

Be sure to define related issues for METdatadb and METviewer, as noted below.

### Time Estimate ###
3 days.

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
No sub-issues, but this work will also satisfy a related GitHub issue: dtcenter/MET#1031

### Relevant Deadlines ###
October 2021

### Funding Source ###
2712221

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: John HG
- [x] Select **scientist(s)** or **no scientist** required: Michelle and/or Tara

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [x] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
- [x] No METplus issue is needed here in my opinion.
- [x] Create a METdatadb issue to load this new line type: dtcenter/METdatadb#63
- [x] Create a METviewer issue to plot these statistics via the batch and GUI: dtcenter/METviewer#327

## Enhancement Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update log messages for easier debugging.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.

**Comment by JohnHalleyGotway** [comment]
John HG and Michelle discussed this over G-Chat on 5/26/21. Here are some takeaways:
- Stat-Analysis currently supports -job go_index which is defined by [STATAnalysisConfig_GO_Index](https://github.com/dtcenter/MET/blob/main_v10.0/met/data/config/STATAnalysisConfig_GO_Index
).
- Consider defining STATAnalysisConfig_WMO_Index to define the WMO Index (i.e. CBS score) components.
- Also add -job wmo_index as a shortcut for using that config file.
- Enhance STAT-Analysis to write a new line type (maybe SSINDEX or SSIDX?) to store the output of -job go_index, wmo_index, and ss_index.
   - Could set DESC = GO_INDEX, WMO_INDEX, or SS_INDEX
- This is computed once for each model initialization and the skill scores are computed relative to a reference model. The AF often defines their reference using a persistence forecast. Need to determine if that functionality needs to be supported. If so, it could be done via METplus wrappers. 
- Question: How can/should a CI be computed for WMO_INDEX? Would it be computed for a single initialization or not? Where would CI's be computed, MET or METviewer?
- Question: How much detail should the new line type contain? Just the final score or the definition of and skill score for each component?
   - That'd be a lot of "data" columns with strings. How would that be loaded by METdatadb and plotted by METviewer?
   - Recommend asking for input from UK MetOffice.

**Comment by JohnHalleyGotway** [comment]
@michelleharrold question for you. In MET version 10.0.0, using the "-by" job command option in Stat-Analysis for the go_index and ss_index job types produces the following warning message:
```
WARNING: The -by option is ignored for the "go_index" job type.
```
While I'm working on this logic, should I attempt to make "-by" work here? For example, that'd enable you to compute the GO Index or CBS Score for multiple masking regions and model initializations in a single job:
```
-by VX_MASK,FCST_INIT_BEG
```
Would that functionality be useful the DTC AF projects?

**Comment by michelleharrold** [comment]
@JohnHalleyGotway -- if adding the -by functionality is not a huge lift, that would be useful for DTC AF projects. Thanks!

**Comment by JohnHalleyGotway** [comment]
While meeting with the UK Met Office, they clarified that we should call this the "CBS Index" rather than the "CBS Score". I'm relieved to hear this recommendation because this name is much more consistent with the existing -job go_index and -job ss_index options. @michelleharrold can I add support for -job cbs_index instead of -job cbs_score?

**Comment by JohnHalleyGotway** [comment]
Here's the list of things to be done:
- [x] Fix the .stat output header columns. Need to keep track of the min/max times and list of unique masking regions, etc.
- [x] Would be better to enhance warning message if possible to indicate which column has the null string.
Getting lots of warnings when writing the output .stat file:
```
WARNING: check_hdr_str() -> null string!
```
Done, this warning is now more useful:
```
WARNING: check_hdr_str() -> output header column MODEL is empty!
```
- [x] Make the -by option work for -go_index, -cbs_index, and -ss_index jobs.
- [x] Refine the log messages.
- [x] Update the STATAnalysisConfig_CBS_Index with ACTUAL definition of it as defined in:
[cbs_score.tar.gz](https://github.com/dtcenter/MET/files/7050733/cbs_score.tar.gz)
- [x] Move the definition of the skill score index name (i.e. GO_INDEX, CBS_INDEX, SS_INDEX) into the config file to make defining new ones very easy (NOTE: this adds a new config option named ss_index_name).
- [x] Add/update unit tests.
- [x] Add/update docs.

**Comment by JohnHalleyGotway** [comment]
@michelleharrold @briannen and/or @hertneky, please test this functionality in kiowa:/d1/projects/MET/MET_pull_requests/met-10.1.0/met-10.1.0_beta2/feature_1788/MET-feature_1788_SSIDX/met/bin/stat_analysis

You can find some great examples, along with input test data in:
kiowa:/d1/projects/MET/MET_pull_requests/met-10.1.0/met-10.1.0_beta2/feature_1788/test_feature_1788_SSIDX

And here's a tarfile of the scripts/data:
[test_feature_1788_SSIDX.tar.gz](https://github.com/dtcenter/MET/files/7062172/test_feature_1788_SSIDX.tar.gz)

Please also review documentation updates:
(1) Describing the [ss_index](https://met.readthedocs.io/en/feature_1788_ssidx/Users_Guide/stat-analysis.html#skill-score-index) job, [go_index](https://met.readthedocs.io/en/feature_1788_ssidx/Users_Guide/stat-analysis.html#go-index) job, and [cbs_index](https://met.readthedocs.io/en/feature_1788_ssidx/Users_Guide/stat-analysis.html#cbs-index) job.
(2) And the description of the [output](https://met.readthedocs.io/en/feature_1788_ssidx/Users_Guide/stat-analysis.html#job-ss-index-go-index-cbs-index).
