### ISSUE TITLE
Change -type for gen_vx_mask from an optional argument to a required one.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1792]
## Describe the Enhancement ##
A met-help question revealed that having the -type option for gen_vx_mask as an optional argument with "poly" as the default value causes some confusion. Changing -type from an optional to a required argument would be more clear:
https://rt.rap.ucar.edu/rt/Ticket/Display.html?id=99861

This task is to:
- Change -type from optional to required.
- Make sure the resulting error message is clear.
- Update existing unit tests and add the -type option to them, as needed.
- Update the documentation to indicate this change.
- Coordinate with METplus to make sure all the existing use cases still run after this change.

### Time Estimate ###
1 day

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
No sub-issue required.

### Relevant Deadlines ###
None

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [x] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
Should be no impacts, but as noted above, be sure to test that this change doesn't break any of the METplus use cases.

## Enhancement Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
Please be sure that your changes include:

1. Update [masking.rst](https://github.com/dtcenter/MET/blob/main_v10.0/met/docs/Users_Guide/masking.rst) changing "-type" from an optional argument to a required one (remove the square braces which indicate optional).
2. Update [unit_gen_vx_mask.xml](https://github.com/dtcenter/MET/blob/main_v10.0/test/xml/unit_gen_vx_mask.xml). Several of those calls to gen_vx_mask do NOT include "-type" and just rely on the default of "-type poly". Add "-type poly" to any calls in which they're missing.
3. Update [test_gen_vx_mask.sh](https://github.com/dtcenter/MET/blob/main_v10.0/met/scripts/examples/test_gen_vx_mask.sh) by adding "-type poly" where needed. This is run by "make test".
