### ISSUE TITLE
Enhance python embedding to support using MET_PYTHON_INPUT_ARG across all tools.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1793]
## Describe the Enhancement ##
The idea for this enhancement arose during the GSWR Air Force evaluation in 2021. The DTC team used METplus to do a comparison of analysis datasets. However, two details caused a challenge. First, neither dataset was at a consistent time interval. Second, python embedding was required for reading both datasets.

The goal was to use METplus to run Grid-Stat and MODE at routine time intervals. For each evaluation time, choose files from the two data sources closest to that time stamp. Pass them through python embedding to be evaluated by Grid-Stat and MODE. The challenge is in setting up those calls in METplus. When the input filename template is set to a constant PYTHON_NUMPY, it lacks the necessary timestamp information with which to search for files falling within the time window.

The fix is to support a new option for METplus constructing commands for python embedding. Instead of setting the filename template to a constant PYTHON_NUMPY, set it to the actual path for the input data files but also include the "file_type = PYTHON_NUMPY;" configuration option. And have the python command to be run specify "MET_PYTHON_INPUT_ARG" in place of the input filename defined by the template.

This approach is already supported in Series-Analysis, MTD, Ensemble-Stat, and Plot-Data-Plane. This task is to modify the code to support its use in the rest of the tools, including Grid-Stat, Point-Stat, and MODE. In version 10.0.0, the Met2dDataFileFactory class sets MET_PYTHON_INPUT_ARG as an environment variable whenever a new factory is created. The problem is in the order of operations... Grid-Stat creates separate factory instances for both the forecast and observation files before actually reading any data from them. So the observation environment variable settings override the one for the forecast.

Consider modifying this implementation. Instead of relying on environment variables to be set at proper time and in the proper order, modify the factory class to store the name of the input file used to instantiate it. Prior to executing any python commands to read data for that factory object replace instances of MET_PYTHON_INPUT_ARG with the name of file used to create that factory object. This could be a more robust solution and would hopefully require no changes to the application code.

Be sure to enhance unit_python.xml with example that demonstrate this usage.

### Time Estimate ###
1 day.

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
No sub-issues required.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [x] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
Coordinate with METplus developers and define related issue(s) there as needed.

## Enhancement Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
