### ISSUE TITLE
Create anchors for MET variable in MET User's Guide

### ISSUE THREAD

**Issue by jprestop** [dtcenter/MET#1811]
## Describe the Task ##
Create anchors for MET variable in MET User's Guide. On these pages:
https://met.readthedocs.io/en/latest/Users_Guide/config_options.html#config-options
https://met.readthedocs.io/en/latest/Users_Guide/config_options.html#settings-specific-to-individual-tools
create anchors for the numerous variables that are bolded without creating section headers for each variable.

### Time Estimate ###
1 to 3 days of work

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
None; self-imposed; see selection in Projects/Milestones

### Funding Source ###
2702691

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by jprestop** [comment]
This is how existing internal links are referenced:
On this[page](https://met.readthedocs.io/en/latest/Users_Guide/point-stat.html), exists this sentence:
> Common statistics that use a climatological reference include: the mean squared error skill score (MSESS), the Anomaly Correlation (ANOM_CORR and ANOM_CORR_UNCNTR), scalar and vector anomalies (SAL1L2 and VAL1L2), continuous ranked probability skill score (CRPSS and CRPSS_EMP), Brier Skill Score (BSS) (Wilks, 2011; [Mason, 2004](https://met.readthedocs.io/en/latest/Users_Guide/refs.html#mason-2004)).

The point-stat.rst file has the following syntax for the Mason reference:

:ref:\`Mason, 2004 \<Mason-2004\>\`

And, ref.rst has the following syntax to enable linking to this Mason reference:

.. _Mason-2004:

| Mason, S. J., 2004: On Using "Climatology" as a Reference Strategy
|   in the Brier and Ranked Probability Skill Scores. *Monthly Weather Review*,
|   132, 1891-1895.

However, this does not have all of the functionality we would like.  We would like a link to Mason, so that it can be easily referenced by a developer to give to a user so that the developer does not have to go into the .rst file to see what the header is to link to. In the above example the link is:

https://met.readthedocs.io/en/latest/Users_Guide/refs.html#mason-2004

However, the developer would not know to add "#mason-2004" to the link without looking at the .rst file.  The link reference needs to be visible and easily obtainable.

This page may have some guidance on how to proceed:

https://stackoverflow.com/questions/30822880/python-sphinx-anchor-on-arbitrary-line

Please scroll down to the following text:

> EDIT:
> There is one more option. This will create an anchor and the hover effect.

and try that method out to see if it gives us what we want.  If that doesn't give us what we want, we'll need to do some further digging, but don't spend too much time on it.

**Comment by lisagoodrich** [comment]
We ended up using the reference links above.  If the link is clicked on, the full address will appear in the web address and can be copied from there.
