### ISSUE TITLE
Enhance MET's NetCDF library interface to support level strings that include coordinate variable values instead of just indexes.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1815]
## Describe the Enhancement ##
This feature request arose via met-help for a NASA user:
  https://rt.rap.ucar.edu/rt/Ticket/Display.html?id=100072
While this idea arose via met-help, it would be widely useful.

When reading gridded data from NetCDF the level string defines how to index into the variable dimensions to extract the 2D field of data. For example:
```
name = "varname"; level = "(0,4,*,*)";
```
The \*,\* indicates the gridded dimensions, and the 0,4 indicates that the 0-th index from the first dimension and 4-th index from the second dimension should be used.

MET's NetCDF library code includes a special case for the "time" dimension. Instead of an integer index value, the user can supply a timestring in YYYYMMDD[_HH[MMSS]] format. The NetCDF library code parses the timestamp, searches the time dimension for that time, and then uses the index for that matching value.

This issue is to extend that same logic to non-time dimensions as well. For example, let's say there is a coordinate variable named "pressure", meaning there is both a variable and dimension named pressure. For example:
```
name = "varname"; level = "(550,d02,*,*)"; // for varname(pressure,domain,Nx,Ny)
```
The logic should be:
- For "550" in the first dimension, search the "pressure" coordinate variable to find the matching index.
- For "d02" in the second dimension, search the "domain" coordinate variable to find the matching index.

If either value is not found, error out with a useful error message.

The big challenge here is that 550 is an integer. So it could conceivably either specify a coordinate variable VALUE or an INDEX. The difficulty is distinguishing between them. We could consider supporting embedded single or double quotes to differentiate between strings and indices. For example:
```
name = "varname"; level= "(550,'d02',*,*)"; // 550 is an index
name = "varname"; level = "('550','d02',*,*)"; // 550 is a pressure level value
```
Recommend that we think more about this.

### Time Estimate ###
3 days.

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
No sub-issues needed.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
2799991

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
Will likely need a METplus issue to support the use of this new option.

## Enhancement Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by hsoh-u** [comment]
Considerations:
- Allowed characters: digits, period, and the negative sign. In case of time dimension, digits and the underline character ("_") are allowed.
- single/double quotation mark for the value should be escaped (the single and the double quotation marks are already used to defined "field" argument
   - single quotation marks to escape the whole "field" argument
   - double quotation marks are used for the "name" and "level" settings
- The value must not match with the available offset/index
- The range is separated by "-", for example (start-end,*,*). The negative number will cause a problem. --> change "-" to ":"?
- possibly precision issue

**Comment by JohnHalleyGotway** [comment]
Note that this issue was also discussed with the MetOffice on March 3, 2022. They have configured METplus to read data for 76 different levels. The config file is VERY long and difficult to maintain and is built upon the assumption that all levels are present and in sequence.

According to @mpm-meto, that is a reasonable assumption for operational data, but is NOT a good assumption when using data pulled from the tape archive. Even worse, if the level indices were used incorrectly, then that would not be obvious... meaning you would not get a runtime error. Instead, you'd just produce bad statistics.

While there is no immediately obvious solution to distinguish between the use of a dimension index versus specify the value for that index, we can just create a convention. I considered distinguishing based on the presence or absence of quotes around the value, but quoted strings are already so loaded, we may want to avoid adding to that confusion.

One option to consider is using some prefix like "value:". For example...
```
level = "(1,0,*,*)";
```

Uses the 2nd value from the first dim and 1st value from the second since the indices are 0-based.
Whereas,
```
level = "(value:500,value:25,*,*)";
```

Would find and use the index for the coordinate variable for the first dimension with a value of 500, and would find and use the index for the coordinate variable for the second dimension with a value of 25.

Of course we could substitute any other formatting convention instead, like enclosing values in square brackets... level = "([500],[25],\*,\*)"; I recommend that we seek user feedback to find the a straightforward and intuitive way of handling this.

**Comment by hsoh-u** [comment]
My suggestion is 
1. using prefix "@" to make the digits to the string value (it's used at the "**date**" command: date -d **@1654209200**).
2. If the string value is a number without prefix @, apply it as an index first. If the index does not exist (bigger than the  dimension), apply it as the value string

```
=== case 1 modified from above description: ===
name = "varname"; level = "(550,20220601_0000,*,*)"; // 550 is an index
name = "varname"; level = "(@550,20220601_0000,*,*)"; // 550 is a pressure level value

=== case 2 (assuming first dimension is height and dimension size is 10)===
name = "varname"; level = "(0,*,*)"; // 0 is an index for height level
name = "varname"; level = "(@0,*,*)"; // 0 is a string value for height level
```

Above cases, 
- case 1: 20220601_0000 is a special case which is supported already. It's not a number because of underscore. Applied as time string value.
- case 1: 550 is applied as the pressure level value only if the dimension of the pressure level is less than 550. 
- case 1: @550 is converted to the string value "550" of the pressure level 
- case 2: 0 is less than the dimension size (10), applied it as an index
- case 2: "@0" is converted to the string value "0"

Using single or double quote. They are already used.
```
./plot_data_plane nam_prmsl.nc PRMSL_meansealevel.ps 'name="PRMSL_meansealevel"; level="(0,*,*)";'
```
So escaping is required to use single or double quotes.

Please confirm this design.

**Comment by JohnHalleyGotway** [comment]
Howard, that sounds like a great idea to me! Nice and concise but also intuitive. Let's go with that.

For backward compatibility, we'd still want to support YYYYMMDD_HHMMSS strings for the time coordinate. But for consistency, it should also work with an @ symbol in front.
