### ISSUE TITLE
Enhance Series-Analysis to support hss_ec_value as a gridded field of values.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1818]
## Describe the Enhancement ##
dtcenter/MET#1749 enhanced MET by adding support for the HSS_EC statistic where the MCTS Heidke Skill Score is computed with a user-configurable expected correct rate. A corresponding hss_ec_value configuration option was added for Point-Stat, Grid-Stat, Series-Analysis, and Stat-Analysis. The hss_ec_value option must be set to a constant value between 0 and 1 which specifies the expected rate for which multi-category contingency table entries will correctly fall on the diagonal by chance.

This option should remain a constant in Point-Stat, Grid-Stat, and Stat-Analysis. However it should be enhanced for Series-Analysis. Since Series-Analysis computes stats separately for each grid point, the hss_ec_value can change for each grid point. This task is to enhance Series-Analysis to support the following.

Current option:
```
hss_ec_value = 0.5;
```
New option:
```
hss_ec_value = {
  file_name = "/path/to/some/file"; // if empty, use the forecast file
  field = { name = "HSS_EC"; level = "something" };
  regrid = { ... }; // options to regrid to the vx domain
}
```
This is very similar to the existing climo_mean option.
Really need sample data from NOAA/CPC to test/demonstrate.

### Time Estimate ###
3 days.

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
No sub-issues required.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
Likely need to add a METplus issue to support this configuration option.

## Enhancement Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
