### ISSUE TITLE
Recommend deprecating the poorly named and unecessary obs_prefbufr_map PB2NC config file option.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1821]
## Describe the Task ##
When running PB2NC for a DTC T&E project, @jwolff-ncar was confused by the two configuration file options which define the mapping of input variable names to output strings.
From https://github.com/dtcenter/MET/blob/main_v10.0/met/data/config/PB2NCConfig_default
```
//
// Mapping of input BUFR variable names to output variables names.
// The default PREPBUFR map, obs_prepbufr_map, is appended to this map.
//
obs_bufr_map = [];

//
// Default mapping for PREPBUFR.  Replace input BUFR variable names with GRIB
// abbreviations in the output.  This default map is appended to obs_bufr_map.
// This should not typically be overridden.
//
obs_prefbufr_map = [
...
```
There are a few issues here:

1. obs_prefbufr_map (with an F instead of a P) is a clear typo.
2. There is no description of obs_prefbufr_map in the documentation.
3. Providing 2 config options that are just appended to eachother is unnecessary and has caused confusion. The concatenation is done in this function:
https://github.com/dtcenter/MET/blob/0c79e00e9e07054d133cb91ee7fbb7cf4da7ac7e/met/src/basic/vx_config/config_util.cc#L1066

Recommend making the following changes:

1. Note that the original changes were done via https://github.com/dtcenter/MET/issues/636.
2. Talk with @hsoh-u to get his approval for these proposed changes.
3. Remove the poorly name obs_prefbufr_map entry from the PB2NC config file.
4. Update the config file comments to recommend that users add to the obs_bufr_map list but leave the defaults in place.
5. However, in parse_conf_obs_bufr_map() continue to parse the obs_prefbufr_map entry, if present, for backward compatibility. Just make sure that parsing doesn't error out when that entry is no longer present.

### Time Estimate ###
4 hours.

### Sub-Issues ###
Consider breaking the task down into sub-issues.
No sub-issues required.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required: @jwolff-ncar 

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
Need to coordinate config file changes with METplus wrappers.

## Task Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
