### ISSUE TITLE
Fix Stat-Analysis aggregation of MPR to MCTC or MCTS.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1830]
## Describe the Enhancement ##
The changes for #1749 introduced a bug in Stat-Analysis. So this is a bug that only appears in the development version of the code. Running the following type of aggregate_stat job in stat_analysis produces the runtime error listed below.
```
stat_analysis -lookin point_stat_SID_INC_EXC_120000L_20120409_120000V_mpr.txt -job aggregate_stat -line_type MPR -out_line_type MCTC -fcst_var UGRD -by VX_MASK -out_thresh 'gt0,gt2'
ERROR  :   AsciiTable::rc_to_n() -> range check error ... 
ERROR  :                            (Nrows, Ncols) = (2, 14)
ERROR  :                            (r, c) = (0, 14)
```
This is to...
- Add a new call to Stat-Analysis in the unit tests to replicate this problem.
- Fix the aggregation logic in Stat-Analysis that causes this runtime error.

### Time Estimate ###
4 hours.

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
No sub-issues required.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: John HG
- [x] Select **scientist(s)** or **no scientist** required: No scientist needed

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
No impacts.

## Enhancement Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
