### ISSUE TITLE
Update FAQ in User's Guide with info from webpage FAQ 

### ISSUE THREAD

**Issue by jprestop** [dtcenter/MET#1834]
## Describe the Task ##
There are two FAQs with different information:
https://dtcenter.org/community-code/model-evaluation-tools-met/faqs
https://met.readthedocs.io/en/latest/Users_Guide/appendixA.html

We will maintain the FAQ in the User's Guide and will reduce the webpage to a link to the User's Guide FAQ. 

Feedback from John O.:
There is some redundancy and a few points (mostly in the User's Guide) that aren't the most helpful/relevant. Examples:

- the points about graphics
- MODE differing from Grid-Stat
- how MET differs from previously mentioned verification packages

The DTC page FAQ is more in-depth and descriptive.

Lisa will take John's feedback into consideration and ask if she has any questions.  She will add the information from the website to the User's Guide.  Once finished, Julie will update the webpage to point to the FAQ.

### Time Estimate ###
1-3 days of work

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
Self imposed - MET 10.1.0-beta2 (08/13/21), if possible

### Funding Source ###
2792541

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_1834_faq`
- [x] Complete the development and test your changes.
- [x] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [X] Delete your fork or branch.
- [X] Close this issue.

**Comment by JohnHalleyGotway** [comment]
@j-opatz I just committed some changes to the FAQs here:
https://github.com/dtcenter/MET/blob/feature_1834_faq/met/docs/Users_Guide/appendixA.rst

Unfortunately, I don't have the time/bandwidth right now to do an exhaustive set of updates, but I did want to commit my changes to the first few. This task is to migrate the FAQs from the website into the docs... which @lisagoodrich and @jprestop have done. I'm fine with committing them largely as-is knowing that we can go back and revise them in the future.

So I'd like to hand this off to you for whatever additional changes you see fit to make.

**Comment by jprestop** [comment]
@JohnHalleyGotway, you mentioned you didn't have the time/bandwidth right now to do an exhaustive set of updates.  We have merged in the changes by @lisagoodrich and @j-opatz. Would you like us to leave this issue open for a more exhaustive set of updates, or would you prefer that we close it?

**Comment by JohnHalleyGotway** [comment]
@jprestop this issue is for migrating the content over from the [MET website](https://dtcenter.org/community-code/model-evaluation-tools-met/faqs) into the [User's Guide](https://met.readthedocs.io/en/develop/Users_Guide/appendixA.html). Assuming it's all been moved, I'd recommend:
- Remove the FAQ's from the MET website.
- Close this issue.
- Create a new Documentation issue for "Future Versions" to review/revise the content of the FAQ's in Appendix A.

**Comment by lisagoodrich** [comment]
Closing the issue.  #1878 has been created for @JohnHalleyGotway  to review at a later date.
