### ISSUE TITLE
Add support for calculating vector partial sums using Python Embedding

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/MET#1839]
MET Help ticket 100090 discovered a possible limitation using Python Embedding. The required level name is not saved when using Python embedding because it typically isn't used, however it looks like this value is part of the check to find matching U and V fields.

See: https://github.com/dtcenter/MET/blob/e903f8fed8916dd5a97536777c48d8c191e2c7d7/met/src/tools/core/grid_stat/grid_stat_conf_info.cc#L188-L194

I confirmed that this comparison is what prevents the U and V fields from being matched:

`vx_opt[i].fcst_info->req_level_name() == vx_opt[j].fcst_info->req_level_name()`

The value for each is an empty string, but the comparison still results in 'false.' I also tried using set_attr_level to override the value for level, but the resulting value for req_level_name() was still empty.

On kiowa, there is an environment and command set up to run:

```
cd /d1/projects/MET/MET_Help/100090
./run_cmd.sh
```

You can also start up gdb on the same command using:

`./start_gdb.sh`

The following is output from GDB with commands and notable output in bold:

> **(gdb) break grid_stat_conf_info.cc:190**
> Breakpoint 1 at 0x1c14de: file grid_stat_conf_info.cc, line 190.

> **(gdb) run**
> Starting program: /d1/projects/MET/MET_releases/met-10.0.0/src/tools/core/grid_stat/grid_stat -v 3 PYTHON_NUMPY PYTHON_NUMPY /d1/projects/MET/MET_Help/100090/METplus/parm/met_config/GridStatConfig_wrapped -outdir /d1/projects/MET/MET_Help/100090/out
> ...
> Breakpoint 1, GridStatConfInfo::process_config (this=0x555555d845e0 <conf_info>, ftype=FileType_Python_Numpy,
>     otype=FileType_Python_Numpy) at grid_stat_conf_info.cc:190
> 190                       vx_opt[i].fcst_info->req_level_name() ==

> **(gdb) p vx_opt[j].fcst_info->is_v_wind()**
> $1 = **true**

> **(gdb) p vx_opt[j].obs_info->is_v_wind()**
> $2 = **true**

> **(gdb) p vx_opt[i].fcst_info->req_level_name().c_str()**
> $3 = 0x555556210430 ""

> **(gdb) p vx_opt[j].fcst_info->req_level_name().c_str()**
> $4 = 0x55555620f740 ""

> **(gdb) p vx_opt[i].fcst_info->req_level_name() == vx_opt[j].fcst_info->req_level_name()**
> $5 = **false**

## Describe the Enhancement ##
Update the Python embedding logic to properly handle this case.

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [X] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [ ] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by georgemccabe** [comment]
Also, it looks like the MET User's Guide should be updated to include more information on using is_u_wind and is_v_wind. Currently searching for the keywords does not find any information about the settings: https://met.readthedocs.io/en/latest/search.html?q=is_u_wind&check_keywords=yes&area=default

**Comment by JohnHalleyGotway** [comment]
Coordinate testing of this functionality with @easatterfield from NRL.
