### ISSUE TITLE
Add Scatter Index to the CNT line type.

### ISSUE THREAD

**Issue by j-opatz** [dtcenter/MET#1843]
## Describe the New Feature ##
As work continues in the marine and coastal verification area, the variable Scatter Index has been used more and more in the user Python code. As MET is already producing 99% of the variables calculated for marine and coastal verification, the addition of Scatter Index seems appropriate.

Scatter Index (SI) is calculated by

SI = 100.0*[ (avg((fcst-obs)^2)^0.5) - (avg(fcst-obs)^2) ] / avg(obs)

### Acceptance Testing ###
Input data types and formats vary, but this should be first tested against ice cover data (netCDF4 format). A sample forecast and obs file are on Kiowa:

Fcst file: /d1/projects/MET/MET_test_data/ice_cover_ScatterIndex/20210305_rtofs_glo_2ds_n024_ice.nc
Obs file: /d1/projects/MET/MET_test_data/ice_cover_ScatterIndex/2021030512_UKMO_L4.nc
Python embedding: /d1/projects/MET/MET_test_data/ice_cover_ScatterIndex/ice_code_hera.py

Python script requires the following arguments to run:
Fcst_file Obs_file hemisphere<north or south> file_indicator<fcst or obs>

Depending on the file indicator, the script will either pass the forecast field or observation field in memory for MET to utilize. Success of this issue is the return of the Scatter Index by MET in the CNT line type.

### Time Estimate ###
*Need estimate from engineer*

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
None

### Funding Source ###
2788881

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
- Need to add issues for METdatadb to update the CNT line type and METviewer to plot this new statistic.
- dtcenter/METdatadb#61
- dtcenter/METviewer#317

## New Feature Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update log messages for easier debugging.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.

**Comment by JohnHalleyGotway** [comment]
Recommend making the following changes for this work:
- In met/src/basic/vx_util/stat_column_defs.h, add "SI" or "SCATTER" (or whatever name @j-opatz says) as the last column of cnt_columns. And ask @j-opatz about confidence intervals? Is there a normal approximation for this or should we bootstrap it? Maybe @ericgilleland knows?
- Add new column(s) to the met/data/table_files/met_header_columns_V10.1.txt  for the CNT line.
- Add new column(s) to test/hdr/met_10_1.hdr for the CNT line.
- Update write_cnt_cols() function in met/src/libcode/vx_stat_out/stat_columns.cc.
- Add "scatter" variable to CNTInfo in met/src/libcode/vx_statistics/met_stats.h (either "CIInfo scatter" or "double scatter" depending on what @j-opatz says about CI's.
- Update met/src/libcode/vx_statistics/met_stats.cc to actually compute it (somewhere).
   - Add it to the list of stats in "CNTInfo::get_stat()".
- In met/src/libcode/vx_statistics/compute_stats.cc, update compute_cntinfo() to compute scatter index... probably around line 344.
- Update the CNT table 9.6 in met/docs/Users_Guide/point-stat.rst and also update Appendix C with the definition of this new stat.

I don't think any changes to Stat-Analysis are needed.

**Comment by ericgilleland** [comment]
Sorry, I lost the thread here.  What is CNT?

**Comment by JohnHalleyGotway** [comment]
@ericgilleland CNT stands for "continuous" statistics. It's the .stat line type to which MET writes continuous statistics and the contents are described in these two tables in the user's guide:
https://met.readthedocs.io/en/latest/Users_Guide/point-stat.html#id10
https://met.readthedocs.io/en/latest/Users_Guide/point-stat.html#id11

This issue will tack on at least 1 more column to the end of it for the "scatter index". The question for you is whether or not MET should compute any parametric or non-parametric CI's for this statistic. It'd be pretty easy to add it to the list of stats for which we perform bootstrapping. Should we? And what about a parametric CI estimate?

**Comment by ericgilleland** [comment]
Hi John,

Ok, I'm not familiar with scatter index.  Is there a reference I can see
for it?

Eric

**Comment by sethlinden** [comment]
Hi John, What c++ application or python script do I run for testing these changes? Is it ice_code_hera.py? What c++ application does this call? I'd like to run a c++ command line by hand if possible for this? I'm just getting setup to work on this issue.

**Comment by TaraJensen** [comment]
It appears there's a reference for Scatter Index on the ECMWF website.  Here's the link: h[ttps://www.ecmwf.int/sites/default/files/elibrary/1989/13201-verification-study-global-wam-model-december-1987-november-1988.pdf](url)  @ericgilleland - can you review in the very near future to determine how to apply CIs?

**Comment by ericgilleland** [comment]
The SI defined in this document seems to differ from the SI from the other
source.  Here, it is just RMSE/Obar.  Although one could argue that the
RMSE follows a normal df (it is a mean after all), I would recommend using
the bootstrap to obtain confidence intervals for it.

Eric

**Comment by sethlinden** [comment]
@ericgilleland what version of SI should I use

From NOAA:

SI = 100 * (RMSE -BiasMean^2) / ObsMean

or from ECMWF:

SI = RMSE / ObsMean

**Comment by sethlinden** [comment]
Eric mentioned in an email that we should probably use the version from ECMWF:

SI = RMSE / ObsMean

This is the equation I currently used for SI in the CNT stats.

**Comment by ericgilleland** [comment]
I've been looking through the documentation about scatter index and also
did a literature search.  The ECMWF document (
https://www.ecmwf.int/sites/default/files/elibrary/1989/13201-verification-study-global-wam-model-december-1987-november-1988.pdf),
which defines the SI to be just the RMSL / Obar, is not very detailed about
the index.  At one point it mentions that the scatter is high, but I think
it's referring to a scatter plot and not the SI. In the same are of text,
it mentions that the SI of 0.37 is rather high, so perhaps the SI is an
indication of the amount of "scatter" seen in a scatter plot?  SI does seem
to be tied to regression models, but if 0.37 is high and the mentioned
scatter plot shows a lot of scatter, then I'm not sure how to interpret it
because (although this particular scatter plot is difficult to interpret
for me) I don't see what they mean by the scatter is high here.

The only mention I found in the literature is this paper (
https://doi.org/10.1029/92JC02258) but it has a different definition (three
different definitions) that is similar.  It has scatter indices just for
the model, just for the obs, and then one that is defined (Eqs 7 to 9) by
MSL / (Fbar * Obar).  It says that they are the relative variabilities (Eqs
7 and 8) and relative errors (Eq 9).  Low values of the former are obtained
for constant wave height (the variable used in this paper) while low values
of Eq (9) indicate perfect agreement between the model and obs.

I found no mention of the other version, let's call it SI2 (v. SI1), 100 *
(RMSL - Bias^2) / Obar.  The SI does seem to fall between zero and one, so
multiplying it by 100 makes sense.  I don't know why the bias is squared
when using the RMSL, but it makes sense to remove the bias.  It could be an
interesting index to study further, if that is of interest to any
applications?  If so, I could put something about it in the next plan for
the vx base funding.

In terms of whether to use SI1 or SI2, I would suggest using both but
without studying them, I'm not sure what effect removing the (squared) bias
would have.

In terms of CI's, I stand by using bootstrap CI's.  It would need to be
studied more to see if a parametric CI is viable or not, and will likely
depend on the specific variables used (i.e., if an assumption about the
sample distribution of F_i - O_i, i = 1,...,n can be made, or at least by
its average); SI2 would be a bit trickier in this regard but it may still
be possible.

Best,

Eric

**Comment by ericgilleland** [comment]
I found this recent paper that uses SI1 (doi: 10.1016/j.oceaneng.2018.03.029).
Also, I don't see any reason that SI1 (or SI2) should fall between zero and
one, but it does seem that it is usually a small number in that interval.

Eric

**Comment by ericgilleland** [comment]
Although both the paper I just sent and this other one (doi:
10.1016/j.oceaneng.2017.04.043) suggest that SI is in (0,1).

**Comment by sethlinden** [comment]
Eric, thanks for digging into this and providing more information on Scatter Index. For now we will stick with the simple SI calculation (SI = RMSE / ObsMean) along with using bootstrapped confidence intervals. We can always go back and change the equation / confidence intervals. I'll be formulating a pull request for the SI changes this morning.

**Comment by ericgilleland** [comment]
Yes, I think sticking to SI1 for now is best.  BTW-- if it can be assumed
that RMSL and Obar are both N(0,1) (a big assumption), then their quotient
(i.e., SI1) would be Cauchy distributed, so for a parametric CI, you'd have
to write a routine for the Cauchy.  I'm guessing (w/o working it out) that
the quotient of any two normals would be some kind of similar df.

Eric

**Comment by TaraJensen** [comment]
@j-opatz - can you follow-up with Todd re: the discrepencies in SI and confirm we are doing what makes sense??

**Comment by JohnHalleyGotway** [comment]
Feedback from Todd Spindler on 7/29/21:

The Scatter Index was a cross-over from the wave validation work Henrique Alves and Deanna Spindler were working on at the time.  Unfortunately Henrique no longer works at EMC, but we're pinging him to see if he remembers any of the SI calculation details.  However, a rather brief lit survey shows me what you're seeing.  As discussed in Bryant 2016 (attached),

"Like the RMSE, ambiguities exist in the definition of the scatter index, with authors either defining it as the standard deviation of the errors (i.e., demeaned RMSE) divided by the mean of the observations (Mentaschi et al. 2013), as done by WIS, or defining it as the ERMS (defined above) divided by the mean of the observations (Ris et al. 1999; Rogers et al. 2012; Akpinar et al. 2012)."

The ECMWF definition appears to originate with Zambresky (1989) (attached), but we also see the alternative definition used by JCOMM, from Bidlot and Holt (2006) (attached). 

From this rather confused mess, it would appear, at least to me, that there doesn't appear to be a compelling reason to prefer one over the other, beyond perhaps using the simpler definition of the two, which as you note excludes model bias.   I'd leave it up to you to make the final determination.  The use of SI in ice was, to be sure, something of a novel application, and I don't know if it ever generated much interest.  I'm not particularly concerned with exact reproducibility of the stats calculations between my python workflows and MET, as even minor differences in, say, the handling of the land/sea masks at the coastlines can cause some grid points to be excluded in one and included in the other, and introduce minor variations in the final numbers.
[wmo-td_1333_en.pdf](https://github.com/dtcenter/MET/files/6909991/wmo-td_1333_en.pdf)
[13201-verification-study-global-wam-model-december-1987-november-1988.pdf](https://github.com/dtcenter/MET/files/6909992/13201-verification-study-global-wam-model-december-1987-november-1988.pdf)
[ERDC-CHL CHETN-I-91-1.pdf](https://github.com/dtcenter/MET/files/6909993/ERDC-CHL.CHETN-I-91-1.pdf)
