### ISSUE TITLE
Enhance Ensemble-Stat, Point-Stat, Plot-Point-Obs, and Point2Grid to support python embedding of point observations.

### ISSUE THREAD

**Issue by j-opatz** [dtcenter/MET#1844]
## Describe the New Feature ##

This issue was originally titled "Allow read into memory for Point2Grid". However this feature request should be done as part of a larger task to more broadly support python embedding of point observations across multiple tools. Currently, this type of python embedding is only supported in ascii2nc. This task is to expand that support to include point_stat, ensemble_stat, point2grid, and plot_point_obs. I believe those are all the tools which read the NetCDF point observation files written by the *2NC point pre-processing tools. If needed, consider breaking this issue out into separate ones for each of those tools. Make sure that the conventions for requesting python embedding of point observations are as consistent as possible across these tools.

Currently, The MET user's guide states the Point2Grid tool "...takes point observations from a NetCDF output file from one of the four previously mentioned MET tools (ascii2nc, madis2nc, pb2nc, lidar2nc) and creates a gridded NetCDF file." The original workflow did not take advantage of the Python embedding, which is now prevalent in MET.

A recent use case highlighted the cumbersome task of converting an ASCII file to a grid for analysis, via (ASCII2NC w/ Python Embedding) --> (Point2Grid) --> (GridStat). The ASCII2NC tool creates netCDF files each time it runs, but since these files are immediately passed into Point2Grid, they only take up disk space and are unwanted by the user.

The desire is for the Point2Grid tool to no longer require a file input when it is a tool called in a series of tools (as described above). Instead, Point2Grid should be able to utilize a file *or* point data from a memory-read list which the user provides via Python embedding.

### Acceptance Testing ###
An ASCII file of any amount of point data will suffice for testing. @j-opatz can provide an example file and companion Python script if required.
The successful resolution of this issue will be Point2Grid being able to read in point data from memory.

### Time Estimate ###
*Need input from engineer*

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
None

### Funding Source ###
2788881 (do not charge as of 16Dec21)
Instead split 2792541, 2702691, 2799991, 2700042, 

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## New Feature Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by TaraJensen** [comment]
As per our discussion on 12/9/21 - This capability would be very helpful to assess if Python-embedding using Met Office's VARPy code to read ODB might be efficient enough or optimizable enough to work for operational verification.  If it isn't, then we might have to develop the C++ interface, which will be substantial work.

**Comment by JohnHalleyGotway** [comment]
@hsoh-u you mentioned in the MetOffice meeting on 12/9/21 that you've made progress on supporting this in the plot_point_obs tool. I'm wondering if the solution is application specific - meaning you'll need to make lots of changes to each MET tool (plot_point_obs, point2grid, point_stat, ensemble_stat). Or is there something that can be done within the library code so that incorporating it into each tool is relatively easier.

It may be a good idea to schedule a design review meeting to discuss your plans and progress so far.

**Comment by hsoh-u** [comment]
This is a python script 1) with default data or 2) which reads a MET point observation NetCDF file (output of xxx2nc).

[read_met_point_obs.py.txt](https://github.com/dtcenter/MET/files/7687227/read_met_point_obs.py.txt)

**Comment by hsoh-u** [comment]
Support MET NetCDF with grib_code instead of variable name & index
[read_met_point_obs.py.txt](https://github.com/dtcenter/MET/files/7722902/read_met_point_obs.py.txt)

**Comment by hsoh-u** [comment]
Design document:
[Design of Python Embedding for MET point observation.pdf](https://github.com/dtcenter/MET/files/7723747/Design.of.Python.Embedding.for.MET.point.observation.pdf)

**Comment by hsoh-u** [comment]
Performance issue: The time differences between NetCDF input and the python embedding were about 5 seconds for point2grid and plot_point_obs. It took less than 1 second to read and to build the python objects at the python script for point2grid python embedding. The additional 4 or 5 seconds would be caused by 1) loading python interpreter, and 2) invoking python script, and 3) converting Python object to C/C++ objects. There is a chance that at least 4 to 5 seconds delay with python embedding at kiowa.
