### ISSUE TITLE
Add Point-Stat and Ensemble-Stat obs_quality_exc configuration option to specify which quality flags should be excluded

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1858]
## Describe the New Feature ##
This feature was requested by the UK Met Office via [GitHub Discussions](https://github.com/dtcenter/METplus/discussions/1005).

Recommend the following changes:
- Rename the existing "obs_quality" config option for Point-Stat and Ensemble-Stat as "obs_quality_inc".
- Add a new config option for "obs_quality_exc" to specify which quality strings should be excluded.
- If "obs_quality_inc" is not defined, parse the old "obs_quality" config option and store use its value, for backwards compatibility.
- Be sure that these options are parsed separately for each verification tasks, just like the existing "obs_quality" option is.
- Be sure to update the documentation and unit tests to exercise this.

### Acceptance Testing ###
*List input data types and sources.*
*Describe tests required for new functionality.*

### Time Estimate ###
2 days.

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
No sub-issues needed.

### Relevant Deadlines ###
Needed for the operational use of METplus by the UK Met Office

### Funding Source ###
Met Office Support key: 2799991

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: Seth
- [x] Select **scientist(s)** or **no scientist** required: no scientist required but request that the Met Office test the resulting beta release.

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
- [X] Define a METplus issue to handle the config option changes for obs_quality_inc and obs_quality_exc: dtcenter/METplus#1213

## New Feature Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
For my last [commit](https://github.com/dtcenter/MET/commit/31e98f22d925415c9e66e7c70a516cb5b9ed8c02), I performed the following testing:
1. Ran Ensemble-Stat using:
```
obs_quality = [];
```
And get:
```
WARNING: 
WARNING: parse_conf_obs_qty_inc() -> Set the "obs_quality_inc" value ((nul)) from the deprecated "obs_quality" configuration entry. Replace "obs_quality" with "obs_quality_inc".
WARNING: 
```
2. Ran Ensemble-Stat using:
```
obs_quality = ["1", "2", "3" ];
```
And get:
```
WARNING: 
WARNING: parse_conf_obs_qty_inc() -> Set the "obs_quality_inc" value (1,2,3) from the deprecated "obs_quality" configuration entry. Replace "obs_quality" with "obs_quality_inc".
WARNING:
```
3. Ran Ensemble-Stat using:
```
obs_quality = [ "1", "2", "3" ];
obs_quality_inc = [ "8", "9", "10" ];
```
And get:
```
WARNING: 
WARNING: parse_conf_obs_qty_inc() -> Set the "obs_quality_inc" value (1,2,3) from the deprecated "obs_quality" configuration entry. Replace "obs_quality" with "obs_quality_inc".
WARNING: 
```
4. Ran Ensemble-Stat using:
```
obs_quality_inc = [ "8", "9", "10" ];
```
And get NO warning message.

This is all as expected. The presence of "obs_quality" in the config file results in a warning message. But if it is present, it's value takes precedence over "obs_quality_inc". And the warning message clearly states that.

**Comment by sethlinden** [comment]
This all looks good to me. Thanks!
