### ISSUE TITLE
Fix URLs in default MET config files

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/MET#1864]
The URLs in TCStatConfig_default is out-of-date:

https://github.com/dtcenter/MET/blob/3e33a4ec46e0a867cd4abb49d1e506b8cfe89de6/met/data/config/TCStatConfig_default#L21

There may be others.

## Describe the Enhancement ##
Review config files and update comments to reflect new location of files, i.e.
https://met.readthedocs.io/en/latest/Users_Guide/tc-stat.html

### Time Estimate ###
~1 day

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [X] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
10.1.0

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [X] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
@georgemccabe good catch on the bad link. This is the only bad reference to GitHub pages in the config files. However, all of the config files do mention the MET User's Guide. For example:
```
////////////////////////////////////////////////////////////////////////////////
//
// TC-Gen configuration file.
//
// For additional information, please see the MET User's Guide.
//
////////////////////////////////////////////////////////////////////////////////
```
Should we leave this as-is, or should I change all of these references to:
```
////////////////////////////////////////////////////////////////////////////////
//
// TC-Gen configuration file.
//
// For additional information, please see the MET User's Guide:
//    https://met.readthedocs.io/en/latest
//
////////////////////////////////////////////////////////////////////////////////
```
Or use the full path to the User's Guide?
https://met.readthedocs.io/en/latest/Users_Guide/index.html

The risk is, when we put specifics in there, we may need to change them in the future.

What's your preference?

**Comment by georgemccabe** [comment]
@JohnHalleyGotway , I am unsure of the best way to handle this, but I am leaning towards removing the URL to reduce the number of places that need to be updated if there is a change.

**Comment by JohnHalleyGotway** [comment]
Note that I used the following commands to fix these stale links in the GitHub issue and pull request templates:
```
cd .github
for file in `find ./ -name "*.md"`; do
  cat $file | sed 's%https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html%https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html%g' > t
  mv t $file
done
git add ISSUE_TEMPLATE/ pull_request_template.md
git commit -m "Fix stale URL in GitHub issue and pull request templates."
git push
```
Did this for:
- [x] MET (main_v10.0, develop)
- [x] METplus (main_v4.0, develop)
- [x] METviewer (main_v4.0, develop)
- [x] METplotpy (main_v1.0, develop)
- [x] METcalcpy (main_v1.0, develop)
- [x] METdatadb (main_v1.0, develop)
- [x] METexpress (development)

I did NOT update METexpress:main since I believe @mollybsmith-noaa is the only person who updates that branch.
