### ISSUE TITLE
Enhance TC-Pairs to only write output for a configurable list of valid times.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1870]
## Describe the Enhancement ##
Model developers at NOAA/GSL would like to run TC-Pairs/METexpress in realtime to analyze model performance while the BEST track file for that storm is still actively being updated. Recommend adding new TC-Pairs configuration file options to support this usage.

TC-Pairs currently supports valid_beg and valid_end. Only tracks that are completely contained in that window are retained. Just like we have init_inc and init_exc, recommend adding valid_inc and valid_exc options. If empty, their default values, all track points will be used. If valid_inc is non-empty, discard any track points that do not appear in that list. If valid_exc is non-empty, discard any track points that do appear in that list.

While TC-Pairs will still process all track data passed as input, provide an option to specify a list of one or more valid times for which output is desired. An empty list, the default value, means that all data should be written to the output. For a non-empty list, only write output for track points whose valid time appears in that list.

When running tc_pairs in realtime, processing a single valid time at once, the config options listed below would be useful.
```
valid_inc   = [ "20210807_060000", "20210807_120000" ];
valid_exc   = [ ];
write_valid = [ "20210807_120000" ];
```
When evaluating for valid_time = 20210807_120000, tc_pairs should only need the current time and one previous time. However, only write output for the current time.

### Time Estimate ###
2 days

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
No sub-issues needed.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
2792541

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: John HG
- [x] Select **scientist(s)** or **no scientist** required: Molly Smith

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
- [x] Define a METplus issue to make these config options configurable: dtcenter/METplus#1069

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update log messages for easier debugging.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.

**Comment by JohnHalleyGotway** [comment]
I worked on these changes yesterday/today while the details were still fresh. I've finished the code changes on the feature_1870_realtime branch and did some initial testing to make sure it works as I intended.

On 8/5/2021 (when jet is back up), I will compile this feature_1870_realtime branch on jet for @mollybsmith-noaa to test.

I do still need to:
- update tc_pairs documentation - DONE on 8/5/21
- update unit tests to exercise these options - DONE on 8/5/21
- writeup a METplus issue to make valid_inc, valid_exc, and write_valid configurable via the wrapper - DONE on 8/5/21

**Comment by JohnHalleyGotway** [comment]
@mollybsmith-noaa this feature branch is compiled on jet and ready for your testing. To test, please run:
```
module load intel
module load intelpython/3.6.5
module load netcdf/4.6.1
module load hdf5/1.10.4
/lfs1/HFIP/dtc-hurr/John.H.Gotway/MET/MET_development/MET-feature_1870_realtime/met/bin/tc_pairs
```
The additions to the TCPairsConfig file are "valid_inc", "valid_exc", and "write_valid".
Let's say that they current valid time being evaluated is stored in an environment variable named $CUR_VALID_TIME. In the TCPairs config file, you'd add:
```
write_valid = [ "${CUR_VALID_TIME}" ];
```
And then check the output file to confirm that only track points for that single time have been written.

If you're testing via METplus, @georgemccabe could tell you how to use MET config overrides. So please let him know if you are and have questions about that.

**Comment by georgemccabe** [comment]
To test using METplus, you will have to set MET_INSTALL_DIR in your user config file to use the feature branch version of tc_pairs:

`MET_INSTALL_DIR = /lfs1/HFIP/dtc-hurr/John.H.Gotway/MET/MET_development/MET-feature_1870_realtime/met`

You can also set this in the call to run_metplus.py by adding:

`config.MET_INSTALL_DIR=/lfs1/HFIP/dtc-hurr/John.H.Gotway/MET/MET_development/MET-feature_1870_realtime/met`

To set the value of write_valid to the current valid time for your run, you should be able to set:

`TC_PAIRS_MET_CONFIG_OVERRIDES = write_valid = [ "{valid?fmt=%Y%m%d_%H}" ];`

Let me know if that doesn't work. If it does, then we can add support for setting the variable in the METplus config so you would be able to set:

`TC_PAIRS_WRITE_VALID = {valid?fmt=%Y%m%d_%H}`

**Comment by mollybsmith-noaa** [comment]
Thanks, John and George! Today I got my post-TC verification working smoothly with rocoto, so this is top of my list for tomorrow. I'll let you know how it goes.

**Comment by JohnHalleyGotway** [comment]
@mollybsmith-noaa glad you hadn't started yet. Some testing this afternoon revealed that I hadn't added support for "write_valid" to subset the PROBRIRW output line type written by TC-Pairs. I just finished adding that and am recompiling that feature branch on jet now.

Not sure if you're generating any PROBRIRW output right now, but it seems like write_valid should apply to all TC-Pairs output.

**Comment by mollybsmith-noaa** [comment]
Thanks, John! I'm not currently generating probrirw output, but I do plan to in the future.

**Comment by JohnHalleyGotway** [comment]
@mollybsmith-noaa I'd really like to get these changes into the met-10.1.0-beta2 release. Can you please let me know once you've confirmed that they work as expected, and I'll submit a pull request?
Thanks.

**Comment by mollybsmith-noaa** [comment]
@JohnHalleyGotway Okay, I've gotten it to run with the various paths playing nicely, but I'm still having tracks discarded for falling outside the valid time window. If I want to verify at one example valid time, 2021070800, what do you recommend as the correct procedure? Set the INIT_BEG to a week prior, set the INIT_END to 2021070800, and set the write_valid to 2021070800 so I only get the output I want? If there's a storm that's been going for two weeks, but I only want to verify the last week of forecasts, will this exclude it?

**Comment by mollybsmith-noaa** [comment]
Basically, do I have to reprocess the entire hurricane season each time this runs to get just the valid time specified in valid_inc?

**Comment by mollybsmith-noaa** [comment]
It does work if I do that, though! So thumbs up on the write_valid and valid_inc options. They do what they're supposed to.

**Comment by JohnHalleyGotway** [comment]
@mollybsmith-noaa, essentially yes. TC-Pairs needs to re-process all tracks which may INCLUDE a track point for the new valid time. If your model produces output out to 14 days (for example), then you could process tracks for INIT_BEG = current valid time - 14 days and INIT_END = current valid time.

**Comment by mollybsmith-noaa** [comment]
@JohnHalleyGotway Okay, that makes sense. But if there was a storm that lasted longer that two weeks, would it stop processing new forecasts once the earliest forecasts fell outside of that two-week window?

**Comment by JohnHalleyGotway** [comment]
No, the INIT_BEG and INIT_END window is applied to the FORECAST tracks, not the verifying BEST track data. And by definition, it is not possible for a FORECAST track to last longer than 2 weeks, assuming 2 weeks is the maximum forecast length. Of course the BEST track can persist longer than 2 weeks... and with these settings, TC-Pairs should match that long BEST track up with whatever forecast tracks came from initializations within the last 2 weeks.

**Comment by mollybsmith-noaa** [comment]
Oh, okay! In that case, this should be a good solution for realtime verification.
