### ISSUE TITLE
FAQ detailed review

### ISSUE THREAD

**Issue by lisagoodrich** [dtcenter/MET#1878]
*Replace italics below with details for this issue.*

## Describe the Task ##
In July of 2021 the FAQ from the DTC site,
[ https://dtcenter.org/community-code/model-evaluation-tools-met/faqs](url) (Please Note: this link is now hidden.  It can only be accessed by this exact address.)
was merged into
[https://met.readthedocs.io/en/develop/Users_Guide/appendixA.html](url).  
This merger consolidated all FAQ questions into one location.  This work was completed under issue #1834  and #1867.
There are now 60 questions in the FAQ.
The original format from the DTC wasn’t in question format and had to be created to match the question format in appendixA. @lisagoodrich, @jprestop  and @j-opatz reviewed the material.  
* When @JohnHalleyGotway has some time, his keen understanding of the material is needed to make sure all of the questions and answers are accurate and clearly stated. 
* A clear organizational structure needs to be implemented to accommodate the larger number of questions.

### Time Estimate ###
*Estimate the amount of work required here.*
*3 days of work.*

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
Future versions

### Funding Source ###
Please confirm #2792541 is still active and appropriate to use.

### Assignee ###
- [x] Select ** @JohnHalleyGotway , @jprestop, @j-opatz and @lisagoodrich  **
- [ ] **no scientist** required at this time.

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Organization** level **Project(s)** 
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components. 
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.  Waiting until there is time to complete this project.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by jprestop** [comment]
Thanks @lisagoodrich!  In addition to listing the assignees in the text box, I added them to the issue, by selecting them under "Assignees" in the upper right.  I also changed the milestone to "Future Versions" based on @JohnHalleyGotway's request.

**Comment by lisagoodrich** [comment]
Darn it, I knew that!  Thanks for adding everyone.
