### ISSUE TITLE
Complete Application Security and Development STIG for MET version 10.1.0.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1882]
## Describe the Task ##
On 8/17/2021, METplus staff met with USAF to review issues in the statement of work. Prior to the next release on MET, version 10.1.0, complete the Application Security and Development STIG for MET. See below for details:

Included in this year's statement of work is the completion of STIGs for MET and METviewer. This should be completed for the next release. The STIG is required for any software to be installed on USAF machines. The STIG consists of 300+ questions which attempt to assess how an application is configured with respect to security. The answers are used to track vulnerabilities. This review is required for government-developed software. STIGS must be less than 90 days old. Major releases would come with a STIGS report. DSSA publishes the STIGS at cyber.mil. There is a STIG viewer that comes via a .jar. This is a requirement for the cybersecurity team to get this installed. This is in the new statement of work from February. This will be daunting the first time we do it, but will get easier in time.
ex. Does the s/w use SAML? Are things encrypted?

Steps for this:
(a) Download/install a STIG viewer from https://public.cyber.mil/stigs/srg-stig-tools/

(b) Retrieve the Application Security and Development STIG from here:
https://public.cyber.mil/stigs/downloads/?_dl_facet_stigs=app-security%2Capp-security-dev

Use the viewer to edit STIGs for both MET and METviewer. The goal is to characterize the current status of the application rather than trying to fix any/all issues that may arise. They want to establish a baseline from which we can do future work.

### Time Estimate ###
3 days.

### Sub-Issues ###
Consider breaking the task down into sub-issues.
No sub-issues needed.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: John HG and Howard
- [x] Select **scientist(s)** or **no scientist** required: No scientist required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
@fisherhucar recommends coordinating with Stephen Dowdy who completes the STIGs for other RAL projects.

**Comment by JohnHalleyGotway** [comment]
From @TaraJensen on 10/6/21:
Also - we need to start looking at the STIGS.  Maybe we can find a time in the next two weeks to get started.  I'll be asked about it again the first week of November so it would be good to make some progress ;-)
