### ISSUE TITLE
Enhance pcp_combine subtract mode to handle missing fields for 0-hour accumulated precipitation.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1884]
## Describe the Enhancement ##
This issue arose during the METplus/UK Met Office collaboration meeting on 8/19/2021. The 0-hour accumulated precipitation data from the Met Office does not, in general, contain all 0's. Instead, the data assimilation process results in non-zero values. The METplus pcp_combine wrapper does support this, as of version 4.0.0. When running in subtract mode, rather than subtracting A6 - A0 precip, it automatically switches from subtract mode to add mode for the single A6 input file (where A6 is just an example).

The wrapper is setup this way since many input datasets (including GFS) do NOT include APCP in the 0-hour output file. So attempting to run pcp_combine for A6 - A0 results in a runtime error.

The issue is to enhance pcp_combine as follows:
```
pcp_combine -subtract file1 config1 file2 config2 diff.nc
```
1. Attempt to read config2 from file2, and if successful, use that data.
2. If not successful and config2 has "A0", serve up a field of all 0's (basically). Or just return the data from config1 as the output.
3. If file2 does not even exist, exit with an error message stating that.

### Time Estimate ###
4 hours.

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
No sub-issues needed.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: John HG (have George review the PR)
- [x] Select **scientist(s)** or **no scientist** required: none needed

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
- [ ] Need a METplus issue to update the pcp_combine wrapper.

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
Note this can be tested using:
```
pcp_combine -subtract \
$MET_TEST_INPUT/model_data/grib2/gfsanl/gfsanl_4_20120409_0000_003.grb2 'name="APCP";level="A3";' \
$MET_TEST_INPUT/model_data/grib2/gfsanl/gfsanl_4_20120409_0000_000.grb2 'name="APCP";level="A0";' 
diff.nc
```
Currently this errors out with:
```
WARNING: 
WARNING: MetGrib2DataFile::data_plane() -> No matching record found for 'APCP/A0'
WARNING: 
ERROR  : 
ERROR  : get_field() -> can't get data plane from file "/Volumes/d1/projects/MET/MET_unit_test/MET_test_input/model_data/grib2/gfsanl/gfsanl_4_20120409_0000_000.grb2"
ERROR  : 
```
