### ISSUE TITLE
Remove ensemble post-processing from the Ensemble-Stat tool.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1908]
## Describe the Enhancement ##
MET#1904 added a new Gen-Ens-Prod ensemble post-processing tool to MET version 10.1.0, and MET#1907 warned users that ensemble product generation would be removed from Ensemble-Stat in a future version. This issue is to strip the processing of the "ens" dictionary, along with ensemble product generation options out of the Ensemble-Stat tool.

Need to more carefully define which, if any, of the "ensemble_flag" options should remain. For example, depending on the "output_flag" options requested, Ensemble-Stat will still need to compute the ensemble mean, standard deviation, and gridded ranks. Should it retain the ability to write those fields to an output NetCDF file?

Propose REMOVING minus, plus, min, max, range, frequency, nep, and nmep, leaving the following options which remain:
```
ensemble_flag = {
   latlon    = TRUE;
   mean      = TRUE;
   stdev     = TRUE;
   vld_count = TRUE;
   rank      = TRUE;
   weight    = TRUE;
}
```

Recommend that the tool check to see if the user provides and "ens" dictionary in the configuration file, and if so, error out with a useful error message. Also be sure to update the MET flowchart changing Ensemble-Stat from being green and blue, to only blue. It is a statistics generation tool (blue) but no longer does pre-processing (green).

Recommend coordinating these changes with @michelleharrold and the DTC UFS/SRW team.

Note that this work should be done in conjunction with #2139.

### Time Estimate ###
2 days.

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
No sub-issues needed.

### Relevant Deadlines ###
2793541

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: John HG
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
- [x] Define an issue to update the METplus Ensemble-Stat wrapper and remove the "ens" dictionary from the wrapped config file: https://github.com/dtcenter/METplus/issues/1816

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update log messages for easier debugging.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.

**Comment by JohnHalleyGotway** [comment]
Recommend renaming ensemble_flag to something else. Perhaps ens_rank_flag, ensemble_pairs_flag, or obs_rank_flag? This is similar in functionality to nc_pairs_flag in Grid-Stat.
