### ISSUE TITLE
Resolve PB2NC string truncation warning messages.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1909]
## Describe the Task ##
Pull requests for Issue #1855 introduced several hundred warning messages when running PB2NC. These are evident when running:
```
make test >& make_test.log
```
Here's the resulting [make.log](https://github.com/dtcenter/MET/files/7107358/make.log) file.
It contains 986 new warning messages:
```
grep WARNING make_test.log | grep get_variable_info | wc -l
     986
```
And here's what one looks like:
```
WARNING:   get_variable_info() truncated a string var_name from "SAID     | 001007 | SATELLITE IDENTIFIER (SATELLITE REPORTS ONLY)            |
WARNING: " to "SAID    "
```
This task is investigate this situation and get rid of that warning. I suspect that the vertical bar '|' should be interpreted as a field separator. Could you use strtok or string split instead so that this doesn't trigger a warning message?

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
Please fix in the next development cycle, met-10.1.0-beta3.

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: Howard
- [x] Select **scientist(s)** or **no scientist** required: none required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
No impacts.

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by hsoh-u** [comment]
This was introduced by checking the result of stpcpy APIs: give warnings if the string is truncated. **strnpy** does truncate if the target string buffer is smaller than the source string buffer. The checking should be skipped in this case. This will be implemented at m_strXXX API with #1903

**Comment by hsoh-u** [comment]
Fixed with #1903
