### ISSUE TITLE
Enhance the PBL derivation logic in PB2NC.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1913]
## Describe the Enhancement ##
This issue is the result of this METplus Discussion dtcenter/METplus#1140.

There was a lot of back and forth on that discussion thread, but in the end, two necessary changes were identified. This issue is to make the following 2 changes to the PBL derivation logic in PB2NC:

(1) In MET version 10.0.0, PB2NC replaces any computed PBL values > 5000 with a value of 5000. Change this behavior by defining the upper limit as 10,000 and replace any values > 10000 with BAD DATA. Note that these bad data observation values should not be written to the output.
 
(2) Check the input level data for the PBL derivation algorithm and omit any levels that contain non-pyhsical values, namely a pressure value of 0. For an example, see this Discussion [comment](https://github.com/dtcenter/METplus/discussions/1140#discussioncomment-1292156) which includes the following bad input level:
```
DEBUG 8: compute_pbl()     input to calpbl_: 0   0.00000 0.00000 36893488147419103232.00000 36893488147419103232.00000 -2.29688 1.30000
```

### Time Estimate ###
1 day.

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
No sub-issues.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: @hsoh-u 
- [x] Select **scientist(s)** or **no scientist** required: @PerryShafran-NOAA 

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
No impacts.

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
@hsoh-u here is the sample NDAS file and PB2NC config file I was using for testing:
[example_ndas.tar.gz](https://github.com/dtcenter/MET/files/7162869/example_ndas.tar.gz)
