### ISSUE TITLE
Add support for point-based climatologies for use in SEEPS

### ISSUE THREAD

**Issue by RachelNorth** [dtcenter/MET#1941]
## Describe the New Feature ##
Some verification metrics require components from a pre-determined climatology in order to calculate the score. 
 
In the specific case of calculating the Stable Equitable Error in Probability Space (SEEPS) it is necessary to use a climatology calculated at station locations to construct the score.  MET #563 contains details of the point-based climatology from ECMWF for use specifically to calculate SEEPS (specifically https://github.com/dtcenter/MET/issues/563#issuecomment-488135306). These are in text file format, with each column representing a particular aspect of the required climatology.

However, this functionality could also be applicable more generally, and other use cases could conceivably contain the required point-based climatology within a netcdf file.

### Acceptance Testing ###
ASCII text files or NetCDF anticipated as input.

### Time Estimate ###
Unknown as yet.

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
Part of Met Office contract, ending August 2022. MET v11.

### Funding Source ###
Met Office contract

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required @TaraJensen 
- [x] Select **scientist(s)** or **no scientist** required @mpm-meto, @RachelNorth

### Labels ###
- [x] Select **component(s)** MET/METplus possibly METcalcpy/METplotpy implications
- [x] Select **priority**
- [x] Select **requestor(s)** 

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## New Feature Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
@hsoh-u, I believe you already did this as part of the SEEPS work in MET-11.0.0-beta3. If so, please consider closing this issue.
