### ISSUE TITLE
Enhance Point-Stat to compute SEEPS for point observations and write new SEEPS and SEEPS_MPR STAT line types.

### ISSUE THREAD

**Issue by RachelNorth** [dtcenter/MET#1942]
## Describe the New Feature ##
The Stable Equitable Error in Probability Space (SEEPS) score is described in Rodwell et al. (2010) and was devised for evaluating quantitative precipitation forecasts against SYNOP gauge data at (but not limited to) station locations.  It uses a climatology to account for local variations in rainfall which enables aggregation over otherwise heterogenous locations.  

This issue will detail the work required to implement this capability within MET and to act as an umbrella issue to log progress as it is likely that implementing this will require division into further sub-issues. 

Changes will be required to Point-Stat in order to compute the score.
Support for a point-based climatology will be required. MET #1941 has been opened for the work required for this capability.

This issue will supersede the SEEPS portion of MET #563. 

This still needs more definition on how to implement.

The tasks for this work include:
- Enhance Point-Stat to compute SEEPS.
- Enhance Stat-Analysis to compute SEEPS from the matched pair (MPR) input lines.

There is no way to mathematically aggregate SEEPS over multiple runs. Instead we just compute the mean of the SEEPS over multiple runs.

We do still need to define the columns that should be included in a new SEEPS line type.

### Acceptance Testing ###
*List input data types and sources.*
Input data expected to be either ASCII text or NetCDF files.
Original IDL code can be provided to compare scores. Example C code is provided in the google drive link at https://github.com/dtcenter/MET/issues/563#issuecomment-488135306

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
2799991

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required @TaraJensen 
- [x] Select **scientist(s)** or **no scientist** required @RachelNorth, @mpm-meto

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## New Feature Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
@hsoh-u and @JohnHalleyGotway met on 5/13 to discuss. Here's some notes:

Steps for this...
- Use point ascii format or reformat to NetCDF. NetCDF would be faster and is still pretty easy to work with.
  - Reformat ascii to NetCDF and save script or code to do so in repo as well.
    Could live in: https://github.com/dtcenter/MET/tree/main_v10.1/met/src/tools/dev_utils
    Or find some other spot for a python conversion script.
- Recommend storing the resulting climo data on mohawk so that it appears in https://dtcenter.ucar.edu/dfiles/code/METplus/MET/MET_unit_test/develop/unit_test/climatology_data/

- Still keep them as 2 files per day (365 * 2)? Or combine all the data into 1 file? Or 2 files (00Z and 12Z)?
  - Try making 1 NetCDF file for the full year of data, but structure it to make data access as fast as possible.
  
- Where should SEEPS appear in the output of MET?
   1. Could add SEEPS column to the MPR output line to report the SEEPS value for that station at a single point in time.
   2. Cound enhance Stat-Analysis to read MPR lines from Point-Stat and compute an average SEEPS value through time for each point.
      -job summary -line_type MPR -by OBS_SID -column SEEPS
   3. (Not sure on this) Could add SEEPS column to the CNT output line to report the average SEEPS values across all stations in the masking region for a single point in time.
      Add CNT:SEEPS, run Stat-Analysis like this: -job aggregate_stat -line_type MPR -out_line_type CNT -by OBS_SID

Questions for @RachelNorth:
- Should 3 (above) be done? Is SEEPS always computed/reported separately for each station, or should we be averaging it across stations?
- Any opinion about storing all the climo point data in one NetCDF file versus 365 or 365*2 of them?

**Comment by RachelNorth** [comment]
@JohnHalleyGotway  apologies for the delay in responding to this one.

- Yes! One of the strengths of SEEPS is the diagnostic capabilities offered by having individual scores (and error categories) at station/grid point locations. We need to have the capability to do both output at stations/grid points and aggregate over a defined area. I think this is important, and I think it's important to be able to switch one or the other off. For example, an overview verification performance job might not need the score at stations, but a model upgrade test might want to see them.
- I think it would be a good idea to store in a NetCDF file. We do need to keep the distinction between valid times though, 0UTC and 12UTC. Users will want to verify focussing on the different times in the diurnal cycle. I don't understand the 365, 365\*2 reasoning? IIRC the climatology files have one per month. So surely that should be 12\*2? 
Could you let me have details on how you are going to format this NetCDF? Then I can ensure my TRMM 3B42 gridded climatologies conform to the same format and upload them to assist with your development.

**Comment by JohnHalleyGotway** [comment]
Here are notes from a meeting about SEEPS on 8/19/2022:
https://docs.google.com/document/d/1NS_djvpaoek226eH3R9oSf8tugg5vRQDbbHztEE86wM/edit

**Comment by hsoh-u** [comment]
From  [MetOffice SEEPS  discussion 8/19/2022 & 8/24/2022](https://docs.google.com/document/d/1NS_djvpaoek226eH3R9oSf8tugg5vRQDbbHztEE86wM/edit)
Point-Stat:

- SEEPS Single Station (SEEPS_MPR). Refer to the existing [MPR line type](https://met.readthedocs.io/en/latest/Users_Guide/point-stat.html?highlight=MPR#id24).
  - 21 header columns
  - Obs Station ID (OBS_SID)
  - Lat: latitude of station
  - Lon: longitude of station
  - FCST value: raw fcst value
  - OBS value: raw obs value
  - OBS_QC: quality control information
  - FCST category: 0,1, or 2
  - OBS category: 0, 1, or 2
  - p1: Climo-derived probability value for this station (dry)
  - p2: Climo-derived probability value for this station (dry + light)
  - t1: Threshold 1 for p1
  - t2: Threshold 2 for p2
  - SEEPS: Seeps score for the current pair
- SEEPS Aggregate in space and/or time (SEEPS)
  - 21 header columns
  - Total: number of pairs in this aggregation
  - s12, s13, s21, s23, s31, s32: Counts multiplied by the weights for each category (which come from the climo, and changes for  each month); this is for the 3x3 table cells (minus the reverse diagonal) → these are the SEEPS sub-components for 6 off-diagonal panels for 9-up plotting
  - pv1, pv2, pv3: marginal probabilities of the observed values → for the 3 reverse diagonal panels in 9-up plotting
  - pf1, pf2, pf3: marginal probabilities of the forecast values → for the 3 reverse diagonal panels in 9-up plotting
  - mean obs val: density-weighted mean (or simple mean) obs value
  - mean model val: density-weighted mean (or simple mean) forecast value
  - SEEPS score: density-weighted SEEPS score
    - Question remains as to whether the weight of each station is pre-defined or is it computed dynamically based on the density of the lat/lon’s being evaluated. Could call [GSL function](https://www.gnu.org/software/gsl/doc/html/filter.html?highlight=gaussian%20kernel#c.gsl_filter_gaussian_kernel) if needed.
  - Could report Unweighted SEEPS mean and density weighted SEEPS mean. Not sure?
- Stat-Analysis job types we should support:
  - Read multiple SEEPS_MPR for different stations/times and compute aggregated SEEPS output line (-job aggregate_stat -line_type SEEPS_MPR -out_line_type SEEPS)
  - Read multiple SEEPS_MPR for the same station/different times and compute aggregated SEEPS output line (e.g. -by OBS_SID).
  - Aggregate multiple SEEPS lines together (-job aggregate -line_type SEEPS).

**Comment by JohnHalleyGotway** [comment]
@hsoh-u, do the seeps point climo values in PPT24_seepsweights.nc ONLY apply to 24-hour accumulations of precip? I'm guessing that that's the case, but want to confirm.

If so we need to add that logic in Point-Stat. Right now, those climo values are being applied to 3-hourly accumulations in the Point-Stat unit tests. We'll need to update Point-Stat to only compute SEEPS for 24-hour accumulations of precip.

Of course, it'd make sense to handle climos for other accumulation intervals and/or other variable altogether. In the next round of development, we may want to rethink how we configure things. Perhaps we have the user specify the path to the point climo data file directly in the obs.field array entry (e.g. point_climo = "MET_BASE/climo/seeps/PPT24_seepsweights.nc";)? If its specified, we use that to compute seeps. If empty, we don't compute seeps. That'd make things more configurable for the user and also make the logic in the code much easier... just use whatever point climo data the user has provided.

**Comment by hsoh-u** [comment]
It's not checking if 24 hour precipitations. Rachel's recommendation was focusing 24 hours. SEEPS can be calculated for any accumulation length for which the user has an appropriate climatology.
