### ISSUE TITLE
Enhance Grid-Stat to compute SEEPS for gridded observations and write the SEEPS STAT line type.

### ISSUE THREAD

**Issue by RachelNorth** [dtcenter/MET#1943]
## Describe the New Feature ##
The Stable Equitable Error in Probability Space (SEEPS) score is described in Rodwell et al. (2010) and was devised for evaluating quantitative precipitation forecasts against SYNOP gauge data at (but not limited to) station locations. It uses a climatology to account for local variations in rainfall which enables aggregation over otherwise heterogenous locations. Recent work (North et al., 2021) has used a gridded product for calculating the score over both land and sea areas.

This issue will act as an umbrella ticket for the implementation of the gridded score capability.

- MET #1942 added SEEPS to Point-Stat.
- MET #2269 will add it to Series-Analysis after this one is completed.

While Point-Stat writes the SEEPS and SEEPS_MPR line types, Grid-Stat should only write the SEEPS line type. However, recommend also adding support for:
```
nc_pairs_flag = {
...
    seeps = TRUE;
...
}
```
There setting the `nc_pairs_flag.seeps` setting enables some output to be written to the "_pairs.nc" file created by Grid-Stat. At a minimum, it should write the seeps value for each grid point.

Please talk to @RachelNorth to determine if any other columns from the SEEPS_MPR line type should also be written to the "_pairs.nc" NetCDF file.

We do still need to define the columns that should be included in a new SEEPS line type.
MET #1942 left the S12 through PV3 columns set as NA. Work for this issue should actually define their contents.

### Acceptance Testing ###
*List input data types and sources.*
*Describe tests required for new functionality.*

### Time Estimate ###
*Estimate the amount of work required here.*
Unknown

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
Part of Met Office contract, ending August 2022 MET v11.

### Funding Source ###
2799991

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: @hsoh-u 
- [x] Select **scientist(s)** or **no scientist** required: @RachelNorth

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority** medium-to-high
- [x] Select **requestor(s)** UK Met Office

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [ ] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
- [ ] Need METplus issue to add `output_flag.seeps` and `nc_pairs_flag.seeps` as configurable options.

## New Feature Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
Note that PR #2257 for issue #1942 added SEEPS and SEEPS_MPR line types to the output of Point-Stat for met-11.0.0-beta3. However, the SEEPS line type contains many columns with NA in them (S12 to S32,  PV columns and PF columns). While working on this issue for met-11.0.0-beta4, please also complete the SEEPS line type.

In addition, consider modifying how SEEPS logic is enabled. Currently, Point-Stat checks to see if both the forecast and observation data is flagged as being precipitation (i.e. variable name `APCP` or `is_precipitation = TRUE;`). If so, AND IF the accumulation interval is exactly 24-hours, only then is SEEPS computed.

This makes adding support for computing SEEPS for other variables or accumulation intervals difficult. The logic for doing so would need be hard-coded, as it is now. Consider instead, switching to a config file option to point to the climo data file that should be used for computing SEEPS. Something like:
```
seeps_climo = "/path/to/seeps/climo/file";
```
If that string is non-empty, Point-Stat (and Grid-Stat) would read data from it to compute SEEPS. That'd make adding support for additional variables and accumulation intervals much easier.

**Comment by RachelNorth** [comment]
@hsoh-u I've uploaded the sample gridded daily climatology netcdf files, into North_data on the ftp server.  These fields are the 0-0UTC climatology derived from the TRMM 3B42 satellite product (https://disc.gsfc.nasa.gov/datasets/TRMM_3B42_7/summary). The metadata for these fields isn't ideal, but I hope the variable names will be obvious. If you have any questions, please get in touch.

**Comment by TaraJensen** [comment]
@mpm-meto - can you provide any guidance on our current blocker while Rachel is out?

Blocker:
We do still need to define the columns that should be included in a new SEEPS line type.
MET https://github.com/dtcenter/MET/issues/1942 left the S12 through PV3 columns set as NA. Work for this issue should actually define their contents.

**Comment by JohnHalleyGotway** [comment]
Testing of MET-11.0.0-beta5 revealed a couple of issues with the SEEPS implementation. Reopening this issue to fix the following:
- seeps_p1_thresh is included in the Grid-Stat config file but not actually referenced in the code. Update Grid-Stat to use it.
- The SeepsClimo constructor is called and loads the climo data every time Point-Stat and Grid-Stat are run. This should be changed to only load the data when it is actually needed.
