### ISSUE TITLE
Enhance the documentation with meta-data that is expected by MET for netCDF

### ISSUE THREAD

**Issue by jprestop** [dtcenter/MET#1949]
## Describe the Enhancement ##
Clearly identify what needs to be included in a gridded file for efficient MET ingest. Provide a clear list of meta-data that is expected by MET for netCDF, with regard to CF-compliant files.  Add this information to the User’s Guide in the [Input data formats section](https://met.readthedocs.io/en/develop/Users_Guide/data_io.html#input-data-formats) of MET Data I/O.
  
### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
ASAP

### Funding Source ###
2799991

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by jprestop** [comment]
Note from Marion from Slack on 10/21: 

> I think what we may be after is something with the following headings: a) Size of input files (limits, implications etc); b) splitting files (e.g. keeping forecast ranges separate, can different variables be in the same file, is it ok to have multi-level data in one file, and implications for how to access this via the format string, do ensemble members need to be in separate files, "detecting"/specifying control members), c) filenaming conventions and how MET diagnoses the time/date info and uses it for output file naming. What I am hoping for is that we develop a guide which basically provides useful pointers of "how to make life a lot easier for yourself" when you want to use METplus. This is therefore one level down from the more top-level capability of which formats it can read, CF compliance etc.

**Comment by jprestop** [comment]
This work was completed with [PR 1951](https://github.com/dtcenter/MET/pull/1951).
