### ISSUE TITLE
Sort mask.sid station lists to check their contents more efficiently.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1950]
## Describe the Enhancement ##

The MetOffice often defines masking regions using the mask.sid option. That defines a list of station ID names to be included in the verification region. Those station name lists are stored in a StringArray object which in turn stores them as a vector of strings. For each point observation, the PairDataPoint class checks to see if the station names appears in the specified list. However, the StringArray::has() function searches the list linearly for a match which is O(n). This task is to optimize that search to be O(log(n)):
- Add "bool Sorted" as a member of the StringArray class (mimic logic of NumArray).
- Should be false by default and reset to false by all "add" fuctions.
- Add "StringArray::sort_array()" member function (naming consistent with existing NumArray::sort_array())... which sets Sorted = true after sorting. See [StackOverflow](https://stackoverflow.com/questions/8122488/fast-search-algorithm-with-stdvectorstdstring) for quick/easy sorting example:
```
std::sort( serverList.begin() , serverList.end() )
```
- Enhance 2 "StringArray::has()" member function variations to check if the StringArray has already been sorted, and, if so, search more efficiently. See [StackOverflow](https://stackoverflow.com/questions/8122488/fast-search-algorithm-with-stdvectorstdstring) for quick/easy searching example:
```
std::lower_bound(serverList.begin() , serverList.end() , valuetoFind) to find first matching
```
- Also look at NumArray::has() and TimeArray::has()/index() to see if similar enhancements could be made for sorted arrrays.
- In config_util.cc, update the parse_sid_mask() function so that just prior to returning, call StringArray::sort(). Storing the station ID list in a sorted order should always be a good idea.
- Lastly, devise a test before/after these changes to quantify how much time is saved using this strategy. Note that this does not need to be added as a new unit test... just to quantify the improvement this work provides.

### Time Estimate ###
2 days (?)

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
No sub-issues needed.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
2799991

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: @sethlinden 
- [x] Select **scientist(s)** or **no scientist** required: @robdarvell (would be good for advice on testing)

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
No impacts.

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by sethlinden** [comment]
Hi @robdarvell I am just starting to work on this task. John and I thought it would be a good idea to do some testing with a much larger, more realistic station list (to test the searching / sorting of stations). For my testing, I'm running point_stats on a NAM forecast file (that covers the CONUS). Can you send a sample station list that the MetOffice actually uses: either for CONUS or global or both. A large enough list to test the searching for stations. Thanks in advance, we appreciate it.

**Comment by robdarvell** [comment]
Hi,
I have put a file onto the ftp server which contains a series of station lists as examples as to what we use. We don't have an exact list covering the areas which you refer to above.
The list of stations lists which are included are mentioned at the top. Some of the lists are quite long, which may assist in your task. You will also see some lists which are just a single site (eg: 71000). With the WMO blocks, there is no --000 value, so in these cases what we do when this value is found is we expand things out to search for all sites which start 71--- (it is a bit of a fudge because we just expand out and create a list 71001-71999 (knowing that a large number won't actually exist)

**Comment by sethlinden** [comment]
@JohnHalleyGotway I've been doing some timing tests today using some bigger lists. First it was not clear initially how to use the StationList_Options that Rob put on the ftp server (I did grab that and look at it).

But I have been comparing my feature-branch version of point_stats to a development branch version.
The feature branch version uses sorted vectors and the lower_bound search. The development branch does not.

First I looked at timing using the masking that was in place (in the config file: PointStatConfig_MASK_SID): using "KDEN" (1 site) and "SID_CO.txt" (56 sites)

Using the time command:
Feature:   real    0m29.655s, user    0m28.706s
Develop:  real    0m32.501s, user    0m28.567s

Next I used a much bigger SID file that has all CONUS METAR icao-ids: using "KDEN" (1 site) and "SID_CONUS.txt" (1579 sites)
 
Using the time command
Feature:  real    0m33.644s, user    0m32.973s
Develop: real    0m37.422s, user    0m33.384s

So initially I see fairly good results, the feature branch version is a bit faster but not by much. But the strange thing is when I use both "SID_CO.txt" and "SID_CONUS.txt" in same config file, the feature branch is a little slower, which doesn't make sense.

Next I was going to test point_stats using PointStatConfig_sid_inc_exc

John any other tests that you would suggest?

I will also take another look at the code and see if I can further optimize the string search.

**Comment by sethlinden** [comment]
@JohnHalleyGotway should I check in the test/config/SID_CONUS.txt

Also should I check in the new version of PointStatConfig_MASK_SID which uses:

sid   = [ "KDEN", "${CONFIG_DIR}/SID_CONUS.txt" ];

Wasn't sure if we wanted to update the test for this?

**Comment by sethlinden** [comment]
@JohnHalleyGotway I was able to use part of Rob's StationList_Options, I used the section: "2001 CBS North America station list (60N-25N, 145W-50W)"...but this is only 100 sites. Testing point-stats using this list and the CONUS_METAR list (1579)...still seeing just small differences in timing (feature branch with sort and lower_bound) only about 1 second faster. Looking at code to see if I can optimize this more.

**Comment by sethlinden** [comment]
Getting slightly faster results using just upper_bound. Still experimenting with the code in string_array.cc.

**Comment by sethlinden** [comment]
After meeting with John yesterday I implemented a new has() function that calls binary_search and returns true or false if the text string is found. I also re-worked the other versions of has() to be compatible /  backwards compatible.

I looked into ways to do a faster Case Insensitive search (IgnoreCase true) but it would require using the boost library, so based on that, I did not implement it. The original has() function is now just used for Unsorted vectors of strings (Sort is false) or for a Case Insensitive search (IgnoreCase true)

After fixing the code, doing some time testing. I'm testing with a CONUS site list that is multiplied by 10 (17369).

Now seeing good results comparing development branch to feature branch

Development branch is taking 41 seconds to run, Feature branch is taking 33 seconds to run.

**Comment by sethlinden** [comment]
Doing a bit more time testing before submitting a pull request. Time differences are most notable for the feature branch using a very large site-list, less noticeable for small site-lists, or using multiple masking site-lists in the config file (due to sorting each vector).

Using just sid   = [ "${CONFIG_DIR}/SID_CONUS.txt" ]; (1579 sites)
Feature  branch, three runs in a row: 0m33.913s, 0m33.898s, 0m33.970s
Develop branch, three runs in a row: 0m34.107s, 0m34.079s, 0m33.908s

Using just sid   = [ "${CONFIG_DIR}/SID_CONUS_times11.txt" ]; (17369 sites)
Feature  branch, three runs in a row: 0m33.920s, 0m33.965s, 0m34.019s
Develop branch, three runs in a row: 0m37.557s, 0m37.918s, 0m37.478s

**Comment by sethlinden** [comment]
Attaching the site-list files used for testing.
[SID_CONUS_times11.txt](https://github.com/dtcenter/MET/files/8399941/SID_CONUS_times11.txt)
[SID_CONUS.txt](https://github.com/dtcenter/MET/files/8399942/SID_CONUS.txt)

**Comment by sethlinden** [comment]
After checking everything in. Ran: make clean install test. It finished successfully. Going to run unit tests as well.
