### ISSUE TITLE
Update the TC-Stat RIRW job type to write complete CTC and CTS output lines.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1960]
## Describe the Enhancement ##
This enhancement request came up in [METplus Discussions](https://github.com/dtcenter/METplus/discussions/1244) from @YanJin-NOAA. Currently, the TC-Stat [RIRW job type](https://met.readthedocs.io/en/develop/Users_Guide/tc-stat.html?highlight=rirw#rapid-intensification-weakening) can write MPR, CTC, and CTS outputs. However, they are written to a custom version of those line types rather than a complete .stat output file containing the full set of header columns. This custom, RIRW job-specific categorical output cannot be loaded into a database for use by METviewer... nor can the output be further aggregated or processed by the STAT-Analysis tool, which can only full STAT lines.

Here are sample CTC, CTS, and MPR outputs from the TC-Stat RIRW job type:
```
JOB_LIST: -job rirw -amodel AHWI -amodel BCLP -storm_id ALAL2010 -match_points true -rirw_time 240000 -rirw_exact true -rirw_thresh <=-15 -rirw_window -120000 120000 -out_line_type CTC -out_line_type CTS -out_line_type MPR -out_alpha 0.05000 
COL_NAME: ATIME  BTIME  AEXACT BEXACT ATHRESH BTHRESH WINDOW_BEG WINDOW_END TOTAL FY_OY FY_ON FN_OY FN_ON
RIRW_CTC: 240000 240000 true   true   <=-15   <=-15   -120000    120000        42     2     0     2    38

COL_NAME: ATIME  BTIME  AEXACT BEXACT ATHRESH BTHRESH WINDOW_BEG WINDOW_END TOTAL    BASER BASER_NCL BASER_NCU BASER_BCL BASER_BCU    FMEAN FMEAN_NCL FMEAN_NCU FMEAN_BCL FMEAN_BCU     ACC ACC_NCL ACC_NCU ACC_BCL ACC_BCU FBIAS FBIAS_BCL FBIAS_BCU PODY PODY_NCL PODY_NCU PODY_BCL PODY_BCU PODN PODN_NCL PODN_NCU PODN_BCL PODN_BCU POFD POFD_NCL POFD_NCU POFD_BCL POFD_BCU FAR FAR_NCL  FAR_NCU FAR_BCL FAR_BCU CSI CSI_NCL CSI_NCU CSI_BCL CSI_BCU   GSS GSS_BCL GSS_BCU  HK  HK_NCL  HK_NCU HK_BCL HK_BCU     HSS HSS_BCL HSS_BCU ODDS ODDS_NCL ODDS_NCU ODDS_BCL ODDS_BCU LODDS LODDS_NCL LODDS_NCU LODDS_BCL LODDS_BCU ORSS ORSS_NCL ORSS_NCU ORSS_BCL ORSS_BCU     EDS  EDS_NCL EDS_NCU EDS_BCL EDS_BCU    SEDS SEDS_NCL SEDS_NCU SEDS_BCL SEDS_BCU EDI EDI_NCL EDI_NCU EDI_BCL EDI_BCU SEDI SEDI_NCL SEDI_NCU SEDI_BCL SEDI_BCU BAGSS BAGSS_BCL BAGSS_BCU
RIRW_CTS: 240000 240000 true   true   <=-15   <=-15   -120000    120000        42 0.095238  0.037662   0.22065        NA        NA 0.047619  0.013158    0.1579        NA        NA 0.95238  0.8421 0.98684      NA      NA   0.5        NA        NA  0.5  0.35526  0.64474       NA       NA    1   0.9162        1       NA       NA    0        0 0.083799       NA       NA   0       0 0.083799      NA      NA 0.5 0.35526 0.64474      NA      NA 0.475      NA      NA 0.5 0.11865 0.88135     NA     NA 0.64407      NA      NA   NA       NA       NA       NA       NA    NA        NA        NA        NA        NA    1       NA       NA       NA       NA 0.54466 0.047459 1.04186      NA      NA 0.77233  0.20185  1.34281       NA       NA  NA      NA      NA      NA      NA   NA       NA       NA       NA       NA    NA        NA        NA

COL_NAME: ATIME  BTIME  AEXACT BEXACT ATHRESH BTHRESH WINDOW_BEG WINDOW_END AMODEL BMODEL STORM_ID            INIT    LEAD           VALID AMAX_WIND_PRV AMAX_WIND_CUR AMAX_WIND_DLT ARIRW BMAX_WIND_PRV BMAX_WIND_CUR BMAX_WIND_DLT BRIRW CATEGORY
RIRW_MPR: 240000 240000 true   true   <=-15   <=-15   -120000    120000       AHWI   BEST AL062010 20100831_000000  000000 20100831_000000            NA            60            NA   NA             NA            60            NA   NA        NA
RIRW_MPR: 240000 240000 true   true   <=-15   <=-15   -120000    120000       AHWI   BEST AL062010 20100831_000000  120000 20100831_120000            NA            50            NA   NA             NA            55            NA   NA        NA
RIRW_MPR: 240000 240000 true   true   <=-15   <=-15   -120000    120000       AHWI   BEST AL062010 20100831_000000  240000 20100901_000000            60            53            -7 false            60            45           -15  true    FN_OY
R
```
This task it to enhance TC-Stat to write the CTC and CTS lines to a complete .stat output file. The challenge is in deciding how to map the custom, RIRW-specific output columns to the existing STAT header columns. Recommend writing CTC and CTS output to a .stat file. But it's unclear whether the matched pair (RIRW_MPR) output should we written in this way. The columns are really just so specific to RIRW that they cannot really be mapped into the existing MPR line type.

Note that this situation also exists in Stat-Analysis for the ramp jobs (-job ramp). It also writes custom job-specific categorical output to lines identified as RAMP_CTC, RAMP_CTS, and RAMP_MPR. Consider whether this should be changed in Stat-Analysis too.

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
Closing this as a duplicate of issue #2425.
