### ISSUE TITLE
Fix Point-Stat and Grid-Stat to write VCNT output even if no VL1L2 or VAL1L2 output is requested.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1991]
## Describe the Enhancement ##
While doing some testing for another issue, I ran into a slight problem in the output_flag functionality in Grid-Stat and Point-Stat. If a user requests VCNT output without also requesting VL1L2 or VAL1L2 output, then no VCNT output is created. There's an issue in the processing logic in these tools. The fix is simple, just include the VCNT line type in the conditional which determines whether or not vector statistics are computed.

### Time Estimate ###
2 hours.

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
None required.

### Relevant Deadlines ###
None

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: @JohnHalleyGotway 
- [x] Select **scientist(s)** or **no scientist** required: no scientist required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
No related issues.

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update log messages for easier debugging.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.

**Comment by JohnHalleyGotway** [comment]
I updated the logic in Grid-Stat and Point-Stat to compute VL1L2 partial sums when VCNT output is requested. I noticed that Grid-Stat was NOT writing VCNT output for the Fourier method. However the logic of get_n_txt_rows() assumes (on this [line](https://github.com/dtcenter/MET/blob/f81d25081861e603cb4a9c40c51e7f5e22fab3ec/met/src/tools/core/grid_stat/grid_stat_conf_info.cc#L1039)) that VCNT Fourier output is being written.

So I made that change as well. However this should change the output of the NB and require that develop-ref be updated with this change.
