### ISSUE TITLE
Enhance the MET documentation to follow the standard for sections

### ISSUE THREAD

**Issue by jprestop** [dtcenter/MET#1998]
## Describe the Enhancement ##
From https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html
\# with overline, for parts
\* with overline, for chapters
=, for sections
-, for subsections
^, for subsubsections
“, for paragraphs

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
NONE

### Funding Source ###
If easy - charge 2702691 (up to 3 hours)
If harder - spread across all METplus keys

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.

**Comment by JohnHalleyGotway** [comment]
@jprestop and @lisagoodrich I recommend that we move this issue from MET version 11.0.0 to MET version 10.1.0. Here's why.

The current version in develop includes many individual references. However, I've found that the reference names are not entirely unique.

```
> cd MET/met/docs/Users_Guide
> grep ':ref:' *.rst | sed 's/:ref:/\n:ref:/g' | sed -r 's/>`/>`\n/g'  | grep ':ref:' | egrep -v "[A-Z]" | wc -l
160
> grep ':ref:' *.rst | sed 's/:ref:/\n:ref:/g' | sed -r 's/>`/>`\n/g'  | grep ':ref:' | egrep -v "[A-Z]" | sort -u | wc -l
156
```

So there are 160 :ref: names but only 156 unique ones, meaning that 4 are used twice.

And here they are:

```
grep ':ref:' *.rst | sed 's/:ref:/\n:ref:/g' | sed -r 's/>`/>`\n/g'  | grep ':ref:' | egrep -v "[A-Z]" | sort -u > ref_names
while read line; do n=`grep "${line}" *.rst | wc -l`; echo $n $line; done < ref_names
```

```
2 :ref:`ci_alpha <ci_alpha>`
2 :ref:`desc <desc>`
2 :ref:`output_flag <output_flag>`
2 :ref:`version <version>`
```

In all 4 cases, these anchors show up in both config_options.rst and config_options_tc.rst.

So at a minimum, we should fix these 4 links. But it's also the case that adding all the section/sub-sections well should also fix it. So if this issue is relatively easy, let's do it in 10.1.0. If it's hard, you could manually update these 4 to make them unique... and do this issue later.

**Comment by jprestop** [comment]
@TaraJensen Please read @JohnHalleyGotway's comment above.  With regard to funding, would it be possible to have this work done by @lisagoodrich for MET version 10.1.0?

**Comment by TaraJensen** [comment]
@lisagoodrich @jprestop - Thanks for bringing this to my attention.  I went ahead and gave guidance on keys, updated label and assigned to beta6.

**Comment by jprestop** [comment]
@TaraJensen Thank you.  I see that "alert: NEED ACCOUNT KEY" was removed but Funding Source still says "TBD".  Please advise.

**Comment by TaraJensen** [comment]
@jprestop - I put the charging guidance in the wrong place.  It was in Time Estimate - oops.  I moved it to correct location.

**Comment by jprestop** [comment]
@TaraJensen - Thanks, I totally missed that and didn't look elsewhere first.  I'll check more thoroughly in the future. Thanks for fixing that up.
