### ISSUE TITLE
Fix PB2NC to reduce redundant verbosity level 3 log messages.

### ISSUE THREAD

**Issue by hsoh-u** [dtcenter/MET#2015]
*Replace italics below with details for this issue.*

## Describe the Enhancement ##
*Provide a description of the enhancement request here.*

bash
export MASK_GRID=''
export MASK_POLY=''
export QUALITY_MARK_THRESH='2'
export STATION_ID=''
/d1/projects/MET/MET_regression/develop/NB20220112/MET-develop-ref/met/share/met/../../bin/pb2nc \
/d1/projects/MET/MET_test_data/unit_test/obs_data/prepbufr/nam.20210311.t00z.prepbufr.tm00 \
/d1/projects/MET/MET_regression/develop/NB20220112/MET-develop-ref/test_output/pb2nc/nam.20210311.t00z.prepbufr.tm00.pbl.nc \
/d1/projects/MET/MET_regression/develop/NB20220112/MET-develop-ref/test/config/PB2NCConfig_pbl \
-v 3

The below debug message is repeated a lot:

DEBUG 3:
DEBUG 3: process_pbfile() -> Skip the derived variables because of not requested (0).
DEBUG 3:

### Time Estimate ###
4 hours

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
2793541

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required: None

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
