### ISSUE TITLE
Add Anomaly Correlation Coefficient to VCNT Line Type

### ISSUE THREAD

**Issue by malloryprow** [dtcenter/MET#2022]
## Describe the Enhancement ##
In the CNT line type, Anomaly Correlation Coefficient is part of the output from the line type. It would be good to add this to the VCNT line type, so that Anomaly Correlation Coefficient can be calculated for Vector Wind. See the bottom of slide 11 for the equation at https://www.emc.ncep.noaa.gov/users/verification/global/gfs/doc/RMSE_decomposition.pdf. Additionally, it can be computed from the VAL1L2 line type by the equation 

A=sum[(uf-uc)*(uo-uc)+(vf-vc)*(vo-vc)]
B=sum[(uf-uc)**2+(vf-vc)**2]
C=sum[(uo-uc)**2+(vo-vc)**2]
ACC=A/sqrt(B*C)

uf = u wind forecast
uo = u wind observation
uc = u wind climatology
vf = v wind forecast
vo = v wind observation
vc = v wind climatology

or in terms from the VAL1L2 line type...

ACC = (UVFOABAR)/(sqrt(UVFFABAR*UVOOABAR) 

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
2793541, 2702691

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [ ] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
Recommend that @JohnHalleyGotway and @sethlinden meet to discuss what changes are needed where. Need to write issues for METdatadb and METviewer.

**Comment by JohnHalleyGotway** [comment]
These changes will be similar to #1450 and corresponding PR #1662. Based on that PR, here's where we need to make changes.

Note that anomaly correlation is named ANOM_CORR in the [CNT line type](https://met.readthedocs.io/en/latest/Users_Guide/point-stat.html?highlight=CNT%20line%20type#id11). And "ACC" is already used for accuracy in the [MCTS line type](https://met.readthedocs.io/en/latest/Users_Guide/point-stat.html?highlight=CNT%20line%20type#id11). Recommend adding 3 columns to the end of VCNT named ANOM_CORR, ANOM_CORR_BCL, ANOM_CORR_BCU.

1. met/data/table_files/met_header_columns_V11.0.txt modify the VCNT line by adding ANOM_CORR to the end of the line.
2. test/hdr/met_11_0.hdr modify the VCNT line by adding ANOM_CORR to the end.
3. met/docs/Users_Guide/appendixC.rst update the documentation to add the definition of this stat.
4. met/docs/Users_Guide/point-stat.rst to add ANOM_CORR to the [VCNT line type](https://met.readthedocs.io/en/latest/Users_Guide/point-stat.html?highlight=CNT%20line%20type#id23).
5. met/src/basic/vx_util/stat_column_defs.h add ANOM_CORR to the vcnt_columns variable.
6. met/src/libcode/vx_stat_out/stat_columns.cc update write_vcnt_cols() function.
7. src/libcode/vx_statistics/met_stats.h add the new stat to the VL1L2Info class.
8. src/libcode/vx_statistics/met_stats.cc update the VL1L2Info functions to initialize and compute this stat. Actual derivation goes into the VL1L2Info::calc_ncep_stats() function.
```
   if ( vacount > 0 ) ANOM_CORR = valid value
   else               ANOM_CORR = bad_data_double
```

@JohnHalleyGotway will write up 2 related issues:
1. Update the development version number from 10.1.0 to 11.0.0.
2. Enhance MET to actually compute/write the bootstrapped values for VCNT stats.

**Comment by JohnHalleyGotway** [comment]
@ericgilleland we're looking for some advice from you.

This issue adds anomaly correlation computed from vector partial sums, as defined by:
```
ANOM_CORR = (UVFOABAR)/(sqrt(UVFFABAR*UVOOABAR)
```

Two questions for you.

1. I see that anomaly correlation in the CNT line type (ANOM_CORR) includes parametric confidence intervals (ANOM_CORR_NCL and ANOM_CORR_NCU). It's computed starting on this line of code:
https://github.com/dtcenter/MET/blob/afd53d217e064c6c4d6ec818ce07d99f289968e1/met/src/libcode/vx_statistics/met_stats.cc#L967
And here's a code snippet:
```
         v = 0.5*log((1 + anom_corr.v)/(1 - anom_corr.v));
         cl = v + cv_normal_l/sqrt((double) (n-3));
         cu = v + cv_normal_u/sqrt((double) (n-3));
         anom_corr.v_ncl[i] = (pow(vx_math_e, 2*cl) - 1)/(pow(vx_math_e, 2*cl) + 1);
         anom_corr.v_ncu[i] = (pow(vx_math_e, 2*cu) - 1)/(pow(vx_math_e, 2*cu) + 1);
```

Should parametric CI's be added for vector-based anomaly correlation? If so, should we use exactly this same code?

2. I see that the CNT line type includes both ANOM_CORR and ANOM_CORR_UNCTR. Do centered and uncentered anomaly correlation apply to vectors as well? Can you tell, is the equation we're using consistent with the uncentered one included in the CNT:ANOM_CORR output column?

**Comment by ericgilleland** [comment]
The parametric CI's are being computed using Fisher's transformation.  What
is different about the vector-based?  That is, I guess I don't know what
you mean by vector partial sums. Are you talking about partial
correlations?  That is, removing the effect of a confounding variable?  If
so, then yes, the Fisher's transform still applies.

In terms of the uncentered v. centered, usually correlation is calculated
with centering, so it's unclear to me if the uncentered actually follows
the standard normal df or not.  Is the uncentered compared against a
non-standard normal df?  It seems reasonable that it should still follow a
normal df, but I'd need to double check.

**Comment by sethlinden** [comment]
@JohnHalleyGotway based on @ericgilleland reply sounds like we should add the parametric confidence intervals for the VCNT anomaly correlation? But I'll wait for you to chime in about his question in regards to vector partial sums. I know you are in the MET workshop today.

**Comment by JohnHalleyGotway** [comment]
Additional tasks:

- See the [CIInfo](https://github.com/dtcenter/MET/blob/2b109502a82124ae767771b6b950ee7bf4c80ebd/met/src/libcode/vx_statistics/met_stats.h#L28) class and note its usage in the [CNTInfo class](https://github.com/dtcenter/MET/blob/2b109502a82124ae767771b6b950ee7bf4c80ebd/met/src/libcode/vx_statistics/met_stats.h#L182). Update the VL1L2Info class to switch from double to CIInfo any variables written the [VCNT output line type](https://met.readthedocs.io/en/latest/Users_Guide/point-stat.html?highlight=VCNT#id23). We'll ultimately need CIInfo to store the confidence limits that we'll compute in a future issue. This also initializing the stats to a bad data (i.e. NA) output value.

- In the VL1L2Info member functions, be sure to call CIInfo::clear() as needed, see existing CNTInfo code for examples.

- In VL1L2Info class, we should have:
```
CIInfo ANOM_CORR, ANOM_CORR_UNCNTR;
```

- In met_stats.cc, update VL1L2Info::calc_ncep_stats() to compute ANOM_CORR_UNCNTR by calling compute_anom_corr_uncntr() with the *right* partial sums. Compute ANOM_CORR by calling compute_corr() with the *right* partial sums.

      vl1l2_info.anom_corr_uncntr.v = compute_anom_corr_uncntr(uvffa_bar, uvooa_bar, uvfoa_bar);

Let's talk to @ericgilleland about this some more.

- Update compute_anom_corr_uncntr() function to make sure all of its inputs are not bad data.
- Also need to compute the normal ci's for ANOM_CORR_UNCNTR... following the example from the CNTInfo class.

**Comment by JohnHalleyGotway** [comment]
Based on our meeting on 4/29/2022, I suspect we need to do the following:
- [x] @sethlinden will complete the first round of adding vector anomaly correlation and push changes to GitHub. Actually compute the uncentered version but report the centered version as bad data. Be sure to add output columns for ANOM_CORR_NCL/NCU and BCL/BCU and ANOM_CORR_UNCNTR_BCL/BCU.
- [ ] @JohnHalleyGotway will work on that branch to add FA_SPEED_BAR and OA_SPEED_BAR outputs to the VAL1L2 line type to match the existing VL1L2 outputs. Update Stat-Analysis to 
- [ ] @JohnHalleyGotway will add add call to compute_corr() to use those along with the other partial sums to actually compute the correlation.

We will confirm the equations with @ericgilleland or @rgbullock to make sure this is correct.

We also need to actually compute the NCL/NCU CI's for ANOM_CORR.

**Comment by sethlinden** [comment]
@JohnHalleyGotway all the changes we talked about this morning are completed and pushed up to GitHub. I just ran a "make clean install test" and it all compiled without issue and all the tests ran to completion.

I checked the first box. You can proceed with your changes when you get a chance.

**Comment by JohnHalleyGotway** [comment]
As of 5/17/22, the first test in unit_climatology_1.5deg.xml is failing. It does run Point-Stat to completion but the point_stat*_vcnt.txt output file is empty and that's what triggers the failure. Comparing the .stat output file... from the nightly build for develop, it has 1747 lines... and this feature branch only generates 1745 lines. I confirmed the difference being that 2 VCNT lines are missing.

Since we are now writing some parametric CI's for the VCNT output line type, the write_vcnt_row() function loops over and writes output for each CI alpha value specified. I strongly suspect that problem is that we haven't actually stored any alpha values upstream. So we're looping over a list of length 0.

Will work on this logic to get it properly writing VCNT output lines again.

**Comment by JohnHalleyGotway** [comment]
@sethlinden FYI this feature branch is in good shape and unit_climatology_1.5deg.xml is running fine now. I'd like to hand this back to you for you to determine what, if any, additional work is needed.

**Comment by sethlinden** [comment]
@JohnHalleyGotway thanks for making all these changes. I assume I just need to do some more testing. I'll run some of my initial tests that I was doing and look at the output. Is there any additional testing that you suggest?

**Comment by JohnHalleyGotway** [comment]
@sethlinden I don't have anything specific in mind. Just review the current state of the code changes and see how the output of the existing unit tests has changed relative to the output from develop. The "check for differences" step in GitHub actions should flag the diffs.

Whenever adding new stats to existing line types, I will often run the output from Point-Stat or Grid-Stat through Stat-Analysis and have Stat-Analysis re-derive the stats. That's just to confirm that the stats computed by Point-Stat/Grid-Stat match what Stat-Analysis reports... which it should.

For example, you could run Stat-Analysis like this...
```-lookin point_stat...stat -job aggregate_stat -line_type VL1L2 -out_line_type VCNT```
And then
```-lookin point_stat...stat -job aggregate_stat -line_type VAL1L2 -out_line_type VCNT```
Some of the VCNT stats are derivable from VL1L2 inputs while others are derivable from VAL1L2 inputs. So checking that logic and comparing to the original output from Point-Stat or Grid-Stat could be good.

**Comment by JohnHalleyGotway** [comment]
Found an issue when testing in Stat-Analysis:

1. This works fine:
```
bin/stat_analysis -lookin /Volumes/d1/projects/MET/MET_unit_test/MET_test_output/climatology_1.5deg/point_stat_WMO_CLIMO_1.5DEG_120000L_20120409_120000V.stat -job aggregate_stat -line_type VAL1L2 -out_line_type VCNT -out_stat agg_stat.stat -by FCST_LEV
```
And produces the same output ANOM_CORR values from Stat-Analysis that Point-Stat is creating.
2. But this does NOT work as expected:
```
bin/stat_analysis -lookin /Volumes/d1/projects/MET/MET_unit_test/MET_test_output/climatology_1.5deg/point_stat_WMO_CLIMO_1.5DEG_120000L_20120409_120000V.stat -job aggregate_stat -line_type VAL1L2 -out_line_type VCNT -out_stat agg_stat.stat
```
ANOM_CORR is NA in the output which indicates that the aggregation of VAL1L2 lines is not working as it should.

**Comment by sethlinden** [comment]
After meeting with John last Thursday (05/26/22) and fixing a few issues. I finished testing last Friday (05/27/22) and today (Tue, 05/31/22). After the Testing workflow was initiated last week, I downloaded and checked all the differences. All the differences (in terms of all the new columns) and output is expected.

Even checked a run of point_stats to confirm that U/V climo values are missing and thus output ANOM-CORR values are missing:

I ran point_stat with the PointStatConfig_PHY file to make sure it wasn't getting U/V climatology values (since ANOM-CORR is basically missing in the _vcnt output file). I just ran

`./point_stat /d1/projects/MET/MET_test_data/unit_test/model_data/grib1/nam/nam_2012040900_F012.grib /d1/personal/linden/git/feature_2022_anom_corr_to_vcnt/MET/test_output/pb2nc/gdas1.20120409.t12z.prepbufr.nc /d1/personal/linden/git/feature_2022_anom_corr_to_vcnt/MET/internal/test_unit/config/PointStatConfig_PHYS -outdir /d1/personal/linden/git/feature_2022_anom_corr_to_vcnt/MET/test_output/point_stat -v 4 > out.txt`

In the debug output I can see that it does find U/V fields in the climatology file but can not find values in the exact pressure level range (or height level range) that is being requested, thus the U/V climo values are missing and subsequently the ANOM-CORR values are missing:

`DEBUG 3: MetGrib1DataFile::data_plane_array() -> Found 1 GRIB records matching VarInfo "VGRD/Z10" in GRIB file "/d1/projects/MET/MET_test_data/unit_test/model_data/grib1/gfs/gfs_2012040900_F012_gNam.grib".
DEBUG 4: Found matching 20120409_120000 "VGRD/Z10" climatology field in file "/d1/projects/MET/MET_test_data/unit_test/model_data/grib1/gfs/gfs_2012040900_F012_gNam.grib".
DEBUG 3: For forecast valid at 20120409_120000, found 1 climatology field(s) with valid time(s): 20120409_120000
DEBUG 3: Found 1 climatology fields.
DEBUG 2: For VGRD/Z10 found 1 forecast levels, 1 climatology mean levels, and 0 climatology standard deviation levels.
DEBUG 4: For GRIB record number 60, the requested level values (700 and 850) do not fall within the current range of level values (50 and 50).
DEBUG 4: For GRIB record number 66, the requested level values (700 and 850) do not fall within the current range of level values (75 and 75).
DEBUG 4: For GRIB record number 72, the requested level values (700 and 850) do not fall within the current range of level values (100 and 100).
DEBUG 4: For GRIB record number 78, the requested level values (700 and 850) do not fall within the current range of level values (125 and 125).
DEBUG 4: For GRIB record number 84, the requested level values (700 and 850) do not fall within the current range of level values (150 and 150).
DEBUG 4: For GRIB record number 90, the requested level values (700 and 850) do not fall within the current range of level values (175 and 175).
DEBUG 4: For GRIB record number 96, the requested level values (700 and 850) do not fall within the current range of level values (200 and 200).
....`

I also checked output for a new unit-test that was added to: unit_climatology_1.5deg.xml: Checked output in:
`/d1/personal/linden/git/feature_2022_anom_corr_to_vcnt/MET/test_output/climatology_1.5deg/stat_analysis_WMO_1.5DEG_VAL1L2_to_VCNT_out.stat`

**Comment by JohnHalleyGotway** [comment]
I found issues with the newly added output from Stat-Analysis:
```
climatology_1.5deg/stat_analysis_WMO_1.5DEG_VAL1L2_to_VCNT_out.stat
```
This is generated by running a `-job aggreagate_stat -line_type VAL1L2 -out_line_type VCNT` job. Several statistics columns are reported with a value of 0 when they should be NA instead (e.g. FBAR, OBAR, FS_RMS). The only non-NA stats should have ANOM_CORR in the name. Also, the ALPHA value should NOT be NA since we're reporting CI's for anomaly correlation.

Will fix this on a new branch from develop and then submit a new PR.
