### ISSUE TITLE
Remove the double-quotes around keywords

### ISSUE THREAD

**Issue by jprestop** [dtcenter/MET#2023]
## Describe the Task ##
For actual keywords supported in the MET config files, remove the double-quotes around them to avoid confusion.  

In the [documentation](https://met.readthedocs.io/en/develop/Users_Guide/config_options.html#grid-weight-flag), for grid_weight_flag, for example, is the following current text:

> “COS_LAT” to define the weight as the cosine of the grid point latitude. This an approximation for grid box area used by NCEP and WMO.

would become:

> COS_LAT to define the weight as the cosine of the grid point latitude. This an approximation for grid box area used by NCEP and WMO.

for all instances similar to that one, with a supported keyword. 

This arose in the MET User's Telecon on [20220124](https://docs.google.com/document/d/1yPXWysPyHaTTAAwMz0YPBsi6Op_4dD5Tn5wWAR1iRlY/edit) where there was some confusion on how to specify this information in the METplus configuration files.

We hope that removing the quotes from the text will make it more clear that in the configuration files:
```
grid_weight_flag = COS_LAT;
```
would be correctly entered and NOT:
```
grid_weight_flag = "COS_LAT";
```

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
Took a guess in the labels for Projects and Milestones.

### Funding Source ###
TBD

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by lisagoodrich** [comment]
@jprestop, I've got permission to start working on the documentation again!  I think this is an easy one for me to complete without supervision.  I'm just letting you know I've started work on this.

@TaraJensen, what account key should I charge?

**Comment by JohnHalleyGotway** [comment]
FYI, you can find a list of such keywords in this [ConfigConstants](https://github.com/dtcenter/MET/blob/develop/data/config/ConfigConstants) file. Basically, any of the all-caps settings in there (e.g. `COS_LAT`) would fall into this category.

You could grep through all the .rst files for occurrences of these keywords.

Here's are some commands to help.

There are 95 such keywords:
```
> cd MET
> cat data/config/ConfigConstants | cut -d'=' -f1 | egrep -v '//' | egrep '[A-Z]' | sort -u | wc -l
95
```
And here's how you can grep for each one:
```
for KEYWORD in `cat data/config/ConfigConstants | cut -d'=' -f1 | egrep -v '//' | egrep '[A-Z]' | sort -u`; do
  grep $KEYWORD `find ./ -name "*.rst"`
done
```
This should help make it easier to find what needs to be changed. Note however, that this can be a little confusing. For example, this instance of `"FCST"` really is and should remain a string with double quotes around it:
```
docs/Users_Guide/point-stat.rst:  model          = "FCST";
```

**Comment by jprestop** [comment]
Thanks so much @JohnHalleyGotway for this helpful information. We were just talking about how this was going to take a bit more effort than expected.  I think the commands you've listed here will prove to be helpful and make this task easier.
