### ISSUE TITLE
Enhance TC-Pairs consensus logic to compute the spread of the location, wind speed, and pressure.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#2036]
## Describe the Enhancement ##
This enhancement request initially arose via METplus discussions in dtcenter/METplus#1341.

The METplus team met with NOAA/EMC on 2/2/2022 to discuss this issue and this GitHub issue is the result. Here are the steps:
- [ ] Enhance the consensus derivation logic in TC-Pairs to also compute the location spread  and standard deviation of the wind speed and pressure values.
   - Compute the location spread as the mean of the great circle distance from the consensus location to the location of each of the members.
   - Compute the standard deviation of wind speeds and pressure values as you normally would.
- [ ] After these are computed, need to decide where/how to write these 3 additional values to the output.
   - One option to consider is adding 3 new columns to the end of the existing TCMPR line type. That wouldn't require many changes to the TC-Stat and the METdatadb load logic updates would be pretty easy. One downside is that the mean location and location spread would be very far from eachother in the output line. And that solution may conflict with the solution for dtcenter/MET#392.
   - Another option to consider is defining a new version of the TCMPR line type (perhaps "TCMPRCON" or something?) that is the same as the existing TCMPR line type, but with 3 extra columns added internally (not at the end). After the average location, speed, and pressure, we'd report the corresponding spread values. The downside is extra documentation and testing, upgrading TC-Stat to handle this, and upgrading METdata/METviewer to handle it. You'd often want to visualize TCMPR data from constituent models on the same plot at the TCMPRCON data. That may be difficult if they're stored in different line types.

Please see attached slides from the 2/2/2022 meeting:
[J.Peng_discussion_20220202_new.pdf](https://github.com/dtcenter/MET/files/7990226/J.Peng_discussion_20220202_new.pdf)

### Time Estimate ###
*Estimate the amount of work required here.*

*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
27703542

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
- [ ] Define a METdatadb issue to account for any changes to the output format.
- [ ] Define a METviewer and/or METplotpy issue to include the spread info in plots.

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
Mentioned in the gap analysis for EVS version 1.0 on 9/7/22.
@JiayiPeng-NOAA should be added as an assignee on this issue.

**Comment by JohnHalleyGotway** [comment]
@KathrynNewman, on 9/22/22, I talked to @sethlinden about working on this issue. I wanted to point him to some examples of using the `consensus` option in TC-Pairs that he could use for development and testing. However I was very surprised to find that no such example exists in our unit tests!

By that I mean that `consensus = [ ];` is set to an empty list in all the TC-Pairs config files in [this directory](https://github.com/dtcenter/MET/tree/develop/internal/test_unit/config).

So part of this issue should also be adding a consensus TC-Pairs example to [unit_tc_pairs.xml](https://github.com/dtcenter/MET/blob/develop/internal/test_unit/xml/unit_tc_pairs.xml).

Please see [this documentation](https://met.readthedocs.io/en/develop/Users_Guide/config_options_tc.html?highlight=consensus#consensus) about consensus tracks.

The TC data we use for other TC tests is mainly from 2010 and can be found here:
https://dtcenter.ucar.edu/dfiles/code/METplus/MET/MET_unit_test/unit_test/tc_data/

@KathrynNewman questions for you:
- Any idea where those tests went? I actually can't find any history of them in Git. So maybe they never existed?
- If we add new ones, should we use our existing track data from 2010 or pull/use more recent track data? If so, please provide them.
- Please advise on the config settings @sethlinden should use for this. We can define many consensus tracks in a single config file. The goal is exercising the s/w options but doing so in a somewhat meaningful way scientifically.

**Comment by KathrynNewman** [comment]
Hi @JohnHalleyGotway - my guess is that the unit tests for the consensus option never existed. This option was used heavily in 2010-2014 when were were doing the stream 1.5 evaluations for HFIP. I believe this pre-dates METplus on Git?

We can just use the 2010 track data if it's already pulled. Would the information you need from me be the config file settings that would be reasonable? I can point to the consensus settings we used for the old HFIP evaluations on eyewall (or just copy/paste them into this issue).

**Comment by JohnHalleyGotway** [comment]
@KathrynNewman, yes please, that'd be great.

**Comment by sethlinden** [comment]
@JohnHalleyGotway and @KathrynNewman thanks for the follow up on this issue. Once this is figured out, please let me know what config file to use (or what options to put in the config file)? Also where are the input files located for this located? What is the example command line?

I will plan on adding a new unit test to unit_tc_pairs.xml.

Thanks in advance!

**Comment by JohnHalleyGotway** [comment]
@KathrynNewman I did some hunting on the NHC website and see the definition of the consensus tracks they compute listed in Table 2 of [this page](https://www.nhc.noaa.gov/modelsummary.shtml). I propose that our next test use these consensus definitions for the ones NOT marked with an asterisk which indicates non-public data.

Our existing 2010 track data is insufficient since it only contains data for these models:
AHWI, AVNI, DSHP, GFNI, GHMI, HWFI, LGEM, NGPI, P43I, SPC3

Recommend adding a more complete set of more recent track data from the [NHC ATCF Archive](https://ftp.nhc.noaa.gov/atcf/archive/). I'll work on pulling that data and establishing this test.

**Comment by JohnHalleyGotway** [comment]
@sethlinden OK, I just finished adding this [consensus example](https://github.com/dtcenter/MET/blob/21998250710bdc9f7dedbdd325c82a155a5fd3ae/internal/test_unit/xml/unit_tc_pairs.xml#L39) to unit_tc_pairs.xml. I have updated the unit test data to provide these 2 required input files:
[al132020.tar.gz](https://github.com/dtcenter/MET/files/9659637/al132020.tar.gz)

This computes 7 different types of consensus forecasts which match the definitions from Table 2 of [this NHC page](https://www.nhc.noaa.gov/modelsummary.shtml). Note that the NHC-computed consensus tracks do already appear in the track data. And I didn't get exactly the same result. Here's a simple consensus of 2 models:
```
   {
      name     = "GFEX_CONS";
      members  = [ "GFSI", "EMXI" ];
      required = [];
      min_req  = 2;
   }
```
And here's data for 1 track point for GFSI, EMXI, GFEX (NHC-computed), GFEX_CONS (MET-computed): 
```
VERSION AMODEL    BMODEL DESC STORM_ID BASIN CYCLONE STORM_NAME INIT            LEAD    VALID           INIT_MASK VALID_MASK LINE_TYPE TOTAL INDEX LEVEL WATCH_WARN INITIALS ALAT     ALON      BLAT BLON  TK_ERR     X_ERR      Y_ERR       ALTK_ERR      CRTK_ERR      ADLAND        BDLAND     AMSLP      BMSLP AMAX_WIND BMAX_WIND AAL_WIND_34 BAL_WIND_34 ANE_WIND_34 BNE_WIND_34 ASE_WIND_34 BSE_WIND_34 ASW_WIND_34 BSW_WIND_34 ANW_WIND_34 BNW_WIND_34 AAL_WIND_50 BAL_WIND_50 ANE_WIND_50 BNE_WIND_50 ASE_WIND_50 BSE_WIND_50 ASW_WIND_50 BSW_WIND_50 ANW_WIND_50 BNW_WIND_50 AAL_WIND_64 BAL_WIND_64 ANE_WIND_64 BNE_WIND_64 ASE_WIND_64 BSE_WIND_64 ASW_WIND_64 BSW_WIND_64 ANW_WIND_64 BNW_WIND_64 ARADP BRADP ARRP BRRP AMRD      BMRD AGUSTS BGUSTS AEYE BEYE ADIR BDIR ASPEED BSPEED ADEPTH BDEPTH
V11.0.0 GFSI      BEST   NA   AL132020 AL    13      LAURA      20200823_060000 240000  20200824_060000 NA        NA         TCMPR        13     3    TS         NA       NA 21.1     -77.6     20.2 -77.8   55.15518   11.22928    53.99998     1.49863     55.12489     -17.97403      20.74757   NA        1000  42              50          NA          NA   159               150   134               130    NA                NA    97                NA          NA          NA    NA                40    NA                40    NA                NA    NA                NA          NA          NA    NA                NA    NA                NA    NA                NA    NA                NA    NA  1009   NA  150  NA         25     NA     65   NA   NA   NA    0     NA      0     NA      M
V11.0.0 EMXI      BEST   NA   AL132020 AL    13      LAURA      20200823_060000 240000  20200824_060000 NA        NA         TCMPR        13     3    TS         NA       NA 20.9     -77.7     20.2 -77.8   42.37407    5.61854    41.99993     4.19678     42.15807     -17.97403      20.74757   NA        1000  45              50          NA          NA   176               150    74               130     4                NA    82                NA          NA          NA    NA                40    NA                40    NA                NA    NA                NA          NA          NA    NA                NA    NA                NA    NA                NA    NA                NA    NA  1009   NA  150  NA         25     NA     65   NA   NA   NA    0     NA      0     NA      M
V11.0.0 GFEX      BEST   NA   AL132020 AL    13      LAURA      20200823_060000 240000  20200824_060000 NA        NA         TCMPR        13     3    TS         NA       NA 21       -77.7     20.2 -77.8   48.32746    5.6167     47.99995     5.57908     47.99558     -17.97403      20.74757   NA        1000  NA              50          NA          NA    NA               150    NA               130    NA                NA    NA                NA          NA          NA    NA                40    NA                40    NA                NA    NA                NA          NA          NA    NA                NA    NA                NA    NA                NA    NA                NA    NA  1009   NA  150  NA         25     NA     65   NA   NA   NA    0     NA      0     NA      M
V11.0.0 GFEX_CONS BEST   NA   AL132020 AL    13      LAURA      20200823_060000 240000  20200824_060000 NA        NA         TCMPR        13     3    TS         NA       NA 21       -77.65    20.2 -77.8   48.73366    8.42462    47.99995     2.84702     48.64164     -17.97403      20.74757   NA        1000  43.5            50          NA          NA   167.5             150   104               130    NA                NA    89.5              NA          NA          NA    NA                40    NA                40    NA                NA    NA                NA          NA          NA    NA                NA    NA                NA    NA                NA    NA                NA    NA  1009   NA  150  NA         25     NA     65   NA   NA   NA    0     NA      0     NA      M
```
The latitude discrepancy (NHC -77.7 vs MET -77.65) is the difference in precision (NHC rounds to 0.1 while MET does not). Note that this causes diffs in many other columns, such as TK_ERR, X_ERR, and Y_ERR. When the location differs by up to 0.05 degrees, we'll see differences in those location error computations. It also looks like MET is computing average intensity values while NHC is not always doing so.

**Comment by sethlinden** [comment]
@KathrynNewman I am computing three new variables: track spread, wind-speed standard deviation and pressure standard deviation (track_spread, vmax_stdev, mslp_stdev).

Should I be appending them to the TCMPR line type or adding a new line type to report the consensus spread info? Thanks!

**Comment by KathrynNewman** [comment]
@JohnHalleyGotway thanks for digging up the NHC consensus track definitions. I think the 7 consensus tracks without restricted data exercise the various options well. Did you want follow-up on the discrepancy between the MET computed and NHC computed solutions?

@sethlinden Good question! I think it would be sufficient to just add these new variables to the TCMPR line type. Is there an argument for a new line type that I am overlooking?

**Comment by sethlinden** [comment]
@KathrynNewman thank you. I will add the output to the TCMPR line type for now.

**Comment by sethlinden** [comment]
@KathrynNewman I'll be adding 3 new columns to the TCMPR line type. @JohnHalleyGotway thought it would be good to ask you what we should really name the columns (so they make sense to the users). The three options he came up with are:

LOCATION_SPREAD, MSLP_SPREAD, MAX_WIND_SPREAD
or
ALOCATION_SPREAD, AMSLP_SPREAD, AMAX_WIND_SPREAD
or
CONS_LOCATION_SPREAD, CONS_MSLP_SPREAD, CONS_MAX_WIND_SPREAD

For reference these are all consensus track type variables (spread of the tracks, v_max_stdev of the track, mslp_stdev of the tracks), all for a given lead time.

I personally am leaning towards the first option. But let me know what the scientists prefer?

**Comment by JiayiPeng-NOAA** [comment]
Hi Seth,
I prefer the first option too. Or POSITION_SPREAD, TRACK_SPREAD.
For the location spread, you need to calculate the ensemble mean positions
(the average of 30-members (for GEFS) latitudes/longitudes) first.
Then you could calculate the distances between each member and the ensemble
mean position, the position spread is the average of 30-member distances
from the ensemble-mean position.
Thanks,
Jiayi.

**Comment by sethlinden** [comment]
@JiayiPeng-NOAA thanks for the feedback. I like using TRACK_SPREAD (instead of LOCATION_SPREAD). So we will use:

TRACK_SPREAD, MSLP_SPREAD, MAX_WIND_SPREAD

We are calculating the track spread properly along with mslp and max-wind standard-deviations.

**Comment by JiayiPeng-NOAA** [comment]
Sounds good.

**Comment by KathrynNewman** [comment]
@sethlinden - I agree with @JiayiPeng-NOAA, looks good!

**Comment by sethlinden** [comment]
@JiayiPeng-NOAA @KathrynNewman @JohnHalleyGotway 

Per a discussion with John HG this morning, the units of the track spread values will be in nautical miles (instead of kilometers), unless it should be km instead?

Also wanted to mention, related to these new consensus variables (track-spread, mslp-spread, max-wind-speed) we could also output the number of models (ensemble members) that went into each consensus forecast. But since this is not required we decided to leave that out for now (unless otherwise stated).

**Comment by JiayiPeng-NOAA** [comment]
Sounds good to me.

**Comment by KathrynNewman** [comment]
@sethlinden - I would go with nm rather than km for consistency. I could see the number of ensemble members being useful information to have, but if @JiayiPeng-NOAA doesn't think it's a necessary feature, it's probably fine to hold off on that!

**Comment by JiayiPeng-NOAA** [comment]
Hi Seth,
I just checked the operational code for GEFS ensemble mean track
calculation (see below).
GEFS has 30 ensemble members (plus one control), I set the minimum number
12 for its mean/spread calculations.
Sometimes we do not have 12 GEFS members' track data, there will be no
output for ensemble mean track and spread.

So, it's quite important to output the number of the ensemble members for
the mean/spread calculations in the Met/MetPlus stat file.
When we run the statistics, we will have the capability to filter out those
cases with ensemble members' number <= 12.
Thanks,
Jiayi
--------------------------------------
        integer, parameter :: ncmaxmem = 30 ! max # ncep ensemble perts
        integer, parameter :: ccmaxmem = 20 ! max # cmc ensemble perts
        integer, parameter :: ecmaxmem = 50 ! max # ecmwf ensemble perts

        integer, parameter :: ncminmem = 12 ! min # of ncep ensemble
        integer, parameter :: ccminmem =  8 ! min # of cmc ensemble
        integer, parameter :: ecminmem = 20 ! min # of ecmwf ensemble

**Comment by sethlinden** [comment]
@KathrynNewman yep sounds good, ywa the track-spread is being output in nautical miles now.

@JiayiPeng-NOAA we can certainly add a new output column to the TCMPR stat line type that shows the number of ensemble members. What do you think we should call it?

NUM_MEMBERS?
or
CONS_MEMBERS?
or
SPREAD_MEMBERS?

Open to suggestions?

**Comment by JiayiPeng-NOAA** [comment]
Hi Seth,
I prefer the first one: NUM_MEMBERS.
While you are outputting TRACK_SPREAD, MSLP_SPREAD, MAX_WIND_SPREAD,
NUM_MEMBERS, please also include:
TRACK_MEAN (LAT_MEAN; LON_MEAN), MSLP_MEAN, MAX_WIND_MEAN in the same stat
file.
Thanks,
Jiayi

**Comment by sethlinden** [comment]
@JiayiPeng-NOAA sounds good. I think we may already be producing some of that output for the "consensus" model (TRACK_MEAN (LAT_MEAN; LON_MEAN), MSLP_MEAN, MAX_WIND_MEAN). But if we are not, I can certainly add those variables. I will also add output for NUM_MEMBERS. Thanks!

**Comment by JiayiPeng-NOAA** [comment]
Hi Seth,
While you are calculating ensemble spread, you have all the ensemble mean
data (Mean_LAT, Mean_LON, Mean_SLP and Mean_WindSpeed).
Please output these variables in one file, which will help for further
statistical analysis.
Thanks,
Jiayi

**Comment by JohnHalleyGotway** [comment]
Received feedback from @JiayiPeng-NOAA on 11/14/2022 recommending that we rename the 5 new TCMPR output columns as follows. Note that I swapped the order of TRACK_SPREAD and TRACK_STDEV below to group all the STDEV columns together:
```
NUM_MEMBERS, TRACK_SPREAD, TRACK_STDEV, MSLP_STDEV, MAX_WIND_STDEV
```
I confirmed and approved these changes with @KathrynNewman.

Reopening this issue to handle this renaming.
