### ISSUE TITLE
Update error messages to redirect users from the MET-Help desk to METplus Discussions.

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/MET#2054]
I received the following error from MET:

> ERROR  : MetGrib2DataFile::data_plane() -> PDS template number (6) is not supported. Please email [met_help@ucar.edu](mailto:met_help@ucar.edu).

## Describe the Enhancement ##
We should update any error messages that mention met_help@ucar.edu and replace it with a link to the METplus GitHub Discussions page: https://github.com/dtcenter/METplus/discussions

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
2792541

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] #2063
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.

**Comment by davidalbo** [comment]
In this file:
https://github.com/dtcenter/MET/blob/develop/met/docs/Users_Guide/appendixA.rst

does it make sense to refer to the METplus discussion page in the troubleshooting instructions here?
                                                                                                                                                                     
```
After doing that, please try recompiling MET. If it fails,                                                                                                            
please send met_help@ucar.edu the following log files.                                                                                                                
"make_install.log" as well as "config.log".
```

**Comment by JohnHalleyGotway** [comment]
@davidalbo, yep, that's exactly right, refer them to discussions. Please see [this section](https://met.readthedocs.io/en/develop/Users_Guide/appendixA.html?highlight=discussions#where-to-get-help) for a similar example.
