### ISSUE TITLE
Add new bias ratio statistic to the ECNT line type from Ensemble-Stat and for HiRA

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#2058]
## Describe the Enhancement ##

dtcenter/MET#1583 added support for HiRA to Ensemble-Stat. However, the work on that issue did not address this [comment](https://github.com/dtcenter/MET/issues/1583#issuecomment-1007517205) from @mpm-meto.

Applying HiRA to ensembles effectively means that what is done for a single deterministic forecast in terms of the extraction of neighbourhoods from the forecast field has to be repeated _n_ times _before_ the stats are computed, i.e. if you have a 3 x 3 neighbourhood it gives a pseudo ensemble of 9 for which the scores are calculated in the deterministic case. When the same 3 x 3 neighbourhood is applied to an ensemble of 18 members then 3 x 3 x 18 values are extracted to create a pseudo ensemble from which the scores are calculated. Put another way the neighbourhood relevant to a given location has to be extracted first from each ensemble member; all the values need to be concatenated to create one (long) vector before being fed into the statistical calculation.

One other thing to bear in mind is that we calculate two kinds of bias ratios with HiRA. A mean bias ratio and a bias ratio which is more like a frequency bias. It would be great if these could also be considered for inclusion at some point.

The mean bias ratio is what it says on the tin, calculating the mean of the neighbourhood values (across a site or all sites) normalised by the single or mean for a site or all sites in a list.
The bias ratio is defined as:
![148568706-7cdb3d0e-79cf-40ee-8191-5bebab5fe778](https://user-images.githubusercontent.com/21087144/192033981-0bcfb746-6184-414f-bb25-7bc0527da409.png)

The task for this issue is likely adding a new column of output to the ECNT line type. Adding a new column for MET version 10.1.0 is unrealistic during the last development cycle for that release. It would not provide sufficient time for METdatadb and METviewer to be updated to handle this change. Recommend addressing this in MET version 11.0.0.

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
No sub-issues needed.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: @JohnHalleyGotway 
- [x] Select **scientist(s)** or **no scientist** required: @mpm-meto 

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
- [ ] Need to define METdatadb issue.
- [ ] Need to define METviewer/METplotpy issues.

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update log messages for easier debugging.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.

**Comment by JohnHalleyGotway** [comment]
@mpm-meto please see the documentation I'm adding in Appendix C for this new [BIAS_RATIO statistic](https://met.readthedocs.io/en/feature_2058_bias_ratio/Users_Guide/appendixC.html#:~:text=33.5.4.%20Bias%20Ratio-,%EF%83%81,-Called%20%E2%80%9CBIAS_RATIO%E2%80%9D%20in).

Questions:
- Any changes to my brief description or the equation itself?
- Can you please send me a sentence or two describing the "perfect score" and how to interpret the values?

For example, for [Mean Error](https://met.readthedocs.io/en/feature_2058_bias_ratio/Users_Guide/appendixC.html#mean-error-me) we state simply:
```
A perfect forecast has ME = 0.
```
[Scatter Index](https://met.readthedocs.io/en/feature_2058_bias_ratio/Users_Guide/appendixC.html#scatter-index-si) states:
```
Smaller values of SI indicate better agreement between the model and observations (less scatter on scatter plot).
```
So I'm looking for something like that.

This is a pretty quick turnaround. I need to get this all wrapped up tomorrow (Thurs 10/27) to get it in for the MET-11.0.0-beta4 release.
