### ISSUE TITLE
Add support for the normalize option to all MET tools that use climatology data.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#2062]
## Describe the Enhancement ##
dtcenter/MET#1918 added the normalize option to the gen_ens_prod tool. That enables the ensemble member fields to be normalized relative to the external climatology or to the ensemble mean and standard deviation.

This issue is to extend that support more broadly to all of the MET tools that support the use of external climatology data. And those tools are Point-Stat, Grid-Stat, Ensemble-Stat, and Series-Analysis. For each of these tools, in addition to processing the raw input data, they should be able to process the anomaly (subtract mean) or standardized anomaly (subtract mean and divide by standard deviation).

When adding this support, be sure that both the gridded forecasts, gridded analyses, and point analyses can be normalized... depending on the scope where the normalize option is specified in the config file.

For Point-Stat and Grid-Stat, only normalizing relative to an external climatology can be supported.
For Ensemble-Stat and Series-Analysis, in addition to the external climatology, we could also normalize relative to forecast mean and standard deviation, as is done in Gen-Ens-Prod.

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
No sub-issues needed.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
- [ ] Need to define METplus issue to update the wrappers accordingly.

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
