### ISSUE TITLE
Add entries to the default obs_prepbufr_map setting.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#2070]
## Describe the Enhancement ##
This is a very quick and easy fix that was discussed at length in this METplus Discussion METplus/dtcenter#1417.

The resolution is that we should 2 additional entries to the obs_prepbufr_map PB2NC configuration option:
```
{ key = "HOVI"; val = "VIS"; },
{ key = "TOCC"; val = "TCDC"; },
```

This task is to update all instances of the obs_prepbufr_map config entry with these changes.

### Time Estimate ###
1 hour.

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
None needed.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: @JohnHalleyGotway 
- [x] Select **scientist(s)** or **no scientist** required: Not needed

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
No direct impacts.

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update log messages for easier debugging.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.

**Comment by JohnHalleyGotway** [comment]
@hsoh-u I need some input from you on this issue. I'm trying to do two things here.
1. Add the 2 entries listed above to the obs_prepbufr_map setting in the default PB2NC config file.
2. Update the comments for the obs_bufr_map setting in all existing PB2NC config files to make them consistent.

My question is about the contents of the [test/PB2NCConfig_pbl](https://github.com/dtcenter/MET/blob/af2ce1307fbdaf22b5a36727665c7a562352d10b/test/config/PB2NCConfig_pbl#L109) file. I would like to remove this obs_prepbufr_map entry and move the non-default settings over to the obs_bufr_map setting instead. But I have 2 questions about this.

1. The current setting maps both "D_DPT" and "TDO" to the SAME output "DPT". This seems like a bad idea. We wouldn't be able to differentiate between the raw TDO obs and the derived one in the output. Both would show up as DPT.
2. This maps "D_PBL" to "HPBL", but the [default setting](https://github.com/dtcenter/MET/blob/af2ce1307fbdaf22b5a36727665c7a562352d10b/met/data/config/PB2NCConfig_default#L123) maps "D_PBL" to "PBL". Which one should we be using? Or should I keep "D_PBL -> PBL" in the obs_prepbufr_map and override that with "D_PBL -> HPBL" in the obs_bufr_map for this test?

**Comment by JohnHalleyGotway** [comment]
Actually @hsoh-u, I just made a decision and will request your review on the PR. The PB2NCConfig_pbl output is NOT actually used downstream. It's just an independent test of PB2NC. As such, it doesn't matter so much that D_DPT and TDO are both renamed to the same string. In fact, this is a good test to confirm that the obs_bufr_map settings actually do take precedence over the obs_prepbufr_map settings. Fingers crossed that my proposed changes produce exactly the same result.
