### ISSUE TITLE
Update the GRIB2 MRMS table in MET.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#2081]
## Describe the Enhancement ##
@hertneky raised this issue via GitHub discussions in dtcenter/METplus#1467.

This issue is to update MET's GRIB2 table to match the current MRMS usage, which can be found here:
https://www.nssl.noaa.gov/projects/mrms/operational/tables.php

Updating the tables should be relatively straight-forward. We just need to confirm that this change doesn't cause any differences in the MET unit test output.

### Time Estimate ###
1 day.

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
No sub-issues needed.

### Relevant Deadlines ###
Include in the MET-10.1.0 release - needed for JTTI WPC project

### Funding Source ###
2700042

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required: unassigned
- [x] Select **scientist(s)** or **no scientist** required: @hertneky 

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
Digging into some of the details here.
- In the past, we've pull GRIB table definitions from wgrib2.
- The wgrib2 source code can be found here:
   ftp://ftp.cpc.ncep.noaa.gov/wd51we/wgrib2/wgrib2.tgz
- In grib2/wgrib2, I see 29 scripts named "get_code_Table_X.Y.sh" for various X.Y values.
- Each of those scripts retrieves data from this GitHub repo: https://github.com/wmo-im/GRIB2
- However, after cloning that repo and grepping, I found NO instances of MRMS in those table files. So while this is an interesting detail for MET, it doesn't factor into this issue.

**Comment by JohnHalleyGotway** [comment]
@hertneky can you please share the custom grib2_mrms.txt file you're currently using?

**Comment by hertneky** [comment]
@JohnHalleyGotway I am not sure it's useful as I only added a handful of the new fields to the existing grib2_mrms.txt that were needed for the WPC work, but here it is.
[grib2_mrms.txt](https://github.com/dtcenter/MET/files/8216056/grib2_mrms.txt)
I saw there were a number of name changes from older data to newer data, which I wouldn't know how best to handle.

**Comment by JohnHalleyGotway** [comment]
The changes for this issue should be made in this [MRMS GRIB2 table file](https://github.com/dtcenter/MET/tree/develop/data/table_files). The task it to migrate changes from this [NSSL website]([nssl.noaa.gov/projects/mrms/operational/tables.php](https://www.nssl.noaa.gov/projects/mrms/operational/tables.php)) into that file.

By way of comparison, let's look at the entry for "VIL":
Existing in table:
```
209 10 0 255 161 1 3 41  "VIL"  "Vertically Integrated Liquid"  "kg/m^2"
```
On the website:
```
209 | 3 | 41 | VIL | 2-min | kg/m2 | -1 | n/a | -3 | Vertically Integrated Liquid
```
Using that as a guide, we want to convert each website entry into a MET table entry as...
```
COL#1 10 0 255 161 1 COL#2 COL#3 COL#4 COL#10 COL#6
```

**Comment by sethlinden** [comment]
@JohnHalleyGotway I assume we just want to update entries in the grib2_mrms.txt file based on the mapping you describe above (so it matches the info from the NSSL web-stite)? And then also add new entries (that aren't defined in our grib2_mrms.txt file)? Is that correct? (So for your example, nothing needs to be updated for the "VIL" entry since it matches the columns you map, correct)

I assume we want to create entries (if they don't already exist) for all the fields listed in the NSSL MRMS GRIB 2 table?

**Comment by JohnHalleyGotway** [comment]
@sethlinden yes, that's my understanding as well. Make the MRMS GRIB table in MET match the latest on the NSSL website. @hertneky please advise if you're expecting something different from that.

**Comment by hertneky** [comment]
@JohnHalleyGotway I have no objections to that. It sounds good to me.

**Comment by sethlinden** [comment]
I updated grib2_mrms.txt to match MRMS Version 12.2. Updated existing entries, removed old entries, added new entries. The new file has been pushed to GitHub for this feature branch

FYI, these fields were removed in version 12.2:

209 10 0 255 161 1 4 0  "IRband4"  "Infrared (E/W blend)"  "K"
209 10 0 255 161 1 4 1  "Visible"  "Visible (E/W blend)"  "non-dim"
209 10 0 255 161 1 4 2  "WaterVapor"  "Water Vapor (E/W blend)"  "K"
209 10 0 255 161 1 4 3  "CloudCover"  "Cloud Cover"  "K"
209 10 0 255 161 1 6 9  "GaugeCorrQPE01H"  "Local gauge bias corrected radar precipitation accumulation 1-hour"  "mm"
209 10 0 255 161 1 6 10  "GaugeCorrQPE03H"  "Local gauge bias corrected radar precipitation accumulation 3-hour"  "mm"
209 10 0 255 161 1 6 11  "GaugeCorrQPE06H"  "Local gauge bias corrected radar precipitation accumulation 6-hour"  "mm"
209 10 0 255 161 1 6 12  "GaugeCorrQPE12H"  "Local gauge bias corrected radar precipitation accumulation 12-hour"  "mm"
209 10 0 255 161 1 6 13  "GaugeCorrQPE24H"  "Local gauge bias corrected radar precipitation accumulation 24-hour"  "mm"
209 10 0 255 161 1 6 14  "GaugeCorrQPE48H"  "Local gauge bias corrected radar precipitation accumulation 48-hour"  "mm"
209 10 0 255 161 1 6 15  "GaugeCorrQPE72H"  "Local gauge bias corrected radar precipitation accumulation 72-hour"  "mm"
209 10 0 255 161 1 6 16  "GaugeOnlyQPE01H"  "Gauge only precipitation accumulation 1-hour"  "mm"
209 10 0 255 161 1 6 17  "GaugeOnlyQPE03H"  "Gauge only precipitation accumulation 3-hour"  "mm"
209 10 0 255 161 1 6 18  "GaugeOnlyQPE06H"  "Gauge only precipitation accumulation 6-hour"  "mm"
209 10 0 255 161 1 6 19  "GaugeOnlyQPE12H"  "Gauge only precipitation accumulation 12-hour"  "mm"
209 10 0 255 161 1 6 20  "GaugeOnlyQPE24H"  "Gauge only precipitation accumulation 24-hour"  "mm"
209 10 0 255 161 1 6 21  "GaugeOnlyQPE48H"  "Gauge only precipitation accumulation 48-hour"  "mm"
209 10 0 255 161 1 6 22  "GaugeOnlyQPE72H"  "Gauge only precipitation accumulation 72-hour"  "mm"
209 10 0 255 161 1 6 23  "MountainMapperQPE01H"  "Mountain Mapper precipitation accumulation 1-hour"  "mm"
209 10 0 255 161 1 6 24  "MountainMapperQPE03H"  "Mountain Mapper precipitation accumulation 3-hour"  "mm"
209 10 0 255 161 1 6 25  "MountainMapperQPE06H"  "Mountain Mapper precipitation accumulation 6-hour"  "mm"
209 10 0 255 161 1 6 26  "MountainMapperQPE12H"  "Mountain Mapper precipitation accumulation 12-hour"  "mm"
209 10 0 255 161 1 6 27  "MountainMapperQPE24H"  "Mountain Mapper precipitation accumulation 24-hour"  "mm"
209 10 0 255 161 1 6 28  "MountainMapperQPE48H"  "Mountain Mapper precipitation accumulation 48-hour"  "mm"
209 10 0 255 161 1 6 29  "MountainMapperQPE72H"  "Mountain Mapper precipitation accumulation 72-hour"  "mm"
209 10 0 255 161 1 9 1  "ConusPlusMergedReflectivityQC"  "All Radar 3D Reflectivty Mosaic - 33 CAPPIS (500-19000m)"  "dBZ"
209 10 0 255 161 1 11 4  "Merged_LVL3_BaseHCA"  "flag"  "Level III Base HCA Mosaic (nearest neighbor)"


@JohnHalleyGotway what is the best way to test these changes?

**Comment by sethlinden** [comment]
@JohnHalleyGotway I realized today that my commit for the grib2_mrms.txt did not actually make it into GitHub last Friday for some reason. I started with a fresh checkout of develop and this feature branch and then just commited the new grib2_mrms.txt (I can now see it in the message above). I assume this will kickoff a testing workflow for this change and then I can see the changes in the output. I am also running the unit tests now by hand.
