### ISSUE TITLE
Enhance MET to make the specifying `set_attr` options for multiple variables and levels more concise.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#2101]
## Describe the Enhancement ##
This feature request arose via GitHub discussions in dtcenter/METplus#1513. The user is specifying a whopping 77 input variables to be verified. They are spread across geopotential_height, air_temperature, relative_humidity, and a few variations of height levels.

For some of these variables, the user is specifying multiple levels from a NetCDF input file. However, they're using `set_attr_level` to replace the clumsy NetCDF level strings with something more human-readable.

Here's a selection of METplus settings by way of example:
```
BOTH_VAR66_NAME = relative_humidity_0
BOTH_VAR66_LEVELS = "(17,*,*)"
BOTH_VAR66_OPTIONS = set_attr_level="P500"
BOTH_VAR67_NAME = relative_humidity_0
BOTH_VAR67_LEVELS = "(18,*,*)"
BOTH_VAR67_OPTIONS = set_attr_level="P600"
BOTH_VAR68_NAME = relative_humidity_0
BOTH_VAR68_LEVELS = "(19,*,*)"
BOTH_VAR68_OPTIONS = set_attr_level="P700"
```

This task is to enhance the MET config file handling logic to make this more concise by supporting the following:
```
BOTH_VAR66_NAME = relative_humidity_0
BOTH_VAR66_LEVELS = "(17,*,*)", "(18,*,*)", "(19,*,*)"
BOTH_VAR66_OPTIONS = set_attr_level="P500", "P600", "P700"
```

Point-Stat already supports the specification of multiple levels. The difference here is adding support for multiple set_attr options. Update the processing of the set_attr options with the following logic:

- When parsing the set_attr options for the i-th field out of N...
  - if the set_attr option is a single entry, use it
  - if the set_attr option is an array of entries...
    - with length 1, use it
    - with length N, use the i-th entry
    - with length != N, error out

These changes should be made to Point-Stat, Grid-Stat, and Ensemble-Stat. Is it needed in any other tools?

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
Should be no impact on METplus wrappers. This should just add support for a new variation which should require no wrapper changes.

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
