### ISSUE TITLE
Enhance TC-Gen to quantify GTWO shapefile misses in space and time.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#2110]
## Describe the Enhancement ##
This feature request came via @halperin-erau based on feedback on his TC-Gen presentation at the Interdepartmental Hurricane Conference in March 2022. The requested changes apply to the verification of GTWO shapefile areas specified using the "-shape" command line option.

Each shapefile has a corresponding probability of genesis value. TC-Gen checks the BEST track data to determine whether genesis occurred within the prescribed area and during the prescribed time window. The result is binary, yes/no.

Richard Pasch at NHC asked if there was a way to verify/determine how far off some genesis forecasts might be in the event that genesis occurs just outside of the GTWO shape file.  In other words, could we output something like a minimum distance from the shape file boundary to the nearest BEST genesis location within the 2/5/7-day window?  Kate Musgrave at CIRA asked a similar question, but with respect to timing errors.  Could we output the time of BEST genesis for events that occur within the GTWO shape file, but outside of the 2/5/7-day window? 

Here are my initial thoughts for how this could be handled:

I can see how this functionality they requested could be added. I'd start by updating the logic in the [find_genshape_match()](https://github.com/dtcenter/MET/blob/a32b11b13c994814e9e8e0d2ab116ddc702e6c64/met/src/tools/tc_utils/tc_gen/tc_gen.cc#L1136) function.

To keep track of near misses, we need to...
- Replace this call to [p.is_inside(x, y)](https://github.com/dtcenter/MET/blob/a32b11b13c994814e9e8e0d2ab116ddc702e6c64/met/src/tools/tc_utils/tc_gen/tc_gen.cc#L1159) to a function that would compute the minimum distance to the boundary of the polyline. That logic does already exist elsewhere in MET to find the minimum distance from a point to a series of line segments.
- Define logic as to whether it's better to be closer in space or time... in what order should those be minimized?
- Update the [write_pct_genmpr_row()](https://github.com/dtcenter/MET/blob/a32b11b13c994814e9e8e0d2ab116ddc702e6c64/met/src/tools/tc_utils/tc_gen/tc_gen.cc#L2236) function and output line type as needed to indicate the closest match.

### Time Estimate ###
3 days.

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
No sub-issues needed.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Backlog of Development Ideas**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
Since the TC-Gen MPR line type is NOT loaded into METdatadb, I expect no impacts on the other METplus components.

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
