### ISSUE TITLE
Add the point-to-point 75th quantile Hausdorff Distance to the DMAP line type

### ISSUE THREAD

**Issue by j-opatz** [dtcenter/MET#2112]
## Describe the New Feature ##
In order to replicate the marine and cryosphere verification package at EMC and meet one of METplus' verification goals, we need to create a 75th Quantile Hausdorff Distance Metric column output in MET. This is also listed as one of EMC's gaps in verification. This can be in the same line type as the current Hausdorff output.

The largest obstacle for this work will be the method of calculation. As indicated in the attached code snippet, the lat/lons are not on a grid (as the current DMAP calculations are required to be) but instead completed by point-to-point comparison.

### Acceptance Testing ###
We currently have a use case in development that calculates its own Modified Hausdorff values. I'll attach that snippet of code to this issue.
[Mod Hausdorff code.txt](https://github.com/dtcenter/MET/files/8383540/Mod.Hausdorff.code.txt)
Note that this is for a Modified Hausdorff, while the issue is for the creation of the 75th quantile of Hausdorff. In order for this issue to be resolved, MET should create a 75th quantile Hausdorff distance metric that is benchmarked with the the available EMC code. This can NOT be accomplished with Python embedding, as EMC requires a native-MET value. 

### Time Estimate ###
~2 days.

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- No sub-issues needed.

### Relevant Deadlines ###
Marine and cryo verification package is expected to be completed by the end of April, and a use case in METplus is dependent on the Modified Hausdorff output to be considered complete.

### Funding Source ###
2773542

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: @JohnHalleyGotway 
- [x] Select **scientist(s)** or **no scientist** required: @j-opatz and @mrinalbiswas 
- Recommend requesting a PR review from @ericgilleland 

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
- [ ] Need to defined METplus Analysis Tools issues to handle downstream impacts. 

## New Feature Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by j-opatz** [comment]
After reviewing the input data, this use case appears to be the comparison of a bipolar coordinate system and point data.
The forecast data is from RTOFS model, tracking the 12C isotherm at 400m. While the model itself is on a grid, tracking the isotherm appears to vary and will not be on a consistent grid. 
To observation data is from the NAVOCEANO Ocean Frontal Analysis, an ASCII file that is strictly observational points.
Given this complexity, it may be necessary to have a meeting to discuss the current code and what its doing with these irregular points, to provide a plan forward in the MET development.

**Comment by ericgilleland** [comment]
The original Hausdorff distance definition (not the one we use, but they are equivalent) is max{ max_{a in A} [ d(a,B) ], max_{b in B} [ d(b, A) ] }.  The MHD proposed here just replaces the inner maxima with the averages.  So, I think it is just the maximum of the two MED directions.  Perhaps someone can check if I'm right about that by comparing the max of the two MED's with their MHD?

**Comment by JohnHalleyGotway** [comment]
@ericgilleland, @mrinalbiswas, and @j-opatz that was exactly what I was just trying to figure out. The MHD definition sure looks similar to the [Mean Error Distance](https://met.readthedocs.io/en/latest/Users_Guide/appendixC.html?highlight=dmap#mean-error-distance) (MED) equations. And MET already includes MED_MAX in the [DMAP line type](https://met.readthedocs.io/en/latest/Users_Guide/grid-stat.html?highlight=dmap#id14), to report the maximum of the MED_FO and MED_OF columns. So perhaps the Modified Hausdorff Distance (MHD) = MED_MAX?

If so, we could just update the user's guide to indicate this and include the MHD reference.

@mrinalbiswas or @j-opatz, do you have a test case we can run through both the sample code and Grid-Stat to compare the reported MHD value to the MED_MAX column of the DMAP line type?

**Comment by ericgilleland** [comment]
Yes, from what I read in the paper, what we call MED_MAX should be the same as what they call MHD.  However, keep in mind that the other software might use a different method for obtaining the distances (e.g., a different distance map method), so it could be that there are small differences.  However, I would expect them to be small.  I had never seen that paper, so thanks for the reference.

**Comment by JohnHalleyGotway** [comment]
I ran Grid-Stat and dumped pairs to a NetCDF file. Then I used python to read the data and compute MHD. But an unexpected pattern emerged:
```
FCST_UGRD_Z10_FULL shape: (100, 150)
OBS_UGRD_Z10_FULL shape: (100, 150)
MHD >= 2 : 4.129755758459326
MHD >= 3 : 3.4034079875387793
MHD >= 4 : 2.9573749722233136
MHD >= 5 : 2.1304196282285544
MHD >= 6 : 1.2714305260807373
MHD >= 7 : 0.8191304543187115
```
As I increased the threshold, the MHD decreased.
In MET, I observed the opposite behavior. Increasing the threshold spreads the events out further and increases the distances:
```
FCST_VAR FCST_THRESH MED_MAX
UGRD >=2 0.78407
UGRD >=3 1.32581
UGRD >=4 2.01227
UGRD >=5 4.47825
UGRD >=6 16.87162
UGRD >=7 57.50208
UGRD >=8 48.28046
```
I had been hoping to show the methods to be equivalent, but I'd say I'm a very long way from that! The distance pattern reported by MET certainly makes more intuitive sense.

**Comment by ericgilleland** [comment]
Curious.  It sounds like the MHD is not what they think it is.  The paper discussed several other Hausdorff spinoff methods, but it settled on MED_MAX as the MHD.  Ideally, for increasing thresholds, you don't want the score to get better as you start getting extreme events wrong.  On the other hand, if there is a lot of small-scale noise, you don't want that to increase the measure.  Given that most of the Hausdorff variants are aimed at trying to solve the latter issue, it makes me think that I'm missing something in their description of the MHD.  I'll take another look and think about it.  The G measure, for example, that I think we added, I believe decreases with increasing threshold.  MED_MAX either will or won't depending on how well the high values are matched.

**Comment by ericgilleland** [comment]
I just double checked, and MHD in the paper is MED_MAX.  Not sure what their MHD is then.  They include 24 different Hausdorff variants.  The variants are determined by different combinations of functions d1, ..., , d6 with f1, ... , f4, where for sets A and B, and denoting points within the sets by a and b:

d1 = d1(A,B) = min_{a in A} [ d(a, B) ]
d2 = d2(A,B) = median_{a in A} [ d(a, B) ]
d3 = same but replacing min/median with 0.75 quantile
d4 = same but replacing min/median with 0.9 quantile
d5 = same but replacing min/median with max [as in original Hausdorff distance]
d6 = same but replacing min/median with the average [as used in what the paper calls MHD]

then, f1 = min{ d(A,B), d(B,A) },
f2 = max{ d(A,B), d(B,A) } [as in original Hausdorff distance and MHD in the paper]
f3 = the average of d(A,B) and d(B,A)
f4 = a weighted average of the two.

**Comment by ericgilleland** [comment]
One thing to try would be to make a function that takes arguments for which type of d and which type of f, and then see which combination matches what they have for MHD (if any).

**Comment by mrinalbiswas** [comment]
@JohnHalleyGotway Here is the command to run Todd's code on eyewall: python3 read_rtofs_fronts_loop.py 20210809

Directory: /d1/biswas/EMC_ocean-verification/fronts/ush
