### ISSUE TITLE
Enhance MET to support the GRIB2 grid definition template number 32769.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#2124]
## Describe the Enhancement ##
This issue arose via METplus Discussions dtcenter/METplus#1544. NOAA/GSL would like to process full RAP grids directly which is available via GRIB2 files using the grid definition template number 32769. Please see the [Rapid Refresh website](https://rapidrefresh.noaa.gov/) for additional details and recent sample data is available from the [NCEP FTP site](ftp://ftpprd.ncep.noaa.gov/pub/data/nccf/com/rap/prod). For example, here a GRIB2 file on this grid:
   ftp://ftpprd.ncep.noaa.gov/pub/data/nccf/com/rap/prod/rap.20200401/rap.t00z.wrfmslf12.grib2

Note that the wgrib2 output for this grid is a bit curious:
```
wgrib2 -V -d 1 rap.t00z.wrfmslf12.grib2
    grid_template=32769:winds(grid):
	I am not an Arakawa E-grid. 
	I am rotated but have no rotation angle.
	I am staggered. What am I?
	(953 x 834) units 1e-06 input WE:SN output WE:SN res 56
	lat0 -10.590603 lat-center 54.000000 dlat 121.813000
	lon0 220.914154 lon-center 254.000000 dlon 121.813000 #points=794802
```

Please see the definition of this grid in GRIB2 [Template 3.32769](https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_temp3-32769.shtml).

This grid is described as "Rotate Latitude/Longitude (Arakawa Non-E Staggered grid)". The question is whether or not this grid can be instantiated as a Rotated Lat/Lon grid, that's already supported by MET. Careful comparison of GRIB2 grid [Template 3.1](https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_temp3-1.shtml) (for lat/lon) and [Template 3.32769](https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_temp3-32769.shtml) reveal that they're similar but not identical. Note that template 3.1 defines the location of the south pole while 3.32769 does not. Perhaps there's some way of deriving the location of the south pole from the 32769 information, and we can just use the 32769 data to instantiate a Rotated Lat/Lon grid?

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
No sub-issues needed.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.

### Funding Source ###
2793541

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: @rgbullock
- [x] Select **scientist(s)** or **no scientist** required: Requested by @JeffHamiltonNOAA

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
No impacts.

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
@JeffHamiltonNOAA can you please clarify how soon this support is required? Would adding it to one of the development cycles for MET version 11.0.0 be sufficient? If so, is it needed for beta1 (5/11/22), beta2 (6/22/22), beta3 (8/3/22), or beta4 (9/14/22)?

**Comment by JeffHamiltonNOAA** [comment]
@JohnHalleyGotway, sorry for the delay in replying. I've been trying to get an idea of what to prioritize this functionality from Curtis, but he has been at a JCSDA retreat all week. Adding it to the 11.0.0 development cycle would work great, and if it could be in place by beta3, that would be ideal. Thanks!

**Comment by JohnHalleyGotway** [comment]
@rgbullock here's a screenshot of what I see when I run Panoply to plot surface temperature from a wrfprs RAP file named "rap.t13z.wrfprsf06.grib2".
<img width="1030" alt="Screen Shot 2022-05-11 at 1 57 11 PM" src="https://user-images.githubusercontent.com/21087144/167935185-c5488a07-18b1-4976-9769-9c4750c8d3bb.png">

I *think* that geographic extent corresponds well to this image from the [RAP website](https://rapidrefresh.noaa.gov/displayImage.cgi?image=temp2mimage&width=712&model=rr&title=RAP):
<img width="551" alt="Screen Shot 2022-05-11 at 1 58 45 PM" src="https://user-images.githubusercontent.com/21087144/167935597-5d31b9b9-ac23-4931-b21b-7218f80d1794.png">

And I say that these do NOT correspond well with the tentative map you sent:
<img width="357" alt="Screen Shot 2022-05-11 at 1 59 28 PM" src="https://user-images.githubusercontent.com/21087144/167935779-d11070a2-f69a-4e17-b707-8e628cc88f65.png">

Any idea on next steps?

**Comment by JohnHalleyGotway** [comment]
@rgbullock FYI, since you're actively working on this one, I added it to the 11.0.0 milestone and listed it as "In Progress" on the MET-11.0.0 beta1 project.

**Comment by rgbullock** [comment]
John -

The corner point in europe looks about right, but the other corner points
are off.  Also, this grid clearly straddles the north pole.

I'll see what I can do.

Randy
