### ISSUE TITLE
Enhance MTD to compute and write-out Zonal and Meridional Speed

### ISSUE THREAD

**Issue by TaraJensen** [dtcenter/MET#2131]
*Replace italics below with details for this issue.*

## Describe the Enhancement ##
This came up in our discussions with PSL with regard to adding Object based diagnostics for S2S.   In essence we have identified that MTD can be used to replicate their technique except they find it useful to have the total speed of the object be broken down into Zonal and Meridional (e-w, n-s) components.  This information would then need to be written out to the MTD ascii output (3D single object) file so it can be used as the x-axis in a Contour Plot.

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [ ] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
- [ ] Create METdatadb and METviewer issues for loading and plotting this data.

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
@rgbullock can advise on implementation details.

**Comment by JohnHalleyGotway** [comment]
This may already be done. @TaraJensen will confirm this and close this issue.

**Comment by JohnHalleyGotway** [comment]
@CPKalb, please check with @TaraJensen on this issue. She suspects that MTD already contains the output that is needed. If that is the case, please add a comment about that and close this issue.

**Comment by CPKalb** [comment]
I think it does contain the output needed, but let me check in with Maria (the person who needs it) to be sure.

**Comment by TaraJensen** [comment]
From an email discussion with Maria - I think we can close this with the note that it was determined it is not needed.

<html><body>
<div dir="ltr">Thanks for clarifying John! Tara, I think that's all we need for the zonal speed plots I'm working on.<div><br></div><div>Maria</div><div><br clear="all"><div><div dir="ltr" data-smartmail="gmail_signature"><div dir="ltr"><div><font color="#666666">Maria Gehne</font></div><font color="#666666">Research Associate III</font><div><font color="#666666">CIRES CU Boulder and NOAA Physical Sciences Laboratory</font></div><div><span style="background-color:rgb(255,255,255)"><font color="#666666">325 Broadway St - <span style="font-size:12.8px">Boulder, CO 80305-3337</span><br></font></span></div><div><font color="#666666">Phone: 303-497-4347</font></div><div><font color="#666666">Email:</font> <a href="mailto:maria.gehne@noaa.gov" target="_blank"><font color="#3d85c6">maria.gehne@noaa.gov</font></a></div><div><a href="https://www.psl.noaa.gov/people/maria.gehne/" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://www.psl.noaa.gov/people/maria.gehne/&amp;source=gmail&amp;ust=1666366944733000&amp;usg=AOvVaw3KG2eOz53HeyvqleTC3Mpt"><font color="#3d85c6">https://www.psl.noaa.gov/<wbr>people/maria.gehne/</font></a><br></div></div></div></div><br></div></div><br><div class="gmail_quote"><div dir="ltr" class="gmail_attr">On Thu, Oct 6, 2022 at 11:24 AM John Halley Gotway &lt;<a href="mailto:johnhg@ucar.edu" target="_blank">johnhg@ucar.edu</a>&gt; wrote:<br></div><blockquote class="gmail_quote" style="margin:0px 0px 0px 0.8ex;border-left:1px solid rgb(204,204,204);padding-left:1ex"><div dir="ltr">Tara and Maria,<div><br></div><div>FYI, <a href="https://met.readthedocs.io/en/latest/Users_Guide/mode-td.html#id10" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://met.readthedocs.io/en/latest/Users_Guide/mode-td.html%23id10&amp;source=gmail&amp;ust=1666366944733000&amp;usg=AOvVaw00zALDJJQo6GN09se8D3ZU">this table</a> in the MET User's Guide defines:</div><div>

30 | X_DOT | x component of object velocity
-- | -- | --
31 | Y_DOT | y component of object velocity

</div><div>Shall we refine that table to include zonal and meridional speeds in the description?</div><div><br></div><div>Thanks,<br>John</div></div><br><div class="gmail_quote"><div dir="ltr" class="gmail_attr">On Thu, Oct 6, 2022 at 10:50 AM Tara Jensen &lt;<a href="mailto:jensen@ucar.edu" target="_blank">jensen@ucar.edu</a>&gt; wrote:<br></div><blockquote class="gmail_quote" style="margin:0px 0px 0px 0.8ex;border-left:1px solid rgb(204,204,204);padding-left:1ex"><div dir="ltr"><div>Randy,</div><div><br></div><div>We are working with NOAA/PSL scientist Maria Gehne on some work.  Can you clarify something for us with regard to MTD?  <br></div><div><br></div><div>
<div>From Maria: The output file from MTD that ends in *_3d_single_cluster.txt has 
variables x_dot and y_dot in it. I believe that those are the speed of 
the object, but I couldn't find a description </div><div>of those in the documentation. If those are indeed the x and y speeds then I think we are good!</div><div><br></div><div>Can you clarify what x_dot and y_dot represent?</div><div><br></div><div>Thanks
 in advance for your quick response on this.  We are trying to develop 
if we can remove this issue from the current development cycle.</div><div><br></div><div>Cheers, Tara<br></div>

</div></div><br><div class="gmail_quote"><div dir="ltr" class="gmail_attr">On Thu, Oct 6, 2022 at 10:38 AM Maria Gehne - NOAA Affiliate &lt;<a href="mailto:maria.gehne@noaa.gov" target="_blank">maria.gehne@noaa.gov</a>&gt; wrote:<br></div><blockquote class="gmail_quote" style="margin:0px 0px 0px 0.8ex;border-left:1px solid rgb(204,204,204);padding-left:1ex"><div dir="ltr">Hi Tara,<div><br></div><div>no
 worries! I was out on leave until the end of August and catching up 
took me a while. I got stuck on the MTD and have been working on other 
things in the meantime.</div><div><br></div><div>The output file from 
MTD that ends in *_3d_single_cluster.txt has variables x_dot and y_dot 
in it. I believe that those are the speed of the object, but I couldn't 
find a description </div><div>of those in the documentation. If those are indeed the x and y speeds then I think we are good!</div><div><br></div><div>Maria</div></div></blockquote></div></blockquote></div></blockquote></div>
</body>
</html>Thanks for clarifying John! Tara, I think that's all we need for the zonal speed plots I'm working on.

Maria

Maria Gehne
Research Associate III
CIRES CU Boulder and NOAA Physical Sciences Laboratory
325 Broadway St - Boulder, CO 80305-3337
Phone: 303-497-4347
Email: [maria.gehne@noaa.gov](mailto:maria.gehne@noaa.gov)
https://www.psl.noaa.gov/people/maria.gehne/


On Thu, Oct 6, 2022 at 11:24 AM John Halley Gotway <[johnhg@ucar.edu](mailto:johnhg@ucar.edu)> wrote:

    Tara and Maria,

    FYI, [this table](https://met.readthedocs.io/en/latest/Users_Guide/mode-td.html#id10) in the MET User's Guide defines:

    30
    	

    X_DOT
    	

    x component of object velocity

    31
    	

    Y_DOT
    	

    y component of object velocity
    Shall we refine that table to include zonal and meridional speeds in the description?

    Thanks,
    John

    On Thu, Oct 6, 2022 at 10:50 AM Tara Jensen <[jensen@ucar.edu](mailto:jensen@ucar.edu)> wrote:

        Randy,

        We are working with NOAA/PSL scientist Maria Gehne on some work.  Can you clarify something for us with regard to MTD? 

        From Maria: The output file from MTD that ends in *_3d_single_cluster.txt has variables x_dot and y_dot in it. I believe that those are the speed of the object, but I couldn't find a description 
        of those in the documentation. If those are indeed the x and y speeds then I think we are good!

        Can you clarify what x_dot and y_dot represent?

        Thanks in advance for your quick response on this.  We are trying to develop if we can remove this issue from the current development cycle.

        Cheers, Tara

        On Thu, Oct 6, 2022 at 10:38 AM Maria Gehne - NOAA Affiliate <[maria.gehne@noaa.gov](mailto:maria.gehne@noaa.gov)> wrote:

            Hi Tara,

            no worries! I was out on leave until the end of August and catching up took me a while. I got stuck on the MTD and have been working on other things in the meantime.

            The output file from MTD that ends in *_3d_single_cluster.txt has variables x_dot and y_dot in it. I believe that those are the speed of the object, but I couldn't find a description 
            of those in the documentation. If those are indeed the x and y speeds then I think we are good!

            Maria
