### ISSUE TITLE
Enhance the Release Notes by adding dropdown menus

### ISSUE THREAD

**Issue by jprestop** [dtcenter/MET#2146]
Please use [Sphinx Design for Dropdown menus](https://sphinx-design.readthedocs.io/en/latest/dropdowns.html) . This will allow for searches of material hidden within dropdown menus.

Changes will need to be made to the below files:
1.  config.py 
    add 'sphinx_design' to the "extensions =" section.  (note the underscore.) 
2.  requirements.rst file. 
    add 'sphinx-design==0.3.0' with a dash 
3. MET/.github/workflows/documentation.yml 
    add a line after this example [line 28](https://github.com/dtcenter/METviewer/blob/505660418afbc1debb301c5f0b4bcd28823b3896/.github/workflows/documentation.yml#L28) . Make sure it is correctly indented.
   python -m pip install -r docs/requirements.txt
4.  Remove 'sphinx-panels' from line28 in the code.  This was originally added for dropdown menus.  But the new version is 'sphinx-design'. It isn't needed.  Removing it should avoid future confusion. sphinx-gallery Pillow sphinx_rtd_theme sphinx-panels

It should look like this:
          python -m pip install --upgrade python-dateutil requests sphinx \
          sphinx-gallery Pillow sphinx_rtd_theme 
          python -m pip install -r docs/requirements.txt

Panel drop downs would be added for the subcategories and sub-subcategories.  For example, 
-Repository and build
---Installation
---Static Code Analysis
---Testing
---Continuous Integration
-Documentation
-Library code
---Bugfixes
---Python embedding enhancements
---Miscellaneous
---NetCDF Library
---Statistics computations
etc.

Note: One downside to using panels is that the content of the text contained in the panel will not show up in the search.  However,  I’m not sure the search functionality is particularly important for the Release Notes.

### Time Estimate ###
Less than 1 day

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Split between  accounts 2702691 and 2792542*

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required Lisa Goodrich
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by jprestop** [comment]
@lisagoodrich and I are reopening this issue because we have one more step that needs to be completed.  The build on ReadTheDocs is working fine, but the build in GitHub Actions is not.  The GHA run appeared to be successful, but was actually not successful. We are already aware of this problem and it will be fixed with the issue [Bugfix: Check the return status of the "make clean html" command in build_documentation.sh #2436](https://github.com/dtcenter/MET/issues/2436).  

The following needs to be added to this issue:

MET/.github/workflows/documentation.yml
add a line after these [lines 27 and 28](https://github.com/dtcenter/MET/blob/c38f68b6ebb26b317b92fb1b60be945b78f1dfe4/.github/workflows/documentation.yml#L27). Make sure it is correctly indented.

> python -m pip install -r docs/requirements.txt

It should look like this:
```
          python -m pip install --upgrade python-dateutil requests sphinx \
          sphinx-gallery Pillow sphinx_rtd_theme sphinx-panels
          python -m pip install -r docs/requirements.txt
```

**Comment by lisagoodrich** [comment]
I have updated the issue information with the steps needed to make sure the dropdown menus run correctly.
