### ISSUE TITLE
Add pcp_combine example to MET Users' Guide

### ISSUE THREAD

**Issue by mollybsmith-noaa** [dtcenter/MET#2151]
## Describe the Task ##
I would like to add an example to the users' guide for the `pcp_combine -subtract` option with a list of files. I just used it for the first time and I could not get the syntax right until I found it way down in https://github.com/dtcenter/METplus/discussions/1138. All of the current examples in the users’ guide are either for `-sum` or else only have one file involved instead of a list. Something like:
`pcp_combine -subtract 2022043018_48.grib2 'name="APCP"; level="A48";' 2022043018_36.grib2 'name="APCP"; level="A36";' sample_fcst.nc`

### Time Estimate ###
15 minutes

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update log messages for easier debugging.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.
