### ISSUE TITLE
Enhance MET to handle CF-compliant time strings with an offset defined in months or years.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#2155]
## Describe the Enhancement ##
This issue arose via GitHub discussions dtcenter/METplus#1604 and an enhancement to the MET's support for CF-compliant NetCDF files is needed to read WOA climatology files. This enhancement supports development of the NOAA/EMC EVS verification system.

As of MET version 10.1.0, processing CF-compliant data with times defined with a months or years offset results in this warning message.
```
WARNING: parse_cf_time_string() -> Unsupported time step in the CF convention time unit "months since 1955-01-01 00:00:00"
```
And MET uses sets the valid time to unixtime 0 which is Jan 1, 1970.

The "months" offset is commonly used for climatology data and climate simulations, and this short-coming has come up a few times in the past. 

The use of months is discouraged since they vary. According to this section of the [CF-convention documentation](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.9/cf-conventions.html#time-coordinate), 1 year = 365.242198781 days and 1 month = 1 year / 12. So 1 month = 30.436 days.

However, I recommend against implementing this logic. Instead, let's implement the logic that users actually intend and expect. For example, when time is defined as a value of 377.5 with the string "months since 1955-01-01 00:00:00"...
- Use integer division to convert 377.5 to 31 years + 5 months + 15 days.
- Increment the year from 1955 to 1986.
- Increment the month from 01 to 06.
- Increment the day from 01 to 15.

The last step is confusing. Modelers use 0.5 month to mean the 15th of the months rather than an offset of 15 days (01 + 15). Need to think about that one.

@hsoh-u also ask how to handle these cases, where the compute time does not actually exist?
Another issue is what if the start day is 29, 30 or 31.
"month since 2020-01-29 00:00:00"
"month since 2020-01-31 00:00:00"
30, Feb
31, Apr

We'd need to define logic for handling these edge cases.

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
No sub-issues needed.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
2773542 (was 2793541)

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
No impacts.

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by hsoh-u** [comment]
To support the string value for slicing, MET needs to find the vertical level variable. 
- CF uses the axis variable attribute. MET supports the NETCDF with the variable whcih has "axis" attribute, "Z" for the vertical level.
- If there is a pre-defined variable name for the vertical (pressure) level, please let us know. MET can support it
- The vertical level variable can be found by looking at the dimension name from the data variable. But multiple variables can be identified as vertical level. This will be implemented later.

```
dimensions:
        y = 337 ;
        x = 451 ;
        z = 51 ;
        name_len = 32 ;
        time = 1 ;
variables:
        double z(z) ;
                z:standard_name = "altitude" ;
                z:long_name = "flight_level" ;
                z:units = "feet" ;
                z:positive = "up" ;
                z:axis = "Z" ;

        float edr(time, z, y, x) ;
                edr:units = "m^(2/3) s^-1" ;
                edr:long_name = "Eddy dissipation rate" ;
                edr:coordinates = "lat lon" ;
                edr:_FillValue = -9999.f ;
                edr:grid_mapping = "grid_mapping" ;
```

**Comment by hsoh-u** [comment]
MET supports non-integer offset (for example, 0.5 for day = 60*60*24*0.5 seconds, or 0.5 hour = 60*60*0.5 seconds) and the leap year. MET will convert the unit month and year following ways:

1. non-integer offsets to the nearest offsets
    - 0.6 month to 1 month
    - 2.5 years to 3 years. not 30 months (1 year = 12 month, 2.5 * 12 months = 30 months)
2. non existing day to the last day of the month
    - yyyy-04-31 to yyyy-04-30

**Comment by hsoh-u** [comment]
- For month
  1. get integer part and add it to target month (adjust year if necessary)
  2. get fractional part and get the nearest day after multiplying 30
  3. add it to target day (**do not adjust month**, change day to the last day of the month if necessary)
- For year
  1. get integer part and add it to target year
  2. get fractional part and get the nearest month after multiplying 12
  3. add it to target month (and adjust year and day if necessary)

Examples:
```
units = "months since 1955-01-01 00:00:00"
1.5 month ==> "1955-02-16 00:00:00"
  + Add 1 months to the base time: "1955-02-01 00:00:00"
  + Add 15 days (0.5 * 30 = 15): "1955-02-16 00:00:00"
3.33 month == > "1955-04-11 00:00:00"
  + Add 3 months to the base time: "1955-04-01 00:00:00"
  + Add 10 days (0.33 * 30 = 9.9 days to 10 days): "1955-04-11 00:00:00"

units = "years since 1955-01-01 00:00:00"
3.5 year ==> "1958-07-01 00:00:00"
  + Add 3 years to the base time: "1958-01-01 00:00:00"
  + Add 6 months (0.5 * 12 = 6): "1958-07-01 00:00:00"
3.3 year ==> "1958-05-01 00:00:00"
  + Add 3 years to the base time: "1958-01-01 00:00:00"
  + Add 4 months (0.3 * 12 = 3.6 months to 4 months): "1958-05-01 00:00:00"
```

**Comment by j-opatz** [comment]
I think the approach stated above, 

```
The other approach for non-integer value will be

    For month
        get integer part and add it to target month (adjust year if necessary)
        get fractional part and get the nearest day after multiplying 30
        add it to target day (do not adjust month, change day to the last day of the month if necessary)
    For year
        get integer part and add it to target year
        get fractional part and get the nearest month after multiplying 12
        add it to target month (and adjust year and day if necessary)
```

Seems like good logic. However, there's two issues I want to raise.

In the last example, 3.3 years is evaluated to 1958-07-01. However, that seems like it's slightly further in time than might be desired. 

After adjusting the base time by 3 years, the remainder (0.3) is multiplied by 12 with a resulting 3.6 months. To me, that means the months should be incremented by 3 rather than 4, and there needs to be an increment of days as well. Using the logic of `months_since`, would it be possible to take that remainder and multiply it by 30 to increment the days by 9? Any further down the time stamp than that (e.g. taking the 2nd example's remainder of 0.33 and needing to change the hours in addition to changing the times) seems too picky.

John HG mentioned that 

>Modelers use 0.5 month to mean the 15th of the months rather than an offset of 15 days (01 + 15). Need to think about that one.

I noticed that in the logic provided, 1.5 months goes to the 16th of the month. Do we need a special logic case where a remainder of 0.5 always takes the days to the 15th of whatever month is evaluated to?

**Comment by hsoh-u** [comment]
Need a decision for the algorithm:  Day for 0.5 month
What's the scientific preference: "2020-03-15" or "2020-03-16"?
  - date=0.0, 0.5, 1.0. 1.5, 2,0. 2.5, 2.0 with units = "month  since 2020-03-01 00:00:00"
  - which one?
    - 2020-03-01, 2020-03-15, 2020-04-01, 2020-04-15, 2020-05-01,  2020-05-15
    - 2020-03-01, 2020-03-16, 2020-04-01, 2020-04-16, 2020-05-01,  2020-05-16

Assuming for month and year units:
- 1 month = 30 days (1 year = 360 days)
- DO NOT use nearest day/month
  - 3.5 days is 3 days, NOT 3 days plus 0.5 * 24 hours
  - 3.5 months is 3 months plus (0.5 * 30) days
- Only month and day units are updated for month unit
- Only year, month, and day units are updated for year unit
- When day is updated, the month is not adjusted. Set the last day of the month instead of updating month

Algorithm.
- For month
  - get an integer part and add it to the target month (adjust year if necessary)
  - get a fractional part and multiply 30 days
  - add an integer part of additional days to the target day (do not adjust month, change day to the last day of the month if necessary)
- For year
  - get an integer part and add it to the target year
  - get fractional part and multiply 12 months
  - get an integer part and add it to the month (adjust year in necessary)
  - get a fractional part and multiply 30 days
  - get an integer part and add it to the day (do not adjust month, change day to the last day of the month if necessary)

Examples:
```
- 3.33 months = 3 months + 9 days 
  + 3.33 months = (3 + 0.33) months
  + 0.33 months = (0.33 * 30) days = 9.9 days = int(9.9) days = 9 days
- 3.66 months = 3 months + 19 days 
  + 3.66 months = (3 + 0.66) months
  + 0.66 months = (0.66 * 30) days = 19.8) days = int(19.8) days = 19 days

units = "months since 1955-01-01 00:00:00"
3.33 month == > "1955-04-10 00:00:00"
  + Add 3 months to the base time: "1955-04-01 00:00:00"
  + Add 9 days (0.33 * 30 = 9.9 days to 9 days): "1955-04-10 00:00:00"
3.66 month == > "1955-04-20 00:00:00"
  + Add 3 months to the base time: "1955-04-01 00:00:00"
  + Add 19 days (0.66 * 30 = 19.8 days to 19 days): "1955-04-20 00:00:00"

units = "years since 1955-01-01 00:00:00"
3.5 year ==> "1958-07-01 00:00:00"
  + Add 3 years to the base time: "1958-01-01 00:00:00"
  + Add 6 months (0.5 * 12 = 6): "1958-07-01 00:00:00"
3.33 year ==> "1958-04-29 00:00:00"
  + Add 3 years to the base time: "1958-01-01 00:00:00"
  + Add 3 months (0.33 * 12 = 3.96 months to 3 months): "1958-04-01 00:00:00"
  + Add 4 months (0.96 * 30 = 28.8 days to 28 days): "1958-04-29 00:00:00"

```

**Comment by hsoh-u** [comment]
Decision for 0.5 month: set the day to 15:
- 0.5 month since 2022-03-01 00:00:00" ==> "2022-03-15 00:00:00"
- 0.5 month since 2022-02-01 00:00:00" ==> "2022-02-15 00:00:00"
  - Note: not  "2022-02-14 00:00:00"

- 0.5 month since 2022-03-02 00:00:00" ==> "2022-03-16 00:00:00"
- 0.5 month since 2022-02-02 00:00:00" == >"2022-02-16 00:00:00"

**Comment by hsoh-u** [comment]
Is it OK not to support negative offsets, like -4.5 month or -10 years?
No technical issues on supporting the negative offsets. Just checking before implementing it.
If this is acceptable, MET will give an error message and quit.

**Comment by hsoh-u** [comment]
Two options to support negative offsets
- Option 1 (-4.3 month):
  - move 4 months back
  - move (0.3\*30) days back (set to 1 if less than 1)
- Option 2 (-4.3 month):
  - move 5 months back
  - move ((1-0.3)\*30 = 0.7\*30) days forward (set to last day of month if necessary)

**Comment by j-opatz** [comment]
> Is it OK not to support negative offsets, like -4.5 month or -10 years? No technical issues on supporting the negative offsets. Just checking before implementing it. If this is acceptable, MET will give an error message and quit.

I think it's OK to ignore negative offsets for time. I've never seen it used before and can't imagine a situation where it would be appropriate.

**Comment by hsoh-u** [comment]
Modified to handle the case when the start day (the reference day) is not the first day of the month.
Note: **use nearest day**, no exceptional calculation for February

1. months unit
- when the start day is the first of the month (most common cases)
  - add months from the integer part
  - case 1: 0.5 month is just changing the day to 15
  - case 2: otherwise adds nearest days from the fractional part (times 30 days), but do not update month and adjust to the end of the month if necessary
- when the start day is not the first of the month (few cases)
  - no special meaning for 0.5 month
  - add months from the integer part
  - add the nearest days to the target day from the fractional part (times 30 days)
    - case 1: the target day is equal or less than day 30 (for example, reference time is "months since 2020-02-05")
      - keep the target day (do not update month & adjust day if necessary)
        - for example: day 5 + (0.6 month \* 30 days) = day 5 + 18 days = day 23 
          - calculated day: 2020-02-23
    - case 2:  the target day is greater than day 30 (for example, reference time is "months since 2020-02-05")
      - add one month
      - the target day is subtracted by 30 days
        - for example, day 5 + 0.9 month = day 5 + (0.9 month \* 30 days) = day 5 +  27 days = day 32 
          - day 32 - 30 days = day 2
          - calculated day: 2020-03-02

2. years unit
- add years from the integer part
- months comes from the fractional part times 12 months
- Repeat above algorithm for months
