### ISSUE TITLE
Add M_to_KFT and KM_to_KFT functions to ConfigConstants.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#2180]
## Describe the Task ##
This issue arose during the METplus NOAA telecon on 6/13/2022. @LoganDawson-NOAA requested that we add two new conversion functions to MET's default ConfigConstants file:
```
 M_to_KFT(x) = x * 3.28084 * 0.001;
KM_to_KFT(x) = x * 3280.84 * 0.001;
```
He references these when doing verification of echo tops, and having them be defined by default is more convenient than hard-coding the functions or re-defining them in each METplus configuration file.

### Time Estimate ###
1 hour

### Sub-Issues ###
Consider breaking the task down into sub-issues.
No sub-issues needed.

### Relevant Deadlines ###
Please fix in both the develop and main_v10.1 branches so that they'd be included in any future bugfix releases.

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required: Recommend that @LoganDawson-NOAA review the pull requests.

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
No impacts.

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
