### ISSUE TITLE
gen-ens-prod: add option to ensemble_flag in config file to output user-chosen percentile or standard anomaly value field

### ISSUE THREAD

**Issue by Jeff-Duda** [dtcenter/MET#2197]
## Describe the New Feature ##

Request a new config file option be added so that a user can choose any specific and arbitrary statistical ensemble threshold exceedance field to be generated. That is, add a feature so that the config file changes from this:

> 
> ensemble_flag = {
>   latlon    = TRUE;
>        mean      = TRUE;
>        stdev     = TRUE;
>        minus     = TRUE;
>        plus      = TRUE;
>        min       = TRUE;
>        max       = TRUE;
>        range     = TRUE;
>        vld_count = TRUE;
>        frequency = TRUE;
>        nep       = FALSE;
>        nmep      = FALSE;
>        climo     = FALSE;
>        climo_cdp = FALSE;
> }

to this

> ensemble_flag = {
>   latlon    = TRUE;
>        mean      = TRUE;
>        stdev     = TRUE;
>        minus     = TRUE;
>        plus      = TRUE;
>        min       = TRUE;
>        max       = TRUE;
>        user_spec = TRUE;
>        range     = TRUE;
>        vld_count = TRUE;
>        frequency = TRUE;
>        nep       = FALSE;
>        nmep      = FALSE;
>        climo     = FALSE;
>        climo_cdp = FALSE;
> }
> 

Where _user\_spec_ can be defined as either a percentile value of the ensemble distribution or a standard anomaly of the ensemble distribution (expressed in units of sigmas or "standard deviations above/below the mean or climo value". For example, at an above point in the **GenEnsProdConfig_default** file, you could have the new entries:

ENS_PCT_THRESH = 75
ENS_SIGMA_THRESH = -2.5

To select either the 75th percentile of the input ensemble distribution OR the 2.5 standard deviations below the mean as threshold values for exceedance to calculate a custom probabilistic field value to be output with the yes/no decision to include this field in the output file controlled by the user_spec entry in ensemble_flag{}. NOTE: only one of these options can be chosen - either the first one entered or error/quit gen-ens-prod if both are specified.

NOTE: there should be no need to specify logical relations in either value since probability fields are supplementary (i.e., probabilities all sum to 1.0, so in the example of ENS_PCT_THRESH = 75, the default would be to specify exceedance of the ensemble 75th percentile value, but the user could plot 1 - field to plot non-exceedance of the ensemble 75th percentile value to get the logical supplement to this event)

### Time Estimate ###
<1 hour

### Sub-Issues ###
single issue

### Relevant Deadlines ###
NONE

### Funding Source ###
NONE

### Assignee ###
No engineer required
No scientist required

### Labels ###
gen-ens-prod
lowest priority
requestor: Jeff Duda

### Projects and Milestone ###
No projects or milestones depend directly on this feature

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
Issue may affect METviewer and/or METplotpy for plotting ensemble statistics fields

## New Feature Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
