### ISSUE TITLE
Eliminate Gen-Ens-Prod warning when parsing the nbhrd_prob dictionary

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#2224]
## Describe the Enhancement ##
This issue was raised by the DTC Ensembles team. When running Ensemble-Stat via METplus, the following WARNING message appeared:
```
WARNING:
WARNING: Dictionary::lookup_int() -> integer lookup failed for name "field"
WARNING:
```

I traced through the logic and found the following:

- Gen-Ens-Prod parses the nbrhd_prob dictionary from the config file [here](https://github.com/dtcenter/MET/blob/1f26c5524939021ff5d7c1606546e4b4625ebfde/data/config/GenEnsProdConfig_default#L73).
- It calls [parse_conf_nbrhd()](https://github.com/dtcenter/MET/blob/0cbdd5f97437990e1ab4642d85de277a99242792/met/src/basic/vx_config/config_util.cc#L1654) to do so.
- That calls [lookup_int()](https://github.com/dtcenter/MET/blob/0cbdd5f97437990e1ab4642d85de277a99242792/met/src/basic/vx_config/config_util.cc#L1669) for the "field" entry.

But "field" is NOT included in the default nbrhd_prob dictionary, so that entry will not in general be found.

However the config file logic continues searching higher and higher levels of context. When "field" is found at one of those higher levels of context this warning message is triggered.

For example, adding the following to the Ensemble-Stat config file triggers the warning:
```
field = { name = "BAD"; level = "BAD"; }
```

Recommend writing/using a specific parse_conf_nbrhd_prob() function instead of reusing parse_conf_nbrhd().

### Time Estimate ###
2 hours.

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
None needed.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: @JohnHalleyGotway 
- [x] Select **scientist(s)** or **no scientist** required: None needed

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
No impacts.

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
