### ISSUE TITLE
Refine NetCDF level string handling logic to always interpret @ strings as values

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#2225]
## Describe the Enhancement ##
#1815 enhanced MET-11.0.0-beta2 to support the specification of NetCDF level strings with the VALUE of the dimensions rather the just the INDEX of the dimensions. @robdarvell tested out this new functionality in beta2 and provided feedback to refine the functionality.

For a variable with a dimension that contains 24 levels, he requested `level='(@23,*,*)';`. He expected this call to fail since the corresponding coordinate variable does NOT contain a value of 23. However running plot_data_plane in this way ran without error and it just used 23 as the INDEX for that dimension.

Recommend that we tweak the logic for parsing these levels strings. If the sting begins with an '@' character always interpret it as a VALUE and never as an INDEX.

It is not clear to me how the converse should be handled. For simplicity, should the lack of an '@' character force the interpretation to be as an INDEX and not a VALUE? The issue here is the time dimension. MET version 10.1.0 allows for the time dimension to be specified as a formatted string. For for this NetCDF variable `data(time,lat,lon)` the `level='(20220807_120000,*,*)';` string correctly retrieves the data. In MET 11.0.0-beta2, `level='(@20220807_120000,*,*)';` now also works.

@hsoh-u can we make the presence of the leading @ character optional for time strings to preserve backward compatibility?
But make their presence required when specifying values for non-time strings?

@robdarvell any opinion on this detail?

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
No sub-issues needed.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*
2799991

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required: @robdarvell should review

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
No impacts.

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by hsoh-u** [comment]
There are two exceptional handling:
- with @: if the value does not match, the value is applied as offset (which is described in this issue)
- without @: the index is out of range, the index is applied as value (for example, two vertical levels, i.e  dimension is 2, and values are 2000 and 34768). level="(2000,\*,\*)" is accepted (processed as (@2000,\*,\*)).

Both cases will not be supported.

**Comment by robdarvell** [comment]
Thanks for looking into this question.
With regards to the 'levels' aspect of the netcdf array, how I envisaged this change would work (when setting out my initial testing from building Beta2) was:
 - If you included the @ symbol then it would just search for the (pressure) level value indicated within the netcdf file, and would fail if this was not found
 - If you did not include the @ symbol then it would just search the index size of the array for the value entered and it would fail if it was a larger number than feasible.
 
 But there is also the time setting aspect. That is not something which I have considered using, but backward compatability should be maintained if at all possible.
