### ISSUE TITLE
Add a GHA workflow to update regression test reference branches that can be manually triggered.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#2230]
## Describe the Enhancement ##
It is often the case that new development either changes the output for existing tests or adds new output for new unit tests. Both cases are flagged as differences in both the nightly build regression test and those performed via GHA.

When those diffs are flagged, we manually inspect them to confirm that they are expected. And then we manually submit a pull request to update the reference branch to *accept* those changes as being expected and desired. Changing the reference branch prevents those diffs from being flagged in future development.
  - Examples of updating [develop-ref](https://github.com/dtcenter/MET/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Aclosed+%22Update+develop-ref%22+).
  - Examples of updating [main_v10.1-ref](https://github.com/dtcenter/MET/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Aclosed+%22Update+main_v10.1-ref%22+).

This task is to provide a new GHA workflow to handle these updates. This workflow would only be manually triggered, not run automatically. It would take several required inputs that would include
  - Branch to be updated. For example, selecting develop would merge develop into develop-ref.
  - List of PR's that triggered the differences. These used to the name the PR: "Update develop-ref after #NNNN, #NNNN"
  - Details to be included in the body of the PR.

The job would:
  - Checkout {branch} and {branch}-ref. If either don't exist, error out.
  - Merge {branch}-ref into {branch} using -s OURS option.
  - Create a PR to merge {branch} into {branch}-ref.

The actual approval of the PR and merging should be done manually (at least initially).

### Time Estimate ###
1 day.

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
None.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
Note that this functionality was recently added to METplus:

Each time a pull request changes (adds, removes, modifies) the output of one of the unit tests run by the testing workflow, the difference causes the GHA testing workflow to fail. This is desired, and it is the job of the developer/PR reviewer to confirm that the flagged differences really are expected based on the code changes. After rectifying the differences, we submit a pull request to update the reference truth data branch (i.e. develop-ref or main_v11.0-ref) to move past the diffs.

The update_truth GHA workflow in METplus facilitates this process. Recommend migrating this logic over to MET and ask @georgemccabe for support as needed.
