### ISSUE TITLE
Add support in Point2Grid for additional interpolation methods

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#2245]
## Describe the Enhancement ##
This issue arose via dtcenter/METplus#1768. None of the existing interpolation methods (min/max/median/uw_mean) are appropriate for categorical data such as precipitation type. Recommend enhancing Point2Grid to keep track of the distance between each observation location and the nearest grid point. But consider only doing so for `-method nearest` and `-method dw_mean` to avoid increasing the runtimes in general. Use the distance information to add support for these two interpolation methods.

Also, review other interpolation methods supported by other MET tools to see if any other can be easily added. Specifically, supporting `-method mode` would be useful for categorical data such as precipitation type.

### Time Estimate ###
2 days.

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
None needed.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
- [ ] May need a METplus issue to make this more configurable... or maybe not?

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
Feedback from [cjmelick](https://github.com/cjmelick) on discussion dtcenter/METplus#1768. 

I did think of something to incorporate if going down the path of better capturing artifacts of gridding categorical variable observations. It would be advantageous to give counts for each category value, kind of like you are doing already for specifying the number of records nearby for the variable for each grid point. I guess in that case there might be a flag to switch on and off just for this purpose.

Thanks,
Chris
