### ISSUE TITLE
Enhance Series-Analysis to compute statistics from the SEEPS STAT line type.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#2269]
## Describe the Enhancement ##
- MET #1942 enhanced Point-Stat to write the SEEPS and SEEPS_MPR line types when verifying against point observations.
- MET #1943 will enhance Grid-Stat to write the SEEPS line types when doing grid-to-grid comparisons. Also consider writing SEEPS_MPR information to the "_ncpairs.nc" output file.
- This issue is to extend that grid-to-grid SEEPS vx logic to Series-Analysis as well.

The SEEPS output from Point-Stat and Grid-Stat is configured by setting the corresponding `output_flag.seeps` and `output_flag.seeps_mpr` flags. In Series-Analysis, we'll need to add a setting for `output_stats.seeps`. This is an array of column names for the SEEPS statistics that should be written to the output.

Recommend supporting all SEEPS output columns:
```
output_flag = {
   seeps = ["TOTAL", "S12", "S13", "S21", "S23", "S31", "S32", "PF1", "PF2", "PF3", "PV1", "PV2", "PV3", "MEAN_FCST", "MEAN_OBS", "SEEPS" ];
}
```
But please confirm with @RachelNorth that this is correct.

Note that the column names mentioned above have been modified by #2882. Review those changes and update the description above prior to beginning this work.

### Acceptance Testing ###
*List input data types and sources.*
*Describe tests required for new functionality.*

### Time Estimate ###
*Estimate the amount of work required here.*
Unknown

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
Complete this work prior to the end of the Met Office contract at the end of March 2025.

### Funding Source ###
Not specified.

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: @JohnHalleyGotway
- [x] Select **scientist(s)** or **no scientist** required: @RachelNorth and @j-opatz 

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority** medium-to-high
- [x] Select **requestor(s)** UK Met Office

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
- [ ] Add METplus issue to support this new `output_stats.seeps` configuration option.

## New Feature Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
As discussed with @mpm-meto on 9/20/24, reassigning this issue to the beta2 cycle of the MET-12.1.0 release, to be completed between January - March of 2025. Marking this as required for that development release. However, before doing this work, check with @j-opatz to confirm that sufficient funding remains to support it.
