### ISSUE TITLE
Update the SonarQube version used for routine software scans.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#2270]
## Describe the Task ##
On 9/14/22, folks from SonarSource informed us of a new SonarQube version. See email below.

This task is to update the version of SonarQube we're running for our routine scans. This will impact the development environment for seneca, as defined in [this file](https://github.com/dtcenter/MET/blob/develop/internal/scripts/environment/development.seneca).

Email:

Will you upgrade to a current SonarQube release?
See our recent news below, if you have any questions, please ask.

SonarQube 9.6 [download](https://www.sonarqube.org/downloads/) [announcement](https://www.sonarqube.org/sonarqube-9-6/)  [Release](https://community.sonarsource.com/t/sonarqube-9-6-released/69842) Notes: [Check Here](https://sonarsource.atlassian.net/browse/SONAR-17180?jql=project%20%3D%2010139%20AND%20fixVersion%20%3D%2012633)  + Rich content for Security rules,
Go here to [Version Upgrade ](https://docs.sonarqube.org/latest/setup/upgrade-notes/) and [Upgrade](https://docs.sonarqube.org/latest/setup/upgrading/)  to a supported version.

[PCI](https://docs.sonarqube.org/latest/user-guide/security-reports/) / DSS Reports and Regulatory reports in SQ 9.6 
Set Expiration on [Tokens](https://docs.sonarqube.org/latest/setup/upgrade-notes/), SAML Assertion Encryption,
Kubernetes support, rules to find misconfiguration, [here](https://community.sonarsource.com/t/6-rules-to-find-security-misconfigurations-in-your-kubernetes-files/68965/3)  
Java analyzer detects Passwords and [Secrets](https://community.sonarsource.com/t/the-java-analyzer-detect-secrets-hidden-in-your-java-files/64295) in SonarQube 
Roadmap follow and post suggestions: [SonarLint](https://www.sonarlint.org/roadmap) and [SonarQube](https://portal.productboard.com/sonarsource/3-sonarqube/tabs/12-planned-for-9-1)

### Time Estimate ###
4 hours (?)

### Sub-Issues ###
Consider breaking the task down into sub-issues.
None needed.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
2771021 - Air Force METplus

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: @hsoh-u 
- [ ] Select **scientist(s)** or **no scientist** required: None required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
No impacts.

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by hsoh-u** [comment]
SonarQube is updated:
- SonarServer at mandan: 9.6.1.59531 (was 8.9.6.50800)
- sonar-scanner at seneca: 4.7.0.2747 (was 4.6.2.2472)
- build-wrapper at seneca: 6.37 (was 6.20)
