### ISSUE TITLE
Enhance Regrid-Data-Plane to regrid multiple levels in a single run

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#2275]
## Describe the Enhancement ##
This issue was discussed during a MET team meeting and is mentioned in [these notes](https://docs.google.com/document/d/1KWRiC45zLQXSra85_RoTyzHP84TVbtOjTxdR3a7w1Io/edit). The `-field` command line option of the regrid_data_plane tool specifies which 2D field should be regridded to the target grid. While the `-field` option can be used multiple time to specify multiple fields, each entry is processed as a single 2D field.

This issue is to enhance regrid_data_plane to regrid a volume of data consisting of multiple levels rather than just 2D slices. For example, support the specification of `-field 'name="TMP"; level="P500-1000";` instead of `-field 'name="TMP"; level="P500";' -field 'name="TMP"; level="P600"'`, and so on.

While the description sounds rather simple, the implementation details can get tricky. The current option `-field 'name="TMP"; level="P500";'` creates a 2D output NetCDF variable named `TMP_P500`. One approach would be doing basically the same thing for multiple levels, creating multiple 2D output NetCDF variables named `TMP_P500`, `TMP_P600`, and so on.

However, writing a 3D NetCDF output variable named `TMP(level,*,*)` would likely be preferable. This would also represent a small step toward making the MET NetCDF files more closely aligned with the NetCDF CF-conventions. However, it doing this option, we'd also need to make sure that downstream MET tools can actually read this output! If not, we'd need to update the MET NetCDF library to do so.

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
None needed.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required: @CPKalb 

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
Likely no impacts.

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
