### ISSUE TITLE
Fix MET-11.0.0-beta3 linker errors

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#2281]
## Describe the Enhancement ##
@robdarvell reported compilation problems on the UK Met Office Cray machine for both MET versions 11.0.0-beta2 and 11.0.0-beta3. The beta2 issue resulted in dtcenter/MET#2255 which was fixed for beta3. However, the larger issue of more proactively testing for internal linker issues was not solved. @robdarvell reports a linker error when compiling the GSI Tools related to the newly added -lvx_seeps library.

This issue consists of multiple tasks.
1. Compile MET version 11.0.0-beta3, as released, in such a way to replicate the linker error reported by the Met Office. This may be done using older versions of compilers and linkers, potentially via Docker containers.
2. Once successful, consider if/how that test could be automated via GitHub actions to ensure future development does not introduce additional linker issues. This test should be run at least once prior to each release.
3. Once the error can be replicated, modify the offending Makefile.am files to fix it.

### Time Estimate ###
Unknown

### Sub-Issues ###
Consider breaking the task down into sub-issues.
None needed.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
2792541

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: @jprestop 
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
