### ISSUE TITLE
Fix GHA warnings and update the version of actions (i.e. actions/checkout@v3)

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#2297]
## Describe the Task ##
Based on [this article](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/), we need to prepare all of our GitHub actions to run on Node 16 rather than Node 12. This is easily done by switching from `uses: actions/checkout@v2` to `uses: actions/checkout@v3`.

In addition, several warning messages also appeared in this recent GHA run:
https://github.com/dtcenter/MET/actions/runs/3236125880

This task is to update to `checkout@v3` and check for/debug/resolve any additional GHA warnings.

### Time Estimate ###
1-2 hours

### Sub-Issues ###
Consider breaking the task down into sub-issues.
None

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: @JohnHalleyGotway 
- [x] Select **scientist(s)** or **no scientist** required: not needed

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
No direct impacts, but similar changes are needed in other METplus repos.

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update log messages for easier debugging.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
Based on https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files
Also need to update our use of set-output.
FROM: `echo ::set-output name=run_compile::$run_compile`
TO: `echo "run_compile=${run_compile}" >> $GITHUB_OUTPUT`

**Comment by JohnHalleyGotway** [comment]
The trigger METplus action is still not working as seen in [this run](https://github.com/dtcenter/MET/actions/runs/3237047363/jobs/5303626888):
```
RUNNING: docker build -t dtcenter/met-dev:refs/heads/develop-lite --build-arg SOURCE_BRANCH --build-arg MET_BASE_REPO --build-arg MET_BASE_TAG -f /home/runner/work/MET/MET/internal/scripts/docker/Dockerfile.copy /home/runner/work/MET/MET
...
ERROR: 'docker build -t dtcenter/met-dev:refs/heads/develop-lite --build-arg SOURCE_BRANCH --build-arg MET_BASE_REPO --build-arg MET_BASE_TAG -f /home/runner/work/MET/MET/internal/scripts/docker/Dockerfile.copy /home/runner/work/MET/MET' exited with status = 125
```
Compare to a previously [successful run](https://github.com/dtcenter/MET/actions/runs/3191983526/jobs/5208937579):
```
RUNNING: docker build -t dtcenter/met-dev:develop-lite --build-arg SOURCE_BRANCH --build-arg MET_BASE_REPO --build-arg MET_BASE_TAG -f /home/runner/work/MET/MET/internal/scripts/docker/Dockerfile.copy /home/runner/work/MET/MET
```
So `develop-lite` has become `refs/heads/develop-lite`. Need to fix this.
