### ISSUE TITLE
Move release notes into its own chapter in the User's Guide

### ISSUE THREAD

**Issue by jprestop** [dtcenter/MET#2298]
## Describe the Task ##
Move the [MET Release Notes](https://met.readthedocs.io/en/develop/Users_Guide/overview.html#met-release-notes) section out of the Overview chapter and into it's own chapter (under Overview - the Release Notes will become chapter 2). Rename in the following way:

- 1.5 MET Release Notes -> 2 MET Release Information
- Modify the index.rst file to add the new chapter "release-notes" after "overview"
- Create a new 2.1 section called MET Release Notes 
- The existing information in current sections in 1.5.1 - 1.5.3 should be moved to 2.1.1 - 2.1.3. 
- Create a new 2.2 section called MET Upgrade Instructions (with paragraph text "Upgrade instructions will be listed here if they are applicable for this release.")

This work will require changing the types of headers to follow the standard guidelines:
https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html
```
# with overline, for parts
* with overline, for chapters
=, for sections
-, for subsections
^, for subsubsections
“, for paragraphs
```

### Time Estimate ###
<1 day

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
MET-11.0.0-beta4 release

### Funding Source ###
2792541

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update log messages for easier debugging.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.

**Comment by lisagoodrich** [comment]
My feature branch is :  feature_2296_release_notes_move

On the pull request I linked to [Move release notes into its own chapter #2298](https://github.com/dtcenter/MET/issues/2298). Please note the numbers are different.  I didn't know how to handle this.

**Comment by lisagoodrich** [comment]
Work is completed.
