### ISSUE TITLE
Add MAE to the ECNT line type from Ensemble-Stat and for HiRA

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#2325]
## Describe the Enhancement ##
This is a short-fuse request from NOAA/EMC that arose during the NOAA METplus User telecon on 10/31/22. This task is to enhance the ECNT line type to include the MAE of the ensemble mean in the output. The existing ECNT line type includes ME and RMSE but not MAE. Since the ME/RMSE output is provided for both unperturbed and perturbed ensemble means, consider doing the same for MAE. While NOAA/EMC, only needs the unperturbed version, we might as well be consistent with existing outputs.

Note that the plan is to add this for MET-11.0.0-beta4 which was actually released yesterday.

So part of this issue will be deleting/recreating that development release.

### Time Estimate ###
4 hours.

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
None needed.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: @JohnHalleyGotway 
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by BinbinZhou-NOAA** [comment]
Based on the new ECNT table in the document of MET_110.0.0_beta4, I have checked MAE values in 
the ECNT line type from the tested output stat files  on HERA. Since there is no reference, I used
Yan's verification plots (from EMC Verification page). The results show that the MAE values in
the new  ECNT are very closed to Yan's plots for all fields.
