### ISSUE TITLE
Rename the TCDIAG SOURCE column as DIAG_SOURCE

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#2337]
## Describe the Task ##
dtcenter/METdataio#131 updates the schema to load the TCDIAG line type into the database. However @venitahagerty notes that the INDEX and SOURCE column names in the TCDIAG line type cause a namespace conflict with reserved database names.

We discussed this at the 20221109 METplus Analysis tools meeting and decided:
1. Since INDEX appears in several MET output line types, keep its name as-is and follow the paradigm used for the TCMPR line type and store it with the name `pair_index`.
2. Since SOURCE does not appear in any other MET output line type, we have flexibility in what name we choose. Rename it to DIAG_SOURCE since @venitahagerty is loading it into a database using the same name.

And that's the task for this issue, renaming the TCDIAG SOURCE column as DIAG_SOURCE.

### Time Estimate ###
2 hours.

### Sub-Issues ###
Consider breaking the task down into sub-issues.
None needed.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
TCDIAG project funding 2770043

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: @JohnHalleyGotway 
- [x] Select **scientist(s)** or **no scientist** required: not needed

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
None.

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by venitahagerty** [comment]
I don't think it makes a difference to MET, but just for consistency, noting that the MySQL field name in line_data_tcmpr and line_data_tcdiag for the index is index_pair.
