### ISSUE TITLE
Enhance Stat-Analysis to aggregate SEEPS_MPR and SEEPS line types.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#2339]
## Describe the Enhancement ##
- MET #1942 enhances Point-Stat to write the SEEPS and SEEPS_MPR line types when verifying against point observations.
- MET #1943 enhances Grid-Stat to write the SEEPS line types when doing grid-to-grid comparisons. Also consider writing SEEPS_MPR information to the "_ncpairs.nc" output file.
- This issue is to enhance Stat-Analysis to aggregate these new line types as described below:

1. `-job aggregate -line_type SEEPS`
2. `-job aggregate_stat -line_type SEEPS_MPR -out_line_type SEEPS`

### Acceptance Testing ###
*List input data types and sources.*
*Describe tests required for new functionality.*

### Time Estimate ###
*Estimate the amount of work required here.*
Unknown

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Funding Source ###
2799991

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: @JohnHalleyGotway
- [x] Select **scientist(s)** or **no scientist** required: @RachelNorth

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority** medium-to-high
- [x] Select **requestor(s)** UK Met Office

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
No specific METplus changes needed.
- [ ] Write METcalcpy issue to add support for aggregating SEEPS to a future release.

## New Feature Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
