### ISSUE TITLE
Add a new `derive` configuration option to summarize data across multiple levels

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#2359]
## Describe the New Feature ##
This feature request arose via dtcenter/METplus#1948 and is described in this [comment](https://github.com/dtcenter/METplus/discussions/1948#discussioncomment-4267404). It was requested in the context of the gen_ens_prod tool but could be applied widely across the MET tools. Recommend adding a new `derive` configuration option to specify how multiple levels of input data could be collapsed down into a single field. The name `derive` is consistent with the `-derive` command line option for pcp_combine and should provide the same functionality.

For example, the following settings would request all TMP levels between 500 and 1000mb from a GRIB input file and derive the mean for each column of data:
```
name = "TMP";
level = "P500-1000";
derive = "max";
```
Support the following type of derivations:
- sum, min, max, range, mean, stdev, vld_count, diff (but only when exactly 2 inputs are provided)

Similar to pcp_combine, by default, construct the output variable name as the input name followed by the operation (e.g. "TMP_max" for the example above).

Ensure that the `set_attr_` options (`set_attr_name` in particular) are applied to the resulting data, if provided.

Recommend requesting that Jeff Duda test this new functionality.

### Acceptance Testing ###
*List input data types and sources.*
*Describe tests required for new functionality.*

### Time Estimate ###
3 days?

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
- Check with METplus developers for how to make this configurable.

## New Feature Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
