### ISSUE TITLE
Documentation: Add content to the Contributor's Guide

### ISSUE THREAD

**Issue by jprestop** [dtcenter/MET#2360]
## Describe the Task ##
A Contributor's Guide outline was created with the [Create outline for a MET Contributor's Guide #1774](https://github.com/dtcenter/MET/issues/1774) issue.  We must still add content. 

See this [Planning Document](https://docs.google.com/document/d/1u13hVLYHh2KjtSuqj9T0wrLtHk-I5VMqDAwgE6B83aQ/edit#), which contains more information.

### Time Estimate ###
On-going

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ]  #2361
- [ ] See dtcenter/METplus-Internal#26
- [ ] Modernize MET's build system by switching from legacy Autotools to CMake #3225

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
TBD

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
Recommend doing this work during the MET-13.0.0-beta1 (version number naming?) development cycle, likely in mid-2025.
