### ISSUE TITLE
Enhance the logic for determining quality flags for time summaries of point observations.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#2363]
## Describe the Enhancement ##
While documenting MET's handling of quality flags for dtcenter/MET#2278, @JohnHalleyGotway found that that handling could be improved when computing time summaries of point observations. This step is preformed by calling common library code from the point pre-processing tools, including pb2nc, madis2nc, ascii2nc, and so on. As of MET version 11.0.0, the quality flag of the time summary observations is always stored by `summary_obs.cc` as being NA.

This issue is to enhance the time summary logic to provide more useful quality flag data.

MET supports the computation of several types of time summaries (min, max, range, mean, stdev, median, P##, sum). Recommend the following loigc:
- For min and max: Select the actual matching observation and report its quality flag string.
- For median, and P##: If the percentile corresponds to an actual observation, report its quality flag string. If its the average of 2 values, and those quality strings are numeric, report the maximum of their values.
- For the range: If the quality flags for the min/max are numeric, report the maximum of their values.
- For mean, stdev, and sum: If the quality flags are numeric, report the maximum of all values in the time window.

The question is what to do otherwise? If the quality flags are not numeric, should the output quality flag be "NA" or the most common string?

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
No impacts.

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
