### ISSUE TITLE
Enhance the point pre-processing tools to support data censoring and conversion

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#2377]
## Describe the Enhancement ##
During the [NOAA METplus User Telecon](https://docs.google.com/document/d/1LQGNj_1M5YjA3RGyB3GxOAZl8t1gnfbwUUobc08JAbs/edit) on 12/12/2022, the idea of supporting data censoring in the MET point pre-processing tools arose.

It would be useful when processing AirNow datasets in ascii2nc where observed concentration values can be reported as being slightly negative due to the observation uncertainty logic applied. The negative values should be reassigned a value of 0. While this data censoring can already be performed in the Point-Stat and Ensemble-Stat tools downstream, providing the option to handle this during the pre-processing step would be convenient. Similarly, if adding support for `censor_thresh` and `censor_val`, we should also support `convert(x)` to handle unit conversions.

This task is to add new configuration options for this functionality to the point pre-processing tools. Recommend modeling it after the existing `time_summary` dictionary which is supported across all these tools. Pick a good name and define an array of dictionaries, each defining data censoring and/or conversion logic for one or more `obs_var` names.
```
data_processing = [
  {
    obs_var       = [];
    censor_thresh = [];
    censor_val    = [];
    convert(x)    = x;
    units = ""; // Define a units string that should be written to the output NetCDF file, if applicable.
  }
];
```
An empty array means that no `data_processing` steps should be performed. Otherwise, apply them in the order they are listed in the config file.
### Time Estimate ###
2 days.

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
None needed.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
2783544 - UFS R2O

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
- [ ] Define a METplus issue to make these options configurable.

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
Per Ho-Chun, this should be addressed for both AQM and GEFS verification in EVSv2.0.  The data-preprocessing ability will be useful for both AirNOW and ABI/VIIRS AOD dataset.  It will improve the OPS EVSv1.0 AQM o3/pm25 verification on using the AirNOW and EVSv2.0 for models using the ABI/VIIRS AOD.
