### ISSUE TITLE
Refactor the existing vx_grid library as an interface to the external PROJ library

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#2486]
## Describe the New Feature ##
This is a large task. MET's vx_grid library supports several projection types and includes logic for converting between grid (x, y) and (lat, lon) space. However, adding support for a new projection requires significant development time and testing.

This issue is to switch this approach from supporting grids/projections directly within the vx_grid library to using it as an interface to an external package instead. Recommend considering the widely-used [PROJ library](https://proj.org/).

Recommend also investigating the ECMWF ATLAS package: https://github.com/ecmwf/atlas

The latter was discussed during the METplus Governance Telecon on 3/13/23.

### Acceptance Testing ###
*List input data types and sources.*
*Describe tests required for new functionality.*

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## New Feature Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
Cory Martin from NOAA/EMC confirms that ATLAS is required by JEDI and is installed/available on WCOSS2 (cactus)...

Yes, ATLAS is required by JEDI and it is currently available in dev space on Cactus:
module use /apps/dev/lmodules/intel/19.1.3.304/
module load atlas/0.30.0

@LoganDawson-NOAA notes that "it would probably still be good to get a thumbs up directly from NCO (Justin Cooke and George Liu) before going too far down the road of leveraging ATLAS... just so DTC has a record of NCO approving that library for incorporation in METplus."

**Comment by jprestop** [comment]
From George Liu in an email with the subject "Libraries on WCOSS2":

> Thanks for letting us know the potential change of the MET's dependencies.  Since proj/7.1.0 and Atlas are already approved and installed on WCOSS2, Justin and I do not see any issues in incorporating either package into the METplus components.

and 

> If Atlas is needed in prod space, we will recommend install in prod space as well.

so it sounds like NCO is fine with us proceeding with either Proj or Atlas.

**Comment by JohnHalleyGotway** [comment]
@rgbullock and @JohnHalleyGotway met on 8/29/23 to brainstorm incorporating Proj into MET. We discussed adding a new library tentatively named `vx_mesh` to contain the Proj grid implementation library code. Allowing `vx_mesh` (new) and `vx_grid` (old) to exist side-by-side would facilitate comparison testing between the libraries.

We also discussed ideally defining a grid hierarchy with an abstract Grid base class along with derived classes for a (1) proj-based regular grid implementation and (2) unstructured grids. The challenge is whether or not the abstract base class can provide sufficient functionality for handling both derived classes and then updating all of the MET application code to interact with that base class.

**Comment by JohnHalleyGotway** [comment]
As discussed with @TaraJensen on 9/28/23, MET should continue with its ability to read gridded NetCDF output generated by previous versions of the code, but we should switch to writing new output in the "new" way, meaning based on the Proj implementation.

Recommend coordinating closely with DTC T&E teams to give them plenty of lead time to make any needed changes downstream.

**Comment by JohnHalleyGotway** [comment]
Recent status update from @rgbullock via email:

On 9/26/23:

I put some files on /scratch/bullock. There are four of them:
```
proj_grid.h
proj_grid.cc
grid_proj_comparison.cc
output.txt
```
The two proj_grid files are a first-pass attempt at a grid class based on PROJ.  They're the result of a fair amount of experimenting.  They don't use the C++ shared_ptr though, so they currently don't allow copying or assignment.  The do implement all the other stuff I think we need for the new grid class, however.

`grid_proj_comparison.cc` is a test program that implements the same grid twice: once using the current grid code (or at least my copy of it) and then the new PROJ-based code in order to do some comparisons.  If you look at it, you'll be able to see what's involved in instantiating a PROJ-based grid.  We might want to make member functions for the ProjGrid class to handle the old structs.  It depends on how much of a break with the old code we want to make.

Then on lines 142-161, it does a comparison of the old xy_to_latlon code with the new latlon_to_xy code over the entire grid.  The file output.txt is the output from this test.  I think an error on the order of 10^-12 is plenty good enough.  ^_^

This code is just for you to look over and see if it looks good to you.  If so, I'll finish it up (with the shared_ptr, and a few other things ... probably should do similar testing with grids based on other projections), and we can put it into github.

On 9/28/23:

OK, I think I've got the shared_ptr stuff working with the ProjGrid class now.

**Comment by JohnHalleyGotway** [comment]
@rgbullock I'm rethinking our plan to introduce a new internal library named `vx_mesh` to store your new proj-based grid implementation. We'd planned to use `vx_mesh` to handle support for both the proj-grid and unstructured grid implementations.

However, it was recently decided that support for unstructured grids should be *optional*. And storing the interface for optional dependencies in its own library makes the organization easier. So I recommend that we introduce a new `vx_ugrid` (or similarly-named) internal library that'll be compiled only when support for unstructured grids is requested.

I was also expecting that we'd develop this new `vx_mesh` library and eventually delete the existing `vx_grid` library in its entirety. But it isn't as simple as that. As we discussed, we'll want to keep several data structures from `vx_grid` around. And moving those files from the existing `vx_grid` to a new `vx_mesh` library seems like an unnecessary step.

With that in mind, I propose that we just add your new proj-based grid implementation to the existing `vx_grid` library. When we're ready to remove the legacy grid code, we can just strip the source code out of that existing library.

I dropped your recent working version of the proj-based grid implementation into this new feature branch named [feature_2486_proj](https://github.com/dtcenter/MET/tree/feature_2486_proj). While it *does* compile, the `grid_proj_comparison` function returns large diffs (`max error = 1811.97`) but that's because I had to comment out the call to `Affine::set_b()` which is not yet implemented in the MET repo.

**Comment by JohnHalleyGotway** [comment]
@rgbullock I'm finally circling back around to this work. I'm looking for an updated version of affine.h and affine.cc which define `Affine::set_b()` that's referenced on this [line of code](https://github.com/dtcenter/MET/blob/6ce4634712f8a77fe1a89b5bc666fa21d2b8734f/internal/test_util/libcode/vx_grid/grid_proj_comparison.cc#L119). I went hunting around on seneca but didn't find an updated version of the Affine class. Are you able to point me to one on your personal machine?

**Comment by rgbullock** [comment]
Hi John -

Here's the version I have on my laptop.

void Affine::set_b(double _b1, double _b2)

{

TX  = _b1;
TY  = _b2;

return;

}

It's just a convenience function for setting the translation part of the
affine map.

BTW, it's been a while since we connected.  How are you doing?

Randy

**Comment by JohnHalleyGotway** [comment]
Note that this issue was referenced by discussion dtcenter/METplus#2914 that seeks support for the Albers-Equal Area Projection.
