### ISSUE TITLE
Update the default ASCII2NC `message_type_map` configuration option for Little R input data

### ISSUE THREAD

**Issue by CPKalb** [dtcenter/MET#2487]
## Describe the Enhancement ##
When running ascii2nc on the file [qc_out_2023-03-11_18:00:00.0000.txt](https://github.com/dtcenter/MET/files/10964179/qc_out_2023-03-11_18.00.00.0000.txt), warnings appear:
WARNING: LittleRHandler::_readObservations() -> Storing message type as "FM-18X_BUOY" for unexpected report type "FM-18X BUOY".
WARNING: 
WARNING: 
WARNING: LittleRHandler::_readObservations() -> Storing message type as "FM-16_SPECI" for unexpected report type "FM-16 SPECI".
WARNING: 
WARNING: 
WARNING: LittleRHandler::_readObservations() -> Storing message type as "FM-97_AMDAR" for unexpected report type "FM-97 AMDAR".

The ascii2nc little r dictionary needs to be updated for these additional report types.  The command to produce these warnings is:
ascii2nc qc_out_2023-03-11_18:00:00.0000 test.nc -format little_r

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
No impacts.

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
@CPKalb good news. All that is required here is an update to the ascii2nc configuration file. Please take a look at the `message_type_map` dictionary on this line:
https://github.com/dtcenter/MET/blob/c200ee23f2a36af9100c208a4288aab92cd220aa/data/config/Ascii2NcConfig_default#L36

Please try re-running ascii2nc with an updated configuration file and propose the exact changes you'd like to see in the ascii2nc configuration file.

**Comment by CPKalb** [comment]
Awesome, I will give this a try for our UAE data!

**Comment by CPKalb** [comment]
I've updated the dictionary in the copy on atmosphere, and this has removed all the warnings:

message_type_map = [
   { key = "FM-12 SYNOP";  val = "ADPSFC"; },
   { key = "FM-13 SHIP";   val = "SFCSHP"; },
   { key = "FM-15 METAR";  val = "ADPSFC"; },
   { key = "FM-16 SPECI";  val = "ADPSFC"; },
   { key = "FM-18 BUOY";   val = "SFCSHP"; },
   { key = "FM-18X BUOY";   val = "SFCSHP"; },
   { key = "FM-281 QSCAT"; val = "ASCATW"; },
   { key = "FM-32 PILOT";  val = "ADPUPA"; },
   { key = "FM-35 TEMP";   val = "ADPUPA"; },
   { key = "FM-88 SATOB";  val = "SATWND"; },
   { key = "FM-97 ACARS";  val = "AIRCFT"; },
   { key = "FM-97 AMDAR";  val = "AIRCFT"; }
];

Should I update it somewhere in MET?
