### ISSUE TITLE
Enhance PB2NC to derive PBL and CAPE from aircraft-based soundings

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#2503]
## Describe the Enhancement ##
This issue was raised via METplus Discussion dtcenter/METplus#1860 and was discussed during the [METplus NOAA User telecon](https://docs.google.com/document/d/1JrHjHXoEIryYTrAkCARao1nPO4osFueQNnVYisqRO30/edit) on 4/3/2023. @PerryShafran-NOAA notes that existing VSDB code does derive PBL and CAPE from aircraft sounding data. However the logic is complicated since the derivation combines model analysis-derived moisture data with aircraft point observations. So that'd require PB2NC to combine gridded model data with point observations.

This task is to collaborate with @PerryShafran-NOAA, @LoganDawson-NOAA, and @jason-english to determine if/how the PB2NC tool should be enhanced to derive PBL and/or CAPE from aircraft sounding data.

Many questions remain on how to perform those derivations and how to validate the quality of the derived values.

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
Note that this functionality is NOT included in EVS version 1.0 but should be fully investigated for EVS version 2.0. As such, the work should be done for the MET version 12.0.0 release.

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
No direct impacts. May want to add a METplus Use Case to demonstrate this functionality.

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
@DanielAdriaansen will reach to @PerryShafran-NOAA to discuss this work further.

**Comment by JohnHalleyGotway** [comment]
Removed from the 12.0.0 release during the METplus NOAA telecon on 6/10/24 since aircraft obs will not be included in EVS v2.
