### ISSUE TITLE
Add support to Grid-Stat for `interp.field = NONE`

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#2510]
## Describe the Enhancement ##
This recommended enhancement arose via GitHub Discussion dtcenter/METplus#2105. While it does not add any new functionality, it makes the Grid-Stat config file settings a bit more intuitive for users.

In Grid-Stat, the `interp` dictionary provides options to smooth the gridded forecast and/or observation data prior to verifying them. The default settings (shown below) in the default config file apply a "nearest-neighbor" smoothing operation to both the the forecast and observation fields. Of course, "nearest-neighbor" does no actual smoothing at all. And the library code explicitly checks for this setting and skips the smoothing operation.
```
interp = {
   field      = BOTH; 
   vld_thresh = 1.0;  
   shape      = SQUARE;

   type = [ 
      {
         method = NEAREST;
         width  = 1;
      }
   ];
}
```
The default settings above do what you'd expect them to do (i.e. no smoothing) but in a round-about, somewhat confusing way. This issue to clarify this as follows:
- Add support to Grid-Stat for `interp.field = NONE`.
- Change the default Grid-Stat config file to set `interp.field = NONE`.
- Update the processing logic in `grid_stat.cc` to skip over the smoothing logic in this case.
- However, ensure that when `interp.field = NONE` is used, then `INTERP_MTHD = NEAREST` and `INTERP_WDTH = 1` is written to the output files. That will help with backward compatibility of the output created.
- Step back and consider where similar changes to support `field = NONE` should be added to other contexts of the Grid-Stat config file or the config files for other MET tools.

### Time Estimate ###
Perhaps 3 days?

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
None needed.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
- [ ] Will need to coordinate with METplus wrappers about this update and default config file.

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by jwraby** [comment]
Looks good, John. Thanks for creating the enhancement request.
