### ISSUE TITLE
Update NDBC locations prior to the MET-11.1.0 release

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#2511]
## Describe the Task ##
The [ndbc_stations.xml](https://github.com/dtcenter/MET/blob/main_v11.0/data/table_files/ndbc_stations.xml) file defines the "current" locations of the NDBC buoys. Prior to creating the 11.1.0 release, the contents of this file should be updated. While the [MET_NDBC_STATIONS](https://met.readthedocs.io/en/latest/Users_Guide/config_options.html#met-ndbc-stations) environment variable can be set to point to a user-specified version of this file, doing so operationally at EMC is problematic. As such, the MET team should ensure that static file is as up to date as possible.

The longterm preference is to modify this approach to use a version of the NDBC buoy data that is self-describing (i.e. including its lat/lon location). But that version of the NDBC data does not yet exist.

### Time Estimate ###
4 hours?

### Sub-Issues ###
Consider breaking the task down into sub-issues.
None needed

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
No impcats.

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update log messages for easier debugging.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by davidalbo** [comment]
It seems the content of the files on the web may have changed format.  Running the script gives errors for all stations, for example, the wget succeeds, but an error when grepping for a particular string:

```
wget "https://www.ndbc.noaa.gov/station_page.php?station=32D13"
Command failed  grep "var currentstnid" /d1/personal/dave/MET/MET_development/MET/scripts/python/utility/ndbc_temp_data/stations/station_page.php?station=32D13
```
which would make this a non-trivial issue to resolve.
