### ISSUE TITLE
Enhance TC-RMW to reorder the dimensions of the NetCDF output to store the gridded dimensions last

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#2523]
## Describe the Enhancement ##
During development for MET #2168, it was noted that the NetCDF output generated by the TC-Diag tool should order the NetCDF output dimensions as time, lat, lon. The python diagnostics code expects the dimensions to be ordered in this way. I also see this convention in WRF files:
```
float UU(Time, num_metgrid_levels, south_north, west_east_stag) ;
```
And in SWPC NetCDF output files:
```
float TEC(time, latitude, longitude) ;
```
While the CF-convention does *NOT* force an order for the dimensions, the earlier COARDS convention does, as described in [this section](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.10/cf-conventions.html#coards-relationship). And it is generally encouraged to considered to continue with this ordering for compatibility with existing tools, such as `ncview`.

This task is to reorder the dimensions of the NetCDF output from the `tc_rmw` tool to list the range and azimuth dimensions last. So change...
FROM: `double TMP(range, azimuth, pressure, track_point) ;`
  TO: `double TMP(track_point, pressure, range, azimuth) ;`

### Time Estimate ###
4 hours.

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
None needed

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
TC-Diag project 2770043

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
- [ ] Define a new METplotpy issue to update the plotting of the TC-RMW output.

Thanks @bikegeek for finding the code to generate TCRMW plots in METplotpy:
   https://github.com/dtcenter/METplotpy/blob/develop/metplotpy/contributed/tc_rmw/plot_fields.py
Its reads in data via read_tcrmw in the tc_utils.py:
   https://github.com/dtcenter/METplotpy/blob/develop/metplotpy/contributed/tc_rmw/tc_utils.py
These will need to be updated.

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
