### ISSUE TITLE
Internal: Trigger METplus tests for main branches from MET

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/MET#2538]
Currently changes to the develop branch in the MET, METcalcpy, METplotpy, and METdataio repositories trigger a METplus testing workflow to ensure that changes to those components do not break any use cases. We should implement similar logic to trigger a METplus run for the main_vX.Y branch when changes to the corresponding main_* MET branch are pushed.

## Describe the Task ##
Create a GitHub Actions workflow that triggers on push events to main_v* branches that trigger a workflow run for the corresponding METplus main branch.

Existing workflow that triggers develop: https://github.com/dtcenter/MET/blob/main_v11.0/.github/workflows/build_docker_and_trigger_metplus.yml

This involves:

* Determining which METplus version corresponds to the MET version. Currently the versions are 6 major versions apart, so MET main_v11.0 corresponds to METplus main_v5.0. This could work for now, but we would need to come up with a better approach if the version numbers ever become out of sync.
* Determining how to handle new releases. MET official releases are created before METplus, so the main_vX.Y run for a newly created release will fail because the corresponding METplus main_vX.Y branch will not exist yet. When the METplus branch is created, we will want to make sure that this is run. How should we handle this?
  * Should we allow the first run to fail and the team should remember to follow up and re-run the failed workflow after the METplus release is created?
  * Should we try to check if the METplus branch exists and force it to succeed without running?

There may be other decisions that need to be made to complete the work for this issue.

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Once this logic has been implemented for MET, create issues and implement similar changes for the other repositories:
- [ ] METcalcpy
- [ ] METplotpy
- [ ] METdataio

Should this be implemented for METviewer as well??

### Relevant Deadlines ###
None

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED CYCLE ASSIGNMENT** label
- [ ] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by georgemccabe** [comment]
This was completed with commit 30bf4fb
See issue dtcenter/METplus#2816 for details
