### ISSUE TITLE
Add support for native WRF output files already on pressure levels

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#2547]
## Describe the New Feature ##
For the NCAR/RAL I-WRF project, MET needs to be enhanced to directly read NetCDF WRF output files that are already on pressure levels. The breadth of the changes needed are not entirely clear at this time, but MET should be able to interrogate the input NetCDF files to automatically determine whether or not they satisfy the requirement of being reported on pressure levels. Another key question is how to handle the location of velocity points (i.e. winds) which are staggered one half grid points from the mass points. Should that data be processed on the velocity points as-is or automatically interpolated to the mass points?

Also consider automated derivation of wind speed. Is this needed?

Should this be a new file type handle this or should the existing file_type = NETCDF_PINT be expanded to include it? Perhaps add NETCDF_WRF?

### Acceptance Testing ###
*List input data types and sources.*
*Describe tests required for new functionality.*

### Time Estimate ###
2 weeks.

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
None yet.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
7790013

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: @JohnHalleyGotway 
- [ ] Select **scientist(s)** or **no scientist** required: Perhaps Jared?

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED CYCLE ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## New Feature Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
From Jared Lee:

At our last I-WRF project meeting I said I would send you some sample WRF output that is on constant pressure levels and constant height levels, so that you could use it as input for testing new developments in MET to read in those files directly. Output for a 48-h WRF-Solar simulation with domains centered over Kuwait is available on Campaign Store:

/glade/campaign/ral/wsap/kuwait/wrf/exp9/2019-08-31_00

wrfout_solarwind_d0*: A trimmed-down set of mostly 2D variables on the native grid, one file per output time

wrfout_solarwind_plev_d0*: A subset of variables on 4 pressure levels (850, 700, 500, and 300 hPa), one file with all output times (this could be changed in the namelist to have one file per output time, too, but that's just how these were done)

wrfout_solarwind_zlev_d0*: A subset of variables on 5 height levels (78, 100, 200, 300, 400, and 500 m AGL), one file with all output times (this could be changed in the namelist to have one file per output time, too)

**Comment by JohnHalleyGotway** [comment]
@georgemccabe and @JohnHalleyGotway met on December 13, 2023.
- Recommend supporting i-wrf files and existing pinterp files with the same vx_data2d library and renaming `vx_data2d_pinterp` as `vx_data2d_wrf` instead for clarity.
- See [pressure level output](https://www2.mmm.ucar.edu/wrf/users/wrf_users_guide/build/html/output.html#pressure-level-output) docs in the WRF User's Guide.
- We do want to differentiate input file types between p-interp and raw wrf output. But we'd like to support them in a single `vx_data2d_wrf` library.
- When it comes to handling data on staggered dimensions, recommend checking how UPP handles this to inform our decision on how MET should.

**Comment by JohnHalleyGotway** [comment]
On 12/19/23, @JohnHalleyGotway and @georgemccabe met to discuss some of these details. We had a relatively simple approach for handling data defined on staggered x/y dimensions. Note that U wind is staggered in the x dimension, and V grid is staggered in the y dimension. It's also possible for variables to be staggered in both dimensions, but we don't have any examples of that immediately available.

Recommend a simple approach for handling staggered data. But also recommend comparing this simple approach to how its handled in UPP. Ideally, MET would use the same algorithm as UPP:
- Enhance the DataPlane class to add a `destagger(bool xdim, bool ydim)` function.
- If xdim && !ydim, for (Nx, Ny) input, return data (Nx-1,Ny).
- If !xdim && ydim, for (Nx, Ny) input, return data (Nx,Ny-1).
- If xdim && ydim, for (Nx, Ny) input, return data (Nx-1,Ny-1).
- To destagger, compute the value for x as the mean of x-1 and x+1.
- If destaggering in both dimensions, compute the value as the mean of the 4 values at x-1, x+1, y-1, and y+1.

**Comment by georgemccabe** [comment]
@dudhia, it is unclear to me if we will need to de-stagger the WRF data to read into MET. MET can only read a 2D slab of data. De-staggering in the X and Y dimensions makes sense to me since the data will need to be on the same X/Y grid as the rest of the fields. The MET configuration would specify a vertical level to read, so it would pull and use the data from that level. Is that sufficient or de-staggering the data in the vertical dimension necessary? If so, would it be assumed that the tool would de-stagger using the requested vertical level and the level above it?

**Comment by dudhia** [comment]
@georgemccabe U and V only need destraggering in the horizontal direction. The only ones that need vertical destaggering of the regular output should be the PH and W fields.
