### ISSUE TITLE
Enhance TC-Diag to actually compute and write diagnostics

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#2550]
## Describe the Enhancement ##
Review details of the initial development version in #2168.

The initial version of the TC-Diag tool is slated for inclusion in the MET-11.1.0 release. It transforms a configurable list of input gridded data fields into range/azimuth cylindrical coordinates and calls python script to compute diagnostics on the result. If the storm track (i.e. OFCL) differs from the gridded data (i.e. GFS), the center of the storm vortex and the track location may not coincide. This task is to incorporate NHC's vortex removal logic into TC-Diag prior to converting to cylindrical coordinates.

CSU/CIRA will provide the algorithm for doing so.

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
None needed.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED CYCLE ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
This may impact the METplus wrapper of TC-Diag.
- [x] dtcenter/METbaseimage#15 adds the new required yaml Python package to the base image testing environment.

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
As discussed at the TC-Diag project meeting on 9/12/23, we should ideally test with at least 3 input data sources:
1. NOAA generated GRIB2 inputs (with variable names like `TMP`, `UGRD`, and `VGRD`).
2. ECMWF generated GRIB2 inputs (with variable names like `T`, `U`, and `V`).
ECMWF GRIB data are available at: mohawk:/d2/projects/TCGP/data/data_realtime/ecmwf/2023/09/12/06z
3. NetCDF wrfout files on which the GFDL vortex tracker can be run.

**Comment by JohnHalleyGotway** [comment]
From @robertdemariacira on 8/17/23:

I have a version of the code (v0.5.0) that can now read the provided temp netCDF files and perform diagnostic computations from them:
https://github.com/robertdemariacira/tc_diag_driver/tree/main

Instructions for how to use the code are included at the bottom of the README.  Example configs and a manual test of the code are provided.  Let me know if you have any questions.

**Comment by JohnHalleyGotway** [comment]
@robertdemariacira I've followed the instructions listed in the [README](https://github.com/robertdemariacira/tc_diag_driver/blob/main/README.md) file and am trying to figure out how to make a call to the driver code to have it compute diagnostics. I'd like to pass to it a NetCDF file for a single time step and see its output. Can you advise on that?

**Comment by JohnHalleyGotway** [comment]
Based on TC-Diag meeting on 9/20/23:
- Update TC-Diag to error out if handed a track to define diagnostics with an 'I' or a '2'.
- Update TC-Pairs to error out if the user requests to match diagnostics to track ending with an 'I' or a '2'.
Note that using an 'I' or '2' will produce unexpected results.

**Comment by robertdemariacira** [comment]
@JohnHalleyGotway I've updated the [tc_diag_driver repo](https://github.com/robertdemariacira/tc_diag_driver) to v0.6.0. It no longer requires the ATCF tech ID to be specified in the config file.  You can find an example for how to call the driver [here](https://github.com/robertdemariacira/tc_diag_driver#alternate-post-resample-driver).  The text distance to land LUT the code needs (for now) can be downloaded from [here](https://rammb-data.cira.colostate.edu/~/rdemaria/gdland/v2023-04-07_gdland_table.dat).  You'll need to update the example config files described in the above readme section to point to the location of the LUT file.

**Comment by JohnHalleyGotway** [comment]
See the TC-Diag project-wide [meeting notes](https://docs.google.com/document/d/1NKyHrP6g4Px7vlnsMqZrAqmTY-JtCi-omUWWytEy2BM/edit#heading=h.e8dr2x6blirh) from 10/4/23.

Relevant for the TC-Diag tool:
- [ ] @JohnHalleyGotway will define lists of standard storm data and sounding diagnostic names. Anything not in those lists goes in the `CUSTOM DATA` section at the bottom in the output file.
- [x] @robertdemariacira will move the `land_lut_file` setting from the `post_resample.yml` to be an argument for the `diag_calcs` function.
- [x] @robertdemariacira will update the python diagnostics code to compare the maximum radius requested in `post_resample.yml` to the actual cyl coord data handed to it. If the cyl coord radius < max config radius, it'll raise an exception.
- [ ] @JohnHalleyGotway will update `compute_tc_diag.py` to catch that exception.
- [ ] @JohnHalleyGotway will add 2 new config options to the TC-Diag `domain_info` section:
```
diag_config = "MET_BASE/python/tc_diag/config/post_resample.yml"; // for parent
diag_config = "MET_BASE/python/tc_diag/config/post_resample_nest.yml"; // for nest
```
Defines the python config file to be applied to that domain. Will be different for the parent and nest.
```
override_diags = [ "RMW", "SST" ]; // default setting only uses the nest RMW and SST
```
Defines which diagnostics computed for this domain should override previously defined diagnostics. The default value of an empty list means that all diagnostics returned from python should be used.

**Comment by robertdemariacira** [comment]
@JohnHalleyGotway The v0.7.0 TC Diag Driver code addresses the `land_lut_file` and radii validation issues described above.  

The `land_lut_file` config parameter is now optional and can be removed from the config as long as the `land_lut_override` arg is provided to `diag_calcs`.  If the config parameter is not removed, it will be ignored if `land_lut_override` is provided.  See the [README](https://github.com/robertdemariacira/tc_diag_driver#alternate-post-resample-driver) for an example.

I added a config parameter: `radii_to_validate` which is just a list of radii to check against the min/max radii found in the input file.  A `ValueError` will be raised if any of the entries in `radii_to_validate` are found to be outside a valid range.  It should be noted that the code could potentially raise `ValueError`, `IndexError`, `KeyError`, or `IOError` exceptions if other problems are found when the code is preparing to perform diagnostic calculations.  These errors can't be suppressed when `suppress_exceptions` is set to `True` since they're raised when the code is figuring out information needed to pre-populate the returned data with missing values.

**Comment by JohnHalleyGotway** [comment]
@jvigh, @robertdemariacira, and @musgrave-kate, we have an issue with units that needs to be addressed.
Listed below are diagnostic names from a sample diag file (`sal092022_avno_doper_2022092600_diag.dat`). Each name is followed by the units used in the doper file and that's followed by the units reported by the python diagnostics code. I only listed the 1000mb sounding data for brevity.

You'll notice some simple differences in naming conventions (e.g. `DEG` vs `DEGREES`) along with more substantive differences like `10C` versus `K` and `10KT` vs `M/S`.
```
LAT (DEG) (DEGREES_NORTH)
LON (DEG) (DEGREES_EAST)
MAXWIND (KT) (KTS)
RMW (KM) (NA)
MIN_SLP (MB) (MILLIBARS)
SHR_MAG (KT) (M/S)
SHR_HDG (DEG) (DEGREES)
STM_SPD (KT) (KT)
STM_HDG (DEG) (DEGREES)
SST (10C) (K)
OHC (KJ/CM2) (KJ/CM2)
TPW (MM) (KG/M^2)
LAND (KM) (KM)
850TANG (10M/S) (M/S)
850VORT (/S) (/S)
200DVRG (/S) (/S)
T_SURF (10C) (K)
R_SURF (%) (%)
P_SURF (MB) (PA)
U_SURF (10KT) (M/S)
V_SURF (10KT) (M/S)
T_1000 (10C) (K)
R_1000 (%) (%)
Z_1000 (DM) (GPM)
U_1000 (10KT) (M/S)
V_1000 (10KT) (M/S)
TGRD (10^7C/M) (10^7C/M)
```
@robertdemariacira where are these unit discrepancies currently handled when the python code writes the doper output file?

@jvigh is it desirable for the NetCDF output to use precisely the same units as the existing ascii output or are you going to want them to differ?

How should we solve this? Options include:
 - Update the call to `post_resample_driver.diag_calcs()` to return the exact diagnostic names (e.g. change current `VMAX` to `MAXWIND`) and units that should be reported in the output.
 - Leave `post_resample_driver.diag_calcs()` as-is but update MET's python wrapper code to rename things and do unit conversion.
 - Do the same as above, but in C++ rather than python (this is potentially messy and slow to be fixed).
 - Abandon the approach of C++ writing the diagnostics ascii output and figure out how MET can leverage the existing python code to write it and, presumably, handle the discrepancies in naming conventions and unit conversion.

**Comment by robertdemariacira** [comment]
The diagnostic calculations are (mostly) performed using whatever units come from the input file.  We then have a function that takes the Xarray Dataset objects returned by the diagnostic calculations and some configuration information and writes the doper file.  The function uses the configuration information to map between the diagnostic variable name and the output name, the name of the output units, and performs any unit conversion needed.

**Comment by JohnHalleyGotway** [comment]
Thanks @robertdemariacira. As far as I can tell, the code that writes the doper output file does not live in the https://github.com/robertdemariacira/tc_diag_driver repository. I do see a `kelvin_to_celsius` conversion function `unit_conversion.py` in the `diag_lib` CIRA dependency tar file, which presumably would be involved. While it's defined there, I can't find an example of it being called. So I presume the doper output file logic lives elsewhere.

One potential solution would be updating the `tc_diag_driver` repo to provide a function for doing that unit conversion and naming updates -- maybe in `diag_lib`? Hopefully, we'd be able to lift that logic from where it currently lives and drop it in here. MET's `compute_tc_diag.py` wrapper could just pass the results output from `post_resample_driver.diag_calcs()` to that function for updating units and metadata... and then the C++ TC-Diag would just pass the diags as-is to the output file(s) without needing to be aware of the names and units... other than passing them through to the output.

I'm leaning toward this approach of putting the unit and convention handling in python and just using the C++ to manage the data flow and i/o. But of course, there's other ways we could address it.

**Comment by robertdemariacira** [comment]
@JohnHalleyGotway the function that writes the doper file is `tc_diag_driver.output.to_diag_file`.  The reason why you can't find a call to `kelvin_to_celcius` is because the python code looks up the function needed to perform unit conversion at runtime based on what's in the config file.  So `kelvin_to_celcius` is never explicitly called from the code. 

We can do most of what you described by just altering the config info that's being passed to `diag_calcs`.  The variable names that appear in the returned Xarray Datasets come from the config files. By default the units come from the input file, but I can explicitly override them in the config.  I need to change a small amount of logic, but I could run unit conversion functions as part of the work done in `diag_calcs`. 

So you'd receive Xarray Datasets from `diag_calcs` whose contents would be basically ready to be written to a file.  Would that work for you?

**Comment by JohnHalleyGotway** [comment]
@robertdemariacira, yep, that sounds great to me! And if any metadata massaging remains to be done (like, renaming `VMAX` to `MAXWIND` for example), I can do that in the MET python wrapper. Thanks for the update.

**Comment by jvigh** [comment]
Just coming online and catching up. I was away most of the afternoon for a long non-work meeting related to fire recovery.

Regarding units, normally best practice for a NetCDF file would be to use the Climate and Forecast (CF) conventions:
http://cfconventions.org/Data/cf-conventions/cf-conventions-1.10/cf-conventions.html#units

These do allow for non-SI units like "knot". To fully comply with the CF conventions could potentially be a headache though if it requires thinking about the cell boundaries between levels for the soundings, etc. But it might not. The time coordinate has to be called "time" and long_names would be needed. Even if we don't go for full compliance, it's probably good to comply with the spirit of CF (e.g., use the accepted units in https://docs.unidata.ucar.edu/udunits/current/udunits2-common.xml), if that's desired. But if operational people simply don't care, then it wouldn't be necessary. It might just come at the expense of useability for downstream uses.  (Does MET expect CF-compliant NetCDF files?).

Whether to go for full CF compliance or not is a decision best left to @musgrave-kate. Kate, any thoughts on this?

**Comment by JohnHalleyGotway** [comment]
@robertdemariacira and @musgrave-kate,

I've made good progress in the last couple of weeks on the MET TC-Diag tool. Still more work to do, but I've attached the current state of the output files from the truncated unit test I'm using for testing.
`tc_diag_AL092022_GFSO_2022092400_cyl_grid_parent.nc`: NetCDF Cylindrical coordinates output
`tc_diag_AL092022_GFSO_2022092400_diag.nc`: NetCDF Diagnostics output file
`tc_diag_AL092022_GFSO_2022092400_diag.txt`: CIRA ASCII Diagnostics output file

Here's 5 questions I have:
1. Does the CIRA Diag output file name matter? Should I instead use the "doper" naming convention?
- Meaning, should: `tc_diag_AL092022_GFSO_2022092400_diag.txt` be renamed as: `sal092022_gfso_doper_2022092400.dat`?
- If so, should the other 2 files use a similar naming convention? `sal092022_gfso_doper_2022092400.nc` and `sal092022_gfso_doper_2022092400_parent_cyl_grid.nc`?
- Or should we let the naming conventions of these 3 output files differ?

**Per the project meeting on 10/18/23**, need to make the output naming convention configurable by the user. Provide a format string to be filled in with the relevant variables. Let the user specify the output file base name and then append `.txt` rather than `.dat` for the CIRA diag output, `.nc` for NetCDF diagnostics, and `_cyc.nc` for cylindrical coordinates data. See [here](https://github.com/robertdemariacira/tc_diag_driver/blob/a586bb93168defede7831fc0a92bfeaaf493cf4d/tests/special_test/gfs_spec.yml#L25) for an example of output naming convention formatting.
`output_file_format: s{atcf_id}_{atcf_tech_id}_doper_{model_time:%Y%m%d%H_diag.dat}`

2. What about the "gfs" vs "avn" naming convention?
- MET automatically renames all instances of "avn" with "gfs".
- Should I revert all instances of "gfs" back to "avn" when writing this output?

**Per the project meeting on 10/18/23**, keep this all as-is.

3. The naming conventions and units don't match the existing doper output files yet.
- The plan is for Robert to update the driver code to provide "results" with the desired output naming and units conventions.
- Just want to confirm that.

**Per the project meeting on 10/18/23**, Robert is working on this and expects a new version later this week.

4. The `CUSTOM DATA` section contains any diagnostics whose names don't appear in the [STORM_DATA_NAMES](https://github.com/dtcenter/MET/blob/56c4b143885ed1643296c09f4b283082bf8ab251/scripts/python/tc_diag/compute_tc_diag.py#L11) or [SOUNDING_DATA_NAMES](https://github.com/dtcenter/MET/blob/56c4b143885ed1643296c09f4b283082bf8ab251/scripts/python/tc_diag/compute_tc_diag.py#L19) lists.
- Right now, the following all appear in the "CUSTOM" list:
  - `VMAX` (Should be renamed as `MAXWIND`)
  - `200DVRG` (Should be renamed as `200DVG`)
  - `TGRD` (This does belong in CUSTOM)

- **Per the project meeting on 10/18/23**, the following should NOT be written to the output. Update `compute_tc_diag.py` to have a list of variables to be skipped.
     - `850RADIAL` (Not sure if this is actually custom, should be renamed, or should be added to the expected STORM_DATA_NAMES?)
     - `850DVRG` (Should be renamed as `850DVG`)
     - `200VORT` (Should be added to the expected STORM_DATA_NAMES?)

5. The `COMMENTS` section at the bottom describes the configuration settings.
- See example below.
- I assume this output should be preserved?
- Any chance we could enhance the python code to construct these comments and provide it with the existing `results`?
- Otherwise, MET would need to parse these values out of the yml config file.
- You could provide the fully formatted strings, or the diag names and radii needed for the C++ code to construct the strings.

Example `COMMENTS`:
```
                ------------------------------------------------------     COMMENTS     ------------------------------------------------------------
 
               *   SST, OHC averaged from    0-  50 km around storm center [x10 C, kJ/cm2]   *
               *   RMW within    0- 500 km around storm center [km]   *
               *   U, V, SHR averaged from    0- 500 km around storm center [x10 kt, x10 kt, kt]   *
               *   850VORT, 200DVRG averaged from    0-1000 km around storm center [x10^7 /s, x10^7 /s]   *
               *   850TANG averaged from    0- 600 km around storm center [x10 m/s]   *
               *   T, R, Z, P averaged from  200- 800 km around storm center [x10 C, %, dm, mb]   *
               *   TPW averaged from    0- 200 km around storm center [mm]   *
```

- **Per the project meeting on 10/18/23**, Robert is adding comments to the results.

**Comment by robertdemariacira** [comment]
@JohnHalleyGotway 
3. Yes, that's the plan as far as I'm aware. I'm in the process of getting that to work.  I needed to iterate over a couple of different methods for handling the post processing unit conversion, but I think I've landed on a solution I like.  
5. Since your Python wrapper is already calling code to parse the YAML in order to construct the DriverConfig object, I should be able to just add an extra entry for comments in the config.  The wrapper can then simply access the "comments" attribute of the DriverConfig object and pass that back to the C++ code.  Does that solution work for you?

**Comment by jvigh** [comment]
Hi @JohnHalleyGotway ,

I think @musgrave-kate and @robertdemariacira should give the final word on these questions, so I'll defer to them, but here are my thoughts. 

Regarding #1, I'll mention that one of the challenges of ASCII files is that it's not always apparent where they came from, as they often contain little to no metadata. It would be nice if the filenames or files somehow contain an indicator of the source of the output. That way users can distinguish between a file generated by METplus and a file generated by CIRA's python code. @musgrave-kate what do you think? If an exact match to the existing is needed without any such metadata, just let us know.
    
Regarding #2, the files weren't "avn" in the first place were they? I think "gfs" is preferred.

**Comment by JohnHalleyGotway** [comment]
Attempting to parallelize the calls to `process_fields()` results in a segfault.
Switching to development on seneca for debugging, results in a run time error about the `yaml` module not be available:
```
import yaml
ModuleNotFoundError: No module named 'yaml'
```
For now, will just install `yaml` in the MET python instance `/var/autofs/mnt/linux-amd64/debian/stretch/local/met-python3`.
Will eventually need to add support for `$MET_PYTHON_EXE`.

Just installed PyYAML and SciPy in my local user area and that got me past this issue.

**Comment by robertdemariacira** [comment]
@JohnHalleyGotway v0.8.0 of the tc_diag_driver code should allow you to receive DataSet objects whose contents are ready to be output to the doper file with the correct names and units.  You'll need to update your config files to match the example files: `tests/post_resample_test/post_resample.yml` and `tests/post_resample_test/post_resample_nest.yml` to get the correct names and units.  

Additionally, you can now access the formatted block of comments to include in the doper file from the `comment` attribute of the `DriverConfig` object. EX: `print(config.comment)`

I did some checks to verify that the names and units are correct, but there's always a chance that something slipped by.  So let me know if I missed anything.

**Comment by JohnHalleyGotway** [comment]
@robertdemariacira thanks for providing version 0.8.0 of the tc_diag_driver code. There's only one minor change needed, and its my fault. The divergence really should be named `DVRG` and not renamed to `DVG`, as I'd requested. Apologies, I must have gotten confused between existing vs new outputs.

I see `200DVRG` included in this sample [sal092022_avno_doper_2022092400_diag.dat](https://dtcenter.ucar.edu/dfiles/code/METplus/MET/MET_unit_test/unit_test/tc_data/diag/cira_diag_rt/2022/sal092022_avno_doper_2022092400_diag.dat) CIRA Diag file. So that's what it really should be, rather than renaming to `200DVG` as I'd requested.

I'm also fine with you making that minor change but leaving the version number (v0.8.0) unchanged. But it's up to you to decide on versioning. Please just LMK if/when this fix in the `main` branch of https://github.com/robertdemariacira/tc_diag_driver and I'll go grab it from there.

Thanks!

**Comment by robertdemariacira** [comment]
@JohnHalleyGotway I updated the configs to use the corrected DVRG name.  I decided to just leave it at v0.8.0 since it's a config change instead of a change to the actual code.

**Comment by JohnHalleyGotway** [comment]
Thanks @robertdemariacira. Didn't realize it was that easy... that the naming conventions were specified in the yml config file. Thanks!

**Comment by JohnHalleyGotway** [comment]
Moving the progress/TODO list out of the code and into this comment:

TODO after the MET version 11.1.0 release:
  - Processing logic:
    - [x] (#2609) Instead of reading DataPlanes one at a time, read them all at once or perhaps in groups (e.g. all pressure levels).
  - Compute diagnostics:
    - [x] Add CIRA python diagnostics scripts to the MET repository.
    - [x] Read resulting diagnostic data provided by python script.
    - [x] Fix the order of the diags returned by `compute_tc_diag.py` to match existing.
    - [x] Add support for the `$MET_PYTHON_EXE` python embedding option.
  - Write output:
    - [x] Write CIRA ASCII diagnostics output file.
      - [x] Double-check units, names, and spacing of output.
        - [x] On 11/1/2023, fixed the units for height (`Z`) from `GPM` to the expected `DM` by updating the driver config files. 
    - [x] Write NetCDF diagnostics output file.
      - [x] Add comments to NetCDF output.
      - [x] Define long names for diagnostics and write them to the NetCDF output.
        - [ ] Confirm variable long names match the ones listed in this [Google Doc](https://docs.google.com/document/d/1bSXN0LvQoKyRMplwiFvERlhjjAG3pCCBu5myvNHtsl8/edit).
      - [x] Add NetCDF variable attribute to specify the domain from which each diag is defined (e.g. domain = "parent").
      - [x] Add new NetCDF variables (e.g. `parent_domain`) with attributes to define the range/azimuth grid for each domain.
- Configuration options:
  - [x] Use `override_diags` to have nest items override parent.
  - [x] Decided to leave `diag_script` as an array rather than as a string. Users may want to keep the standard diags in place and use a separate script to do new things.
  - [x] Support `regrid` option for each data field entry (e.g. regrid temp using bilin and tpw using budget).
  - Testing:
  - Documentation:
----
  - [ ] Parallelize the processing of valid times. Simple OpenMP does not work. Global python instance is a problem.
  - [ ] Add support for vortex removal. Print a WARNING if the Diag Track differs from the Tech Id for the data files and vortex removal has not been requested.
  - [ ] Update documentation:
    - [ ] Describe CIRA and NetCDF diag outputs.
    - [ ] Update Appendix F with TC-Diag python embedding info.
  - [ ] Update `unit_tc_diag.xml` to run a realistic HWRF parent + nest example. Be sure to test with with and without `MET_PYTHON_EXE` set.
  - [ ] Investigate why the computed diagnostics DO NOT MATCH. As discussed on 11/1/23:
    - It is OK if diag values differ by 1 due to rounding.
    - `V_SURF` is reported as bad data. Need to figure out why.
  - [ ] Enhance the NetCDF diagnostics output to report data in more typical units (e.g. use `C` rather than `10C`). However, recommend keeping knots rather than switching to m/s.
  
- Questions:
  - Should the default regridding method (nearest) vary by input variable (e.g. bilin for TEMP, budget for TPW)?

**Comment by JohnHalleyGotway** [comment]
@robertdemariacira and @musgrave-kate, FYI, I was able to fix the unit problem for height with a simple change in the tc_diag_driver config files. Please see changes in [this commit](https://github.com/dtcenter/MET/commit/d6ee8d6eca1eb5828ce57f1fb55727188cdedf70). Robert, I'd recommend that you make the same change in https://github.com/robertdemariacira/tc_diag_driver to keep the config files in sync.

**Comment by JohnHalleyGotway** [comment]
@robertdemariacira I'm wondering about scipy. It's used in the Python code here:
```
.//diag_lib/cylindrical_grid.py:from scipy import interpolate
```
And `interpolate` is used in:
```
def interpolate_to_cyl_grid(...)
...
class ScipyLinearNDInterpolator(CylindricalGridInterpolator)
```
I don't think that MET is actually *using* that SciPy interpolation functionality. I'm wondering if I should add SciPy as a new Python requirement even though MET is not actually using it. Or perhaps I should just comment out or delete the portion of the code that uses it.

Any suggestions?

**Comment by robertdemariacira** [comment]
@JohnHalleyGotway I don't think the code you're using should ever make a call to scipy.  I could wrap the scipy import in a try/except clause and make it an optional dependency so that you don't need to include it as a dependency for MET.

**Comment by JohnHalleyGotway** [comment]
@robertdemariacira however you'd like to handle it is fine with me. But yes, I'd prefer not to add a dependency on scipy that we won't actually use. For now, I just modified this version of [cyclindrical_grid.py](https://github.com/dtcenter/MET/blob/feature_2550_compute_diagnostics/scripts/python/tc_diag/diag_lib/cylindrical_grid.py) by commenting out the scipy related code.

If you do implement a more elegant solution in your [tc_diag_driver](https://github.com/robertdemariacira/tc_diag_driver) repo, please let me know, and I'll go grab the updated version.

Thanks!

**Comment by robertdemariacira** [comment]
@JohnHalleyGotway Sounds good. I'll let you know when I have that updated.

**Comment by robertdemariacira** [comment]
@JohnHalleyGotway I updated [tc_diag_driver](https://github.com/robertdemariacira/tc_diag_driver/tree/main) to v0.9.0.  This version includes diag_lib v0.5.0 which now has Scipy as an optional dependency.  I tested the driver in an environment where scipy wasn't installed and it appeared to run without any problems.
