### ISSUE TITLE
Automate testing of the compilation of MET with Clang

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#2564]
## Describe the Task ##
METplus discussion https://github.com/dtcenter/METplus/discussions/2127 from @climbfuji noted that MET version 11.0.2 no longer compiles via Clang, while earlier versions did. The Clang compilation was fixed via issue #2514. This task is automate the testing of compiling via Clang for all future MET PR's via GitHub actions.

MET is now included in [NOAA-EMC/hpc-stack](https://github.com/NOAA-EMC/hpc-stack) and Clang compilation is supported for all of those components.

Recommend adding a new base image to dtcenter/METbaseimage for MET's compilation environment that is based on is based on [docker-osx](https://hub.docker.com/r/sickcodes/docker-osx) (or similar). Automate this testing for all MET PR's via GitHub actions.

### Time Estimate ###
2-3 days

### Sub-Issues ###
Consider breaking the task down into sub-issues.
None needed.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
Tentative assignment. Feel free to re-assign as needed.
- [x] Select **engineer(s)** or **no engineer** required: @jprestop 
- [x] Select **scientist(s)** or **no scientist** required: @CPKalb 

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED CYCLE ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
Could consider extending to test the other METplus components, but that isn't strictly necessary since MET is the only compiled components.

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
