### ISSUE TITLE
Add new ECNT statistics that incorporate observational uncertainty as advised in Ferro (2017)

### ISSUE THREAD

**Issue by ericgilleland** [dtcenter/MET#2583]
Add probabilistic measures with observational uncertainty recommended by Ferro (2017).  Eric has written some code to do them, but they need to be put in the right place and connected correctly.  Also, they currently calculate the scores for each category, so they will also need to be averaged over the categories.

## Describe the New Feature ##
The scores are unbiased scores that allow for observational uncertainty to be taken into account.  They are also proper scores.

### Acceptance Testing ###
*List input data types and sources.*
*Describe tests required for new functionality.*

These should take the same data types as the current scores available in MET such as crps.  Not sure how to test them as Ferro does not really demonstrate on a data set.  Perhaps we could ask him to give us a small data set with his own answers to check our code on?

### Time Estimate ###
I expect it will take a day to add it in.

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED CYCLE ASSIGNMENT** label
- [ ] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## New Feature Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
@JohnHalleyGotway and @ericgilleland met on 10/16/23 to discuss this. Here's some notes:

- Note that the Ignorance score in the ECNT line type is also known as the Logarithmic Score. Update [this documentation](https://met.readthedocs.io/en/latest/Users_Guide/appendixC.html#ign) to indicate that.
- This issue would add 3 new statistics to the end of the existing ECNT line type.
	- Error-convolved log score, error-correct log score, and dawid-sebastiani stats
- These modifications are based on the specification of multiplicative and/or additive assumed biases in the observations. Recommend adding 2 new columns to the existing [MET_OBS_ERROR_TABLE](https://met.readthedocs.io/en/latest/Users_Guide/config_options.html#met-obs-error-table) to enable them to be specified with defaults of 0 and 1 (i.e. no modification).
- If biases are specified, recommend also including them in the existing obs error perturbation logic that Ensemble-Stat already performs.
- Note that the `ECNT` line type is created by Ensemble-Stat and Point-Stat, in the context of HiRA. It stands to reason that the handling of these biases would also apply well to HiRA. @mpm-meto, do you have any thoughts or opinions about this?

**Comment by JohnHalleyGotway** [comment]
From Eric on 10/16/23:
```
#include <iostream>
#include <cmath>

using namespace std;

 double y;
 double sigma; 
 double obs_var;
 double mu;
 double mu0;
 double a = 0; // additive obs error for Dawid-Sebastiani score.
 double b = 1; // Multiplicative obs error for Dawid-Sebastiani score.

double ErrorConvolvedLogScore( ) {

    // Function to compute the error-convolved logarithmic scoring rule 
    // described in Ferro (2017, Eq 5) doi:10.1002/qj.3115

    double sigma2 = sigma * sigma;
    double ov2    = obs_var * obs_var;

    double out = 0.5 * log( sigma2 + ov2 ) + ( y - mu )*( y - mu ) / ( 2 * ( sigma2 + ov2 ) );

    return( out );

}

double ErrorCorrectedLogScore() {

    // Function to compute the error-corrected logarithmic scoring rule
    // described in Ferro (2017, Eq 7) doi:10.1002/qj.3115

    double out = log( sigma ) + ( (y - mu) * (y - mu) - obs_var * obs_var ) / ( 2 * sigma * sigma );

    return( out );

}

double DawidSebastiani() {

    // Function to compute the Dawid-Sebastiani scoring rules
    // described in Ferro (2017, Eqs 17 and 18) doi:10.1002/qj.3115
    // Dawid and Sebastiani (1999) doi:10.1214/aos/1018031101
    // These are the recommended scores in Ferro (2017).

    double ls = log( sigma );
    double b2s2 = 2 * b * b * sigma * sigma;
    double ov2 = obs_var * obs_var;

    double eq16 = ls + (y - mu) * (y - mu) / ( 2 * sigma * sigma ); // No obs uncertainty.
    double eq17 = ls + ( (y - a - b * mu) * (y - a - b * mu) - ov2 ) / b2s2;
    double eq18 = ls + ( (y - b*mu) * (y - b*mu) - y * y * ov2 / (b * b + ov2) ) / b2s2;

    return( eq16, eq17, eq18 );
}

double mean( double x ) {

    int N = size( x );

}

int main () {

    ErrorConvolvedLogScore();
    s2 = ErrorCorrectedLogScore();
    s3 = DawidSebastiani();

    return( 0 );

}
```

**Comment by JohnHalleyGotway** [comment]
@ericgilleland, it looks like we want to add 3 new output columns to the existing ECNT line type.

We'd also discussed adding 2 new columns to the existing [MET_OBS_ERROR_TABLE](https://met.readthedocs.io/en/latest/Users_Guide/config_options.html#met-obs-error-table) file to specify the additive and multiplicative biases. I understand that those 2 entries would be used in the computation of the Dawid-Sebastiani score (called `a` and `b` in that equation).

But I do not understand how `sigma`, `obs_var`, `mu`, and `mu0` are specified when computing ErrorConvolvedLogScore and ErrorCorrectedLogScore.

For each observation value, we have n forecast ensemble member values. Are these derived from the n forecast ensemble members or are they some value read from the [MET_OBS_ERROR_TABLE](https://met.readthedocs.io/en/latest/Users_Guide/config_options.html#met-obs-error-table) about the assumed observation error?

**Comment by ericgilleland** [comment]
@JohnHalleyGotway 'sigma' is the forecast standard deviation so should be calculated somewhere in the code.  'obs_var' needs to be supplied by the user (so, they supply the additive and multiplicative bias as well as the observation variance/standard deviation).  I'll have to check again, but I believe 'mu' is the forecast mean so is calculated in the code somewhere, and mu0 is that of the observations, which I believe could also be calculated in the code?

**Comment by JohnHalleyGotway** [comment]
@ericgilleland thanks for clarifying. To summarize, the inputs to the equations you listed in [your comment above](https://github.com/dtcenter/MET/issues/2583#issuecomment-1765192633), are defined as:

- `mu0`, while listed as a variable, does NOT actually appear in the equations. So presumably, it does not apply.
- `sigma` is the standard deviation of the ensemble members corresponding to an *individual* observation value.
- `mu` is the mean of the ensemble members corresponding to an *individual* observation value.
- `obs_var` is the assumed observation error variance, as defined by the `DIST_PARM` column in [obs_error_table.txt](https://github.com/dtcenter/MET/blob/main_v11.1/data/table_files/obs_error_table.txt).
- `a` is the assumed observation additive error, as defined by a *NEW COLUMN TO BE ADDED* to [obs_error_table.txt](https://github.com/dtcenter/MET/blob/main_v11.1/data/table_files/obs_error_table.txt).
- `b` is the assumed observation multiplicative bias, as defined by a *NEW COLUMN TO BE ADDED* to [obs_error_table.txt](https://github.com/dtcenter/MET/blob/main_v11.1/data/table_files/obs_error_table.txt).
- `y` shows up in `(y - mu)` and I'm guessing that `y` is the individual observation value. Please LMK if that's not correct.

So we compute these 3 new stats (ErrorConvolvedLogScore, ErrorCorrectedLogScore, and DawidSebastiani) for each point using the observation and n corresponding ensemble member values. In the ECNT line type, we report the mean of these stats across all points in the current verification task.

Some questions...
- Is this processing logic correct or does it warrant more discussion?
- If these stats are defined for each point observation, should we also write them to the ORANK line type which provides info about individual observation values?

Perhaps a good next step would be you using some existing ORANK sample data to compute these 3 scores using R or Python? And that'd give something with which to test to make sure that MET is computed the expected result.

**Comment by ericgilleland** [comment]
@JohnHalleyGotway I think the processing logic is correct.  If I understand your second question, the answer is yes.  The score is ultimately averaged over all the points, but it is still of interest to look at the individual contributions to the average.  I'm happy to run some tests using R for comparison.

Some answers after having looked at Ferro's paper again.  He uses 'x' to represent the true value and 'y' to represent the observed value, where y = x + w, and w ~ N(0,sigma_0^2), and that the true distribution of 'x' (representing the forecaster's honest belief about 'x') is N(mu_0, sigma_0^2).  He uses c^2 to be the observation error.  Finally, the forecast for the true state 'x' is distributed N(mu, sigma^2).

So,

-  you are correct that mu0 does not apply as it is there for the theory part (I think I probably just put it in thinking it might get used).
- I believe you are correct about sigma and mu.
- yes, 'obs_var' corresponds to 'c'.
- you are correct about 'a', 'b', and 'y'.

**Comment by JohnHalleyGotway** [comment]
Note that we do NOT need to add new columns to the [MET_OBS_ERROR_TABLE](https://met.readthedocs.io/en/latest/Users_Guide/config_options.html#met-obs-error-table) file. The existing INST_BIAS_SCALE and INST_BIAS_OFFSET columns already provide a way to specify systematic error. They default to a value of NA. When left as their default NA value, I'll interpret that as an additive bias of 0 and multiplicative bias of 1.0.

**Comment by JohnHalleyGotway** [comment]
@ericgilleland I'm looking for some confirmation of the naming conventions used in...
```
    double sigma2 = sigma * sigma;
    double ov2    = obs_var * obs_var;

    double out = 0.5 * log( sigma2 + ov2 ) + ( y - mu )*( y - mu ) / ( 2 * ( sigma2 + ov2 ) );
```
Is `sigma` really the *standard deviation* of the ensemble members? And so `sigma2` is just the *variance* of the ensemble members?

While `obs_var` is the assumed *variance* of the observation error? And so `ov2` is the *squared variance* of the observation?

Just want to confirm that `sigma` really indicates *standard deviation* while `var` indicates *variance* to avoid being off by a square root.

**Comment by ericgilleland** [comment]
@JohnHalleyGotway yes, that is correct.  Standard deviation is always the square root of the variance.  sigma2 is for the forecast and the other for the obs.

**Comment by JohnHalleyGotway** [comment]
Thanks @ericgilleland. OK, next question is about naming conventions. It looks like we're adding 5 new output statistics (error-convolved log score, error-corrected log score, and 3 dawid sebastiani scores). I need to choose column names for this output.

Currently, any stats involving the application of the MET_OBS_ERROR_TABLE include `OERR` in their name.
Also, `IGN` (for ignorance score which is aka the log score) is already included in the ENCT line type.

With that in mind, here's a proposal:
1. Write `ErrorConvolvedLogScore()` output to a new `IGN_OERR_CONV` column.
2. Write `ErrorCorrectedLogScore()` output to a new `IGN_OERR_CORR` column.

No ideas on the 3 Dawid Sebastiani scores equations 16, 17, and 18. Ultimately, we'll need to document them in Appendix C, including a description of them, and recommended interpretation. The name we choose should be consistent with that description.

Updated based on [Eric's comment below](https://github.com/dtcenter/MET/issues/2583#issuecomment-1789532894):

3. Eq(16): DS_OERR
4. Eq(17): DS_ADD_OERR
5. Eq(18): DS_MULT_OERR

**Comment by ericgilleland** [comment]
Eq (16) - Dawid Sebastiani (DS)
Eq (17) - Additive-Error DS 
Eq (18) - Multiplicative-Error DS

**Comment by JohnHalleyGotway** [comment]
@ericgilleland I marked this issue as being "Stalled" since we haven't touched it in over 3 months. Do we want to pick back up the development on this one and get it across the finish line?

I'm coordinating with @bikegeek so that we only need to update the METdataio database loader once during the beta4 development cycle, rather than multiple times. I'd like to lump together all the output file format changes into METplus Analysis tools issue rather than multiple.

**Comment by ericgilleland** [comment]
@JohnHalleyGotway I think it would be good to get it across the finish line as I think it is relatively straightforward (I hope) to add.  But if not, I'll defer to your judgment.  Might also ask Tara.

**Comment by ericgilleland** [comment]
@JohnHalleyGotway I see I didn't fully answer your previous question above.  Your names sound good to me.  Let me know where to add the other information and I can do that.

**Comment by JohnHalleyGotway** [comment]
@ericgilleland, OK, I can pick this back up and try to get it finished. I'm curious, is there any active project in the DTC that is interested in this new output? Perhaps @michelleharrold and @JeffBeck-NOAA with the RRFS work?

I'd like to know what scientist(s) I should ask to test this out using real data to make sure that the stats are added correctly, documented well in the user's guide, and they understand how to interpret the results.

**Comment by JohnHalleyGotway** [comment]
TODO:
- [x] No need to add new columns to the `obs_error_table.txt` table specify additive and multiplicative errors for Dawid Sebastiani. Instead, just use the existing columns for `INST_BIAS_SCALE` and `INST_BIAS_OFFSET`.
- [x] Support Stat-Analysis `-job aggregate -line_type ECNT` by computing 5 new stats as a weighted average of the inputs. Ran a job to confirm that the aggregation of these columns as a weighted mean of the inputs works as expected.
- [x] Support Stat-Analysis `-job aggregate_stat -line_type ORANK -out_line_type ECNT` see [ORANK columns](https://met.readthedocs.io/en/latest/Users_Guide/ensemble-stat.html#id7).
   - Decided to back out the assumed error variance from the ORANK columns:
      - `oerr_var = SPREAD_PLUS_OERR ^ 2 - SPREAD ^ 2`
      - Can use `oerr_var` along with the values in columns `OBS`, `ENS_MEAN`, and `SPREAD` to compute these 5 statistics. The only short-coming is not knowing the assumed additive and multiplicative biases. For now, just pass them as bad data, and the `compute_dawid_sebastiani()` function will assume an additive bias of 0 and multiplicative bias of 1.0.
 - [x] Check with @ericgilleland as to whether or not that's sufficient.
      - This is no longer an issue since we decided to omit the additive and multiplicative bias DS scores (see below).
      - The alternatives are:
         1. Could just write `DS_ADD_OERR` and `DS_MULT_OERR` as bad data since the assumed additive and multiplicative biases cannot be know by Stat-Analysis without new ORANK columns being added.
         2. Could add 2 new columns to the ORANK line type to specify the `inst_bias_scale` and `inst_bias_offset` values that were actually used by Ensemble-Stat for that single point.
         3. Could add Stat-Analysis job command options to explicitly override the default values of 1 and 0, resp.
         4. Could use the `OBS_VAR` and `OBS_LEVEL` values to do a lookup into the `MET_OBS_ERROR_TABLE`... but that may not be sufficient. If someone has hard-coded the [obs_error](https://met.readthedocs.io/en/latest/Users_Guide/config_options.html#obs-error) `inst_bias_scale` and `inst_bias_offset` values in their config file, those will differ from this table.
- [x] Add/refine unit tests: No changes are needed since `unit_ensemble_stat.xml` already includes an obs error test.
- [ ] Update User's Guide as needed.

@JohnHalleyGotway and @ericgilleland met on 2/22/24:
- It's OK to just ignore the points for which these stats can't be computed and exclude them from the summary average.
- We discussed how the additive and multiplicative observation errors are already being used in MET. If those are defined (either in the config file or in the MET obs error table), the Ensemble-Stat already applies the bias-correction to the actual observation value. That makes it unclear if/how they should used when computing the `DS_ADD_OERR` and `DS_MULT_OERR` statistics. Should they the bias-corrected obs value be used? The un-bias-corrected obs value? Rather than writing confusing statistics, whose interpretation is unclear, we decided it would be prudent to NOT write those two. So for this issue, we'll add 3 new output statistics rather than 5.
- This choice sidesteps the question about what to do when the additive and multiplicative biases are not defined. We had been using 0 and 1 for undefined additive and multiplicative biases, but the interpretation of the resulting stats was not clear.

Eric's TODO list:
- [ ] Eric please review the [Ensemble Observation Error](https://met.readthedocs.io/en/feature_2583_ecnt/Users_Guide/ensemble-stat.html#ensemble-observation-error) documentation section for accuracy.
- [ ] Eric to define Appendix C content for [log obs error section](https://met.readthedocs.io/en/feature_2583_ecnt/Users_Guide/appendixC.html#observation-error-logarithmic-scoring-rules) and [dawid-sebastiani section](https://met.readthedocs.io/en/feature_2583_ecnt/Users_Guide/appendixC.html#dawid-sebastiani-scoring-rules). Send it to John HG to add the content.
- [x] Eric will ask Chris Ferro for some sample data against which we can check the output from MET.

**Comment by JohnHalleyGotway** [comment]
Tested Stat-Analysis to confirm that it's parsing/recomputing the new stats correctly.

1. Run Ensemble-Stat command from `unit_ensemble_stat.xml`:
```
export DESC='OBSERR'
export OBS_ERROR_FLAG='TRUE'
export OUTPUT_PREFIX='OBSERR'
export SKIP_CONST='TRUE'
echo "/Volumes/d1/projects/MET/MET_unit_test/MET_test_input/model_data/grib1/arw-fer-gep1/arw-fer-gep1_2012040912_F024.grib \
                /Volumes/d1/projects/MET/MET_unit_test/MET_test_input/model_data/grib1/arw-fer-gep5/arw-fer-gep5_2012040912_F024.grib \
                /Volumes/d1/projects/MET/MET_unit_test/MET_test_input/model_data/grib1/arw-sch-gep2/arw-sch-gep2_2012040912_F024.grib \
                /Volumes/d1/projects/MET/MET_unit_test/MET_test_input/model_data/grib1/arw-sch-gep6/arw-sch-gep6_2012040912_F024.grib \
                /Volumes/d1/projects/MET/MET_unit_test/MET_test_input/model_data/grib1/arw-tom-gep3/arw-tom-gep3_2012040912_F024.grib \
                /Volumes/d1/projects/MET/MET_unit_test/MET_test_input/model_data/grib1/arw-tom-gep7/arw-tom-gep7_2012040912_F024.grib" \
                > /Volumes/d1/projects/MET/MET_unit_test/MET_test_output/ensemble_stat/input_file_list; \
          /Volumes/d1/projects/MET/MET_development/MET-feature_2583_ecnt/internal/test_unit/../../share/met/../../bin/ensemble_stat \
      /Volumes/d1/projects/MET/MET_unit_test/MET_test_output/ensemble_stat/input_file_list \
      /Volumes/d1/projects/MET/MET_development/MET-feature_2583_ecnt/internal/test_unit/config/EnsembleStatConfig \
      -point_obs /Volumes/d1/projects/MET/MET_unit_test/MET_test_output/ascii2nc/gauge_2012041012_24hr.nc \
      -outdir /Volumes/d1/projects/MET/MET_unit_test/MET_test_output/ensemble_stat -v 10 -log run_es.log
```
2. Use this output file:
[ensemble_stat_OBSERR_20120410_120000V.stat.txt](https://github.com/dtcenter/MET/files/14422642/ensemble_stat_OBSERR_20120410_120000V.stat.txt)
3. Run these Stat-Analysis commands:
```
bin/stat_analysis \
-lookin /Volumes/d1/projects/MET/MET_unit_test/MET_test_output/ensemble_stat/ensemble_stat_OBSERR_20120410_120000V.stat \
-job aggregate_stat -line_type ORANK -out_line_type ECNT \
-v 10 -log run_sa_aggr_stat.log \
-by VX_MASK,FCST_VAR,OBS_THRESH -out_stat sa_aggr_stat_orank_to_ecnt.txt


bin/stat_analysis \
-lookin /Volumes/d1/projects/MET/MET_unit_test/MET_test_output/ensemble_stat/ensemble_stat_OBSERR_20120410_120000V.stat \
-job aggregate -line_type ECNT \
-v 10 -log run_sa_aggr.log \
-by VX_MASK,FCST_VAR,OBS_THRESH -out_stat sa_aggr_ecnt.txt
```
4. Confirm that the stats generated by these jobs replicate the output generated by Ensemble-Stat... and they do!

**Comment by JohnHalleyGotway** [comment]
From Eric:

> Something to think about is that in the ignorance score we have the 2*pi*\sigma^2 term, whereas in our obs error conv./corr. versions, we don't.  Perhaps we should to be consistent with the other one.  It is equivalent because 2*pi*\sigma^2 = \xi^2 (i.e., just a scale change).

Based on this direction, I'll update the equations to multiply by `2*pi`. I'll also correct the formatting of the documented equations as Eric instructed via email.

**Comment by JohnHalleyGotway** [comment]
@ericgilleland, I see how to incorporate 2*pi into the error-convolved log score, but don't know if/how to update the error-corrected one. Can you please review the change to the error-convolved log score, and tell me if/what change to make to the error-corrected one?

```
double ErrorConvolvedLogScore( ) {

    // Function to compute the error-convolved logarithmic scoring rule 
    // described in Ferro (2017, Eq 5) doi:10.1002/qj.3115

    double sigma2 = sigma * sigma;
    double ov2    = obs_var * obs_var;

    // OLD EQUATION
    // double out = 0.5 * log( sigma2 + ov2 ) + ( y - mu )*( y - mu ) / ( 2 * ( sigma2 + ov2 ) );

    // NEW EQUATION updated to include 2 * pi
    double out = 0.5 * log( 2 * pi * (sigma2 + ov2) ) + ( y - mu )*( y - mu ) / ( 2 * ( sigma2 + ov2 ) );

    return( out );

}

double ErrorCorrectedLogScore() {

    // Function to compute the error-corrected logarithmic scoring rule
    // described in Ferro (2017, Eq 7) doi:10.1002/qj.3115

    double out = log( sigma ) + ( (y - mu) * (y - mu) - obs_var * obs_var ) / ( 2 * sigma * sigma );

    return( out );

}
```

**Comment by ericgilleland** [comment]
The error-convolved score looks good to me.  For the error-corrected score, it is a bit more different than the other two, so not sure we should change it at all.  If we were being consistent, we would include a sqrt( 2 * pi ) inside the log term, but I don't think it necessary here.

**Comment by JohnHalleyGotway** [comment]
From @ericgilleland on 3/14/2024, based on email interactions with Chris Ferro.

Need to update the equations and documentation based on the following R code.

First, download this sample data file: [Eric.RData.gz](https://github.com/dtcenter/MET/files/14605022/Eric.RData.gz)

And run the following:
```
gunzip Eric.RData.gz
R
load("Eric.RData")

ignconv <- function( obs, mod, sigma, c = 2 ) {

    s2 <- sigma^2 + c^2
    res <- 0.5 * log(2 * pi * s2 ) + (obs - mod)^2 / ( 2 * s2 )
    res <- mean( res )

    return( res )

} # end of 'ignconv' function.

ignconv( obs = obs, mod = m1, sigma = s1 )

igncorr <- function( obs, mod, sigma, c = 2 ) {

    res <- 0.5 * log( 2 * pi * sigma^2 ) + ((obs - mod)^2 - c^2) / (2 * sigma^2)
    res <- mean( res )

    return( res )

} # end of 'gincorr' function.

igncorr( obs = obs, mod = m1, sigma = s1 )
```
And note that the results should be reported as:
error-convolved log score = 2.294332
error-corrected log score = 1.821426

**Comment by JohnHalleyGotway** [comment]
To complete the validation with the MET code itself, I did the following:
1. Translated data from `Eric.RData` into this [orank.txt](https://github.com/dtcenter/MET/files/14606304/orank.txt) file.
2. Ran the following STAT-Analysis command to convert the ORANK lines into an ECNT line:
```
stat_analysis -lookin orank.txt -job aggregate_stat -line_type ORANK -out_line_type ECNT -out_stat ecnt.txt
```
3. Observed the expected scores in the output [ecnt.txt](https://github.com/dtcenter/MET/files/14606363/ecnt.txt) file where:
IGN_CONV_OERR = 2.29433
IGN_CORR_OERR = 1.82143

And these match the expected values noted above.
