### ISSUE TITLE
Enhance Point-Stat to compute vector wind line types from observations of wind speed and direction

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#2607]
## Describe the Enhancement ##
This issue arose via discussion dtcenter/METplus#2240. Point observations often report wind speed and direction rather than separate U and V wind components. As of MET version 11.1, the Point-Stat tool computes vector statistic line types (e.g. VL1L2, VAL1L2, and VCNT) when comparing forecasts of U/V wind components to observations of U/V wind components. This issue is to generalize that logic to allow for wind speed and direction to be provided instead in place of U/V wind components. Note that **forecasts** of wind speed and direction and/or **observations** of wind speed and direction and/or **climatologies** of wind speed and direction should be supported.

If vector output is requested in the configuration file (VL1L2, VAL1L2, or VCNT), then the wind speed and direction pairs should automatically be converted to U/V components and used to compute those vector outputs.

Consider making these same changes for other MET tools that can write vector output, including Grid-Stat, Series-Analysis, Stat-Analysis, and potentially Ensemble-Stat. If needed, create new GitHub issues for those other tools.

Recommend that this work be done in conjunction with #1518.

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
None needed at this time.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED CYCLE ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
- [ ] Recommend adding a METplus use case to demonstrate.

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
