### ISSUE TITLE
Consider adding instructions for removing import of `convert_point_data`

### ISSUE THREAD

**Issue by DanielAdriaansen** [dtcenter/MET#2624]
## Describe the Task ##
In dtcenter/MET#2509, the location of the `convert_point_data` function has been moved. We should consider providing details in the upcoming release notes. I will note, that it's likely this affects a very, very small number of users but it's hard to know exactly.

Previously, this used to live in `share/met/python/met_point_obs.py`, and a user accessed this function in their Python embedding script like this:

```
from met_point_obs import convert_point_data
met_point_data = convert_point_data(point_data)
```

This no longer works. The user can now remove both of the above lines, and MET automatically reformats `point_data` into the correct format if it is not already. BUT, the user MUST have a variable named `point_data`. For instance, if their script looked like this:
```
from met_point_obs import convert_point_data
my_11col_data = pd.DataFrame('foo')
met_point_data = convert_point_data(my_11col_data)
```

They must also change this line:
`my_11col_data = pd.DataFrame('foo')`
to be:
`point_data = pd.DataFrame('foo')`

@DanielAdriaansen will add a few sentences to "upgrade instructions" for this major release describing this. Make these changes in the main_v11.1 branch (here: https://met.readthedocs.io/en/main_v11.1/Users_Guide/release-notes.html#met-version-11-1-0-upgrade-instructions). This section is transient and won't apply to future versions so it will be nice to put it here. Use feature branch because this branch is protected so make a PR.

### Time Estimate ###
30 minutes

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED CYCLE ASSIGNMENT** label
- [ ] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by DanielAdriaansen** [comment]
This came up in RC testing here:
https://github.com/dtcenter/METplus/discussions/2218#discussioncomment-6452031
