### ISSUE TITLE
Update MET User's Guide with SEEPS information

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#2629]
## Describe the Task ##
@mpm-meto and @RachelNorth had difficulties testing the SEEPS functionality in the MET-11.1.0-rc2 release. The initial challenge was in retrieving and configuring the climatology data required to compute SEEPS in both the Grid-Stat and Point-Stat tools in MET.

As decided in a METplus/Met Office telecon on July 27, 2023, the Met Office plans to *publish* the SEEPS climatology data at zenodo.org. Once they do, this issue is to update the MET and/or METplus User's Guide with a link to its location on zenodo, along with practical instructions for pulling and using that data to compute SEEPS.

Consider making updates in:
1. MET SEEPS in [Appendix C](https://met.readthedocs.io/en/latest/Users_Guide/appendixC.html?highlight=seeps#stable-equitable-error-in-probability-space-seeps)
2. MET SEEPS for [Grid-Stat](https://met.readthedocs.io/en/latest/Users_Guide/appendixC.html?highlight=seeps#stable-equitable-error-in-probability-space-seeps).
3. MET SEEPS for [Point-Stat](https://met.readthedocs.io/en/latest/Users_Guide/point-stat.html?highlight=seeps#seeps-scores).
4. Somewhere in the METplus User's Guide, or at least update it to link to relevant sections of the MET User's Guide.

While the SEEPS config options can be set via METplus, no use cases exist yet to demonstrate them. However, they should be added prior to Coordinated METplus 6.0.0 release.

### Time Estimate ###
1 day?

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED CYCLE ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
