### ISSUE TITLE
Deprecate and remove R scripts from the MET repository

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#2649]
## Describe the Task ##
As of MET version 12.0.0, R scripts are deprecated within the MET repository and this issue is to remove them, if possible. The [MET/scripts/Rscripts](https://github.com/dtcenter/MET/tree/main_v11.1/scripts/Rscripts) directory contains 11 utility R scripts which are described below. This issue consists of multiple steps.

@TaraJensen:
   - Review these scripts and determine which ones can be deprecated and removed. If possible, note the replacement functionality provided by other METplus components (e.g. `plot_tcmpr.R` functionality moved to METplotpy, `plot_cnt.R` functionality supported by METviewer, etc).

Assigned Engineer:
   - Remove the scripts marked for deletion.
   - If all are removed, delete the `Rscripts` directory as well.
   - Update `Makefile.am` files as needed.
   - Delete any unit tests that reference these R scripts.
   - Update the release notes/upgrade instructions to describe this change.
      - Direct users to replacement functionality in other METplus components.
      - Link to these Rscripts from earlier versions of MET.

Description of R scripts:
- `gspairs2mpr.R`: Reformat NetCDF matched pairs from Grid-Stat into the MPR .stat line type for processing by Stat-Analysis.
- `mode_nc_inventory.R`: Summarize object counts and statistics in MODE NetCDF output files. Used mostly for development and testing.
- `mode_quilt_plot.R`: Read MODE ascii object files for runs for multiple radii and thresholds and create quilt plots.
- `mode_summary.R`: Read MODE ascii object files and summarize object counts, areas, and statistics.
- `plot_cnt.R`: Read CNT .stat line type and create summary plots for each case.
- `plot_ensemble.R`: Read ensemble .stat line types and create summary plots for each case.
- `plot_mpr.R`: Read MPR .stat line type and create summary plots for each case.
- `plot_probri.R`: Read PROBRI .tcst line type and create summary plots for each case.
- `plot_tcmpr.R`: Read TCMPR .tcst line type and create summary plots for requested columns/diffs/absolute values of diffs.
   - Largely moved to METplotpy. Should link to relevant documentation.
- `trmm2nc.R`: Reformat ASCII TRMM data into NetCDF format for MET.
   - Precursor to python embedding.
- `trmmbin2nc.R`: Reformat binary TRMM data in NetCDF format for MET.
   - Precursor to python embedding.

### Time Estimate ###
< 1 day

### Sub-Issues ###
Consider breaking the task down into sub-issues.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
TBD, recommend that DTC HAFS funding fully transitions the functionality to METplus-Analysis.

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED CYCLE ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
- [ ] Coordinate with METplus to modify or remove any use cases or wrappers that call these scripts.

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
@TaraJensen question for you. @jprestop and I tracked down a difference in the MET nightly build from last night back to an issue with the use of temporary files in the `plot_tcmpr.R` script. I started writing up an issue to fix up the logic to avoid future diffs, but then remembered this issue.

Should I *fix* that issue by removing the `plot_tcmpr.R` script from the MET repo along with the corresponding `unit_plot_tc.xml` test that exercises it? Or should I patch up the logic that resides there?

I'll note that @KathrynNewman was running that script on seneca as recently as February, 2023. While we want to make corresponding TC plots with Python instead, perhaps @KathrynNewman could advise as to whether or not the Python plotting is sufficiently mature?

**Comment by JohnHalleyGotway** [comment]
Note that on 20230925, the nightly build for the develop branch on seneca flagged differences in the following 3 output files:
```
file2: MET-develop/test_output/plot_tc/ABS_AMAX_WIND-BMAX_WIND_boxplot.png
file2: MET-develop/test_output/plot_tc/plot_tc_TCMPR_data.tcst
file2: MET-develop/test_output/plot_tc/TK_ERR_boxplot.png
```
These are all output from a single call to `plot_tcmpr.R` script in the `unit_plot_tc.xml` unit test. The following is a very likely explanation for these diffs.

- The `plot_tcmpr.R` script uses its current process id to define a temporary filename named `/tmp/plot_tcmpr_${PID}.tcst`.
- As of 20230925, 225 such temp files already existed in `/tmp` with a wide variety of process id's, owned by @KathrynNewman, and not group-writeable.
- It is likely that that `plot_tcmpr.R` run happened to have a process id for which one of those temp files already existed.
- The `plot_tcmpr.R` script ran `tc_stat` attempting to write to that existing file name but file permissions prevented it from over-writing the existing file.
- The call to `tc_stat` likely returned bad status, but the `plot_tcmpr.R` script FAILED to error out. It continued on to the plotting step, reading data from the existing, stale temp file.
- This is evidenced by the fact that those stale temp files all contain data for `V11.0.0` which matches the output version listed in `MET-develop/test_output/plot_tc/plot_tc_TCMPR_data.tcst`.
- While we could fix up the temp file logic in `plot_tcmpr.R` and enhance it to check the return status from `tc_stat`, we could also just remove it from the repo entirely.

**Comment by JohnHalleyGotway** [comment]
On 9/28/23, @TaraJensen decided that this should be removed for version 12.0.0.

**Comment by JohnHalleyGotway** [comment]
@KathrynNewman and @bikegeek, during the METplus project meeting on 5/26/26, we discussed this issue. We're wondering whether the functionality of the `plot_tcmpr.R` script, in particular, has been sufficiently replaced in the METplus Analysis tools?

Can `plot_tcmpr.R` be removed from the MET repository?
