### ISSUE TITLE
Review and refine the documentation of the `obs_summary` configuration option

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#2686]
## Describe the Task ##
This issue is to review and refine the documentation of the `obs_summary` configuration option found in [this section](https://met.readthedocs.io/en/develop/Users_Guide/config_options.html#obs-summary) of the MET User's Guide. This issue was raised during the METplus/Met Office developer's checkin meeting on 9/14/23. In particular, listing `(lat,lon,level,elev)` in the documentation is confusing. Stating `elev` indicates that its the station elevation (Column 6 in this [ASCII2NC table](https://met.readthedocs.io/en/develop/Users_Guide/reformat_point.html#id8)). However its actually stored as the height of the observation rather than the station elevation.

This is likely not just a simple documentation change. Instead, check the observation summary code in `pair_base.cc` and note that elevation is used throughout the code, including in log messages. And it may be the case that what's currently called `elev` is actually the height (when verifying vertical level forecasts) or pressure (when verifying pressure level forecasts).

Recommend that we clarify the actual logic, update the variable names used in the code and corresponding log messages, and finally, fix the documentation.

Please run the result past @robdarvell since he originally raised the issue.

### Time Estimate ###
2 hours.

### Sub-Issues ###
Consider breaking the task down into sub-issues.
None.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
2799991

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Review default **alert** labels
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Milestone and Projects ###
- [x] Select **Milestone** as the next official version or **Backlog of Development Ideas**
- [x] For the next official version, select the **MET-X.Y.Z Development** project

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
No impacts.

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the next official version
Select: **MET-X.Y.Z Development** project for development toward the next official release
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
