### ISSUE TITLE
Upgrade SonarQube server version from 9.8 to 10.2

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#2689]
## Describe the Task ##
Based on an email from Eli Goodrich on 9/21/23, the SonarQube server version 9.8 that we're currently using is deprecated. He advises upgrading to version 9.9 or the most recent release, 10.2. This issue is to upgrade the SonarQube server version installed in mandan:/d2/projects/METplus/SonarQube. Ideally, upgrade all the way to version 10.2 to minimize the frequency of updates.

Make any changes needed to the corresponding run scripts in the MET repo.

### Time Estimate ###
4 hours?

### Sub-Issues ###
Consider breaking the task down into sub-issues.
None.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
METplus AirForce Funding: 2771022

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Review default **alert** labels
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Milestone and Projects ###
- [x] Select **Milestone** as the next official version or **Backlog of Development Ideas**
- [x] For the next official version, select the **MET-X.Y.Z Development** project

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

If SonarQube is being run routinely for other METplus components, may need to update the run scripts in the other METplus repos. If so, please add a corresponding issue in those repos to track the work.

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the next official version
Select: **MET-X.Y.Z Development** project for development toward the next official release
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
