### ISSUE TITLE
Minimize the use of temporary files in Stat-Analysis

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#2698]
## Describe the Enhancement ##
As discussed in the Contributor's Guide documentation, the [Stat-Analysis Tool](https://met.readthedocs.io/en/develop/Contributors_Guide/dev_details/tmp_file_use.html#stat-analysis-tool) writes a temporary file. It reads all the input files, applies any common filtering logic requested, and writes the result to a temporary file. All subsequent jobs read data from that temp file, apply any additional filtering options, and then perform the requested operation. The temp file is always written, even if only one job is run on the command line or a config file is used without any common filtering options.

This issue is to revise that logic to minimize the use of that temp file. If only one job is specified (on the command line or via a config file), there is no need to write to/read from a config file. In addition, if no common filtering logic is specified in the config file, we might be able to avoid writing the temp file. So investigate that to see if it's feasible to skip the config file there too.

### Time Estimate ###
4 days

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
None needed

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
2025 USAF METplus Funding (PRJ013851 AF METPLUS)

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Review default **alert** labels
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Milestone and Projects ###
- [x] Select **Milestone** as the next official version or **Backlog of Development Ideas**
- [x] For the next official version, select the **MET-X.Y.Z Development** project

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
No impacts.

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the next official version
Select: **MET-X.Y.Z Development** project for development toward the next official release
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
- [x] Updated the logic to only write a temp file when multiple jobs are being run.
- [x] Updated the `TCStatFiles` class to inherit from the new `TCDataFiles` class instead of reimplementing basically the same logic.
- [x] All the unit tests run and produce no diffs.
- [x] Extend the logic to only use a temp file when ACTUALLY needed in the config file, based on the presence of common filtering options at the top of the config file.
