### ISSUE TITLE
Enhance Multivariate MODE to change the default `merge_flag` setting to NONE 

### ISSUE THREAD

**Issue by davidalbo** [dtcenter/MET#2708]
## Describe the Enhancement ##
Change the `merge_flag default` to` NONE`, and allow it to not be set for MvMode fields. If not set right now the code uses a default `merge_flag=THRESH` and `merge_thresh = ">=1.25"`. MvMode is now implemented so that the user MUST set all the merge_flag (and merge_thresh) values explicitly. 

### Time Estimate ###
1 day

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] See if changing for both mvmode and single var mode causes problems for single var mode.

### Relevant Deadlines ###
November 7 2023 (beta 2)

### Funding Source ###
2702691

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Review default **alert** labels
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Milestone and Projects ###
- [ ] Select **Milestone** as the next official version or **Backlog of Development Ideas**
- [ ] For the next official version, select the **MET-X.Y.Z Development** project

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update log messages for easier debugging.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the next official version
Select: **MET-X.Y.Z Development** project for development toward the next official release
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [ ] Close this issue.

**Comment by davidalbo** [comment]
Looks like mode always reads the MODEConfig_default, not the MODEMultivarConfig_default.  These default files are similar but not quite the same. The latter does already have default merge_flag=NONE.  

mode needs to read an actual config to be able to detect whether it's multivar or not, so on startup it does not know which of these is the default file to read.
One option would be to change the MODEConfig_defauilt so that merge_flag=NONE is the default, which might impact single var mode. 
Another option is to read the config as is now to determine if it's multivar or not, then read again using  MODEMultivarConfig_default if it was determined it's a multivar case.

**Comment by davidalbo** [comment]
@hertneky @JohnHalleyGotway

I did change the code so that it uses `MODEMultivarConfig_default`, once it determines the user config has multivar content by doing a 'double read'.  If the user config does not have multivar content, `MODEConfig_default` is used.   The former file has `merge_flag=NONE `as the default, so now if the user does not specify `merge_flag` for a field, that field will get `merge_flag=NONE `(unless the user puts something else into the 'parent' part of the config, 'parent' being outside of the individual input fields).

I also added debug printing (level 2) for the case where a field does not have merge_flag/merge_thresh set, and it is defaulting to the parent values, to show what the merge_flag/merge_thresh values that field is using.  Just to make sure the user is getting what they want.

I also added some code to disallow certain combinations and error exit:

1. individual fields with `merge_flag` specified, but without `merge_thresh` specified.  This is to prevent `merge_thresh` to come from the parent, which probably would be an error.
2. individual fields with` merge_thresh` specified, but without `merge_flag`.  Same idea, to prevent `merge_flag `to come from the parent, which probably would be an error.

Possible tests to try:

1. create a config with a field that does not specify `merge_flag/merge_thresh` and make sure it defaults to `NONE`.
2. create a config with a field that has `merge_flag` but no `merge_thresh` and observe the error exit.
3. create a config with a field that has `merge_thresh` but no `merge_flag `and observe the error exit.

**Comment by davidalbo** [comment]
The use of the  MODEMultivarConfig_default file caused a value to change when Metplus tests were run, it was multivar_name = "ALPHA_BETA_GAMMA".  Previously this name was not set so reverted to the default name "Super".  Changed the MODEMultivarConfig_default to have multivar_name = "Super".

Another bugfix was put into this branch, found by @hertneky, in which the default output directory was never set for multivar mode, causing the output directory to be the empty string, which caused an error exit. The fix was to set the default output directory to ".", consistent with single var mode.
