### ISSUE TITLE
Enhance Multivariate MODE to support multiple convolution radii and thresholds

### ISSUE THREAD

**Issue by davidalbo** [dtcenter/MET#2709]
## Describe the Enhancement ##

- Allow multiple convolution radii and thresholds without quilting.
- Currently disallowed in multivariate mode.
- Can also do this with multiple METplus configurations (I think) in case this does not get done.
- Possibly also allow quilting if it is trivial to do so.

### Time Estimate ###
40 hours

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [x] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
Work must be completed by 12/30 for NRL METplus funding

### Funding Source ###
NRL METplus 7730022

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Review default **alert** labels
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Milestone and Projects ###
- [ ] Select **Milestone** as the next official version or **Backlog of Development Ideas**
- [ ] For the next official version, select the **MET-X.Y.Z Development** project

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the next official version
Select: **MET-X.Y.Z Development** project for development toward the next official release
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by davidalbo** [comment]
Added both quilting and non-quilting options.  
Without quilting all inputs (forecast and obs) need to have the same number N of convolution radii and thresholds, with one mvmode run for the first set, one for the second set, etc. for a total of N runs.

With quilting all inputs must have the same number of convolution radii N, and all inputs must have the same number of convolution thresholds M, but N and M can differ.  N*M mvmode runs are performed.
