### ISSUE TITLE
Documentation: Make Headers Consistent in All MET Guides

### ISSUE THREAD

**Issue by lisagoodrich** [dtcenter/MET#2716]
This is a sub-issue of #*898*.
https://github.com/dtcenter/METplus/issues/898

## Describe the Sub-Issue ##
This task is for all METplus component.  This specific issue is for MET only:

The headers for the MET components User's Guides may not be consistent, but we want them to be. 

Here is the syntax from the RST docs (https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#sections):

\# with overline, for parts (e.g. the RTD documentation for the component (i.e. docs/index.rst), each guide (e.g. User's Guide, Contributor's Guide) (i.e. docs/Users_Guide/index.rst, docs/Contributors_Guide/index.rst))
\* with overline, for chapters
=, for sections
-, for subsections
^, for subsubsections
", for paragraphs

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Review default **alert** labels
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Milestone and Projects ###
- [x] Select **Milestone** as the next official version or **Backlog of Development Ideas**
- [x] For the next official version, select the **MET-X.Y.Z Development** project

### Funding Source ###
2783543 - Lisa has hours on this account.
