### ISSUE TITLE
Review MODE implementation to look for more computational efficiencies

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#2727]
## Describe the Enhancement ##
Issue #2724 and corresponding PR #2726 enhance MODE in MET-12.0.0-beta2 by improving its convolution algorithm, adding OpenMP, and minimizing avoidable memory allocation. This issue to conduct a careful review of the rest of the MODE application and associated library code to look for additional potential efficiencies.

Some ideas to consider are copied below from this [issue comment:](https://github.com/dtcenter/MET/issues/2724#issuecomment-1792733754)

- The `ShapeData::n_objects()` function calls split which loops over the entire grid and can be slow. Could eliminate calls to `n_objects()` or remove that function entirely to prevent its use.
- Most of the time MODE loops over a grid that is very sparse, often only containing a single object. Consider adding bounding box information to the ShapeData class to keep track of the extent of non-zero object data. Update member functions to loop over that bounding box rather than the entire domain.
- Review each call to `DataPlane::get(x,y)` which calls `two_to_one()` which performs a bounds check. Can they replaced with direct operation on the vector of `Data`? Or can they be replaced with a new accessor function that skips the bounds checking? Running @DanielAdriaansen test case with 75 tiny objects through a profiler, 50% of the ~10 min runtime is spent accessing data.
- Data is read in twice in multivar_frontend.cc, with calls to `ModeFrontEnd::create_multivar_simple_objects()` and `ModeFrontend::create_multivar_merge_objects()`.  Instead the data should be kept in memory when creating the simple objects and accessed when creating the merge objects. 

### Time Estimate ###
2 days?

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Review default **alert** labels
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Milestone and Projects ###
- [x] Select **Milestone** as the next official version or **Backlog of Development Ideas**
- [x] For the next official version, select the **MET-X.Y.Z Development** project

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
Expect no impacts.

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the next official version
Select: **MET-X.Y.Z Development** project for development toward the next official release
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by davidalbo** [comment]
The subtask of reading data in twice was resolved in this issue:  [https://github.com/dtcenter/MET/issues/2745](url)
