### ISSUE TITLE
Bugfix: Fix the Point-Stat CNT header line typo causing duplicate `SI_BCL` column names 

### ISSUE THREAD

**Issue by John-Sharples** [dtcenter/MET#2730]
## Describe the Problem ##
Small issue one of the devs here at BoM noticed:

`point_stat` cnt file has a repeated header: Last 2 header values are "SI_BCL", but last one should be "SI_BCU" instead, as per docs here: https://met.readthedocs.io/en/latest/Users_Guide/point-stat.html#id11

### To Reproduce ###
```
sudo docker run -it dtcenter/metplus:6.0.0-beta1 /bin/bash

pushd /met/MET-develop/scripts

export TEST_OUT_DIR=/metplus/OUTPUT

mkdir -p ${TEST_OUT_DIR}/point_stat

point_stat \
   ../data/sample_fcst/2007033000/nam.t00z.awip1236.tm00.20070330.grb \
   ${TEST_OUT_DIR}/pb2nc/sample_pb.nc \
   config/PointStatConfig \
   -point_obs ${TEST_OUT_DIR}/ascii2nc/sample_ascii.nc \
   -outdir ${TEST_OUT_DIR}/point_stat -v 2

cat ${TEST_OUT_DIR}/point_stat/point_stat_360000L_20070331_120000V_cnt.txt
```

### Relevant Deadlines ###
NONE

### Funding Source ###
NONE

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Review default **alert** labels
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Milestone and Projects ###
- [x] Select **Milestone** as the next bugfix version
- [x] Select **Coordinated METplus-X.Y Support** project for support of the current coordinated release
- [x] Select **MET-X.Y.Z Development** project for development toward the next official release

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
- [ ] @georgemccabe indicates that this fix will likely be flagged as a difference in the METplus Use Case output. If that is the case, we'll need to update the truth dataset to move past these changes.

## Bugfix Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **main_\<Version>**.
Branch name: `bugfix_<Issue Number>_main_<Version>_<Description>`
- [ ] Fix the bug and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **main_\<Version>**.
Pull request: `bugfix <Issue Number> main_<Version> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the next bugfix version
Select: **Coordinated METplus-X.Y Support** project for support of the current coordinated release
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Complete the steps above to fix the bug on the **develop** branch.
Branch name:  `bugfix_<Issue Number>_develop_<Description>`
Pull request: `bugfix <Issue Number> develop <Description>`
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the next official version
Select: **MET-X.Y.Z Development** project for development toward the next official release
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
Thanks @John-Sharples for finding this bug. It's now fixed in the main_v11.1 and develop branches and will be included in all future releases.
