### ISSUE TITLE
Enhance Plot-Point-Obs to print a summary of the point observations processed

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#2738]
## Describe the Enhancement ##
This idea arose during the METplus Advanced Training Series on 11/15/23 when discussing Python embedding. When preparing Python scripts, users are advised to run plot_data_plane and plot_point_obs to validate their Python embedding scripts for gridded and point data, respectively.

Running plot_data_plane with `-v 4` prints the following information about the grid and values being plotted:
```
DEBUG 4: Grid information:
DEBUG 4:    Projection: Lambert Conformal
DEBUG 4:    Nx: 185
DEBUG 4:    Ny: 129
DEBUG 4:    Lat_LL: 12.190
DEBUG 4:    Lon_LL: 133.459
DEBUG 4:    Lon_orient: 95.000
DEBUG 4:    Alpha: 406.820
DEBUG 4:    Cone: 0.423
DEBUG 4:    Bx: 104.0012
DEBUG 4:    By: 356.7313
DEBUG 4: 
DEBUG 4: Data plane information:
DEBUG 4:    plane min: 252
DEBUG 4:    plane max: 270
DEBUG 4:    valid time: 20050807_120000
DEBUG 4:    lead time: 120000
DEBUG 4:    init time: 20050807_000000
DEBUG 4:    accum time: 000000
```
However, running plot_point_obs with `-v 4` only prints info about the lat/lon locations being plotted:
```
DEBUG 3: For point data group 1, plotting 2312 locations for 78376 observations.
DEBUG 4: [1] Plotting location [ lat, lon, val ] = [ 31.87, -106.7, -9999 ]
DEBUG 4: [2] Plotting location [ lat, lon, val ] = [ 31.94, -102.19, -9999 ]
```
This issue is to enhance plot_point_obs to log additional summary information about the point observations processed. Recommend printing a list of variable names, levels, values, and locations. Consult with @DanielAdriaansen to decide how to organize the summary info in a user-friendly way. This summary info could be printed at `-v 3` or `-v 4`, at the discretion of @DanielAdriaansen.

### Time Estimate ###
1 day

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Review default **alert** labels
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Milestone and Projects ###
- [x] Select **Milestone** as the next official version or **Backlog of Development Ideas**
- [x] For the next official version, select the **MET-X.Y.Z Development** project

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
No impacts.

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the next official version
Select: **MET-X.Y.Z Development** project for development toward the next official release
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
