### ISSUE TITLE
More support for NetCDF files following the UGRID convention

### ISSUE THREAD

**Issue by hsoh-u** [dtcenter/MET#2746]
The requirements (from #2231)

Additional work for UGRID

- [documentation](https://github.com/dtcenter/MET/issues/2748)
- Support other datasets
- Vertical level handling (vertical interpolation and multiple vertical levels)
- Support nearest neighbor as well as the min/max/uw_mean/dw_mean of the nearest N points.
- Enhance Series-Analysis to compare UGRID to UGRID on the same grid (Need more info).
- Enhance Plot-Point-Obs (???).

Future considerations include:
- Using lookup tables to make the interpolation to point locations more efficient rather than calling kdtrees.

Included at beta2:
- Supported the global attribute ```Conventions = "UGRID"```
- Supported MPAS dataset
- Added a new vx_data2d_ugrid library
- Added unstructured grid to vx_grid library
- Make UGRID optional (--enable-ugrid)
- Supported the nearest neighbor (the nearest 1 point with max_distance_km).
- Enhanced Point-Stat to verify points natively on the UGRID.
- Enhance Grid-Stat to compare UGRID to UGRID on the same grid with regridding for the output.
- F]Ind the variables by combining "name" and "level" for MPAS diagnostic 

## Describe the Enhancement ##
*Provide a description of the enhancement request here.*

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] https://github.com/dtcenter/MET/issues/2748

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*
2799991 Met Office METplus Support

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Review default **alert** labels
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Milestone and Projects ###
- [ ] Select **Milestone** as the next official version or **Backlog of Development Ideas**
- [ ] For the next official version, select the **MET-X.Y.Z Development** project

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the next official version
Select: **MET-X.Y.Z Development** project for development toward the next official release
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by AliciaBentley-NOAA** [comment]
@JohnHalleyGotway @DanielAdriaansen  This particular MET issue and [a second MET issue (now closed)](https://github.com/dtcenter/MET/issues/2860) are listed under adding "Unstructured Grids" to MET-12.0.0 on the [METplus Gaps spreadsheet](https://docs.google.com/spreadsheets/d/1yvvM65t-vC7Gk0n54wzAJGYwjpy72E1SAIHi4cBJ2NY/edit#gid=217592017). Does this paritcular issue need to be finished in order for Unstructured grids to be added to MET-12.0.0? If this issue is required in order to add unstructured grids, can it please be marked as a blocker to the MET-12.0.0 official release? Thank you!

**Comment by AliciaBentley-NOAA** [comment]
@j-opatz @georgemccabe This particular MET issue is listed under adding "Unstructured Grids" to MET-12.0.0 on the [METplus Gaps spreadsheet](https://docs.google.com/spreadsheets/d/1yvvM65t-vC7Gk0n54wzAJGYwjpy72E1SAIHi4cBJ2NY/edit#gid=217592017). Does this paritcular issue need to be finished in order for Unstructured grids to be added to MET-12.0.0? If this issue is required in order to add unstructured grids, can it please be marked as a blocker to the MET-12.0.0 official release? Thank you!

**Comment by DanielAdriaansen** [comment]
Hi @AliciaBentley-NOAA, sorry for not getting back sooner. The current unstructured grid capability is detailed in the MET documentation here: https://met.readthedocs.io/en/develop/Users_Guide/appendixH.html, which will be included in MET-12.0.0. The items listed in this issue are **in addition** to the functionality described in the documentation. If you feel any of the additional functionality listed in this issue is needed for the MET-12.0.0 release, please let us know which items and we can break them out into specific issues to be prioritized for MET-12.0.0. Otherwise the intent here is to document work to build upon the current implementation in future MET versions, and thus probably this issue isn't necessarily "required for release" (12.0.0) but parts of it may be depending on your needs. Thanks!

**Comment by AliciaBentley-NOAA** [comment]
Hi @DanielAdriaansen  - Thanks! Tara asked me to review all of the open MET issues on Github and note which ones may be critical to the MET-12.0.0 official release. As long as the functionality shown in closed issue https://github.com/dtcenter/MET/issues/2860 makes it into MET-12.0.0, we can check off this particular box. Can you please confirm that the User's Guide covers https://github.com/dtcenter/MET/issues/2860? Thanks!

**Comment by DanielAdriaansen** [comment]
@AliciaBentley-NOAA got it! You are correct, the description in the User Guide is consistent with the version used for testing in #2860 ✅

**Comment by AliciaBentley-NOAA** [comment]
Thanks, @DanielAdriaansen !
