### ISSUE TITLE
Upgrade to G2C library version that supports CCSDS encoding

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#2759]
## Describe the Enhancement ##
METplus Discussion dtcenter/METplus#2449 points out a segfault from MET when processing GRIB2 files from ECMWF encoded using the CCSDS encoding option. The problem lies not in MET itself, but in the GRIB2C Library (G2C) to which MET links.

As noted in this [Discussion Comment](https://github.com/dtcenter/METplus/discussions/2449#discussioncomment-7803061) pre-processing the GRIB2 files using the `grib_set` or `wgrib2` utilities to change the encoding method provide a temporary workaround.

This issue is to monitor the progress on issue NOAA-EMC/NCEPLIBS-g2c#461 which is meant to fix the underlying problem in the GRIB2C library. When that issue is fixed and an updated version of the G2C library is released, update the MET compilation script as needed to begin using the new version of that library.

Consider recompiling the existing MET builds for [MET version 11.1.0](https://dtcenter.org/community-code/metplus/metplus-5-1-existing-builds) and [MET version 12.0.0](https://dtcenter.org/community-code/metplus/metplus-6-0-existing-builds) using the updated G2C library version, as needed.

### Time Estimate ###
3 days?

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
None needed.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: @jprestop 
- [ ] Select **scientist(s)** or **no scientist** required: None needed

### Labels ###
- [x] Review default **alert** labels
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Milestone and Projects ###
- [x] Select **Milestone** as the next official version or **Backlog of Development Ideas**
- [x] For the next official version, select the **MET-X.Y.Z Development** project

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
No impacts.

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the next official version
Select: **MET-X.Y.Z Development** project for development toward the next official release
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by jprestop** [comment]
@JohnHalleyGotway After moving this issue forward to 12.1.0, I looked into this issue further. The description of this issue includes:

> This issue is to monitor the progress on issue https://github.com/NOAA-EMC/NCEPLIBS-g2c/issues/461 which is meant to fix the underlying problem in the GRIB2C library. When that issue is fixed and an updated version of the G2C library is released, update the MET compilation script as needed to begin using the new version of that library.

Note that the referenced NCEPLIBS-g2c issue is currently closed, however, after reading through the comments, there were no changes made.

The developer suggests to the user that there "could be an incompatibility between g2c (built with MSVC++) and g2 (Intel Fortran) and your program (Intel Fortran) what does not show itself until program execution".  And then indicated:

> As of now there are no changes to g2c needed. The AEC compression is working correctly from within the g2c library. Changes are definitely needed in NCEPLIBS-g2, but we can perhaps discuss that in an issue for g2, likely in https://github.com/NOAA-EMC/NCEPLIBS-g2/issues/705 or https://github.com/NOAA-EMC/NCEPLIBS-g2/issues/458. IMO, this specific issue can be closed.

However, we are not using g2, but rather only g2c.  I'm not sure where this leaves us.  I don't have a full understanding of the underlying issue, but am wondering if you think we need to submit an issue to g2c for this problem?

**Comment by jprestop** [comment]
@mollybsmith-noaa Please see my [comment above](https://github.com/dtcenter/MET/issues/2759#issuecomment-2394442627).  It looks like no fix is coming for this issue.  Please let us know if you have any concerns.

**Comment by mollybsmith-noaa** [comment]
@jprestop The re-encoding via wgrib2 is an acceptable workaround, albeit clunky, so the fix is not vital at this point.

**Comment by jprestop** [comment]
@mollybsmith-noaa Thank you.  I'm going to close this issue as "not planned".  We can reopen it in the future if necessary.
