### ISSUE TITLE
Switch from writing temporary Python files in NetCDF to JSON and NumPy serialization

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#2772]
## Describe the Enhancement ##
This idea was discussed during the METplus Engineering meeting on 12/19/23. @jprestop has been having challenges installing MET-12.0.0-beta2 on HPC machines. In particular, there is a runtime linker issue with NetCDF/HDF5 libraries. The MET C++ code requires and links to NetCDF. In addition, the version of Python with which MET is compiled is required to support the NetCDF Python package since that's what is used for writing temporary NetCDF files when the $MET_PYTHON_EXE environment variable is set.

These two NetCDF shared object library files can come into conflict. And requiring them to be identical, i.e. compiled by the same compiler family/version is unrealistic. It may be useful to REMOVE that Python NetCDF requirement. We could try doing so by switching to writing temporary Python files in JSON instead. Note that this is actually how its already being handled in the Python embedding used for TC-Diag.

This is an idea that requires more research to determine whether or not its feasible. Recommend testing by modifying the `write_tmp_dataplane.py` and `read_tmp_dataplane.py` scripts to use JSON instead of NetCDF. The real test is how performant JSON will be compared to NetCDF.

It is not clear whether or not this will actually improve the linker issues that @jprestop has encountered.

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*
2702691

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Review default **alert** labels
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Milestone and Projects ###
- [x] Select **Milestone** as the next official version or **Backlog of Development Ideas**
- [x] For the next official version, select the **MET-X.Y.Z Development** project

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
No impacts.

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the next official version
Select: **MET-X.Y.Z Development** project for development toward the next official release
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by hsoh-u** [comment]
The default is changed to a JSON output plus a numpy serialized output. The existing NetCDF format temporary file is still available by setting the environment variable "**MET_PYTHON_TMP_FORMAT**" to "**netcdf**" (case sensitive).
