### ISSUE TITLE
Update GitHub actions workflows to switch from node 16 to node 20

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#2796]
## Describe the Task ##
As of January 24, 2024, the following warning messages began appearing on the MET GitHub action workflow runs:
```
[Build Documentation](https://github.com/dtcenter/MET/actions/runs/7642630271/job/20822701483)
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-python@v4, actions/upload-artifact@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```
Our call to `actions/checkout@v3` triggers this warning message, as do other similar actions. Recommend upgrading action version numbers as needed to move past this warning. Make these change in both the develop and main_v11.1 branches.

Can use the following commands to update:
```
cd .github/workflows
for file in `ls *.yml`; do 
  cat $file | \
  sed 's%actions/checkout@v3%actions/checkout@v4%g' | \
  sed 's%actions/upload-artifact@v3%actions/upload-artifact@v4%g' | \
  sed 's%actions/download-artifact@v3%actions/download-artifact@v4%g' | \
  sed 's%actions/setup-python@v4%actions/setup-python@v5%g' | \
  sed 's%actions/github-script@v6%actions/github-script@v7%g' > tmp;
  mv tmp $file;
done
```

### Time Estimate ###
2 hours.

### Sub-Issues ###
Consider breaking the task down into sub-issues.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Review default **alert** labels
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Milestone and Projects ###
- [x] Select **Milestone** as the next official version or **Backlog of Development Ideas**
- [x] For the next official version, select the **MET-X.Y.Z Development** project

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
If this is successful, recommend that the other METplus repo's be updated in a similar way.

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the next official version
Select: **MET-X.Y.Z Development** project for development toward the next official release
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by lisagoodrich** [comment]
@JohnHalleyGotway the beginning of this issue says: As of January 24, 2023, 

Did you mean 2024?  I'm just checking before I copy across 4 new issues.

**Comment by jprestop** [comment]
@lisagoodrich, Yes, @JohnHalleyGotway meant "2024".  I've updated this issue to reflect that, along with the other two that you created.
