### ISSUE TITLE
Enhance MET library code to support additional vertical level types in WRF files

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/MET#2818]
@mrinalbiswas provided WRF Chem sample files that contain some vertical levels dimensions that are not currently supported by MET but could easily be added.

## Describe the Enhancement ##
Add support for reading WRF files that use the following vertical dimensions:

* bio_emissions_dimension_stag
* klevs_for_dvel
* soil_layers_stag
* seed_dim_stag

Sample data is available in derecho:/glade/derecho/scratch/biswas/forMETplus

### Time Estimate ###
<2 hours

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
None needed.

### Relevant Deadlines ###
12.1.0

### Funding Source ###
I-WRF (7790013)

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [X] Select **scientist(s)** or **no scientist** required - recommend @mrinalbiswas test these changes

### Labels ###
- [X] Review default **alert** labels
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Milestone and Projects ###
- [X] Select **Milestone** as the next official version or **Backlog of Development Ideas**
- [X] For the next official version, select the **MET-X.Y.Z Development** project

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
No impacts.

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [X] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the next official version
Select: **MET-X.Y.Z Development** project for development toward the next official release
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
