### ISSUE TITLE
Add convex hull to MODE output

### ISSUE THREAD

**Issue by Jeff-Duda** [dtcenter/MET#2819]
*Replace italics below with details for this issue.*

## Describe the New Feature ##
I request that, like the regular objects currently are, the convex hull can be output from MODE.

### Acceptance Testing ###
Existence of convex hull object in output netcdf file (or a list of polygon vertices for manual plotting of it)

### Time Estimate ###
1 hour

### Sub-Issues ###
none

### Relevant Deadlines ###
None.

### Funding Source ###
None.

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED CYCLE ASSIGNMENT** label
- [ ] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## New Feature Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
@Jeff-Duda, in our development meeting today, we reviewed the "new" issues and discussed this one.

I see that you're looking for information about the convex hulls of the objects generated by MODE. I took at look at the existing MODE output and do see that the lat/lon of the vertices which comprise those convex hulls are already being written. Of course, there's multiple types of objects, but MODE is writing the convex hulls for both simple and cluster, forecast and observation objects... so 4 categories.

For example, the forecast cluster info is provided by the following variables:
```
	int fcst_clus_hull_start(fcst_clus) ;
		fcst_clus_hull_start:long_name = "Forecast Cluster Convex Hull Starting Index" ;
	int fcst_clus_hull_npts(fcst_clus) ;
		fcst_clus_hull_npts:long_name = "Number of Forecast Cluster Convex Hull Points" ;
	float fcst_clus_hull_lat(fcst_clus_hull) ;
		fcst_clus_hull_lat:long_name = "Forecast Cluster Convex Hull Point Latitude" ;
		fcst_clus_hull_lat:units = "degrees_north" ;
	float fcst_clus_hull_lon(fcst_clus_hull) ;
		fcst_clus_hull_lon:long_name = "Forecast Cluster Convex Hull Point Longitude" ;
		fcst_clus_hull_lon:units = "degrees_east" ;
        int fcst_clus_hull_x(fcst_clus_hull) ;
                fcst_clus_hull_x:long_name = "Forecast Cluster Convex Hull Point X-Coordinate" ;
        int fcst_clus_hull_y(fcst_clus_hull) ;
                fcst_clus_hull_y:long_name = "Forecast Cluster Convex Hull Point Y-Coordinate" ;
```
The `fcst_clus_hull_lat` and `fcst_clus_hull_lon` variables provide a long list of latitude and longitude values. The `fcst_clus_hull_x` and `fcst_clus_hull_y` variables provide the corresponding grid (x, y) locations. The `fcst_clus` dimension defines the number of cluster forecast objects. The `fcst_clus_hull_start` variable is an integer that defines a starting index for each object into the list of lat/lon's. The `fcst_clus_hull_npts` variable is an integer length for the number of points which comprise that cluster.

By way of example, I'm looking at output for a MODE with 2 forecast cluster objects, and have:
```
dimensions:
   fcst_clus = 2 ;
...
variables:
...
 fcst_clus_hull_start = 0, 16 ;
 fcst_clus_hull_npts = 16, 11 ;
 fcst_clus_hull_lat = 30.53024, 31.98145, 33.049, 37.19469, 37.52252,
    37.46346, 36.94013, 35.6331, 34.78508, 33.56855, 32.4935, 30.5206,  
    28.12394, 28.1774, 28.65582, 29.42194, 29.36289, 29.72653, 30.87579,
    35.71614, 35.71322, 35.35007, 34.62545, 31.37023, 26.59204, 26.56783,
    28.31108 ;    
 fcst_clus_hull_lon = -88.6646, -88.58471, -88.09238, -84.68615, -84.20391,
    -83.30848, -81.12036, -78.61959, -77.41997, -76.29839, -76.47556, 
    -78.49377, -84.6472, -85.47262, -87.51628, -88.3054, -102.9483,
    -102.9728, -101.7792, -95.88449, -93.67458, -93.23839, -92.81214, 
    -92.87391, -99.08608, -99.90255, -102.0481 ;
```
The (lat, lon) points for the first object are the first 16 points. The (lat, lon) points for the second object are the next 11 points.

This output is briefly mentioned in the [MODE output section](https://met.readthedocs.io/en/latest/Users_Guide/mode.html#mode-output) of the User's Guide.

So the question is, is this existing output sufficient? Or are you looking for something in addition to this?

**Comment by Jeff-Duda** [comment]
I suppose I'm being a bit lazy by being this brief, but my ultimate goal is to have the ability to determine if a single/simple object is within the convex hull of another object. I'm not 100% sure if the existing output you described satisfies that, as I'm not sure how to compute the "interior" of a polygon merely from the lat/lon coordinates of the vertices.

**Comment by JohnHalleyGotway** [comment]
@Jeff-Duda we discussed this during the MET Development meeting today. I hear that you'd like the ability to detect when one object is within the convex hull of another.

As noted, the MODE NetCDF output does include the lat/lon vertices of the convex hulls... but does NOT include a gridded field of them. So I suppose that's what you're requesting with this issue? To enhance the `nc_pairs_flag` configuration option in MODE to include the option for writing the convex hulls as a gridded field?
```
nc_pairs_flag   = {
   latlon       = TRUE;
   raw          = TRUE;
   object_raw   = TRUE;
   object_id    = TRUE;
   cluster_id   = TRUE;
   cluster_hull_id = TRUE; // NEW option to write the convex hulls of the cluster objects
   polylines    = TRUE;
}
```
If this were easily done, it wouldn't be a big deal to add that new option. However, the object convex hull is computed and stored in MET as a `Polyline` collection of lat/lon points. Its computed by the [ShapeData::convex_hull()](https://github.com/dtcenter/MET/blob/14969779a342969d3093abb8f3a4099e9bcfd56c/src/libcode/vx_shapedata/shapedata.h#L152) member function.

So MODE would need to do extra processing to convert that Polyline to a 2D field of data for it to be written to the output file. And that 2D field of convex hull data isn't actually used by MODE for computations.

My guess is that there's likely a Python solution to this problem. You could read the existing NetCDF output from MODE into Python, parse the lat/lon outlines of the simple/cluster/convex hull shapes, and then write a function to determine if/how much they overlap. I don't have an obvious solution to offer but am guessing ESRI Shapefiles or Polygon from shapely.geometry may be useful.

There's another pretty slow, multi-step method, where you could extract the lat/lon points for convex hull from the MODE NetCDF file, write them to ASCII as a "polyline", and then run the Gen-Vx-Mask tool to create a 2D field of grid points that fall inside the convex hull. Not saying that's a great idea... just saying its also an option.

If you give it more thought, and come up with a tweak to MODE's output that'd make things easier for you, please let me know. I'm just reticent to add more processing time to write the convex hulls as gridded fields when MODE isn't already computing them. Of course, we wouldn't actually incur that processing time unless you request that they be written.

Any thoughts on how you'd like to proceed?

**Comment by Jeff-Duda** [comment]
Thanks, John. I think the development team's reticence to want to add processing code to MODE is reasonable, and I won't request that. I think you're right that there is probably a function somewhere in one of the Python libraries that handle image processing that can handle this request. I think I will declare this issue closed and myself satisfied with the responses and I will attempt to perform this work outside of the MET software. But I appreciate the enlightening discussion.
