### ISSUE TITLE
Enhance Point2Grid to filter quality control strings with config file options

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#2880]
## Describe the Enhancement ##
Note, the changes for this issue rename the existing point2grid “-qc” command line option as “-goes_qc”, although the old “-qc” option is still quietly supported.

While developing a wrapper for the Point2Grid tool via dtcenter/METplus#2540, a short-coming in the Point2Grid configuration file was discovered. Please see this [issue comment](https://github.com/dtcenter/METplus/issues/2540) for details. Put simply, the existing `quality_mark_thresh` config file option should be replaced by the `obs_quality_inc` and `obs_quality_exc` config file options supported for the Point-Stat and Ensemble-Stat tools.

Be sure to update the unit tests to demonstrate these options and update the documentation accordingly.

### Time Estimate ###
1 day

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
2782544

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Review default **alert** labels
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Milestone and Projects ###
- [x] Select **Milestone** as the next official version or **Backlog of Development Ideas**
- [x] For the next official version, select the **MET-X.Y.Z Development** project

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
- [x] dtcenter/METplus#2540 already exists to add a Point2Grid wrapper.

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update log messages for easier debugging.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the next official version
Select: **MET-X.Y.Z Development** project for development toward the next official release
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
This issue is blocking dtcenter/METplus#2540.

**Comment by JohnHalleyGotway** [comment]
Added logic in point2grid to filter by the obs_qty_inc/exc settings but I get a segfault whenever that code is exercised. Recommend debugging on seneca to see why the `MetPointObsData::get_obs_qty(int index)` segfaults. Presumably, the obs_qids array it is references is not populated... or something like that.
