### ISSUE TITLE
Enhance TC-Stat to support the `-set_hdr` job command option

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#2911]
## Describe the Enhancement ##
This issue arose from @mollybsmith-noaa via the dtcenter/METplus#2608 discussion. While the Stat-Analysis tool supports the `-set_hdr` job command option, the TC-Stat tool does not. This issue to enhance TC-Stat to add that support.

Run the following job on output from the MET unit tests to demonstrate what's needed:
```
./tc_stat -lookin test_output/tc_pairs -job rirw -line_type TCMPR -by CYCLONE -out_line_type CTC -out_stat ctc.stat -set_hdr DESC CYCLONE
```
That produces the following error message:
```
ERROR  : TCStatJob *TCStatJobFactory::new_tc_stat_job(const char *jobstring) -> unsupported job command options "-set_hdr DESC CYCLONE".
```
The task is to enhance TC-Stat to support `-set_hdr` so that the job listed above works.

Note that this may be a little tricky since TC-Stat writes both `.stat` and `.tcst` output files. Ideally, the `-set_hdr` option would work for both types of output.

### Time Estimate ###
2 days

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
None needed.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Review default **alert** labels
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Milestone and Projects ###
- [x] Select **Milestone** as a **MET-X.Y.Z** version, **Consider for Next Release**, or **Backlog of Development Ideas**
- [x] For a **MET-X.Y.Z** version, select the **MET-X.Y.Z Development** project

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
No impacts.

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the next official version
Select: **MET-X.Y.Z Development** project for development toward the next official release
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
Remember to do the following:
- [x] Consider whether or not `StatHdrInfo::get_shc(...)` should be reimplemented using a call to `StatHdrColumns::apply_set_hdr_opts(...)`.
   - Done by updating `StatHdrInfo::get_shc()` to initialize all the output header columns first and then call the common `apply_set_hdr_opts()` function second.
- [x] Update TC-Stat documentation.
- [x] Update `unit_tc_stat.xml` to demonstrate `-set_hdr`.
