### ISSUE TITLE
Enhance multivariate MODE to support Python embedding inputs

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#2940]
## Describe the Enhancement ##
This issue is based on the dtcenter/METplus#2644 discussion. @CPKalb has found that running multi-variate MODE with 2 inputs that use Python embedding does not work as expected. @JohnHalleyGotway tested multivariate MODE directly and found that it errors out when parsing an input file list containing `PYTHON_NUMPY PYTHON_NUMPY`. Since those are not filenames that actually exist on the file system, it treats them as being missing files and thinks that it has 0 inputs.

This task is to do the following:
1. Spend a couple of hours investigating this issue to see layering in Python embedding support is easily done. If so, fix this for the MET-12.0.0 release. If the issue is more involved, reassign this work to the next coordinated release.
2. Enhance multivariate MODE to support Python embedding inputs.
3. Add a unit test to demonstrate this functionality.
4. Review the documentation for needed changes.

### Time Estimate ###
Approx 2 days.

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
7760062 Integrating Fire Wx
Confirmed funding source with Amanda on 4/4/25 for spending 2 days on this work prior to Nov 30, 2025.

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Review default **alert** labels
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Milestone and Projects ###
- [x] Select **Milestone** as a **MET-X.Y.Z** version, **Consider for Next Release**, or **Backlog of Development Ideas**
- [x] For a **MET-X.Y.Z** version, select the **MET-X.Y.Z Development** project

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
Don't expect any impacts, but @CPKalb should test through METplus to confirm it works as expected.

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the next official version
Select: **MET-X.Y.Z Development** project for development toward the next official release
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
@j-opatz please take a look at this issue.

**Comment by JohnHalleyGotway** [comment]
Progress on this issue:
1. Added new test in `unit_python.xml` to run MvMODE using 2 Python inputs for both the forecast and observation objects. The forecast is their intersection and the observation is their union.
2. The input file lists only contain `PYTHON_NUMPY PYTHON_NUMPY` which yields this runtime error:
```
DEBUG 5: parse_ascii_file_list() -> File "/d1/personal/johnhg/MET/MET_development/MET-feature_2940_mv_mode_python/internal/test_unit/../../test_output/python/mode_multivar_obs_file_list" is not an ASCII file list since there are too many missing files.
ERROR  : 
ERROR  : MultivarFrontEnd::_setup_inputs() -> Want at least 2 input files for fcst or obs in multivar mode, neither had 2 or more
ERROR  : 
```
3. Re-running with file lists containing `file_list PYTHON_NUMPY PYTHON_NUMPY` produces this error message:
```
ERROR  : Met2dDataFile::grid() -> no grid defined!
```
Need to work on the grid processing logic.

**Comment by JohnHalleyGotway** [comment]
I ran across some unexpected behavior in regards to merging the super objects. When `multivar_intensity_compare_fcst` and `multivar_intensity_compare_obs` are both set to an empty list, threshold merging is applies to the super objects regardless of how `merge_flag` is set in the config file:
```
DEBUG 2: Performing merging (THRESH) in the forecast field.
DEBUG 2: Performing merging (THRESH) in the observation field.
```
This does not seem correct. Recommend investigating.

**Comment by JohnHalleyGotway** [comment]
@CPKalb I have a feature branch ready for you to test multivariate MODE with Python embedding. Please find it on seneca in:
`/d1/projects/MET/MET_pull_requests/met-12.1.0/rc1/MET-feature_2940_mode_multivar_python/bin/mode`

The unit test I added using fake data can also be run as follows:
```
runas met_test
/d1/projects/MET/MET_pull_requests/met-12.1.0/rc1/MET-feature_2940_mode_multivar_python/internal/test_unit/unit_mode_multivar_python.sh
```
It runs 2 Python embedding scripts to read same input for both the forecast and observation fields. The forecast is the intersection of the 2 inputs while the observation in the union.

Please run using the your real data to make sure it works.

FYI, the fix (see [commit](https://github.com/dtcenter/MET/commit/bfe990f84dd2883fe825051e475d97c230358550)) was very straightforward. Previously, we were extracting the grid from the input file immediately after "opening" it. For Python embedding, the grid information is not populated until the script to run to ingest the data. So the fix is to wait to set the grid until after the data has been read from the input files.
