### ISSUE TITLE
Modify configure.ac to define C++17 as the default compilation standard

### ISSUE THREAD

**Issue by jprestop** [dtcenter/MET#2948]
## Describe the Task ##
Due to the [need to upgrade to versions atlas/0.35.0 and eckit/1.24.4](https://github.com/dtcenter/METbaseimage/issues/27), which require the C++17 standard, modify configure.ac.  See @JohnHalleyGotway's [comment](https://github.com/dtcenter/MET/issues/2949#issuecomment-2299911541) in #2949 which recommends taking the following approach.

1. Add support in the MET configure.ac file for a new environment variable named MET_CXX_STANDARD (or something similar).
2. Update configure.ac to add MET_CXX_STANDARD it to the list of "influential env vars" along with a description of how it works.
3. Update configure.ac to check to see if it's set. If so, set a local variable to the same value. If not, set that local variable to the default value of 17.
4. Update configure.ac so that the CXXFLAGS setting includes -std=c++${MET_CXX_STANDARD}... or something similar to specify the C++ standard flag that should be used.

### Time Estimate ###
<1 day

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
MET-12.0.0-beta6

### Funding Source ###
TBD

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Review default **alert** labels
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Milestone and Projects ###
- [x] Select **Milestone** as a **MET-X.Y.Z** version, **Consider for Next Release**, or **Backlog of Development Ideas**
- [x] For a **MET-X.Y.Z** version, select the **MET-X.Y.Z Development** project

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the next official version
Select: **MET-X.Y.Z Development** project for development toward the next official release
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by jprestop** [comment]
Closed with PR #2953
