### ISSUE TITLE
Bugfix: Fix Grid-Stat segfault when SEEPS is the only NetCDF output type requested

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#3020]
## Describe the Problem ##
As described in discussion dtcenter/METplus#2794, Grid-Stat segfaults when SEEPS is the only NetCDF output type requested. Grid-Stat attempts to write the SEEPS data to the NetCDF output file prior to that file being created.

Remember to fix this in both the develop and main_v12.0 branches.

### Expected Behavior ###
 This issue is to update the Grid-Stat logic to create and initialize the NetCDF output file, even if SEEPS is the only type requested.

### Environment ###
Describe your runtime environment:
- Identified by the MetOffice and replicated on seneca.

### To Reproduce ###
Describe the steps to reproduce the behavior:
- Replicated in `seneca:/d1/projects/METplus/discussions/2794/run_gs.sh` using sample data provided for dtcenter/METplus#2794.

### Relevant Deadlines ###
Include fix in the MET-12.0.0 release.

### Funding Source ###
2799991

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Review default **alert** labels
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Milestone and Projects ###
- [x] Select **Milestone** as the next bugfix version
- [x] Select **Coordinated METplus-X.Y Support** project for support of the current coordinated release
- [x] Select **MET-X.Y.Z Development** project for development toward the next official release

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
No impacts.

## Bugfix Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **main_\<Version>**.
Branch name: `bugfix_<Issue Number>_main_<Version>_<Description>`
- [ ] Fix the bug and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **main_\<Version>**.
Pull request: `bugfix <Issue Number> main_<Version> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the next bugfix version
Select: **Coordinated METplus-X.Y Support** project for support of the current coordinated release
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Complete the steps above to fix the bug on the **develop** branch.
Branch name:  `bugfix_<Issue Number>_develop_<Description>`
Pull request: `bugfix <Issue Number> develop <Description>`
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the next official version
Select: **MET-X.Y.Z Development** project for development toward the next official release
- [ ] Close this issue.
