### ISSUE TITLE
Enhance Series-Analysis to compute statistics from the GRAD line type

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#3030]
## Describe the Enhancement ##

MET #3024 adds 4 new columns to the GRAD line type written by Grid-Stat to quantify sharpness. This issue is to enhance Series-Analysis to compute the statistics from the GRAD line type to enable sharpness to be assessed spatially.

Recommend reconfiguring an existing unit test for Series-Analysis to also compute GRAD statistics.

### Time Estimate ###
2 days?

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
None needed.

### Relevant Deadlines ###
To be completed by 12/30 and charged to the METplus NRL project.

### Funding Source ###
METplus NRL project (7730022)

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Review default **alert** labels
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Milestone and Projects ###
- [x] Select **Milestone** as a **MET-X.Y.Z** version, **Consider for Next Release**, or **Backlog of Development Ideas**
- [x] For a **MET-X.Y.Z** version, select the **MET-X.Y.Z Development** project

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
- [x] dtcenter/METplus#2827 to update the SeriesAnalysis wrapper accordingly.

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the next official version
Select: **MET-X.Y.Z Development** project for development toward the next official release
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
@KathrynNewman question for you.

I'm adding the `gradient` configuration entry from Grid-Stat to the Series-Analysis configuration file to make this configurable:
```
//
// Gradient statistics
// May be set separately in each "obs.field" entry
//
gradient = {
   dx = [ 1 ];
   dy = [ 1 ];
}
```
Grid-Stat supports an arbitrary number of gradients being computed. Wondering whether Series-Analysis should do the same or only support a single `dx` and `dy` value? The former would require storing more data in memory since the matched pairs for each gradient choice would need to be buffered up. This is doable. I just don't know if multiple gradient choices would actually be used in practice. If so, I can add it. If not, I'd rather not complicate the logic with an extra dimension of information if we don't need to.

--------

As we discussed in person, I'll proceed with supporting a list of `dx` and `dy` gradient definitions since that option is most consistent with the handling in Grid-Stat and could of scientific use. Recommend sticking with the default setting of `dx=[1]; dy=[1];`.
