### ISSUE TITLE
Add LEPS and SEEPS to MET probabilistic verification.

### ISSUE THREAD

**Issue by dwfncar** [dtcenter/MET#563]
*Replace italics below with details for this issue.*

## Describe the New Feature ##
On 10/29/2015, Geoff Dimego at NCEP inquired as to whether MET can compute SEEPS.  Tara responded that no, it can&#39;t, but it could be added in the next release if we can find funding.  Here&#39;s some more details on it...

According to Beth Ebert's website (<a href="http://www.cawcr.gov.au/projects/verification/">http://www.cawcr.gov.au/projects/verification/</a>) both LEPS and SEEPS are computed relative to climatology.  And they require knowledge of the climatological distribution.  In met-5.1, we read the climatological mean but not the spread.  Adding LEPS and SEEPS would require us to read the spread.  If I understand correctly, we convert the actual observed event to the likelihood that value would occur based on the climatological PDF (likely assuming a normal distribution).  And we use that observed likelihood to compute these scores.

I suppose we would add LEPS and SEEPS to the PSTD line type... although they can't be derived from the Nx2 probabilistic contingency table.

Also, if these require the climatological spread, we&#39;d need to add that to the MPR line type so that SEEPS and LEPS could be computed from the MPR line type.  And if we add the climo spread to MPR, we should add it to ORANK to keep things consistent.

Marion Mittermaier says Rachael North can help with development and testing. She also pointed out that Rachael now has a method for SEEPS using TRMM so we will need to implement in Grid Stat as well.  Finally, Marion mentioned that LEPS is not really related to SEEPS.  It's a continuous statistics.

Stat-Analysis will also need to be modified to add this into the WMO/CBS format

### Acceptance Testing ###
*List input data types and sources.*
*Describe tests required for new functionality.*

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
MET-10.0

### Funding Source ###
2799991 - Met Office

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required  RACHAEL NORTH

### Labels ###
- [x] Select **component(s)**
- [X] Select **priority**
- [ X Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [X] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## New Feature Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

On 10/29/2015, Geoff Dimego at NCEP inquired as to whether MET can compute SEEPS.  Tara responded that no, it can&#39;t, but it could be added in the next release if we can find funding.  Here&#39;s some more details on it...
<br/>

<br/>
According to Beth Ebert&#39;s website (<a href="http://www.cawcr.gov.au/projects/verification/">http://www.cawcr.gov.au/projects/verification/</a>) both LEPS and SEEPS are computed relative to climatology.  And they require knowledge of the climatological distribution.  In met-5.1, we read the climatological mean but not the spread.  Adding LEPS and SEEPS would require us to read the spread.  If I understand correctly, we convert the actual observed event to the likelihood that value would occur based on the climatological PDF (likely assuming a normal distribution).  And we use that observed likelihood to compute these scores.
<br/>

<br/>
I suppose we would add LEPS and SEEPS to the PSTD line type... although they can&#39;t be derived from the Nx2 probabilistic contingency table.
<br/>

<br/>
Also, if these require the climatological spread, we&#39;d need to add that to the MPR line type so that SEEPS and LEPS could be computed from the MPR line type.  And if we add the climo spread to MPR, we should add it to ORANK to keep things consistent.
<i>[MET-563] created by johnhg</i>

**Comment by TaraJensen** [comment]
Charge 2780541

**Comment by JohnHalleyGotway** [comment]
Closing this issue since it is superseded by dtcenter/MET#1941, dtcenter/MET#1942, and dtcenter/MET#1943.
