### ISSUE TITLE
Consider enhancing Ensemble-Stat to support ens_mean_thresh option that is analogous to the fcst_thresh option of point_stat/grid_stat.

### ISSUE THREAD

**Issue by dwfncar** [dtcenter/MET#999]
## Describe the Enhancement ##

This issue was originally defined in May, 2018. However, it was requested a second time in August, 2020 via met-help by Binyu Wang from NOAA/EMC:
https://rt.rap.ucar.edu/rt/Ticket/Display.html?id=96270

Ensemble-Stat in met-9.1 includes support for the obs_thresh option which subsets the ensemble verification pairs by applying a filtering threshold to the observation values. A corresponding fcst_thresh filtering option is supported in the point_stat and grid_stat tools. Initially support for this was not added to ensemble_stat because the logic is a little messy... rather than having a single forecast value to check, each observation corresponds to multiple ensemble forecast values.

obs_thresh defines which pairs should be retained in the verification. Similarly fcst_thresh should define the data retention criteria (rather than data exclusion). Recommend that we add support for fcst_thresh to define the filtering threshold(s) and fcst_thresh_ratio to define the ratio of ensemble values for which this criteria must be met. This is analogous to the ens_vld_thresh setting.

For example, with an ensemble of size 10:
   fcst_thresh = [ >1, >2, >3 ];
   fcst_thresh_ratio = 0.75;

Requires that for each of these thresholds, 8 of the 10 members must meet the threshold criteria for the pair to be used. fcst_thresh_ratio = 1.0; requires that the threshold be satisfied for all inputs.

The fcst_thresh applied should be written to the FCST_THRESH output column, just like we do for OBS_THRESH. And the logic should be applied in exactly the same set of cases for which obs_thresh is applied. Probably no need or space to indicate the "fcst_thresh_ratio" value in the output.

Questions:
- How should we handle missing data values? Should bad data simply be counted as not meeting the threshold?
- Should we also filter by some summary of the ensemble members, such as min, max, median, mean? How could the user that summary metric?

### Time Estimate ###
3 days.

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
No sub-issues required.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones
- [ ] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above.
- [ ] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop** and link the pull request to this issue..
Pull request: `feature <Issue Number> <Description>`
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

The ensemble-stat tool enables users to do conditional verification by filtering based on the obs_thresh.  We did not include fcst_thresh filtering there because it&#39;d be confusing to apply filtering logic to the individual ensemble members.  However, it would be reasonable to filter based on the ensemble means.
<br/>

<br/>
No need to do this urgently.  But might be useful.  For example, when processing precip, you might require that the obs be greater than 0 *or* the ensemble mean be greater than 0.
<i>[MET-999] created by johnhg</i>
